# Prior to Running This File:

Ensure you have tabula-py installed on your machine. Uncomment and run the first cell if you do not have it installed.

In [3]:
#!pip install tabula-py

In [4]:
import tabula
import pandas as pd
import re
import math
import sys
from gdpPDFCleaning import *

# GDP 95-00 Data

In [5]:
# create instance of yearly GDP data
GDP95_01 = YearlyGDP('GDP1995-2001.pdf', 8, 1995, 2000, '2001')

In [6]:
# testing that it was initialized with an empty DataFrame
GDP95_01.df

Empty DataFrame
Columns: []
Index: []

In [7]:
# initializeDataFrame() method reads in the PDF, assigns the first DataFrame in the 
# list as the df (only one table per page), and renames the columns. Lastly, it returns 
# the DataFrame for viewing
GDP95_01.initializeDataFrame()

,Area,1995,1996,1997,1998,1999,2000,2001,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000 2001
1,United States.......................,"7,309,516","7,715,901","8,224,960","8,750,174","9,251,541","9,891,187","10,137,190",100 100
2,New England....................,"416,166","439,596","471,336","503,940","533,324","582,874","594,686",5.9 5.9
3,Connecticut......................,"118,645","124,157","134,968","142,701","149,010","161,929","166,165",1.6 1.6
4,Maine...............................,"27,987","28,925","30,409","32,208","34,102","36,276","37,449",0.4 0.4
...,...,...,...,...,...,...,...,...,...
56,California.........................,"925,931","973,395","1,045,254","1,125,331","1,213,355","1,330,025","1,359,265",13.4 13.4
57,Hawaii..............................,"37,243","37,490","38,537","39,371","40,662","42,524","43,710",0.4 0.4
58,Nevada.............................,"49,377","54,564","59,248","63,786","69,534","75,533","79,220",0.8 0.8
59,Oregon.............................,"81,092","91,709","97,510","102,943","110,374","121,383","120,055",1.2 1.2
60,Washington......................,"151,265","161,779","175,242","192,031","208,470","218,095","222,950",2.2 2.2

In [8]:
GDP95_01.cleanStates('Area')

,Area,1995,1996,1997,1998,1999,2000,2001,NaN,Cleaned Area
0,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000 2001,nan
1,United States.......................,"7,309,516","7,715,901","8,224,960","8,750,174","9,251,541","9,891,187","10,137,190",100 100,United States
2,New England....................,"416,166","439,596","471,336","503,940","533,324","582,874","594,686",5.9 5.9,New England
3,Connecticut......................,"118,645","124,157","134,968","142,701","149,010","161,929","166,165",1.6 1.6,Connecticut
4,Maine...............................,"27,987","28,925","30,409","32,208","34,102","36,276","37,449",0.4 0.4,Maine
...,...,...,...,...,...,...,...,...,...,...
56,California.........................,"925,931","973,395","1,045,254","1,125,331","1,213,355","1,330,025","1,359,265",13.4 13.4,California
57,Hawaii..............................,"37,243","37,490","38,537","39,371","40,662","42,524","43,710",0.4 0.4,Hawaii
58,Nevada.............................,"49,377","54,564","59,248","63,786","69,534","75,533","79,220",0.8 0.8,Nevada
59,Oregon.............................,"81,092","91,709","97,510","102,943","110,374","121,383","120,055",1.2 1.2,Oregon
60,Washington......................,"151,265","161,779","175,242","192,031","208,470","218,095","222,950",2.2 2.2,Washington

In [9]:
GDP95_01.addGeoLocColumn('Cleaned Area')

,Area,1995,1996,1997,1998,1999,2000,2001,NaN,Cleaned Area,Geo Loc
0,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000 2001,nan,NaN
1,United States.......................,"7,309,516","7,715,901","8,224,960","8,750,174","9,251,541","9,891,187","10,137,190",100 100,United States,NaN
2,New England....................,"416,166","439,596","471,336","503,940","533,324","582,874","594,686",5.9 5.9,New England,NaN
3,Connecticut......................,"118,645","124,157","134,968","142,701","149,010","161,929","166,165",1.6 1.6,Connecticut,New England
4,Maine...............................,"27,987","28,925","30,409","32,208","34,102","36,276","37,449",0.4 0.4,Maine,New England
...,...,...,...,...,...,...,...,...,...,...,...
56,California.........................,"925,931","973,395","1,045,254","1,125,331","1,213,355","1,330,025","1,359,265",13.4 13.4,California,Far West
57,Hawaii..............................,"37,243","37,490","38,537","39,371","40,662","42,524","43,710",0.4 0.4,Hawaii,Far West
58,Nevada.............................,"49,377","54,564","59,248","63,786","69,534","75,533","79,220",0.8 0.8,Nevada,Far West
59,Oregon.............................,"81,092","91,709","97,510","102,943","110,374","121,383","120,055",1.2 1.2,Oregon,Far West
60,Washington......................,"151,265","161,779","175,242","192,031","208,470","218,095","222,950",2.2 2.2,Washington,Far West

In [10]:
GDP95_01.restructureDataFrame('Cleaned Area')

     year          state current dollars       GDP        GDP_area
0    1995         Alaska            2001   24791.0        Far West
1    1995        Alabama            2001   95514.0       Southeast
2    1995       Arkansas            2001   53809.0       Southeast
3    1995        Arizona            2001  104586.0       Southwest
4    1995     California            2001  925931.0        Far West
..    ...            ...             ...       ...             ...
301  2000        Vermont            2001   18124.0     New England
302  2000     Washington            2001  218095.0        Far West
303  2000      Wisconsin            2001  173016.0     Great Lakes
304  2000  West Virginia            2001   40926.0       Southeast
305  2000        Wyoming            2001   19113.0  Rocky Mountain

[306 rows x 5 columns]

In [11]:
GDP95_01.df

     year          state current dollars       GDP        GDP_area
0    1995         Alaska            2001   24791.0        Far West
1    1995        Alabama            2001   95514.0       Southeast
2    1995       Arkansas            2001   53809.0       Southeast
3    1995        Arizona            2001  104586.0       Southwest
4    1995     California            2001  925931.0        Far West
..    ...            ...             ...       ...             ...
301  2000        Vermont            2001   18124.0     New England
302  2000     Washington            2001  218095.0        Far West
303  2000      Wisconsin            2001  173016.0     Great Lakes
304  2000  West Virginia            2001   40926.0       Southeast
305  2000        Wyoming            2001   19113.0  Rocky Mountain

[306 rows x 5 columns]

# GDP 01 - 03 Data

In [12]:
# create instance of yearly GDP data
GDP01_03 = YearlyGDP('GDP2001-2003.pdf', 5, 2001, 2003, '2004')

In [13]:
# testing that it was initialized with an empty DataFrame
GDP01_03.df

Empty DataFrame
Columns: []
Index: []

In [14]:
# initializeDataFrame() method reads in the PDF, assigns the first DataFrame in the 
# list as the df (only one table per page), and renames the columns. Lastly, it returns 
# the DataFrame for viewing
GDP01_03.initializeDataFrame()

,Area,2001,2002 2003,2004,2001.0,2002 2003,2004
0,United States .........,"10,058,156","10,412,244 10,923,849","11,649,827",100.0,100.0 100.0,100.0
1,New England ............,"584,487","596,017 620,136","664,181",5.8,5.7 5.7,5.7
2,Connecticut .............,"165,434","167,235 174,085","187,086",1.6,1.6 1.6,1.6
3,Maine .....................,"37,094","39,027 40,829","43,279",0.4,0.4 0.4,0.4
4,Massachusetts .........,"283,422","287,191 297,113","317,684",2.8,2.8 2.7,2.7
5,New Hampshire .........,"44,394","46,106 48,202","52,097",0.4,0.4 0.4,0.4
6,Rhode Island ............,"35,489","37,040 39,363","41,921",0.4,0.4 0.4,0.4
7,Vermont ..................,"18,656","19,419 20,544","22,114",0.2,0.2 0.2,0.2
8,Mideast .....................,"1,868,057","1,922,516 2,010,011","2,140,662",18.6,18.5 18.4,18.4
9,Delaware ..................,"45,049","46,991 50,486","54,500",0.4,0.5 0.5,0.5
10,District of Columbia ...,"63,223","67,176 70,668","75,264",0.6,0.6 0.6,0.6
11,Maryland ..................,"192,425","202,840 213,073","226,513",1.9,1.9 2.0,1.9
12,New Jersey ...............,"362,336","377,824 394,040","415,891",3.6,3.6 3.6,3.6
13,New York ..................,"797,145","802,866 838,035","899,660",7.9,7.7 7.7,7.7
14,Pennsylvania ............,"407,880","424,820 443,709","468,833",4.1,4.1 4.1,4.0
15,Great Lakes ...............,"1,565,557","1,611,658 1,669,527","1,758,915",15.6,15.5 15.3,15.1
16,Illinois .....................,"476,851","486,182 499,731","528,904",4.7,4.7 4.6,4.5
17,Indiana .....................,"195,769","203,296 213,342","227,271",1.9,2.0 2.0,2.0
18,Michigan ..................,"335,793","347,014 359,440","372,756",3.3,3.3 3.3,3.2
19,Ohio ........................,"374,771","385,657 398,918","418,258",3.7,3.7 3.7,3.6
20,Wisconsin ...............,"182,373","189,508 198,096","211,727",1.8,1.8 1.8,1.8
21,Plains ........................,"653,388","680,449 714,007","763,082",6.5,6.5 6.5,6.6
22,Iowa ........................,"92,891","97,810 102,400","114,269",0.9,0.9 0.9,1.0
23,Kansas .....................,"87,206","89,875 93,263","99,090",0.9,0.9 0.9,0.9
24,Minnesota ...............,"190,567","199,271 210,184","225,625",1.9,1.9 1.9,1.9
25,Missouri ..................,"182,048","187,090 193,828","203,208",1.8,1.8 1.8,1.7
26,Nebraska ..................,"57,771","60,571 65,399","67,891",0.6,0.6 0.6,0.6
27,North Dakota ............,"18,800","20,007 21,597","23,581",0.2,0.2 0.2,0.2
28,South Dakota ............,"24,104","25,826 27,337","29,419",0.2,0.2 0.3,0.3
29,Southeast ..................,"2,209,061","2,298,332 2,422,079","2,581,437",22.0,22.1 22.2,22.2
30,Alabama ..................,"118,263","123,763 130,792","138,534",1.2,1.2 1.2,1.2
31,Arkansas ..................,"68,574","71,221 74,540","80,056",0.7,0.7 0.7,0.7
32,Florida .....................,"496,861","522,340 553,709","594,525",4.9,5.0 5.1,5.1
33,Georgia .....................,"299,507","307,443 321,199","340,719",3.0,3.0 2.9,2.9
34,Kentucky ..................,"116,545","121,633 128,315","135,412",1.2,1.2 1.2,1.2
35,Louisiana ..................,"137,567","134,360 144,321","151,993",1.4,1.3 1.3,1.3
36,Mississippi ...............,"65,725","68,550 71,872","76,205",0.7,0.7 0.7,0.7
37,North Carolina ............,"287,281","301,254 315,456","335,398",2.9,2.9 2.9,2.9
38,South Carolina .........,"117,779","122,274 127,963","135,253",1.2,1.2 1.2,1.2
39,Tennessee ...............,"180,232","191,394 203,071","216,939",1.8,1.8 1.9,1.9
40,Virginia .....................,"277,214","288,840 304,116","326,630",2.8,2.8 2.8,2.8
41,West Virginia ............,"43,512","45,259 46,726","49,774",0.4,0.4 0.4,0.4
42,Southwest ..................,"1,059,186","1,097,268 1,163,460","1,248,772",10.5,10.5 10.7,10.7
43,Arizona .....................,"164,263","173,052 183,272","199,660",1.6,1.7 1.7,1.7
44,New Mexico ...............,"50,908","53,414 57,078","60,940",0.5,0.5 0.5,0.5
45,Oklahoma ...............,"92,609","95,343 101,168","107,236",0.9,0.9 0.9,0.9
46,Texas .....................,"751,405","775,459 821,943","880,936",7.5,7.4 7.5,7.6
47,Rocky Mountain .........,"326,361","337,408 353,292","377,666",3.2,3.2 3.2,3.2
48,Colorado ..................,"177,526","181,246 188,397","199,953",1.8,1.7 1.7,1.7
49,Idaho ........................,"36,571","38,276 40,358","43,351",0.4,0.4 0.4,0.4
50,Montana ..................,"22,636","23,913 25,584","27,701",0.2,0.2 0.2,0.2
51,Utah ........................,"70,490","73,646 76,674","82,353",0.7,0.7 0.7,0.7
52,Wyoming ..................,"19,138","20,326 22,279","24,308",0.2,0.2 0.2,0.2
53,Far West ..................,"1,792,059","1,868,597 1,971,337","2,115,111",17.8,17.9 18.0,18.2
54,Alaska .....................,"27,358","29,741 31,704","33,876",0.3,0.3 0.3,0.3
55,California ..................,"1,307,880","1,363,577 1,438,134","1,543,835",13.0,13.1 13.2,13.3
56,Hawaii .....................,"41,720","43,806 46,671","50,134",0.4,0.4 0.4,0.4
57,Nevada .....................,"78,092","82,389 89,711","99,372",0.8,0.8 0.8,0.9
58,Oregon .....................,"111,352","115,113 119,973","128,126",1.1,1.1 1.1,1.1
59,Washington ...............,"225,656","233,971 245,143","259,768",2.2,2.2 2.2,2.2

In [15]:
GDP01_03.splitColumns(2, '2002', '2003')

,Area,2001,2002 2003,2004,2001.0,2002 2003,2004,2002,2003
0,United States .........,"10,058,156","10,412,244 10,923,849","11,649,827",100.0,100.0 100.0,100.0,"10,412,244","10,923,849"
1,New England ............,"584,487","596,017 620,136","664,181",5.8,5.7 5.7,5.7,"596,017","620,136"
2,Connecticut .............,"165,434","167,235 174,085","187,086",1.6,1.6 1.6,1.6,"167,235","174,085"
3,Maine .....................,"37,094","39,027 40,829","43,279",0.4,0.4 0.4,0.4,"39,027","40,829"
4,Massachusetts .........,"283,422","287,191 297,113","317,684",2.8,2.8 2.7,2.7,"287,191","297,113"
5,New Hampshire .........,"44,394","46,106 48,202","52,097",0.4,0.4 0.4,0.4,"46,106","48,202"
6,Rhode Island ............,"35,489","37,040 39,363","41,921",0.4,0.4 0.4,0.4,"37,040","39,363"
7,Vermont ..................,"18,656","19,419 20,544","22,114",0.2,0.2 0.2,0.2,"19,419","20,544"
8,Mideast .....................,"1,868,057","1,922,516 2,010,011","2,140,662",18.6,18.5 18.4,18.4,"1,922,516","2,010,011"
9,Delaware ..................,"45,049","46,991 50,486","54,500",0.4,0.5 0.5,0.5,"46,991","50,486"
10,District of Columbia ...,"63,223","67,176 70,668","75,264",0.6,0.6 0.6,0.6,"67,176","70,668"
11,Maryland ..................,"192,425","202,840 213,073","226,513",1.9,1.9 2.0,1.9,"202,840","213,073"
12,New Jersey ...............,"362,336","377,824 394,040","415,891",3.6,3.6 3.6,3.6,"377,824","394,040"
13,New York ..................,"797,145","802,866 838,035","899,660",7.9,7.7 7.7,7.7,"802,866","838,035"
14,Pennsylvania ............,"407,880","424,820 443,709","468,833",4.1,4.1 4.1,4.0,"424,820","443,709"
15,Great Lakes ...............,"1,565,557","1,611,658 1,669,527","1,758,915",15.6,15.5 15.3,15.1,"1,611,658","1,669,527"
16,Illinois .....................,"476,851","486,182 499,731","528,904",4.7,4.7 4.6,4.5,"486,182","499,731"
17,Indiana .....................,"195,769","203,296 213,342","227,271",1.9,2.0 2.0,2.0,"203,296","213,342"
18,Michigan ..................,"335,793","347,014 359,440","372,756",3.3,3.3 3.3,3.2,"347,014","359,440"
19,Ohio ........................,"374,771","385,657 398,918","418,258",3.7,3.7 3.7,3.6,"385,657","398,918"
20,Wisconsin ...............,"182,373","189,508 198,096","211,727",1.8,1.8 1.8,1.8,"189,508","198,096"
21,Plains ........................,"653,388","680,449 714,007","763,082",6.5,6.5 6.5,6.6,"680,449","714,007"
22,Iowa ........................,"92,891","97,810 102,400","114,269",0.9,0.9 0.9,1.0,"97,810","102,400"
23,Kansas .....................,"87,206","89,875 93,263","99,090",0.9,0.9 0.9,0.9,"89,875","93,263"
24,Minnesota ...............,"190,567","199,271 210,184","225,625",1.9,1.9 1.9,1.9,"199,271","210,184"
25,Missouri ..................,"182,048","187,090 193,828","203,208",1.8,1.8 1.8,1.7,"187,090","193,828"
26,Nebraska ..................,"57,771","60,571 65,399","67,891",0.6,0.6 0.6,0.6,"60,571","65,399"
27,North Dakota ............,"18,800","20,007 21,597","23,581",0.2,0.2 0.2,0.2,"20,007","21,597"
28,South Dakota ............,"24,104","25,826 27,337","29,419",0.2,0.2 0.3,0.3,"25,826","27,337"
29,Southeast ..................,"2,209,061","2,298,332 2,422,079","2,581,437",22.0,22.1 22.2,22.2,"2,298,332","2,422,079"
30,Alabama ..................,"118,263","123,763 130,792","138,534",1.2,1.2 1.2,1.2,"123,763","130,792"
31,Arkansas ..................,"68,574","71,221 74,540","80,056",0.7,0.7 0.7,0.7,"71,221","74,540"
32,Florida .....................,"496,861","522,340 553,709","594,525",4.9,5.0 5.1,5.1,"522,340","553,709"
33,Georgia .....................,"299,507","307,443 321,199","340,719",3.0,3.0 2.9,2.9,"307,443","321,199"
34,Kentucky ..................,"116,545","121,633 128,315","135,412",1.2,1.2 1.2,1.2,"121,633","128,315"
35,Louisiana ..................,"137,567","134,360 144,321","151,993",1.4,1.3 1.3,1.3,"134,360","144,321"
36,Mississippi ...............,"65,725","68,550 71,872","76,205",0.7,0.7 0.7,0.7,"68,550","71,872"
37,North Carolina ............,"287,281","301,254 315,456","335,398",2.9,2.9 2.9,2.9,"301,254","315,456"
38,South Carolina .........,"117,779","122,274 127,963","135,253",1.2,1.2 1.2,1.2,"122,274","127,963"
39,Tennessee ...............,"180,232","191,394 203,071","216,939",1.8,1.8 1.9,1.9,"191,394","203,071"
40,Virginia .....................,"277,214","288,840 304,116","326,630",2.8,2.8 2.8,2.8,"288,840","304,116"
41,West Virginia ............,"43,512","45,259 46,726","49,774",0.4,0.4 0.4,0.4,"45,259","46,726"
42,Southwest ..................,"1,059,186","1,097,268 1,163,460","1,248,772",10.5,10.5 10.7,10.7,"1,097,268","1,163,460"
43,Arizona .....................,"164,263","173,052 183,272","199,660",1.6,1.7 1.7,1.7,"173,052","183,272"
44,New Mexico ...............,"50,908","53,414 57,078","60,940",0.5,0.5 0.5,0.5,"53,414","57,078"
45,Oklahoma ...............,"92,609","95,343 101,168","107,236",0.9,0.9 0.9,0.9,"95,343","101,168"
46,Texas .....................,"751,405","775,459 821,943","880,936",7.5,7.4 7.5,7.6,"775,459","821,943"
47,Rocky Mountain .........,"326,361","337,408 353,292","377,666",3.2,3.2 3.2,3.2,"337,408","353,292"
48,Colorado ..................,"177,526","181,246 188,397","199,953",1.8,1.7 1.7,1.7,"181,246","188,397"
49,Idaho ........................,"36,571","38,276 40,358","43,351",0.4,0.4 0.4,0.4,"38,276","40,358"
50,Montana ..................,"22,636","23,913 25,584","27,701",0.2,0.2 0.2,0.2,"23,913","25,584"
51,Utah ........................,"70,490","73,646 76,674","82,353",0.7,0.7 0.7,0.7,"73,646","76,674"
52,Wyoming ..................,"19,138","20,326 22,279","24,308",0.2,0.2 0.2,0.2,"20,326","22,279"
53,Far West ..................,"1,792,059","1,868,597 1,971,337","2,115,111",17.8,17.9 18.0,18.2,"1,868,597","1,971,337"
54,Alaska .....................,"27,358","29,741 31,704","33,876",0.3,0.3 0.3,0.3,"29,741","31,704"
55,California ..................,"1,307,880","1,363,577 1,438,134","1,543,835",13.0,13.1 13.2,13.3,"1,363,577","1,438,134"
56,Hawaii .....................,"41,720","43,806 46,671","50,134",0.4,0.4 0.4,0.4,"43,806","46,671"
57,Nevada .....................,"78,092","82,389 89,711","99,372",0.8,0.8 0.8,0.9,"82,389","89,711"
58,Oregon .....................,"111,352","115,113 119,973","128,126",1.1,1.1 1.1,1.1,"115,113","119,973"
59,Washington ...............,"225,656","233,971 245,143","259,768",2.2,2.2 2.2,2.2,"233,971","245,143"

In [16]:
GDP01_03.splitColumns(5, '2002 %', '2003 %')

,Area,2001,2002 2003,2004,2001.0,2002 2003,2004,2002,2003,2002 %,2003 %
0,United States .........,"10,058,156","10,412,244 10,923,849","11,649,827",100.0,100.0 100.0,100.0,"10,412,244","10,923,849",100.0,100.0
1,New England ............,"584,487","596,017 620,136","664,181",5.8,5.7 5.7,5.7,"596,017","620,136",5.7,5.7
2,Connecticut .............,"165,434","167,235 174,085","187,086",1.6,1.6 1.6,1.6,"167,235","174,085",1.6,1.6
3,Maine .....................,"37,094","39,027 40,829","43,279",0.4,0.4 0.4,0.4,"39,027","40,829",0.4,0.4
4,Massachusetts .........,"283,422","287,191 297,113","317,684",2.8,2.8 2.7,2.7,"287,191","297,113",2.8,2.7
5,New Hampshire .........,"44,394","46,106 48,202","52,097",0.4,0.4 0.4,0.4,"46,106","48,202",0.4,0.4
6,Rhode Island ............,"35,489","37,040 39,363","41,921",0.4,0.4 0.4,0.4,"37,040","39,363",0.4,0.4
7,Vermont ..................,"18,656","19,419 20,544","22,114",0.2,0.2 0.2,0.2,"19,419","20,544",0.2,0.2
8,Mideast .....................,"1,868,057","1,922,516 2,010,011","2,140,662",18.6,18.5 18.4,18.4,"1,922,516","2,010,011",18.5,18.4
9,Delaware ..................,"45,049","46,991 50,486","54,500",0.4,0.5 0.5,0.5,"46,991","50,486",0.5,0.5
10,District of Columbia ...,"63,223","67,176 70,668","75,264",0.6,0.6 0.6,0.6,"67,176","70,668",0.6,0.6
11,Maryland ..................,"192,425","202,840 213,073","226,513",1.9,1.9 2.0,1.9,"202,840","213,073",1.9,2.0
12,New Jersey ...............,"362,336","377,824 394,040","415,891",3.6,3.6 3.6,3.6,"377,824","394,040",3.6,3.6
13,New York ..................,"797,145","802,866 838,035","899,660",7.9,7.7 7.7,7.7,"802,866","838,035",7.7,7.7
14,Pennsylvania ............,"407,880","424,820 443,709","468,833",4.1,4.1 4.1,4.0,"424,820","443,709",4.1,4.1
15,Great Lakes ...............,"1,565,557","1,611,658 1,669,527","1,758,915",15.6,15.5 15.3,15.1,"1,611,658","1,669,527",15.5,15.3
16,Illinois .....................,"476,851","486,182 499,731","528,904",4.7,4.7 4.6,4.5,"486,182","499,731",4.7,4.6
17,Indiana .....................,"195,769","203,296 213,342","227,271",1.9,2.0 2.0,2.0,"203,296","213,342",2.0,2.0
18,Michigan ..................,"335,793","347,014 359,440","372,756",3.3,3.3 3.3,3.2,"347,014","359,440",3.3,3.3
19,Ohio ........................,"374,771","385,657 398,918","418,258",3.7,3.7 3.7,3.6,"385,657","398,918",3.7,3.7
20,Wisconsin ...............,"182,373","189,508 198,096","211,727",1.8,1.8 1.8,1.8,"189,508","198,096",1.8,1.8
21,Plains ........................,"653,388","680,449 714,007","763,082",6.5,6.5 6.5,6.6,"680,449","714,007",6.5,6.5
22,Iowa ........................,"92,891","97,810 102,400","114,269",0.9,0.9 0.9,1.0,"97,810","102,400",0.9,0.9
23,Kansas .....................,"87,206","89,875 93,263","99,090",0.9,0.9 0.9,0.9,"89,875","93,263",0.9,0.9
24,Minnesota ...............,"190,567","199,271 210,184","225,625",1.9,1.9 1.9,1.9,"199,271","210,184",1.9,1.9
25,Missouri ..................,"182,048","187,090 193,828","203,208",1.8,1.8 1.8,1.7,"187,090","193,828",1.8,1.8
26,Nebraska ..................,"57,771","60,571 65,399","67,891",0.6,0.6 0.6,0.6,"60,571","65,399",0.6,0.6
27,North Dakota ............,"18,800","20,007 21,597","23,581",0.2,0.2 0.2,0.2,"20,007","21,597",0.2,0.2
28,South Dakota ............,"24,104","25,826 27,337","29,419",0.2,0.2 0.3,0.3,"25,826","27,337",0.2,0.3
29,Southeast ..................,"2,209,061","2,298,332 2,422,079","2,581,437",22.0,22.1 22.2,22.2,"2,298,332","2,422,079",22.1,22.2
30,Alabama ..................,"118,263","123,763 130,792","138,534",1.2,1.2 1.2,1.2,"123,763","130,792",1.2,1.2
31,Arkansas ..................,"68,574","71,221 74,540","80,056",0.7,0.7 0.7,0.7,"71,221","74,540",0.7,0.7
32,Florida .....................,"496,861","522,340 553,709","594,525",4.9,5.0 5.1,5.1,"522,340","553,709",5.0,5.1
33,Georgia .....................,"299,507","307,443 321,199","340,719",3.0,3.0 2.9,2.9,"307,443","321,199",3.0,2.9
34,Kentucky ..................,"116,545","121,633 128,315","135,412",1.2,1.2 1.2,1.2,"121,633","128,315",1.2,1.2
35,Louisiana ..................,"137,567","134,360 144,321","151,993",1.4,1.3 1.3,1.3,"134,360","144,321",1.3,1.3
36,Mississippi ...............,"65,725","68,550 71,872","76,205",0.7,0.7 0.7,0.7,"68,550","71,872",0.7,0.7
37,North Carolina ............,"287,281","301,254 315,456","335,398",2.9,2.9 2.9,2.9,"301,254","315,456",2.9,2.9
38,South Carolina .........,"117,779","122,274 127,963","135,253",1.2,1.2 1.2,1.2,"122,274","127,963",1.2,1.2
39,Tennessee ...............,"180,232","191,394 203,071","216,939",1.8,1.8 1.9,1.9,"191,394","203,071",1.8,1.9
40,Virginia .....................,"277,214","288,840 304,116","326,630",2.8,2.8 2.8,2.8,"288,840","304,116",2.8,2.8
41,West Virginia ............,"43,512","45,259 46,726","49,774",0.4,0.4 0.4,0.4,"45,259","46,726",0.4,0.4
42,Southwest ..................,"1,059,186","1,097,268 1,163,460","1,248,772",10.5,10.5 10.7,10.7,"1,097,268","1,163,460",10.5,10.7
43,Arizona .....................,"164,263","173,052 183,272","199,660",1.6,1.7 1.7,1.7,"173,052","183,272",1.7,1.7
44,New Mexico ...............,"50,908","53,414 57,078","60,940",0.5,0.5 0.5,0.5,"53,414","57,078",0.5,0.5
45,Oklahoma ...............,"92,609","95,343 101,168","107,236",0.9,0.9 0.9,0.9,"95,343","101,168",0.9,0.9
46,Texas .....................,"751,405","775,459 821,943","880,936",7.5,7.4 7.5,7.6,"775,459","821,943",7.4,7.5
47,Rocky Mountain .........,"326,361","337,408 353,292","377,666",3.2,3.2 3.2,3.2,"337,408","353,292",3.2,3.2
48,Colorado ..................,"177,526","181,246 188,397","199,953",1.8,1.7 1.7,1.7,"181,246","188,397",1.7,1.7
49,Idaho ........................,"36,571","38,276 40,358","43,351",0.4,0.4 0.4,0.4,"38,276","40,358",0.4,0.4
50,Montana ..................,"22,636","23,913 25,584","27,701",0.2,0.2 0.2,0.2,"23,913","25,584",0.2,0.2
51,Utah ........................,"70,490","73,646 76,674","82,353",0.7,0.7 0.7,0.7,"73,646","76,674",0.7,0.7
52,Wyoming ..................,"19,138","20,326 22,279","24,308",0.2,0.2 0.2,0.2,"20,326","22,279",0.2,0.2
53,Far West ..................,"1,792,059","1,868,597 1,971,337","2,115,111",17.8,17.9 18.0,18.2,"1,868,597","1,971,337",17.9,18.0
54,Alaska .....................,"27,358","29,741 31,704","33,876",0.3,0.3 0.3,0.3,"29,741","31,704",0.3,0.3
55,California ..................,"1,307,880","1,363,577 1,438,134","1,543,835",13.0,13.1 13.2,13.3,"1,363,577","1,438,134",13.1,13.2
56,Hawaii .....................,"41,720","43,806 46,671","50,134",0.4,0.4 0.4,0.4,"43,806","46,671",0.4,0.4
57,Nevada .....................,"78,092","82,389 89,711","99,372",0.8,0.8 0.8,0.9,"82,389","89,711",0.8,0.8
58,Oregon .....................,"111,352","115,113 119,973","128,126",1.1,1.1 1.1,1.1,"115,113","119,973",1.1,1.1
59,Washington ...............,"225,656","233,971 245,143","259,768",2.2,2.2 2.2,2.2,"233,971","245,143",2.2,2.2

In [17]:
GDP01_03.cleanStates('Area')

,Area,2001,2002 2003,2004,2001.0,2002 2003,2004,2002,2003,2002 %,2003 %,Cleaned Area
0,United States .........,"10,058,156","10,412,244 10,923,849","11,649,827",100.0,100.0 100.0,100.0,"10,412,244","10,923,849",100.0,100.0,United States
1,New England ............,"584,487","596,017 620,136","664,181",5.8,5.7 5.7,5.7,"596,017","620,136",5.7,5.7,New England
2,Connecticut .............,"165,434","167,235 174,085","187,086",1.6,1.6 1.6,1.6,"167,235","174,085",1.6,1.6,Connecticut
3,Maine .....................,"37,094","39,027 40,829","43,279",0.4,0.4 0.4,0.4,"39,027","40,829",0.4,0.4,Maine
4,Massachusetts .........,"283,422","287,191 297,113","317,684",2.8,2.8 2.7,2.7,"287,191","297,113",2.8,2.7,Massachusetts
5,New Hampshire .........,"44,394","46,106 48,202","52,097",0.4,0.4 0.4,0.4,"46,106","48,202",0.4,0.4,New Hampshire
6,Rhode Island ............,"35,489","37,040 39,363","41,921",0.4,0.4 0.4,0.4,"37,040","39,363",0.4,0.4,Rhode Island
7,Vermont ..................,"18,656","19,419 20,544","22,114",0.2,0.2 0.2,0.2,"19,419","20,544",0.2,0.2,Vermont
8,Mideast .....................,"1,868,057","1,922,516 2,010,011","2,140,662",18.6,18.5 18.4,18.4,"1,922,516","2,010,011",18.5,18.4,Mideast
9,Delaware ..................,"45,049","46,991 50,486","54,500",0.4,0.5 0.5,0.5,"46,991","50,486",0.5,0.5,Delaware
10,District of Columbia ...,"63,223","67,176 70,668","75,264",0.6,0.6 0.6,0.6,"67,176","70,668",0.6,0.6,District of Columbia
11,Maryland ..................,"192,425","202,840 213,073","226,513",1.9,1.9 2.0,1.9,"202,840","213,073",1.9,2.0,Maryland
12,New Jersey ...............,"362,336","377,824 394,040","415,891",3.6,3.6 3.6,3.6,"377,824","394,040",3.6,3.6,New Jersey
13,New York ..................,"797,145","802,866 838,035","899,660",7.9,7.7 7.7,7.7,"802,866","838,035",7.7,7.7,New York
14,Pennsylvania ............,"407,880","424,820 443,709","468,833",4.1,4.1 4.1,4.0,"424,820","443,709",4.1,4.1,Pennsylvania
15,Great Lakes ...............,"1,565,557","1,611,658 1,669,527","1,758,915",15.6,15.5 15.3,15.1,"1,611,658","1,669,527",15.5,15.3,Great Lakes
16,Illinois .....................,"476,851","486,182 499,731","528,904",4.7,4.7 4.6,4.5,"486,182","499,731",4.7,4.6,Illinois
17,Indiana .....................,"195,769","203,296 213,342","227,271",1.9,2.0 2.0,2.0,"203,296","213,342",2.0,2.0,Indiana
18,Michigan ..................,"335,793","347,014 359,440","372,756",3.3,3.3 3.3,3.2,"347,014","359,440",3.3,3.3,Michigan
19,Ohio ........................,"374,771","385,657 398,918","418,258",3.7,3.7 3.7,3.6,"385,657","398,918",3.7,3.7,Ohio
20,Wisconsin ...............,"182,373","189,508 198,096","211,727",1.8,1.8 1.8,1.8,"189,508","198,096",1.8,1.8,Wisconsin
21,Plains ........................,"653,388","680,449 714,007","763,082",6.5,6.5 6.5,6.6,"680,449","714,007",6.5,6.5,Plains
22,Iowa ........................,"92,891","97,810 102,400","114,269",0.9,0.9 0.9,1.0,"97,810","102,400",0.9,0.9,Iowa
23,Kansas .....................,"87,206","89,875 93,263","99,090",0.9,0.9 0.9,0.9,"89,875","93,263",0.9,0.9,Kansas
24,Minnesota ...............,"190,567","199,271 210,184","225,625",1.9,1.9 1.9,1.9,"199,271","210,184",1.9,1.9,Minnesota
25,Missouri ..................,"182,048","187,090 193,828","203,208",1.8,1.8 1.8,1.7,"187,090","193,828",1.8,1.8,Missouri
26,Nebraska ..................,"57,771","60,571 65,399","67,891",0.6,0.6 0.6,0.6,"60,571","65,399",0.6,0.6,Nebraska
27,North Dakota ............,"18,800","20,007 21,597","23,581",0.2,0.2 0.2,0.2,"20,007","21,597",0.2,0.2,North Dakota
28,South Dakota ............,"24,104","25,826 27,337","29,419",0.2,0.2 0.3,0.3,"25,826","27,337",0.2,0.3,South Dakota
29,Southeast ..................,"2,209,061","2,298,332 2,422,079","2,581,437",22.0,22.1 22.2,22.2,"2,298,332","2,422,079",22.1,22.2,Southeast
30,Alabama ..................,"118,263","123,763 130,792","138,534",1.2,1.2 1.2,1.2,"123,763","130,792",1.2,1.2,Alabama
31,Arkansas ..................,"68,574","71,221 74,540","80,056",0.7,0.7 0.7,0.7,"71,221","74,540",0.7,0.7,Arkansas
32,Florida .....................,"496,861","522,340 553,709","594,525",4.9,5.0 5.1,5.1,"522,340","553,709",5.0,5.1,Florida
33,Georgia .....................,"299,507","307,443 321,199","340,719",3.0,3.0 2.9,2.9,"307,443","321,199",3.0,2.9,Georgia
34,Kentucky ..................,"116,545","121,633 128,315","135,412",1.2,1.2 1.2,1.2,"121,633","128,315",1.2,1.2,Kentucky
35,Louisiana ..................,"137,567","134,360 144,321","151,993",1.4,1.3 1.3,1.3,"134,360","144,321",1.3,1.3,Louisiana
36,Mississippi ...............,"65,725","68,550 71,872","76,205",0.7,0.7 0.7,0.7,"68,550","71,872",0.7,0.7,Mississippi
37,North Carolina ............,"287,281","301,254 315,456","335,398",2.9,2.9 2.9,2.9,"301,254","315,456",2.9,2.9,North Carolina
38,South Carolina .........,"117,779","122,274 127,963","135,253",1.2,1.2 1.2,1.2,"122,274","127,963",1.2,1.2,South Carolina
39,Tennessee ...............,"180,232","191,394 203,071","216,939",1.8,1.8 1.9,1.9,"191,394","203,071",1.8,1.9,Tennessee
40,Virginia .....................,"277,214","288,840 304,116","326,630",2.8,2.8 2.8,2.8,"288,840","304,116",2.8,2.8,Virginia
41,West Virginia ............,"43,512","45,259 46,726","49,774",0.4,0.4 0.4,0.4,"45,259","46,726",0.4,0.4,West Virginia
42,Southwest ..................,"1,059,186","1,097,268 1,163,460","1,248,772",10.5,10.5 10.7,10.7,"1,097,268","1,163,460",10.5,10.7,Southwest
43,Arizona .....................,"164,263","173,052 183,272","199,660",1.6,1.7 1.7,1.7,"173,052","183,272",1.7,1.7,Arizona
44,New Mexico ...............,"50,908","53,414 57,078","60,940",0.5,0.5 0.5,0.5,"53,414","57,078",0.5,0.5,New Mexico
45,Oklahoma ...............,"92,609","95,343 101,168","107,236",0.9,0.9 0.9,0.9,"95,343","101,168",0.9,0.9,Oklahoma
46,Texas .....................,"751,405","775,459 821,943","880,936",7.5,7.4 7.5,7.6,"775,459","821,943",7.4,7.5,Texas
47,Rocky Mountain .........,"326,361","337,408 353,292","377,666",3.2,3.2 3.2,3.2,"337,408","353,292",3.2,3.2,Rocky Mountain
48,Colorado ..................,"177,526","181,246 188,397","199,953",1.8,1.7 1.7,1.7,"181,246","188,397",1.7,1.7,Colorado
49,Idaho ........................,"36,571","38,276 40,358","43,351",0.4,0.4 0.4,0.4,"38,276","40,358",0.4,0.4,Idaho
50,Montana ..................,"22,636","23,913 25,584","27,701",0.2,0.2 0.2,0.2,"23,913","25,584",0.2,0.2,Montana
51,Utah ........................,"70,490","73,646 76,674","82,353",0.7,0.7 0.7,0.7,"73,646","76,674",0.7,0.7,Utah
52,Wyoming ..................,"19,138","20,326 22,279","24,308",0.2,0.2 0.2,0.2,"20,326","22,279",0.2,0.2,Wyoming
53,Far West ..................,"1,792,059","1,868,597 1,971,337","2,115,111",17.8,17.9 18.0,18.2,"1,868,597","1,971,337",17.9,18.0,Far West
54,Alaska .....................,"27,358","29,741 31,704","33,876",0.3,0.3 0.3,0.3,"29,741","31,704",0.3,0.3,Alaska
55,California ..................,"1,307,880","1,363,577 1,438,134","1,543,835",13.0,13.1 13.2,13.3,"1,363,577","1,438,134",13.1,13.2,California
56,Hawaii .....................,"41,720","43,806 46,671","50,134",0.4,0.4 0.4,0.4,"43,806","46,671",0.4,0.4,Hawaii
57,Nevada .....................,"78,092","82,389 89,711","99,372",0.8,0.8 0.8,0.9,"82,389","89,711",0.8,0.8,Nevada
58,Oregon .....................,"111,352","115,113 119,973","128,126",1.1,1.1 1.1,1.1,"115,113","119,973",1.1,1.1,Oregon
59,Washington ...............,"225,656","233,971 245,143","259,768",2.2,2.2 2.2,2.2,"233,971","245,143",2.2,2.2,Washington

In [18]:
GDP01_03.addGeoLocColumn('Cleaned Area')

,Area,2001,2002 2003,2004,2001.0,2002 2003,2004,2002,2003,2002 %,2003 %,Cleaned Area,Geo Loc
0,United States .........,"10,058,156","10,412,244 10,923,849","11,649,827",100.0,100.0 100.0,100.0,"10,412,244","10,923,849",100.0,100.0,United States,NaN
1,New England ............,"584,487","596,017 620,136","664,181",5.8,5.7 5.7,5.7,"596,017","620,136",5.7,5.7,New England,NaN
2,Connecticut .............,"165,434","167,235 174,085","187,086",1.6,1.6 1.6,1.6,"167,235","174,085",1.6,1.6,Connecticut,New England
3,Maine .....................,"37,094","39,027 40,829","43,279",0.4,0.4 0.4,0.4,"39,027","40,829",0.4,0.4,Maine,New England
4,Massachusetts .........,"283,422","287,191 297,113","317,684",2.8,2.8 2.7,2.7,"287,191","297,113",2.8,2.7,Massachusetts,New England
5,New Hampshire .........,"44,394","46,106 48,202","52,097",0.4,0.4 0.4,0.4,"46,106","48,202",0.4,0.4,New Hampshire,New England
6,Rhode Island ............,"35,489","37,040 39,363","41,921",0.4,0.4 0.4,0.4,"37,040","39,363",0.4,0.4,Rhode Island,New England
7,Vermont ..................,"18,656","19,419 20,544","22,114",0.2,0.2 0.2,0.2,"19,419","20,544",0.2,0.2,Vermont,New England
8,Mideast .....................,"1,868,057","1,922,516 2,010,011","2,140,662",18.6,18.5 18.4,18.4,"1,922,516","2,010,011",18.5,18.4,Mideast,NaN
9,Delaware ..................,"45,049","46,991 50,486","54,500",0.4,0.5 0.5,0.5,"46,991","50,486",0.5,0.5,Delaware,Mideast
10,District of Columbia ...,"63,223","67,176 70,668","75,264",0.6,0.6 0.6,0.6,"67,176","70,668",0.6,0.6,District of Columbia,Mideast
11,Maryland ..................,"192,425","202,840 213,073","226,513",1.9,1.9 2.0,1.9,"202,840","213,073",1.9,2.0,Maryland,Mideast
12,New Jersey ...............,"362,336","377,824 394,040","415,891",3.6,3.6 3.6,3.6,"377,824","394,040",3.6,3.6,New Jersey,Mideast
13,New York ..................,"797,145","802,866 838,035","899,660",7.9,7.7 7.7,7.7,"802,866","838,035",7.7,7.7,New York,Mideast
14,Pennsylvania ............,"407,880","424,820 443,709","468,833",4.1,4.1 4.1,4.0,"424,820","443,709",4.1,4.1,Pennsylvania,Mideast
15,Great Lakes ...............,"1,565,557","1,611,658 1,669,527","1,758,915",15.6,15.5 15.3,15.1,"1,611,658","1,669,527",15.5,15.3,Great Lakes,NaN
16,Illinois .....................,"476,851","486,182 499,731","528,904",4.7,4.7 4.6,4.5,"486,182","499,731",4.7,4.6,Illinois,Great Lakes
17,Indiana .....................,"195,769","203,296 213,342","227,271",1.9,2.0 2.0,2.0,"203,296","213,342",2.0,2.0,Indiana,Great Lakes
18,Michigan ..................,"335,793","347,014 359,440","372,756",3.3,3.3 3.3,3.2,"347,014","359,440",3.3,3.3,Michigan,Great Lakes
19,Ohio ........................,"374,771","385,657 398,918","418,258",3.7,3.7 3.7,3.6,"385,657","398,918",3.7,3.7,Ohio,Great Lakes
20,Wisconsin ...............,"182,373","189,508 198,096","211,727",1.8,1.8 1.8,1.8,"189,508","198,096",1.8,1.8,Wisconsin,Great Lakes
21,Plains ........................,"653,388","680,449 714,007","763,082",6.5,6.5 6.5,6.6,"680,449","714,007",6.5,6.5,Plains,NaN
22,Iowa ........................,"92,891","97,810 102,400","114,269",0.9,0.9 0.9,1.0,"97,810","102,400",0.9,0.9,Iowa,Plains
23,Kansas .....................,"87,206","89,875 93,263","99,090",0.9,0.9 0.9,0.9,"89,875","93,263",0.9,0.9,Kansas,Plains
24,Minnesota ...............,"190,567","199,271 210,184","225,625",1.9,1.9 1.9,1.9,"199,271","210,184",1.9,1.9,Minnesota,Plains
25,Missouri ..................,"182,048","187,090 193,828","203,208",1.8,1.8 1.8,1.7,"187,090","193,828",1.8,1.8,Missouri,Plains
26,Nebraska ..................,"57,771","60,571 65,399","67,891",0.6,0.6 0.6,0.6,"60,571","65,399",0.6,0.6,Nebraska,Plains
27,North Dakota ............,"18,800","20,007 21,597","23,581",0.2,0.2 0.2,0.2,"20,007","21,597",0.2,0.2,North Dakota,Plains
28,South Dakota ............,"24,104","25,826 27,337","29,419",0.2,0.2 0.3,0.3,"25,826","27,337",0.2,0.3,South Dakota,Plains
29,Southeast ..................,"2,209,061","2,298,332 2,422,079","2,581,437",22.0,22.1 22.2,22.2,"2,298,332","2,422,079",22.1,22.2,Southeast,NaN
30,Alabama ..................,"118,263","123,763 130,792","138,534",1.2,1.2 1.2,1.2,"123,763","130,792",1.2,1.2,Alabama,Southeast
31,Arkansas ..................,"68,574","71,221 74,540","80,056",0.7,0.7 0.7,0.7,"71,221","74,540",0.7,0.7,Arkansas,Southeast
32,Florida .....................,"496,861","522,340 553,709","594,525",4.9,5.0 5.1,5.1,"522,340","553,709",5.0,5.1,Florida,Southeast
33,Georgia .....................,"299,507","307,443 321,199","340,719",3.0,3.0 2.9,2.9,"307,443","321,199",3.0,2.9,Georgia,Southeast
34,Kentucky ..................,"116,545","121,633 128,315","135,412",1.2,1.2 1.2,1.2,"121,633","128,315",1.2,1.2,Kentucky,Southeast
35,Louisiana ..................,"137,567","134,360 144,321","151,993",1.4,1.3 1.3,1.3,"134,360","144,321",1.3,1.3,Louisiana,Southeast
36,Mississippi ...............,"65,725","68,550 71,872","76,205",0.7,0.7 0.7,0.7,"68,550","71,872",0.7,0.7,Mississippi,Southeast
37,North Carolina ............,"287,281","301,254 315,456","335,398",2.9,2.9 2.9,2.9,"301,254","315,456",2.9,2.9,North Carolina,Southeast
38,South Carolina .........,"117,779","122,274 127,963","135,253",1.2,1.2 1.2,1.2,"122,274","127,963",1.2,1.2,South Carolina,Southeast
39,Tennessee ...............,"180,232","191,394 203,071","216,939",1.8,1.8 1.9,1.9,"191,394","203,071",1.8,1.9,Tennessee,Southeast
40,Virginia .....................,"277,214","288,840 304,116","326,630",2.8,2.8 2.8,2.8,"288,840","304,116",2.8,2.8,Virginia,Southeast
41,West Virginia ............,"43,512","45,259 46,726","49,774",0.4,0.4 0.4,0.4,"45,259","46,726",0.4,0.4,West Virginia,Southeast
42,Southwest ..................,"1,059,186","1,097,268 1,163,460","1,248,772",10.5,10.5 10.7,10.7,"1,097,268","1,163,460",10.5,10.7,Southwest,NaN
43,Arizona .....................,"164,263","173,052 183,272","199,660",1.6,1.7 1.7,1.7,"173,052","183,272",1.7,1.7,Arizona,Southwest
44,New Mexico ...............,"50,908","53,414 57,078","60,940",0.5,0.5 0.5,0.5,"53,414","57,078",0.5,0.5,New Mexico,Southwest
45,Oklahoma ...............,"92,609","95,343 101,168","107,236",0.9,0.9 0.9,0.9,"95,343","101,168",0.9,0.9,Oklahoma,Southwest
46,Texas .....................,"751,405","775,459 821,943","880,936",7.5,7.4 7.5,7.6,"775,459","821,943",7.4,7.5,Texas,Southwest
47,Rocky Mountain .........,"326,361","337,408 353,292","377,666",3.2,3.2 3.2,3.2,"337,408","353,292",3.2,3.2,Rocky Mountain,NaN
48,Colorado ..................,"177,526","181,246 188,397","199,953",1.8,1.7 1.7,1.7,"181,246","188,397",1.7,1.7,Colorado,Rocky Mountain
49,Idaho ........................,"36,571","38,276 40,358","43,351",0.4,0.4 0.4,0.4,"38,276","40,358",0.4,0.4,Idaho,Rocky Mountain
50,Montana ..................,"22,636","23,913 25,584","27,701",0.2,0.2 0.2,0.2,"23,913","25,584",0.2,0.2,Montana,Rocky Mountain
51,Utah ........................,"70,490","73,646 76,674","82,353",0.7,0.7 0.7,0.7,"73,646","76,674",0.7,0.7,Utah,Rocky Mountain
52,Wyoming ..................,"19,138","20,326 22,279","24,308",0.2,0.2 0.2,0.2,"20,326","22,279",0.2,0.2,Wyoming,Rocky Mountain
53,Far West ..................,"1,792,059","1,868,597 1,971,337","2,115,111",17.8,17.9 18.0,18.2,"1,868,597","1,971,337",17.9,18.0,Far West,NaN
54,Alaska .....................,"27,358","29,741 31,704","33,876",0.3,0.3 0.3,0.3,"29,741","31,704",0.3,0.3,Alaska,Far West
55,California ..................,"1,307,880","1,363,577 1,438,134","1,543,835",13.0,13.1 13.2,13.3,"1,363,577","1,438,134",13.1,13.2,California,Far West
56,Hawaii .....................,"41,720","43,806 46,671","50,134",0.4,0.4 0.4,0.4,"43,806","46,671",0.4,0.4,Hawaii,Far West
57,Nevada .....................,"78,092","82,389 89,711","99,372",0.8,0.8 0.8,0.9,"82,389","89,711",0.8,0.8,Nevada,Far West
58,Oregon .....................,"111,352","115,113 119,973","128,126",1.1,1.1 1.1,1.1,"115,113","119,973",1.1,1.1,Oregon,Far West
59,Washington ...............,"225,656","233,971 245,143","259,768",2.2,2.2 2.2,2.2,"233,971","245,143",2.2,2.2,Washington,Far West

In [19]:
GDP01_03.restructureDataFrame('Cleaned Area')

     year          state current dollars        GDP        GDP_area
0    2001         Alaska            2004    27358.0        Far West
1    2001        Alabama            2004   118263.0       Southeast
2    2001       Arkansas            2004    68574.0       Southeast
3    2001        Arizona            2004   164263.0       Southwest
4    2001     California            2004  1307880.0        Far West
..    ...            ...             ...        ...             ...
148  2003        Vermont            2004    20544.0     New England
149  2003     Washington            2004   245143.0        Far West
150  2003      Wisconsin            2004   198096.0     Great Lakes
151  2003  West Virginia            2004    46726.0       Southeast
152  2003        Wyoming            2004    22279.0  Rocky Mountain

[153 rows x 5 columns]

In [20]:
GDP01_03.df

     year          state current dollars        GDP        GDP_area
0    2001         Alaska            2004    27358.0        Far West
1    2001        Alabama            2004   118263.0       Southeast
2    2001       Arkansas            2004    68574.0       Southeast
3    2001        Arizona            2004   164263.0       Southwest
4    2001     California            2004  1307880.0        Far West
..    ...            ...             ...        ...             ...
148  2003        Vermont            2004    20544.0     New England
149  2003     Washington            2004   245143.0        Far West
150  2003      Wisconsin            2004   198096.0     Great Lakes
151  2003  West Virginia            2004    46726.0       Southeast
152  2003        Wyoming            2004    22279.0  Rocky Mountain

[153 rows x 5 columns]

#  GDP 04 - 06

In [21]:
# create instance of yearly GDP data
GDP04_06 = YearlyGDP('GDP2004-2006.pdf', 11, 2004, 2006, '2007')

In [22]:
# testing that it was initialized with an empty DataFrame
GDP04_06.df

Empty DataFrame
Columns: []
Index: []

In [23]:
# initializeDataFrame() method reads in the PDF, assigns the first DataFrame in the 
# list as the df (only one table per page), and renames the columns. Lastly, it returns 
# the DataFrame for viewing
GDP04_06.initializeDataFrame()

,Area,2004,2005 2006,2007,2004.0,2005 2006,2007
0,United States...............,"11,607,041","12,346,871 13,119,938","13,743,021",100.0,100.0 100.0,100.0
1,New England..................,"647,473","674,562 712,051","744,672",5.6,5.5 5.4,5.4
2,Connecticut.....................,"182,112","193,281 204,964","216,266",1.6,1.6 1.6,1.6
3,Maine............................,"43,191","44,364 46,340","48,108",0.4,0.4 0.4,0.4
4,Massachusetts..................,"306,827","317,626 335,313","351,514",2.6,2.6 2.6,2.6
5,New Hampshire...............,"51,432","53,468 56,073","57,341",0.4,0.4 0.4,0.4
6,Rhode Island..................,"42,073","43,078 45,733","46,900",0.4,0.3 0.3,0.3
7,Vermont........................,"21,839","22,745 23,628","24,543",0.2,0.2 0.2,0.2
8,Mideast...........................,"2,124,891","2,245,718 2,390,856","2,522,240",18.3,18.2 18.2,18.4
9,Delaware........................,"52,305","57,334 59,589","60,118",0.5,0.5 0.5,0.4
10,District of Columbia.........,"77,913","82,978 88,174","93,819",0.7,0.7 0.7,0.7
11,Maryland........................,"228,223","243,855 257,577","268,685",2.0,2.0 2.0,2.0
12,New Jersey.....................,"410,096","425,497 448,426","465,484",3.5,3.4 3.4,3.4
13,New York........................,"896,422","953,641 1,028,320","1,103,024",7.7,7.7 7.8,8.0
14,Pennsylvania..................,"459,932","482,413 508,769","531,110",4.0,3.9 3.9,3.9
15,Great Lakes.....................,"1,755,486","1,812,433 1,873,436","1,936,573",15.1,14.7 14.3,14.1
16,Illinois...........................,"534,429","554,099 583,990","609,570",4.6,4.5 4.5,4.4
17,Indiana...........................,"228,329","232,799 238,693","246,439",2.0,1.9 1.8,1.8
18,Michigan........................,"363,076","372,174 375,759","381,963",3.1,3.0 2.9,2.8
19,Ohio.............................,"423,735","439,271 451,600","466,309",3.7,3.6 3.4,3.4
20,Wisconsin........................,"205,916","214,090 223,394","232,293",1.8,1.7 1.7,1.7
21,Plains.............................,"759,398","790,222 827,927","872,523",6.5,6.4 6.3,6.3
22,Iowa.............................,"111,937","115,632 121,945","129,026",1.0,0.9 0.9,0.9
23,Kansas...........................,"98,426","103,305 110,645","117,305",0.8,0.8 0.8,0.9
24,Minnesota........................,"223,454","232,001 242,095","254,970",1.9,1.9 1.8,1.9
25,Missouri........................,"204,916","213,012 220,092","229,470",1.8,1.7 1.7,1.7
26,Nebraska........................,"68,404","71,150 75,290","80,093",0.6,0.6 0.6,0.6
27,North Dakota..................,"22,739","24,648 25,851","27,725",0.2,0.2 0.2,0.2
28,South Dakota..................,"29,522","30,473 32,008","33,934",0.3,0.2 0.2,0.2
29,Southeast........................,"2,586,745","2,783,933 2,964,029","3,087,889",22.3,22.5 22.6,22.5
30,Alabama........................,"141,527","150,513 158,566","165,796",1.2,1.2 1.2,1.2
31,Arkansas........................,"82,137","86,139 90,864","95,371",0.7,0.7 0.7,0.7
32,Florida...........................,"607,284","670,237 716,505","734,519",5.2,5.4 5.5,5.3
33,Georgia...........................,"338,470","359,694 376,410","396,504",2.9,2.9 2.9,2.9
34,Kentucky........................,"131,741","138,542 146,415","154,184",1.1,1.1 1.1,1.1
35,Louisiana........................,"163,427","184,042 203,167","216,146",1.4,1.5 1.5,1.6
36,Mississippi.....................,"76,499","79,461 84,586","88,546",0.7,0.6 0.6,0.6
37,North Carolina..................,"324,383","349,216 380,932","399,446",2.8,2.8 2.9,2.9
38,South Carolina..................,"131,851","138,619 146,211","152,830",1.1,1.1 1.1,1.1
39,Tennessee.....................,"214,849","224,169 235,753","243,869",1.9,1.8 1.8,1.8
40,Virginia...........................,"324,870","350,288 368,604","382,964",2.8,2.8 2.8,2.8
41,West Virginia..................,"49,706","53,013 56,016","57,711",0.4,0.4 0.4,0.4
42,Southwest........................,"1,270,084","1,384,061 1,507,770","1,604,494",10.9,11.2 11.5,11.7
43,Arizona...........................,"193,448","215,844 237,397","247,028",1.7,1.7 1.8,1.8
44,New Mexico.....................,"63,452","68,153 72,161","76,178",0.5,0.6 0.6,0.6
45,Oklahoma........................,"111,511","120,753 130,094","139,323",1.0,1.0 1.0,1.0
46,Texas............................,"901,673","979,311 1,068,119","1,141,965",7.8,7.9 8.1,8.3
47,Rocky Mountain...............,"371,715","405,194 434,568","458,897",3.2,3.3 3.3,3.3
48,Colorado........................,"197,329","213,326 226,266","236,324",1.7,1.7 1.7,1.7
49,Idaho............................,"42,626","46,369 48,441","51,149",0.4,0.4 0.4,0.4
50,Montana........................,"27,452","29,966 31,994","34,253",0.2,0.2 0.2,0.2
51,Utah.............................,"80,889","88,944 97,963","105,658",0.7,0.7 0.7,0.8
52,Wyoming........................,"23,420","26,589 29,904","31,514",0.2,0.2 0.2,0.2
53,Far West...........................,"2,091,250","2,250,748 2,409,301","2,515,732",18.0,18.2 18.4,18.3
54,Alaska...........................,"35,102","39,298 43,117","44,517",0.3,0.3 0.3,0.3
55,California........................,"1,519,443","1,632,822 1,742,172","1,812,968",13.1,13.2 13.3,13.2
56,Hawaii...........................,"50,414","54,863 58,676","61,532",0.4,0.4 0.4,0.4
57,Nevada...........................,"100,209","112,451 123,054","127,213",0.9,0.9 0.9,0.9
58,Oregon...........................,"132,835","138,057 150,984","158,233",1.1,1.1 1.2,1.2
59,Washington.....................,"253,247","273,257 291,298","311,270",2.2,2.2 2.2,2.3

In [24]:
GDP04_06.splitColumns(2, '2005', '2006')

,Area,2004,2005 2006,2007,2004.0,2005 2006,2007,2005,2006
0,United States...............,"11,607,041","12,346,871 13,119,938","13,743,021",100.0,100.0 100.0,100.0,"12,346,871","13,119,938"
1,New England..................,"647,473","674,562 712,051","744,672",5.6,5.5 5.4,5.4,"674,562","712,051"
2,Connecticut.....................,"182,112","193,281 204,964","216,266",1.6,1.6 1.6,1.6,"193,281","204,964"
3,Maine............................,"43,191","44,364 46,340","48,108",0.4,0.4 0.4,0.4,"44,364","46,340"
4,Massachusetts..................,"306,827","317,626 335,313","351,514",2.6,2.6 2.6,2.6,"317,626","335,313"
5,New Hampshire...............,"51,432","53,468 56,073","57,341",0.4,0.4 0.4,0.4,"53,468","56,073"
6,Rhode Island..................,"42,073","43,078 45,733","46,900",0.4,0.3 0.3,0.3,"43,078","45,733"
7,Vermont........................,"21,839","22,745 23,628","24,543",0.2,0.2 0.2,0.2,"22,745","23,628"
8,Mideast...........................,"2,124,891","2,245,718 2,390,856","2,522,240",18.3,18.2 18.2,18.4,"2,245,718","2,390,856"
9,Delaware........................,"52,305","57,334 59,589","60,118",0.5,0.5 0.5,0.4,"57,334","59,589"
10,District of Columbia.........,"77,913","82,978 88,174","93,819",0.7,0.7 0.7,0.7,"82,978","88,174"
11,Maryland........................,"228,223","243,855 257,577","268,685",2.0,2.0 2.0,2.0,"243,855","257,577"
12,New Jersey.....................,"410,096","425,497 448,426","465,484",3.5,3.4 3.4,3.4,"425,497","448,426"
13,New York........................,"896,422","953,641 1,028,320","1,103,024",7.7,7.7 7.8,8.0,"953,641","1,028,320"
14,Pennsylvania..................,"459,932","482,413 508,769","531,110",4.0,3.9 3.9,3.9,"482,413","508,769"
15,Great Lakes.....................,"1,755,486","1,812,433 1,873,436","1,936,573",15.1,14.7 14.3,14.1,"1,812,433","1,873,436"
16,Illinois...........................,"534,429","554,099 583,990","609,570",4.6,4.5 4.5,4.4,"554,099","583,990"
17,Indiana...........................,"228,329","232,799 238,693","246,439",2.0,1.9 1.8,1.8,"232,799","238,693"
18,Michigan........................,"363,076","372,174 375,759","381,963",3.1,3.0 2.9,2.8,"372,174","375,759"
19,Ohio.............................,"423,735","439,271 451,600","466,309",3.7,3.6 3.4,3.4,"439,271","451,600"
20,Wisconsin........................,"205,916","214,090 223,394","232,293",1.8,1.7 1.7,1.7,"214,090","223,394"
21,Plains.............................,"759,398","790,222 827,927","872,523",6.5,6.4 6.3,6.3,"790,222","827,927"
22,Iowa.............................,"111,937","115,632 121,945","129,026",1.0,0.9 0.9,0.9,"115,632","121,945"
23,Kansas...........................,"98,426","103,305 110,645","117,305",0.8,0.8 0.8,0.9,"103,305","110,645"
24,Minnesota........................,"223,454","232,001 242,095","254,970",1.9,1.9 1.8,1.9,"232,001","242,095"
25,Missouri........................,"204,916","213,012 220,092","229,470",1.8,1.7 1.7,1.7,"213,012","220,092"
26,Nebraska........................,"68,404","71,150 75,290","80,093",0.6,0.6 0.6,0.6,"71,150","75,290"
27,North Dakota..................,"22,739","24,648 25,851","27,725",0.2,0.2 0.2,0.2,"24,648","25,851"
28,South Dakota..................,"29,522","30,473 32,008","33,934",0.3,0.2 0.2,0.2,"30,473","32,008"
29,Southeast........................,"2,586,745","2,783,933 2,964,029","3,087,889",22.3,22.5 22.6,22.5,"2,783,933","2,964,029"
30,Alabama........................,"141,527","150,513 158,566","165,796",1.2,1.2 1.2,1.2,"150,513","158,566"
31,Arkansas........................,"82,137","86,139 90,864","95,371",0.7,0.7 0.7,0.7,"86,139","90,864"
32,Florida...........................,"607,284","670,237 716,505","734,519",5.2,5.4 5.5,5.3,"670,237","716,505"
33,Georgia...........................,"338,470","359,694 376,410","396,504",2.9,2.9 2.9,2.9,"359,694","376,410"
34,Kentucky........................,"131,741","138,542 146,415","154,184",1.1,1.1 1.1,1.1,"138,542","146,415"
35,Louisiana........................,"163,427","184,042 203,167","216,146",1.4,1.5 1.5,1.6,"184,042","203,167"
36,Mississippi.....................,"76,499","79,461 84,586","88,546",0.7,0.6 0.6,0.6,"79,461","84,586"
37,North Carolina..................,"324,383","349,216 380,932","399,446",2.8,2.8 2.9,2.9,"349,216","380,932"
38,South Carolina..................,"131,851","138,619 146,211","152,830",1.1,1.1 1.1,1.1,"138,619","146,211"
39,Tennessee.....................,"214,849","224,169 235,753","243,869",1.9,1.8 1.8,1.8,"224,169","235,753"
40,Virginia...........................,"324,870","350,288 368,604","382,964",2.8,2.8 2.8,2.8,"350,288","368,604"
41,West Virginia..................,"49,706","53,013 56,016","57,711",0.4,0.4 0.4,0.4,"53,013","56,016"
42,Southwest........................,"1,270,084","1,384,061 1,507,770","1,604,494",10.9,11.2 11.5,11.7,"1,384,061","1,507,770"
43,Arizona...........................,"193,448","215,844 237,397","247,028",1.7,1.7 1.8,1.8,"215,844","237,397"
44,New Mexico.....................,"63,452","68,153 72,161","76,178",0.5,0.6 0.6,0.6,"68,153","72,161"
45,Oklahoma........................,"111,511","120,753 130,094","139,323",1.0,1.0 1.0,1.0,"120,753","130,094"
46,Texas............................,"901,673","979,311 1,068,119","1,141,965",7.8,7.9 8.1,8.3,"979,311","1,068,119"
47,Rocky Mountain...............,"371,715","405,194 434,568","458,897",3.2,3.3 3.3,3.3,"405,194","434,568"
48,Colorado........................,"197,329","213,326 226,266","236,324",1.7,1.7 1.7,1.7,"213,326","226,266"
49,Idaho............................,"42,626","46,369 48,441","51,149",0.4,0.4 0.4,0.4,"46,369","48,441"
50,Montana........................,"27,452","29,966 31,994","34,253",0.2,0.2 0.2,0.2,"29,966","31,994"
51,Utah.............................,"80,889","88,944 97,963","105,658",0.7,0.7 0.7,0.8,"88,944","97,963"
52,Wyoming........................,"23,420","26,589 29,904","31,514",0.2,0.2 0.2,0.2,"26,589","29,904"
53,Far West...........................,"2,091,250","2,250,748 2,409,301","2,515,732",18.0,18.2 18.4,18.3,"2,250,748","2,409,301"
54,Alaska...........................,"35,102","39,298 43,117","44,517",0.3,0.3 0.3,0.3,"39,298","43,117"
55,California........................,"1,519,443","1,632,822 1,742,172","1,812,968",13.1,13.2 13.3,13.2,"1,632,822","1,742,172"
56,Hawaii...........................,"50,414","54,863 58,676","61,532",0.4,0.4 0.4,0.4,"54,863","58,676"
57,Nevada...........................,"100,209","112,451 123,054","127,213",0.9,0.9 0.9,0.9,"112,451","123,054"
58,Oregon...........................,"132,835","138,057 150,984","158,233",1.1,1.1 1.2,1.2,"138,057","150,984"
59,Washington.....................,"253,247","273,257 291,298","311,270",2.2,2.2 2.2,2.3,"273,257","291,298"

In [25]:
GDP04_06.splitColumns(5, '2005 %', '2006 %')

,Area,2004,2005 2006,2007,2004.0,2005 2006,2007,2005,2006,2005 %,2006 %
0,United States...............,"11,607,041","12,346,871 13,119,938","13,743,021",100.0,100.0 100.0,100.0,"12,346,871","13,119,938",100.0,100.0
1,New England..................,"647,473","674,562 712,051","744,672",5.6,5.5 5.4,5.4,"674,562","712,051",5.5,5.4
2,Connecticut.....................,"182,112","193,281 204,964","216,266",1.6,1.6 1.6,1.6,"193,281","204,964",1.6,1.6
3,Maine............................,"43,191","44,364 46,340","48,108",0.4,0.4 0.4,0.4,"44,364","46,340",0.4,0.4
4,Massachusetts..................,"306,827","317,626 335,313","351,514",2.6,2.6 2.6,2.6,"317,626","335,313",2.6,2.6
5,New Hampshire...............,"51,432","53,468 56,073","57,341",0.4,0.4 0.4,0.4,"53,468","56,073",0.4,0.4
6,Rhode Island..................,"42,073","43,078 45,733","46,900",0.4,0.3 0.3,0.3,"43,078","45,733",0.3,0.3
7,Vermont........................,"21,839","22,745 23,628","24,543",0.2,0.2 0.2,0.2,"22,745","23,628",0.2,0.2
8,Mideast...........................,"2,124,891","2,245,718 2,390,856","2,522,240",18.3,18.2 18.2,18.4,"2,245,718","2,390,856",18.2,18.2
9,Delaware........................,"52,305","57,334 59,589","60,118",0.5,0.5 0.5,0.4,"57,334","59,589",0.5,0.5
10,District of Columbia.........,"77,913","82,978 88,174","93,819",0.7,0.7 0.7,0.7,"82,978","88,174",0.7,0.7
11,Maryland........................,"228,223","243,855 257,577","268,685",2.0,2.0 2.0,2.0,"243,855","257,577",2.0,2.0
12,New Jersey.....................,"410,096","425,497 448,426","465,484",3.5,3.4 3.4,3.4,"425,497","448,426",3.4,3.4
13,New York........................,"896,422","953,641 1,028,320","1,103,024",7.7,7.7 7.8,8.0,"953,641","1,028,320",7.7,7.8
14,Pennsylvania..................,"459,932","482,413 508,769","531,110",4.0,3.9 3.9,3.9,"482,413","508,769",3.9,3.9
15,Great Lakes.....................,"1,755,486","1,812,433 1,873,436","1,936,573",15.1,14.7 14.3,14.1,"1,812,433","1,873,436",14.7,14.3
16,Illinois...........................,"534,429","554,099 583,990","609,570",4.6,4.5 4.5,4.4,"554,099","583,990",4.5,4.5
17,Indiana...........................,"228,329","232,799 238,693","246,439",2.0,1.9 1.8,1.8,"232,799","238,693",1.9,1.8
18,Michigan........................,"363,076","372,174 375,759","381,963",3.1,3.0 2.9,2.8,"372,174","375,759",3.0,2.9
19,Ohio.............................,"423,735","439,271 451,600","466,309",3.7,3.6 3.4,3.4,"439,271","451,600",3.6,3.4
20,Wisconsin........................,"205,916","214,090 223,394","232,293",1.8,1.7 1.7,1.7,"214,090","223,394",1.7,1.7
21,Plains.............................,"759,398","790,222 827,927","872,523",6.5,6.4 6.3,6.3,"790,222","827,927",6.4,6.3
22,Iowa.............................,"111,937","115,632 121,945","129,026",1.0,0.9 0.9,0.9,"115,632","121,945",0.9,0.9
23,Kansas...........................,"98,426","103,305 110,645","117,305",0.8,0.8 0.8,0.9,"103,305","110,645",0.8,0.8
24,Minnesota........................,"223,454","232,001 242,095","254,970",1.9,1.9 1.8,1.9,"232,001","242,095",1.9,1.8
25,Missouri........................,"204,916","213,012 220,092","229,470",1.8,1.7 1.7,1.7,"213,012","220,092",1.7,1.7
26,Nebraska........................,"68,404","71,150 75,290","80,093",0.6,0.6 0.6,0.6,"71,150","75,290",0.6,0.6
27,North Dakota..................,"22,739","24,648 25,851","27,725",0.2,0.2 0.2,0.2,"24,648","25,851",0.2,0.2
28,South Dakota..................,"29,522","30,473 32,008","33,934",0.3,0.2 0.2,0.2,"30,473","32,008",0.2,0.2
29,Southeast........................,"2,586,745","2,783,933 2,964,029","3,087,889",22.3,22.5 22.6,22.5,"2,783,933","2,964,029",22.5,22.6
30,Alabama........................,"141,527","150,513 158,566","165,796",1.2,1.2 1.2,1.2,"150,513","158,566",1.2,1.2
31,Arkansas........................,"82,137","86,139 90,864","95,371",0.7,0.7 0.7,0.7,"86,139","90,864",0.7,0.7
32,Florida...........................,"607,284","670,237 716,505","734,519",5.2,5.4 5.5,5.3,"670,237","716,505",5.4,5.5
33,Georgia...........................,"338,470","359,694 376,410","396,504",2.9,2.9 2.9,2.9,"359,694","376,410",2.9,2.9
34,Kentucky........................,"131,741","138,542 146,415","154,184",1.1,1.1 1.1,1.1,"138,542","146,415",1.1,1.1
35,Louisiana........................,"163,427","184,042 203,167","216,146",1.4,1.5 1.5,1.6,"184,042","203,167",1.5,1.5
36,Mississippi.....................,"76,499","79,461 84,586","88,546",0.7,0.6 0.6,0.6,"79,461","84,586",0.6,0.6
37,North Carolina..................,"324,383","349,216 380,932","399,446",2.8,2.8 2.9,2.9,"349,216","380,932",2.8,2.9
38,South Carolina..................,"131,851","138,619 146,211","152,830",1.1,1.1 1.1,1.1,"138,619","146,211",1.1,1.1
39,Tennessee.....................,"214,849","224,169 235,753","243,869",1.9,1.8 1.8,1.8,"224,169","235,753",1.8,1.8
40,Virginia...........................,"324,870","350,288 368,604","382,964",2.8,2.8 2.8,2.8,"350,288","368,604",2.8,2.8
41,West Virginia..................,"49,706","53,013 56,016","57,711",0.4,0.4 0.4,0.4,"53,013","56,016",0.4,0.4
42,Southwest........................,"1,270,084","1,384,061 1,507,770","1,604,494",10.9,11.2 11.5,11.7,"1,384,061","1,507,770",11.2,11.5
43,Arizona...........................,"193,448","215,844 237,397","247,028",1.7,1.7 1.8,1.8,"215,844","237,397",1.7,1.8
44,New Mexico.....................,"63,452","68,153 72,161","76,178",0.5,0.6 0.6,0.6,"68,153","72,161",0.6,0.6
45,Oklahoma........................,"111,511","120,753 130,094","139,323",1.0,1.0 1.0,1.0,"120,753","130,094",1.0,1.0
46,Texas............................,"901,673","979,311 1,068,119","1,141,965",7.8,7.9 8.1,8.3,"979,311","1,068,119",7.9,8.1
47,Rocky Mountain...............,"371,715","405,194 434,568","458,897",3.2,3.3 3.3,3.3,"405,194","434,568",3.3,3.3
48,Colorado........................,"197,329","213,326 226,266","236,324",1.7,1.7 1.7,1.7,"213,326","226,266",1.7,1.7
49,Idaho............................,"42,626","46,369 48,441","51,149",0.4,0.4 0.4,0.4,"46,369","48,441",0.4,0.4
50,Montana........................,"27,452","29,966 31,994","34,253",0.2,0.2 0.2,0.2,"29,966","31,994",0.2,0.2
51,Utah.............................,"80,889","88,944 97,963","105,658",0.7,0.7 0.7,0.8,"88,944","97,963",0.7,0.7
52,Wyoming........................,"23,420","26,589 29,904","31,514",0.2,0.2 0.2,0.2,"26,589","29,904",0.2,0.2
53,Far West...........................,"2,091,250","2,250,748 2,409,301","2,515,732",18.0,18.2 18.4,18.3,"2,250,748","2,409,301",18.2,18.4
54,Alaska...........................,"35,102","39,298 43,117","44,517",0.3,0.3 0.3,0.3,"39,298","43,117",0.3,0.3
55,California........................,"1,519,443","1,632,822 1,742,172","1,812,968",13.1,13.2 13.3,13.2,"1,632,822","1,742,172",13.2,13.3
56,Hawaii...........................,"50,414","54,863 58,676","61,532",0.4,0.4 0.4,0.4,"54,863","58,676",0.4,0.4
57,Nevada...........................,"100,209","112,451 123,054","127,213",0.9,0.9 0.9,0.9,"112,451","123,054",0.9,0.9
58,Oregon...........................,"132,835","138,057 150,984","158,233",1.1,1.1 1.2,1.2,"138,057","150,984",1.1,1.2
59,Washington.....................,"253,247","273,257 291,298","311,270",2.2,2.2 2.2,2.3,"273,257","291,298",2.2,2.2

In [26]:
GDP04_06.cleanStates('Area')

,Area,2004,2005 2006,2007,2004.0,2005 2006,2007,2005,2006,2005 %,2006 %,Cleaned Area
0,United States...............,"11,607,041","12,346,871 13,119,938","13,743,021",100.0,100.0 100.0,100.0,"12,346,871","13,119,938",100.0,100.0,United States
1,New England..................,"647,473","674,562 712,051","744,672",5.6,5.5 5.4,5.4,"674,562","712,051",5.5,5.4,New England
2,Connecticut.....................,"182,112","193,281 204,964","216,266",1.6,1.6 1.6,1.6,"193,281","204,964",1.6,1.6,Connecticut
3,Maine............................,"43,191","44,364 46,340","48,108",0.4,0.4 0.4,0.4,"44,364","46,340",0.4,0.4,Maine
4,Massachusetts..................,"306,827","317,626 335,313","351,514",2.6,2.6 2.6,2.6,"317,626","335,313",2.6,2.6,Massachusetts
5,New Hampshire...............,"51,432","53,468 56,073","57,341",0.4,0.4 0.4,0.4,"53,468","56,073",0.4,0.4,New Hampshire
6,Rhode Island..................,"42,073","43,078 45,733","46,900",0.4,0.3 0.3,0.3,"43,078","45,733",0.3,0.3,Rhode Island
7,Vermont........................,"21,839","22,745 23,628","24,543",0.2,0.2 0.2,0.2,"22,745","23,628",0.2,0.2,Vermont
8,Mideast...........................,"2,124,891","2,245,718 2,390,856","2,522,240",18.3,18.2 18.2,18.4,"2,245,718","2,390,856",18.2,18.2,Mideast
9,Delaware........................,"52,305","57,334 59,589","60,118",0.5,0.5 0.5,0.4,"57,334","59,589",0.5,0.5,Delaware
10,District of Columbia.........,"77,913","82,978 88,174","93,819",0.7,0.7 0.7,0.7,"82,978","88,174",0.7,0.7,District of Columbia
11,Maryland........................,"228,223","243,855 257,577","268,685",2.0,2.0 2.0,2.0,"243,855","257,577",2.0,2.0,Maryland
12,New Jersey.....................,"410,096","425,497 448,426","465,484",3.5,3.4 3.4,3.4,"425,497","448,426",3.4,3.4,New Jersey
13,New York........................,"896,422","953,641 1,028,320","1,103,024",7.7,7.7 7.8,8.0,"953,641","1,028,320",7.7,7.8,New York
14,Pennsylvania..................,"459,932","482,413 508,769","531,110",4.0,3.9 3.9,3.9,"482,413","508,769",3.9,3.9,Pennsylvania
15,Great Lakes.....................,"1,755,486","1,812,433 1,873,436","1,936,573",15.1,14.7 14.3,14.1,"1,812,433","1,873,436",14.7,14.3,Great Lakes
16,Illinois...........................,"534,429","554,099 583,990","609,570",4.6,4.5 4.5,4.4,"554,099","583,990",4.5,4.5,Illinois
17,Indiana...........................,"228,329","232,799 238,693","246,439",2.0,1.9 1.8,1.8,"232,799","238,693",1.9,1.8,Indiana
18,Michigan........................,"363,076","372,174 375,759","381,963",3.1,3.0 2.9,2.8,"372,174","375,759",3.0,2.9,Michigan
19,Ohio.............................,"423,735","439,271 451,600","466,309",3.7,3.6 3.4,3.4,"439,271","451,600",3.6,3.4,Ohio
20,Wisconsin........................,"205,916","214,090 223,394","232,293",1.8,1.7 1.7,1.7,"214,090","223,394",1.7,1.7,Wisconsin
21,Plains.............................,"759,398","790,222 827,927","872,523",6.5,6.4 6.3,6.3,"790,222","827,927",6.4,6.3,Plains
22,Iowa.............................,"111,937","115,632 121,945","129,026",1.0,0.9 0.9,0.9,"115,632","121,945",0.9,0.9,Iowa
23,Kansas...........................,"98,426","103,305 110,645","117,305",0.8,0.8 0.8,0.9,"103,305","110,645",0.8,0.8,Kansas
24,Minnesota........................,"223,454","232,001 242,095","254,970",1.9,1.9 1.8,1.9,"232,001","242,095",1.9,1.8,Minnesota
25,Missouri........................,"204,916","213,012 220,092","229,470",1.8,1.7 1.7,1.7,"213,012","220,092",1.7,1.7,Missouri
26,Nebraska........................,"68,404","71,150 75,290","80,093",0.6,0.6 0.6,0.6,"71,150","75,290",0.6,0.6,Nebraska
27,North Dakota..................,"22,739","24,648 25,851","27,725",0.2,0.2 0.2,0.2,"24,648","25,851",0.2,0.2,North Dakota
28,South Dakota..................,"29,522","30,473 32,008","33,934",0.3,0.2 0.2,0.2,"30,473","32,008",0.2,0.2,South Dakota
29,Southeast........................,"2,586,745","2,783,933 2,964,029","3,087,889",22.3,22.5 22.6,22.5,"2,783,933","2,964,029",22.5,22.6,Southeast
30,Alabama........................,"141,527","150,513 158,566","165,796",1.2,1.2 1.2,1.2,"150,513","158,566",1.2,1.2,Alabama
31,Arkansas........................,"82,137","86,139 90,864","95,371",0.7,0.7 0.7,0.7,"86,139","90,864",0.7,0.7,Arkansas
32,Florida...........................,"607,284","670,237 716,505","734,519",5.2,5.4 5.5,5.3,"670,237","716,505",5.4,5.5,Florida
33,Georgia...........................,"338,470","359,694 376,410","396,504",2.9,2.9 2.9,2.9,"359,694","376,410",2.9,2.9,Georgia
34,Kentucky........................,"131,741","138,542 146,415","154,184",1.1,1.1 1.1,1.1,"138,542","146,415",1.1,1.1,Kentucky
35,Louisiana........................,"163,427","184,042 203,167","216,146",1.4,1.5 1.5,1.6,"184,042","203,167",1.5,1.5,Louisiana
36,Mississippi.....................,"76,499","79,461 84,586","88,546",0.7,0.6 0.6,0.6,"79,461","84,586",0.6,0.6,Mississippi
37,North Carolina..................,"324,383","349,216 380,932","399,446",2.8,2.8 2.9,2.9,"349,216","380,932",2.8,2.9,North Carolina
38,South Carolina..................,"131,851","138,619 146,211","152,830",1.1,1.1 1.1,1.1,"138,619","146,211",1.1,1.1,South Carolina
39,Tennessee.....................,"214,849","224,169 235,753","243,869",1.9,1.8 1.8,1.8,"224,169","235,753",1.8,1.8,Tennessee
40,Virginia...........................,"324,870","350,288 368,604","382,964",2.8,2.8 2.8,2.8,"350,288","368,604",2.8,2.8,Virginia
41,West Virginia..................,"49,706","53,013 56,016","57,711",0.4,0.4 0.4,0.4,"53,013","56,016",0.4,0.4,West Virginia
42,Southwest........................,"1,270,084","1,384,061 1,507,770","1,604,494",10.9,11.2 11.5,11.7,"1,384,061","1,507,770",11.2,11.5,Southwest
43,Arizona...........................,"193,448","215,844 237,397","247,028",1.7,1.7 1.8,1.8,"215,844","237,397",1.7,1.8,Arizona
44,New Mexico.....................,"63,452","68,153 72,161","76,178",0.5,0.6 0.6,0.6,"68,153","72,161",0.6,0.6,New Mexico
45,Oklahoma........................,"111,511","120,753 130,094","139,323",1.0,1.0 1.0,1.0,"120,753","130,094",1.0,1.0,Oklahoma
46,Texas............................,"901,673","979,311 1,068,119","1,141,965",7.8,7.9 8.1,8.3,"979,311","1,068,119",7.9,8.1,Texas
47,Rocky Mountain...............,"371,715","405,194 434,568","458,897",3.2,3.3 3.3,3.3,"405,194","434,568",3.3,3.3,Rocky Mountain
48,Colorado........................,"197,329","213,326 226,266","236,324",1.7,1.7 1.7,1.7,"213,326","226,266",1.7,1.7,Colorado
49,Idaho............................,"42,626","46,369 48,441","51,149",0.4,0.4 0.4,0.4,"46,369","48,441",0.4,0.4,Idaho
50,Montana........................,"27,452","29,966 31,994","34,253",0.2,0.2 0.2,0.2,"29,966","31,994",0.2,0.2,Montana
51,Utah.............................,"80,889","88,944 97,963","105,658",0.7,0.7 0.7,0.8,"88,944","97,963",0.7,0.7,Utah
52,Wyoming........................,"23,420","26,589 29,904","31,514",0.2,0.2 0.2,0.2,"26,589","29,904",0.2,0.2,Wyoming
53,Far West...........................,"2,091,250","2,250,748 2,409,301","2,515,732",18.0,18.2 18.4,18.3,"2,250,748","2,409,301",18.2,18.4,Far West
54,Alaska...........................,"35,102","39,298 43,117","44,517",0.3,0.3 0.3,0.3,"39,298","43,117",0.3,0.3,Alaska
55,California........................,"1,519,443","1,632,822 1,742,172","1,812,968",13.1,13.2 13.3,13.2,"1,632,822","1,742,172",13.2,13.3,California
56,Hawaii...........................,"50,414","54,863 58,676","61,532",0.4,0.4 0.4,0.4,"54,863","58,676",0.4,0.4,Hawaii
57,Nevada...........................,"100,209","112,451 123,054","127,213",0.9,0.9 0.9,0.9,"112,451","123,054",0.9,0.9,Nevada
58,Oregon...........................,"132,835","138,057 150,984","158,233",1.1,1.1 1.2,1.2,"138,057","150,984",1.1,1.2,Oregon
59,Washington.....................,"253,247","273,257 291,298","311,270",2.2,2.2 2.2,2.3,"273,257","291,298",2.2,2.2,Washington

In [27]:
GDP04_06.addGeoLocColumn('Cleaned Area')

,Area,2004,2005 2006,2007,2004.0,2005 2006,2007,2005,2006,2005 %,2006 %,Cleaned Area,Geo Loc
0,United States...............,"11,607,041","12,346,871 13,119,938","13,743,021",100.0,100.0 100.0,100.0,"12,346,871","13,119,938",100.0,100.0,United States,NaN
1,New England..................,"647,473","674,562 712,051","744,672",5.6,5.5 5.4,5.4,"674,562","712,051",5.5,5.4,New England,NaN
2,Connecticut.....................,"182,112","193,281 204,964","216,266",1.6,1.6 1.6,1.6,"193,281","204,964",1.6,1.6,Connecticut,New England
3,Maine............................,"43,191","44,364 46,340","48,108",0.4,0.4 0.4,0.4,"44,364","46,340",0.4,0.4,Maine,New England
4,Massachusetts..................,"306,827","317,626 335,313","351,514",2.6,2.6 2.6,2.6,"317,626","335,313",2.6,2.6,Massachusetts,New England
5,New Hampshire...............,"51,432","53,468 56,073","57,341",0.4,0.4 0.4,0.4,"53,468","56,073",0.4,0.4,New Hampshire,New England
6,Rhode Island..................,"42,073","43,078 45,733","46,900",0.4,0.3 0.3,0.3,"43,078","45,733",0.3,0.3,Rhode Island,New England
7,Vermont........................,"21,839","22,745 23,628","24,543",0.2,0.2 0.2,0.2,"22,745","23,628",0.2,0.2,Vermont,New England
8,Mideast...........................,"2,124,891","2,245,718 2,390,856","2,522,240",18.3,18.2 18.2,18.4,"2,245,718","2,390,856",18.2,18.2,Mideast,NaN
9,Delaware........................,"52,305","57,334 59,589","60,118",0.5,0.5 0.5,0.4,"57,334","59,589",0.5,0.5,Delaware,Mideast
10,District of Columbia.........,"77,913","82,978 88,174","93,819",0.7,0.7 0.7,0.7,"82,978","88,174",0.7,0.7,District of Columbia,Mideast
11,Maryland........................,"228,223","243,855 257,577","268,685",2.0,2.0 2.0,2.0,"243,855","257,577",2.0,2.0,Maryland,Mideast
12,New Jersey.....................,"410,096","425,497 448,426","465,484",3.5,3.4 3.4,3.4,"425,497","448,426",3.4,3.4,New Jersey,Mideast
13,New York........................,"896,422","953,641 1,028,320","1,103,024",7.7,7.7 7.8,8.0,"953,641","1,028,320",7.7,7.8,New York,Mideast
14,Pennsylvania..................,"459,932","482,413 508,769","531,110",4.0,3.9 3.9,3.9,"482,413","508,769",3.9,3.9,Pennsylvania,Mideast
15,Great Lakes.....................,"1,755,486","1,812,433 1,873,436","1,936,573",15.1,14.7 14.3,14.1,"1,812,433","1,873,436",14.7,14.3,Great Lakes,NaN
16,Illinois...........................,"534,429","554,099 583,990","609,570",4.6,4.5 4.5,4.4,"554,099","583,990",4.5,4.5,Illinois,Great Lakes
17,Indiana...........................,"228,329","232,799 238,693","246,439",2.0,1.9 1.8,1.8,"232,799","238,693",1.9,1.8,Indiana,Great Lakes
18,Michigan........................,"363,076","372,174 375,759","381,963",3.1,3.0 2.9,2.8,"372,174","375,759",3.0,2.9,Michigan,Great Lakes
19,Ohio.............................,"423,735","439,271 451,600","466,309",3.7,3.6 3.4,3.4,"439,271","451,600",3.6,3.4,Ohio,Great Lakes
20,Wisconsin........................,"205,916","214,090 223,394","232,293",1.8,1.7 1.7,1.7,"214,090","223,394",1.7,1.7,Wisconsin,Great Lakes
21,Plains.............................,"759,398","790,222 827,927","872,523",6.5,6.4 6.3,6.3,"790,222","827,927",6.4,6.3,Plains,NaN
22,Iowa.............................,"111,937","115,632 121,945","129,026",1.0,0.9 0.9,0.9,"115,632","121,945",0.9,0.9,Iowa,Plains
23,Kansas...........................,"98,426","103,305 110,645","117,305",0.8,0.8 0.8,0.9,"103,305","110,645",0.8,0.8,Kansas,Plains
24,Minnesota........................,"223,454","232,001 242,095","254,970",1.9,1.9 1.8,1.9,"232,001","242,095",1.9,1.8,Minnesota,Plains
25,Missouri........................,"204,916","213,012 220,092","229,470",1.8,1.7 1.7,1.7,"213,012","220,092",1.7,1.7,Missouri,Plains
26,Nebraska........................,"68,404","71,150 75,290","80,093",0.6,0.6 0.6,0.6,"71,150","75,290",0.6,0.6,Nebraska,Plains
27,North Dakota..................,"22,739","24,648 25,851","27,725",0.2,0.2 0.2,0.2,"24,648","25,851",0.2,0.2,North Dakota,Plains
28,South Dakota..................,"29,522","30,473 32,008","33,934",0.3,0.2 0.2,0.2,"30,473","32,008",0.2,0.2,South Dakota,Plains
29,Southeast........................,"2,586,745","2,783,933 2,964,029","3,087,889",22.3,22.5 22.6,22.5,"2,783,933","2,964,029",22.5,22.6,Southeast,NaN
30,Alabama........................,"141,527","150,513 158,566","165,796",1.2,1.2 1.2,1.2,"150,513","158,566",1.2,1.2,Alabama,Southeast
31,Arkansas........................,"82,137","86,139 90,864","95,371",0.7,0.7 0.7,0.7,"86,139","90,864",0.7,0.7,Arkansas,Southeast
32,Florida...........................,"607,284","670,237 716,505","734,519",5.2,5.4 5.5,5.3,"670,237","716,505",5.4,5.5,Florida,Southeast
33,Georgia...........................,"338,470","359,694 376,410","396,504",2.9,2.9 2.9,2.9,"359,694","376,410",2.9,2.9,Georgia,Southeast
34,Kentucky........................,"131,741","138,542 146,415","154,184",1.1,1.1 1.1,1.1,"138,542","146,415",1.1,1.1,Kentucky,Southeast
35,Louisiana........................,"163,427","184,042 203,167","216,146",1.4,1.5 1.5,1.6,"184,042","203,167",1.5,1.5,Louisiana,Southeast
36,Mississippi.....................,"76,499","79,461 84,586","88,546",0.7,0.6 0.6,0.6,"79,461","84,586",0.6,0.6,Mississippi,Southeast
37,North Carolina..................,"324,383","349,216 380,932","399,446",2.8,2.8 2.9,2.9,"349,216","380,932",2.8,2.9,North Carolina,Southeast
38,South Carolina..................,"131,851","138,619 146,211","152,830",1.1,1.1 1.1,1.1,"138,619","146,211",1.1,1.1,South Carolina,Southeast
39,Tennessee.....................,"214,849","224,169 235,753","243,869",1.9,1.8 1.8,1.8,"224,169","235,753",1.8,1.8,Tennessee,Southeast
40,Virginia...........................,"324,870","350,288 368,604","382,964",2.8,2.8 2.8,2.8,"350,288","368,604",2.8,2.8,Virginia,Southeast
41,West Virginia..................,"49,706","53,013 56,016","57,711",0.4,0.4 0.4,0.4,"53,013","56,016",0.4,0.4,West Virginia,Southeast
42,Southwest........................,"1,270,084","1,384,061 1,507,770","1,604,494",10.9,11.2 11.5,11.7,"1,384,061","1,507,770",11.2,11.5,Southwest,NaN
43,Arizona...........................,"193,448","215,844 237,397","247,028",1.7,1.7 1.8,1.8,"215,844","237,397",1.7,1.8,Arizona,Southwest
44,New Mexico.....................,"63,452","68,153 72,161","76,178",0.5,0.6 0.6,0.6,"68,153","72,161",0.6,0.6,New Mexico,Southwest
45,Oklahoma........................,"111,511","120,753 130,094","139,323",1.0,1.0 1.0,1.0,"120,753","130,094",1.0,1.0,Oklahoma,Southwest
46,Texas............................,"901,673","979,311 1,068,119","1,141,965",7.8,7.9 8.1,8.3,"979,311","1,068,119",7.9,8.1,Texas,Southwest
47,Rocky Mountain...............,"371,715","405,194 434,568","458,897",3.2,3.3 3.3,3.3,"405,194","434,568",3.3,3.3,Rocky Mountain,NaN
48,Colorado........................,"197,329","213,326 226,266","236,324",1.7,1.7 1.7,1.7,"213,326","226,266",1.7,1.7,Colorado,Rocky Mountain
49,Idaho............................,"42,626","46,369 48,441","51,149",0.4,0.4 0.4,0.4,"46,369","48,441",0.4,0.4,Idaho,Rocky Mountain
50,Montana........................,"27,452","29,966 31,994","34,253",0.2,0.2 0.2,0.2,"29,966","31,994",0.2,0.2,Montana,Rocky Mountain
51,Utah.............................,"80,889","88,944 97,963","105,658",0.7,0.7 0.7,0.8,"88,944","97,963",0.7,0.7,Utah,Rocky Mountain
52,Wyoming........................,"23,420","26,589 29,904","31,514",0.2,0.2 0.2,0.2,"26,589","29,904",0.2,0.2,Wyoming,Rocky Mountain
53,Far West...........................,"2,091,250","2,250,748 2,409,301","2,515,732",18.0,18.2 18.4,18.3,"2,250,748","2,409,301",18.2,18.4,Far West,NaN
54,Alaska...........................,"35,102","39,298 43,117","44,517",0.3,0.3 0.3,0.3,"39,298","43,117",0.3,0.3,Alaska,Far West
55,California........................,"1,519,443","1,632,822 1,742,172","1,812,968",13.1,13.2 13.3,13.2,"1,632,822","1,742,172",13.2,13.3,California,Far West
56,Hawaii...........................,"50,414","54,863 58,676","61,532",0.4,0.4 0.4,0.4,"54,863","58,676",0.4,0.4,Hawaii,Far West
57,Nevada...........................,"100,209","112,451 123,054","127,213",0.9,0.9 0.9,0.9,"112,451","123,054",0.9,0.9,Nevada,Far West
58,Oregon...........................,"132,835","138,057 150,984","158,233",1.1,1.1 1.2,1.2,"138,057","150,984",1.1,1.2,Oregon,Far West
59,Washington.....................,"253,247","273,257 291,298","311,270",2.2,2.2 2.2,2.3,"273,257","291,298",2.2,2.2,Washington,Far West

In [28]:
GDP04_06.restructureDataFrame('Cleaned Area')

     year          state current dollars        GDP        GDP_area
0    2004         Alaska            2007    35102.0        Far West
1    2004        Alabama            2007   141527.0       Southeast
2    2004       Arkansas            2007    82137.0       Southeast
3    2004        Arizona            2007   193448.0       Southwest
4    2004     California            2007  1519443.0        Far West
..    ...            ...             ...        ...             ...
148  2006        Vermont            2007    23628.0     New England
149  2006     Washington            2007   291298.0        Far West
150  2006      Wisconsin            2007   223394.0     Great Lakes
151  2006  West Virginia            2007    56016.0       Southeast
152  2006        Wyoming            2007    29904.0  Rocky Mountain

[153 rows x 5 columns]

In [29]:
GDP04_06.df

     year          state current dollars        GDP        GDP_area
0    2004         Alaska            2007    35102.0        Far West
1    2004        Alabama            2007   141527.0       Southeast
2    2004       Arkansas            2007    82137.0       Southeast
3    2004        Arizona            2007   193448.0       Southwest
4    2004     California            2007  1519443.0        Far West
..    ...            ...             ...        ...             ...
148  2006        Vermont            2007    23628.0     New England
149  2006     Washington            2007   291298.0        Far West
150  2006      Wisconsin            2007   223394.0     Great Lakes
151  2006  West Virginia            2007    56016.0       Southeast
152  2006        Wyoming            2007    29904.0  Rocky Mountain

[153 rows x 5 columns]

# GDP 07-09 Data

In [30]:
# create instance of yearly GDP data
GDP07_09 = YearlyGDP('GDP2007-2009.pdf', 9, 2007, 2009, '2010')

In [31]:
# testing that it was initialized with an empty DataFrame
GDP07_09.df

Empty DataFrame
Columns: []
Index: []

In [32]:
# initializeDataFrame() method reads in the PDF, assigns the first DataFrame in the 
# list as the df (only one table per page), and renames the columns. Lastly, it returns 
# the DataFrame for viewing
GDP07_09.initializeDataFrame()

,Area,2007,2008 2009,2010,2007.0,2008 2009,2010
0,United States..................,"13,969,323","14,270,462 14,014,849","14,551,782",100.0,100.0 100.0,100.0
1,New England......................,"754,306","772,347 769,308","802,771",5.4,5.4 5.5,5.5
2,Connecticut........................,"222,498","225,958 227,550","237,261",1.6,1.6 1.6,1.6
3,Maine.................................,"49,195","49,972 50,039","51,643",0.4,0.4 0.4,0.4
4,Massachusetts...................,"353,329","365,623 360,538","378,729",2.5,2.6 2.6,2.6
5,New Hampshire.................,"57,856","58,780 59,086","60,283",0.4,0.4 0.4,0.4
6,Rhode Island.....................,"47,334","47,378 47,470","49,234",0.3,0.3 0.3,0.3
7,Vermont.............................,"24,093","24,636 24,625","25,620",0.2,0.2 0.2,0.2
8,Mideast...............................,"2,515,483","2,575,532 2,557,257","2,677,426",18.0,18.0 18.2,18.4
9,Delaware...........................,"60,108","58,674 60,660","62,280",0.4,0.4 0.4,0.4
10,District of Columbia...........,"92,342","97,361 98,892","103,288",0.7,0.7 0.7,0.7
11,Maryland............................,"273,693","281,659 285,116","295,304",2.0,2.0 2.0,2.0
12,New Jersey........................,"472,000","483,560 471,946","487,335",3.4,3.4 3.4,3.3
13,New York...........................,"1,085,225","1,109,080 1,094,104","1,159,540",7.8,7.8 7.8,8.0
14,Pennsylvania.....................,"532,117","545,198 546,538","569,679",3.8,3.8 3.9,3.9
15,Great Lakes........................,"1,984,929","1,985,880 1,963,163","2,037,329",14.2,13.9 14.0,14.0
16,Illinois.................................,"629,379","637,037 631,970","651,518",4.5,4.5 4.5,4.5
17,Indiana...............................,"262,596","263,616 259,894","275,676",1.9,1.8 1.9,1.9
18,Michigan............................,"387,086","375,436 369,671","384,171",2.8,2.6 2.6,2.6
19,Ohio...................................,"468,707","470,640 462,015","477,699",3.4,3.3 3.3,3.3
20,Wisconsin..........................,"237,160","239,150 239,613","248,265",1.7,1.7 1.7,1.7
21,Plains..................................,"889,072","919,248 911,352","948,287",6.4,6.4 6.5,6.5
22,Iowa...................................,"134,410","134,959 136,062","142,698",1.0,0.9 1.0,1.0
23,Kansas...............................,"121,268","125,333 122,544","127,170",0.9,0.9 0.9,0.9
24,Minnesota..........................,"254,567","262,758 258,499","270,039",1.8,1.8 1.8,1.9
25,Missouri.............................,"233,008","241,344 237,955","244,016",1.7,1.7 1.7,1.7
26,Nebraska...........................,"82,185","84,884 86,411","89,786",0.6,0.6 0.6,0.6
27,North Dakota.....................,"28,552","31,677 31,626","34,685",0.2,0.2 0.2,0.2
28,South Dakota.....................,"35,082","38,293 38,255","39,893",0.3,0.3 0.3,0.3
29,Southeast...........................,"3,118,542","3,161,091 3,128,268","3,238,209",22.3,22.2 22.3,22.3
30,Alabama............................,"165,981","169,694 166,819","172,567",1.2,1.2 1.2,1.2
31,Arkansas............................,"97,187","99,497 98,795","102,566",0.7,0.7 0.7,0.7
32,Florida................................,"759,572","747,770 732,782","747,735",5.4,5.2 5.2,5.1
33,Georgia..............................,"400,331","405,269 394,117","403,070",2.9,2.8 2.8,2.8
34,Kentucky............................,"151,506","155,592 155,789","163,269",1.1,1.1 1.1,1.1
35,Louisiana...........................,"205,758","213,441 205,117","218,853",1.5,1.5 1.5,1.5
36,Mississippi.........................,"93,194","96,713 94,406","97,461",0.7,0.7 0.7,0.7
37,North Carolina...................,"397,975","403,927 407,032","424,935",2.8,2.8 2.9,2.9
38,South Carolina...................,"158,041","159,500 158,786","164,445",1.1,1.1 1.1,1.1
39,Tennessee.........................,"242,678","247,796 243,849","254,806",1.7,1.7 1.7,1.8
40,Virginia...............................,"389,319","402,853 409,732","423,860",2.8,2.8 2.9,2.9
41,West Virginia.....................,"57,001","59,039 61,043","64,642",0.4,0.4 0.4,0.4
42,Southwest..........................,"1,622,669","1,691,577 1,615,618","1,688,324",11.6,11.9 11.5,11.6
43,Arizona..............................,"260,122","260,454 249,711","253,609",1.9,1.8 1.8,1.7
44,New Mexico.......................,"74,393","77,168 76,871","79,678",0.5,0.5 0.5,0.5
45,Oklahoma..........................,"140,183","151,850 142,388","147,543",1.0,1.1 1.0,1.0
46,Texas.................................,"1,147,970","1,202,104 1,146,647","1,207,494",8.2,8.4 8.2,8.3
47,Rocky Mountain.................,"474,833","496,537 487,384","502,207",3.4,3.5 3.5,3.5
48,Colorado............................,"242,900","254,218 250,664","257,641",1.7,1.8 1.8,1.8
49,Idaho..................................,"54,344","55,212 53,661","55,435",0.4,0.4 0.4,0.4
50,Montana.............................,"35,100","35,838 34,999","36,067",0.3,0.3 0.2,0.2
51,Utah...................................,"108,815","112,353 111,301","114,538",0.8,0.8 0.8,0.8
52,Wyoming............................,"33,674","38,917 36,760","38,527",0.2,0.3 0.3,0.3
53,Far West.............................,"2,609,491","2,668,247 2,582,493","2,657,228",18.7,18.7 18.4,18.3
54,Alaska................................,"44,587","49,186 45,861","49,120",0.3,0.3 0.3,0.3
55,California...........................,"1,874,783","1,911,741 1,847,048","1,901,088",13.4,13.4 13.2,13.1
56,Hawaii................................,"64,212","66,119 65,428","66,760",0.5,0.5 0.5,0.5
57,Nevada..............................,"133,782","132,270 125,037","125,650",1.0,0.9 0.9,0.9
58,Oregon...............................,"167,016","174,454 167,481","174,151",1.2,1.2 1.2,1.2
59,Washington........................,"325,112","334,477 331,639","340,460",2.3,2.3 2.4,2.3

In [33]:
GDP07_09.splitColumns(2, '2008', '2009')

,Area,2007,2008 2009,2010,2007.0,2008 2009,2010,2008,2009
0,United States..................,"13,969,323","14,270,462 14,014,849","14,551,782",100.0,100.0 100.0,100.0,"14,270,462","14,014,849"
1,New England......................,"754,306","772,347 769,308","802,771",5.4,5.4 5.5,5.5,"772,347","769,308"
2,Connecticut........................,"222,498","225,958 227,550","237,261",1.6,1.6 1.6,1.6,"225,958","227,550"
3,Maine.................................,"49,195","49,972 50,039","51,643",0.4,0.4 0.4,0.4,"49,972","50,039"
4,Massachusetts...................,"353,329","365,623 360,538","378,729",2.5,2.6 2.6,2.6,"365,623","360,538"
5,New Hampshire.................,"57,856","58,780 59,086","60,283",0.4,0.4 0.4,0.4,"58,780","59,086"
6,Rhode Island.....................,"47,334","47,378 47,470","49,234",0.3,0.3 0.3,0.3,"47,378","47,470"
7,Vermont.............................,"24,093","24,636 24,625","25,620",0.2,0.2 0.2,0.2,"24,636","24,625"
8,Mideast...............................,"2,515,483","2,575,532 2,557,257","2,677,426",18.0,18.0 18.2,18.4,"2,575,532","2,557,257"
9,Delaware...........................,"60,108","58,674 60,660","62,280",0.4,0.4 0.4,0.4,"58,674","60,660"
10,District of Columbia...........,"92,342","97,361 98,892","103,288",0.7,0.7 0.7,0.7,"97,361","98,892"
11,Maryland............................,"273,693","281,659 285,116","295,304",2.0,2.0 2.0,2.0,"281,659","285,116"
12,New Jersey........................,"472,000","483,560 471,946","487,335",3.4,3.4 3.4,3.3,"483,560","471,946"
13,New York...........................,"1,085,225","1,109,080 1,094,104","1,159,540",7.8,7.8 7.8,8.0,"1,109,080","1,094,104"
14,Pennsylvania.....................,"532,117","545,198 546,538","569,679",3.8,3.8 3.9,3.9,"545,198","546,538"
15,Great Lakes........................,"1,984,929","1,985,880 1,963,163","2,037,329",14.2,13.9 14.0,14.0,"1,985,880","1,963,163"
16,Illinois.................................,"629,379","637,037 631,970","651,518",4.5,4.5 4.5,4.5,"637,037","631,970"
17,Indiana...............................,"262,596","263,616 259,894","275,676",1.9,1.8 1.9,1.9,"263,616","259,894"
18,Michigan............................,"387,086","375,436 369,671","384,171",2.8,2.6 2.6,2.6,"375,436","369,671"
19,Ohio...................................,"468,707","470,640 462,015","477,699",3.4,3.3 3.3,3.3,"470,640","462,015"
20,Wisconsin..........................,"237,160","239,150 239,613","248,265",1.7,1.7 1.7,1.7,"239,150","239,613"
21,Plains..................................,"889,072","919,248 911,352","948,287",6.4,6.4 6.5,6.5,"919,248","911,352"
22,Iowa...................................,"134,410","134,959 136,062","142,698",1.0,0.9 1.0,1.0,"134,959","136,062"
23,Kansas...............................,"121,268","125,333 122,544","127,170",0.9,0.9 0.9,0.9,"125,333","122,544"
24,Minnesota..........................,"254,567","262,758 258,499","270,039",1.8,1.8 1.8,1.9,"262,758","258,499"
25,Missouri.............................,"233,008","241,344 237,955","244,016",1.7,1.7 1.7,1.7,"241,344","237,955"
26,Nebraska...........................,"82,185","84,884 86,411","89,786",0.6,0.6 0.6,0.6,"84,884","86,411"
27,North Dakota.....................,"28,552","31,677 31,626","34,685",0.2,0.2 0.2,0.2,"31,677","31,626"
28,South Dakota.....................,"35,082","38,293 38,255","39,893",0.3,0.3 0.3,0.3,"38,293","38,255"
29,Southeast...........................,"3,118,542","3,161,091 3,128,268","3,238,209",22.3,22.2 22.3,22.3,"3,161,091","3,128,268"
30,Alabama............................,"165,981","169,694 166,819","172,567",1.2,1.2 1.2,1.2,"169,694","166,819"
31,Arkansas............................,"97,187","99,497 98,795","102,566",0.7,0.7 0.7,0.7,"99,497","98,795"
32,Florida................................,"759,572","747,770 732,782","747,735",5.4,5.2 5.2,5.1,"747,770","732,782"
33,Georgia..............................,"400,331","405,269 394,117","403,070",2.9,2.8 2.8,2.8,"405,269","394,117"
34,Kentucky............................,"151,506","155,592 155,789","163,269",1.1,1.1 1.1,1.1,"155,592","155,789"
35,Louisiana...........................,"205,758","213,441 205,117","218,853",1.5,1.5 1.5,1.5,"213,441","205,117"
36,Mississippi.........................,"93,194","96,713 94,406","97,461",0.7,0.7 0.7,0.7,"96,713","94,406"
37,North Carolina...................,"397,975","403,927 407,032","424,935",2.8,2.8 2.9,2.9,"403,927","407,032"
38,South Carolina...................,"158,041","159,500 158,786","164,445",1.1,1.1 1.1,1.1,"159,500","158,786"
39,Tennessee.........................,"242,678","247,796 243,849","254,806",1.7,1.7 1.7,1.8,"247,796","243,849"
40,Virginia...............................,"389,319","402,853 409,732","423,860",2.8,2.8 2.9,2.9,"402,853","409,732"
41,West Virginia.....................,"57,001","59,039 61,043","64,642",0.4,0.4 0.4,0.4,"59,039","61,043"
42,Southwest..........................,"1,622,669","1,691,577 1,615,618","1,688,324",11.6,11.9 11.5,11.6,"1,691,577","1,615,618"
43,Arizona..............................,"260,122","260,454 249,711","253,609",1.9,1.8 1.8,1.7,"260,454","249,711"
44,New Mexico.......................,"74,393","77,168 76,871","79,678",0.5,0.5 0.5,0.5,"77,168","76,871"
45,Oklahoma..........................,"140,183","151,850 142,388","147,543",1.0,1.1 1.0,1.0,"151,850","142,388"
46,Texas.................................,"1,147,970","1,202,104 1,146,647","1,207,494",8.2,8.4 8.2,8.3,"1,202,104","1,146,647"
47,Rocky Mountain.................,"474,833","496,537 487,384","502,207",3.4,3.5 3.5,3.5,"496,537","487,384"
48,Colorado............................,"242,900","254,218 250,664","257,641",1.7,1.8 1.8,1.8,"254,218","250,664"
49,Idaho..................................,"54,344","55,212 53,661","55,435",0.4,0.4 0.4,0.4,"55,212","53,661"
50,Montana.............................,"35,100","35,838 34,999","36,067",0.3,0.3 0.2,0.2,"35,838","34,999"
51,Utah...................................,"108,815","112,353 111,301","114,538",0.8,0.8 0.8,0.8,"112,353","111,301"
52,Wyoming............................,"33,674","38,917 36,760","38,527",0.2,0.3 0.3,0.3,"38,917","36,760"
53,Far West.............................,"2,609,491","2,668,247 2,582,493","2,657,228",18.7,18.7 18.4,18.3,"2,668,247","2,582,493"
54,Alaska................................,"44,587","49,186 45,861","49,120",0.3,0.3 0.3,0.3,"49,186","45,861"
55,California...........................,"1,874,783","1,911,741 1,847,048","1,901,088",13.4,13.4 13.2,13.1,"1,911,741","1,847,048"
56,Hawaii................................,"64,212","66,119 65,428","66,760",0.5,0.5 0.5,0.5,"66,119","65,428"
57,Nevada..............................,"133,782","132,270 125,037","125,650",1.0,0.9 0.9,0.9,"132,270","125,037"
58,Oregon...............................,"167,016","174,454 167,481","174,151",1.2,1.2 1.2,1.2,"174,454","167,481"
59,Washington........................,"325,112","334,477 331,639","340,460",2.3,2.3 2.4,2.3,"334,477","331,639"

In [34]:
GDP07_09.splitColumns(5, '2008 %', '2009 %')

,Area,2007,2008 2009,2010,2007.0,2008 2009,2010,2008,2009,2008 %,2009 %
0,United States..................,"13,969,323","14,270,462 14,014,849","14,551,782",100.0,100.0 100.0,100.0,"14,270,462","14,014,849",100.0,100.0
1,New England......................,"754,306","772,347 769,308","802,771",5.4,5.4 5.5,5.5,"772,347","769,308",5.4,5.5
2,Connecticut........................,"222,498","225,958 227,550","237,261",1.6,1.6 1.6,1.6,"225,958","227,550",1.6,1.6
3,Maine.................................,"49,195","49,972 50,039","51,643",0.4,0.4 0.4,0.4,"49,972","50,039",0.4,0.4
4,Massachusetts...................,"353,329","365,623 360,538","378,729",2.5,2.6 2.6,2.6,"365,623","360,538",2.6,2.6
5,New Hampshire.................,"57,856","58,780 59,086","60,283",0.4,0.4 0.4,0.4,"58,780","59,086",0.4,0.4
6,Rhode Island.....................,"47,334","47,378 47,470","49,234",0.3,0.3 0.3,0.3,"47,378","47,470",0.3,0.3
7,Vermont.............................,"24,093","24,636 24,625","25,620",0.2,0.2 0.2,0.2,"24,636","24,625",0.2,0.2
8,Mideast...............................,"2,515,483","2,575,532 2,557,257","2,677,426",18.0,18.0 18.2,18.4,"2,575,532","2,557,257",18.0,18.2
9,Delaware...........................,"60,108","58,674 60,660","62,280",0.4,0.4 0.4,0.4,"58,674","60,660",0.4,0.4
10,District of Columbia...........,"92,342","97,361 98,892","103,288",0.7,0.7 0.7,0.7,"97,361","98,892",0.7,0.7
11,Maryland............................,"273,693","281,659 285,116","295,304",2.0,2.0 2.0,2.0,"281,659","285,116",2.0,2.0
12,New Jersey........................,"472,000","483,560 471,946","487,335",3.4,3.4 3.4,3.3,"483,560","471,946",3.4,3.4
13,New York...........................,"1,085,225","1,109,080 1,094,104","1,159,540",7.8,7.8 7.8,8.0,"1,109,080","1,094,104",7.8,7.8
14,Pennsylvania.....................,"532,117","545,198 546,538","569,679",3.8,3.8 3.9,3.9,"545,198","546,538",3.8,3.9
15,Great Lakes........................,"1,984,929","1,985,880 1,963,163","2,037,329",14.2,13.9 14.0,14.0,"1,985,880","1,963,163",13.9,14.0
16,Illinois.................................,"629,379","637,037 631,970","651,518",4.5,4.5 4.5,4.5,"637,037","631,970",4.5,4.5
17,Indiana...............................,"262,596","263,616 259,894","275,676",1.9,1.8 1.9,1.9,"263,616","259,894",1.8,1.9
18,Michigan............................,"387,086","375,436 369,671","384,171",2.8,2.6 2.6,2.6,"375,436","369,671",2.6,2.6
19,Ohio...................................,"468,707","470,640 462,015","477,699",3.4,3.3 3.3,3.3,"470,640","462,015",3.3,3.3
20,Wisconsin..........................,"237,160","239,150 239,613","248,265",1.7,1.7 1.7,1.7,"239,150","239,613",1.7,1.7
21,Plains..................................,"889,072","919,248 911,352","948,287",6.4,6.4 6.5,6.5,"919,248","911,352",6.4,6.5
22,Iowa...................................,"134,410","134,959 136,062","142,698",1.0,0.9 1.0,1.0,"134,959","136,062",0.9,1.0
23,Kansas...............................,"121,268","125,333 122,544","127,170",0.9,0.9 0.9,0.9,"125,333","122,544",0.9,0.9
24,Minnesota..........................,"254,567","262,758 258,499","270,039",1.8,1.8 1.8,1.9,"262,758","258,499",1.8,1.8
25,Missouri.............................,"233,008","241,344 237,955","244,016",1.7,1.7 1.7,1.7,"241,344","237,955",1.7,1.7
26,Nebraska...........................,"82,185","84,884 86,411","89,786",0.6,0.6 0.6,0.6,"84,884","86,411",0.6,0.6
27,North Dakota.....................,"28,552","31,677 31,626","34,685",0.2,0.2 0.2,0.2,"31,677","31,626",0.2,0.2
28,South Dakota.....................,"35,082","38,293 38,255","39,893",0.3,0.3 0.3,0.3,"38,293","38,255",0.3,0.3
29,Southeast...........................,"3,118,542","3,161,091 3,128,268","3,238,209",22.3,22.2 22.3,22.3,"3,161,091","3,128,268",22.2,22.3
30,Alabama............................,"165,981","169,694 166,819","172,567",1.2,1.2 1.2,1.2,"169,694","166,819",1.2,1.2
31,Arkansas............................,"97,187","99,497 98,795","102,566",0.7,0.7 0.7,0.7,"99,497","98,795",0.7,0.7
32,Florida................................,"759,572","747,770 732,782","747,735",5.4,5.2 5.2,5.1,"747,770","732,782",5.2,5.2
33,Georgia..............................,"400,331","405,269 394,117","403,070",2.9,2.8 2.8,2.8,"405,269","394,117",2.8,2.8
34,Kentucky............................,"151,506","155,592 155,789","163,269",1.1,1.1 1.1,1.1,"155,592","155,789",1.1,1.1
35,Louisiana...........................,"205,758","213,441 205,117","218,853",1.5,1.5 1.5,1.5,"213,441","205,117",1.5,1.5
36,Mississippi.........................,"93,194","96,713 94,406","97,461",0.7,0.7 0.7,0.7,"96,713","94,406",0.7,0.7
37,North Carolina...................,"397,975","403,927 407,032","424,935",2.8,2.8 2.9,2.9,"403,927","407,032",2.8,2.9
38,South Carolina...................,"158,041","159,500 158,786","164,445",1.1,1.1 1.1,1.1,"159,500","158,786",1.1,1.1
39,Tennessee.........................,"242,678","247,796 243,849","254,806",1.7,1.7 1.7,1.8,"247,796","243,849",1.7,1.7
40,Virginia...............................,"389,319","402,853 409,732","423,860",2.8,2.8 2.9,2.9,"402,853","409,732",2.8,2.9
41,West Virginia.....................,"57,001","59,039 61,043","64,642",0.4,0.4 0.4,0.4,"59,039","61,043",0.4,0.4
42,Southwest..........................,"1,622,669","1,691,577 1,615,618","1,688,324",11.6,11.9 11.5,11.6,"1,691,577","1,615,618",11.9,11.5
43,Arizona..............................,"260,122","260,454 249,711","253,609",1.9,1.8 1.8,1.7,"260,454","249,711",1.8,1.8
44,New Mexico.......................,"74,393","77,168 76,871","79,678",0.5,0.5 0.5,0.5,"77,168","76,871",0.5,0.5
45,Oklahoma..........................,"140,183","151,850 142,388","147,543",1.0,1.1 1.0,1.0,"151,850","142,388",1.1,1.0
46,Texas.................................,"1,147,970","1,202,104 1,146,647","1,207,494",8.2,8.4 8.2,8.3,"1,202,104","1,146,647",8.4,8.2
47,Rocky Mountain.................,"474,833","496,537 487,384","502,207",3.4,3.5 3.5,3.5,"496,537","487,384",3.5,3.5
48,Colorado............................,"242,900","254,218 250,664","257,641",1.7,1.8 1.8,1.8,"254,218","250,664",1.8,1.8
49,Idaho..................................,"54,344","55,212 53,661","55,435",0.4,0.4 0.4,0.4,"55,212","53,661",0.4,0.4
50,Montana.............................,"35,100","35,838 34,999","36,067",0.3,0.3 0.2,0.2,"35,838","34,999",0.3,0.2
51,Utah...................................,"108,815","112,353 111,301","114,538",0.8,0.8 0.8,0.8,"112,353","111,301",0.8,0.8
52,Wyoming............................,"33,674","38,917 36,760","38,527",0.2,0.3 0.3,0.3,"38,917","36,760",0.3,0.3
53,Far West.............................,"2,609,491","2,668,247 2,582,493","2,657,228",18.7,18.7 18.4,18.3,"2,668,247","2,582,493",18.7,18.4
54,Alaska................................,"44,587","49,186 45,861","49,120",0.3,0.3 0.3,0.3,"49,186","45,861",0.3,0.3
55,California...........................,"1,874,783","1,911,741 1,847,048","1,901,088",13.4,13.4 13.2,13.1,"1,911,741","1,847,048",13.4,13.2
56,Hawaii................................,"64,212","66,119 65,428","66,760",0.5,0.5 0.5,0.5,"66,119","65,428",0.5,0.5
57,Nevada..............................,"133,782","132,270 125,037","125,650",1.0,0.9 0.9,0.9,"132,270","125,037",0.9,0.9
58,Oregon...............................,"167,016","174,454 167,481","174,151",1.2,1.2 1.2,1.2,"174,454","167,481",1.2,1.2
59,Washington........................,"325,112","334,477 331,639","340,460",2.3,2.3 2.4,2.3,"334,477","331,639",2.3,2.4

In [35]:
GDP07_09.cleanStates('Area')

,Area,2007,2008 2009,2010,2007.0,2008 2009,2010,2008,2009,2008 %,2009 %,Cleaned Area
0,United States..................,"13,969,323","14,270,462 14,014,849","14,551,782",100.0,100.0 100.0,100.0,"14,270,462","14,014,849",100.0,100.0,United States
1,New England......................,"754,306","772,347 769,308","802,771",5.4,5.4 5.5,5.5,"772,347","769,308",5.4,5.5,New England
2,Connecticut........................,"222,498","225,958 227,550","237,261",1.6,1.6 1.6,1.6,"225,958","227,550",1.6,1.6,Connecticut
3,Maine.................................,"49,195","49,972 50,039","51,643",0.4,0.4 0.4,0.4,"49,972","50,039",0.4,0.4,Maine
4,Massachusetts...................,"353,329","365,623 360,538","378,729",2.5,2.6 2.6,2.6,"365,623","360,538",2.6,2.6,Massachusetts
5,New Hampshire.................,"57,856","58,780 59,086","60,283",0.4,0.4 0.4,0.4,"58,780","59,086",0.4,0.4,New Hampshire
6,Rhode Island.....................,"47,334","47,378 47,470","49,234",0.3,0.3 0.3,0.3,"47,378","47,470",0.3,0.3,Rhode Island
7,Vermont.............................,"24,093","24,636 24,625","25,620",0.2,0.2 0.2,0.2,"24,636","24,625",0.2,0.2,Vermont
8,Mideast...............................,"2,515,483","2,575,532 2,557,257","2,677,426",18.0,18.0 18.2,18.4,"2,575,532","2,557,257",18.0,18.2,Mideast
9,Delaware...........................,"60,108","58,674 60,660","62,280",0.4,0.4 0.4,0.4,"58,674","60,660",0.4,0.4,Delaware
10,District of Columbia...........,"92,342","97,361 98,892","103,288",0.7,0.7 0.7,0.7,"97,361","98,892",0.7,0.7,District of Columbia
11,Maryland............................,"273,693","281,659 285,116","295,304",2.0,2.0 2.0,2.0,"281,659","285,116",2.0,2.0,Maryland
12,New Jersey........................,"472,000","483,560 471,946","487,335",3.4,3.4 3.4,3.3,"483,560","471,946",3.4,3.4,New Jersey
13,New York...........................,"1,085,225","1,109,080 1,094,104","1,159,540",7.8,7.8 7.8,8.0,"1,109,080","1,094,104",7.8,7.8,New York
14,Pennsylvania.....................,"532,117","545,198 546,538","569,679",3.8,3.8 3.9,3.9,"545,198","546,538",3.8,3.9,Pennsylvania
15,Great Lakes........................,"1,984,929","1,985,880 1,963,163","2,037,329",14.2,13.9 14.0,14.0,"1,985,880","1,963,163",13.9,14.0,Great Lakes
16,Illinois.................................,"629,379","637,037 631,970","651,518",4.5,4.5 4.5,4.5,"637,037","631,970",4.5,4.5,Illinois
17,Indiana...............................,"262,596","263,616 259,894","275,676",1.9,1.8 1.9,1.9,"263,616","259,894",1.8,1.9,Indiana
18,Michigan............................,"387,086","375,436 369,671","384,171",2.8,2.6 2.6,2.6,"375,436","369,671",2.6,2.6,Michigan
19,Ohio...................................,"468,707","470,640 462,015","477,699",3.4,3.3 3.3,3.3,"470,640","462,015",3.3,3.3,Ohio
20,Wisconsin..........................,"237,160","239,150 239,613","248,265",1.7,1.7 1.7,1.7,"239,150","239,613",1.7,1.7,Wisconsin
21,Plains..................................,"889,072","919,248 911,352","948,287",6.4,6.4 6.5,6.5,"919,248","911,352",6.4,6.5,Plains
22,Iowa...................................,"134,410","134,959 136,062","142,698",1.0,0.9 1.0,1.0,"134,959","136,062",0.9,1.0,Iowa
23,Kansas...............................,"121,268","125,333 122,544","127,170",0.9,0.9 0.9,0.9,"125,333","122,544",0.9,0.9,Kansas
24,Minnesota..........................,"254,567","262,758 258,499","270,039",1.8,1.8 1.8,1.9,"262,758","258,499",1.8,1.8,Minnesota
25,Missouri.............................,"233,008","241,344 237,955","244,016",1.7,1.7 1.7,1.7,"241,344","237,955",1.7,1.7,Missouri
26,Nebraska...........................,"82,185","84,884 86,411","89,786",0.6,0.6 0.6,0.6,"84,884","86,411",0.6,0.6,Nebraska
27,North Dakota.....................,"28,552","31,677 31,626","34,685",0.2,0.2 0.2,0.2,"31,677","31,626",0.2,0.2,North Dakota
28,South Dakota.....................,"35,082","38,293 38,255","39,893",0.3,0.3 0.3,0.3,"38,293","38,255",0.3,0.3,South Dakota
29,Southeast...........................,"3,118,542","3,161,091 3,128,268","3,238,209",22.3,22.2 22.3,22.3,"3,161,091","3,128,268",22.2,22.3,Southeast
30,Alabama............................,"165,981","169,694 166,819","172,567",1.2,1.2 1.2,1.2,"169,694","166,819",1.2,1.2,Alabama
31,Arkansas............................,"97,187","99,497 98,795","102,566",0.7,0.7 0.7,0.7,"99,497","98,795",0.7,0.7,Arkansas
32,Florida................................,"759,572","747,770 732,782","747,735",5.4,5.2 5.2,5.1,"747,770","732,782",5.2,5.2,Florida
33,Georgia..............................,"400,331","405,269 394,117","403,070",2.9,2.8 2.8,2.8,"405,269","394,117",2.8,2.8,Georgia
34,Kentucky............................,"151,506","155,592 155,789","163,269",1.1,1.1 1.1,1.1,"155,592","155,789",1.1,1.1,Kentucky
35,Louisiana...........................,"205,758","213,441 205,117","218,853",1.5,1.5 1.5,1.5,"213,441","205,117",1.5,1.5,Louisiana
36,Mississippi.........................,"93,194","96,713 94,406","97,461",0.7,0.7 0.7,0.7,"96,713","94,406",0.7,0.7,Mississippi
37,North Carolina...................,"397,975","403,927 407,032","424,935",2.8,2.8 2.9,2.9,"403,927","407,032",2.8,2.9,North Carolina
38,South Carolina...................,"158,041","159,500 158,786","164,445",1.1,1.1 1.1,1.1,"159,500","158,786",1.1,1.1,South Carolina
39,Tennessee.........................,"242,678","247,796 243,849","254,806",1.7,1.7 1.7,1.8,"247,796","243,849",1.7,1.7,Tennessee
40,Virginia...............................,"389,319","402,853 409,732","423,860",2.8,2.8 2.9,2.9,"402,853","409,732",2.8,2.9,Virginia
41,West Virginia.....................,"57,001","59,039 61,043","64,642",0.4,0.4 0.4,0.4,"59,039","61,043",0.4,0.4,West Virginia
42,Southwest..........................,"1,622,669","1,691,577 1,615,618","1,688,324",11.6,11.9 11.5,11.6,"1,691,577","1,615,618",11.9,11.5,Southwest
43,Arizona..............................,"260,122","260,454 249,711","253,609",1.9,1.8 1.8,1.7,"260,454","249,711",1.8,1.8,Arizona
44,New Mexico.......................,"74,393","77,168 76,871","79,678",0.5,0.5 0.5,0.5,"77,168","76,871",0.5,0.5,New Mexico
45,Oklahoma..........................,"140,183","151,850 142,388","147,543",1.0,1.1 1.0,1.0,"151,850","142,388",1.1,1.0,Oklahoma
46,Texas.................................,"1,147,970","1,202,104 1,146,647","1,207,494",8.2,8.4 8.2,8.3,"1,202,104","1,146,647",8.4,8.2,Texas
47,Rocky Mountain.................,"474,833","496,537 487,384","502,207",3.4,3.5 3.5,3.5,"496,537","487,384",3.5,3.5,Rocky Mountain
48,Colorado............................,"242,900","254,218 250,664","257,641",1.7,1.8 1.8,1.8,"254,218","250,664",1.8,1.8,Colorado
49,Idaho..................................,"54,344","55,212 53,661","55,435",0.4,0.4 0.4,0.4,"55,212","53,661",0.4,0.4,Idaho
50,Montana.............................,"35,100","35,838 34,999","36,067",0.3,0.3 0.2,0.2,"35,838","34,999",0.3,0.2,Montana
51,Utah...................................,"108,815","112,353 111,301","114,538",0.8,0.8 0.8,0.8,"112,353","111,301",0.8,0.8,Utah
52,Wyoming............................,"33,674","38,917 36,760","38,527",0.2,0.3 0.3,0.3,"38,917","36,760",0.3,0.3,Wyoming
53,Far West.............................,"2,609,491","2,668,247 2,582,493","2,657,228",18.7,18.7 18.4,18.3,"2,668,247","2,582,493",18.7,18.4,Far West
54,Alaska................................,"44,587","49,186 45,861","49,120",0.3,0.3 0.3,0.3,"49,186","45,861",0.3,0.3,Alaska
55,California...........................,"1,874,783","1,911,741 1,847,048","1,901,088",13.4,13.4 13.2,13.1,"1,911,741","1,847,048",13.4,13.2,California
56,Hawaii................................,"64,212","66,119 65,428","66,760",0.5,0.5 0.5,0.5,"66,119","65,428",0.5,0.5,Hawaii
57,Nevada..............................,"133,782","132,270 125,037","125,650",1.0,0.9 0.9,0.9,"132,270","125,037",0.9,0.9,Nevada
58,Oregon...............................,"167,016","174,454 167,481","174,151",1.2,1.2 1.2,1.2,"174,454","167,481",1.2,1.2,Oregon
59,Washington........................,"325,112","334,477 331,639","340,460",2.3,2.3 2.4,2.3,"334,477","331,639",2.3,2.4,Washington

In [36]:
GDP07_09.addGeoLocColumn('Cleaned Area')

,Area,2007,2008 2009,2010,2007.0,2008 2009,2010,2008,2009,2008 %,2009 %,Cleaned Area,Geo Loc
0,United States..................,"13,969,323","14,270,462 14,014,849","14,551,782",100.0,100.0 100.0,100.0,"14,270,462","14,014,849",100.0,100.0,United States,NaN
1,New England......................,"754,306","772,347 769,308","802,771",5.4,5.4 5.5,5.5,"772,347","769,308",5.4,5.5,New England,NaN
2,Connecticut........................,"222,498","225,958 227,550","237,261",1.6,1.6 1.6,1.6,"225,958","227,550",1.6,1.6,Connecticut,New England
3,Maine.................................,"49,195","49,972 50,039","51,643",0.4,0.4 0.4,0.4,"49,972","50,039",0.4,0.4,Maine,New England
4,Massachusetts...................,"353,329","365,623 360,538","378,729",2.5,2.6 2.6,2.6,"365,623","360,538",2.6,2.6,Massachusetts,New England
5,New Hampshire.................,"57,856","58,780 59,086","60,283",0.4,0.4 0.4,0.4,"58,780","59,086",0.4,0.4,New Hampshire,New England
6,Rhode Island.....................,"47,334","47,378 47,470","49,234",0.3,0.3 0.3,0.3,"47,378","47,470",0.3,0.3,Rhode Island,New England
7,Vermont.............................,"24,093","24,636 24,625","25,620",0.2,0.2 0.2,0.2,"24,636","24,625",0.2,0.2,Vermont,New England
8,Mideast...............................,"2,515,483","2,575,532 2,557,257","2,677,426",18.0,18.0 18.2,18.4,"2,575,532","2,557,257",18.0,18.2,Mideast,NaN
9,Delaware...........................,"60,108","58,674 60,660","62,280",0.4,0.4 0.4,0.4,"58,674","60,660",0.4,0.4,Delaware,Mideast
10,District of Columbia...........,"92,342","97,361 98,892","103,288",0.7,0.7 0.7,0.7,"97,361","98,892",0.7,0.7,District of Columbia,Mideast
11,Maryland............................,"273,693","281,659 285,116","295,304",2.0,2.0 2.0,2.0,"281,659","285,116",2.0,2.0,Maryland,Mideast
12,New Jersey........................,"472,000","483,560 471,946","487,335",3.4,3.4 3.4,3.3,"483,560","471,946",3.4,3.4,New Jersey,Mideast
13,New York...........................,"1,085,225","1,109,080 1,094,104","1,159,540",7.8,7.8 7.8,8.0,"1,109,080","1,094,104",7.8,7.8,New York,Mideast
14,Pennsylvania.....................,"532,117","545,198 546,538","569,679",3.8,3.8 3.9,3.9,"545,198","546,538",3.8,3.9,Pennsylvania,Mideast
15,Great Lakes........................,"1,984,929","1,985,880 1,963,163","2,037,329",14.2,13.9 14.0,14.0,"1,985,880","1,963,163",13.9,14.0,Great Lakes,NaN
16,Illinois.................................,"629,379","637,037 631,970","651,518",4.5,4.5 4.5,4.5,"637,037","631,970",4.5,4.5,Illinois,Great Lakes
17,Indiana...............................,"262,596","263,616 259,894","275,676",1.9,1.8 1.9,1.9,"263,616","259,894",1.8,1.9,Indiana,Great Lakes
18,Michigan............................,"387,086","375,436 369,671","384,171",2.8,2.6 2.6,2.6,"375,436","369,671",2.6,2.6,Michigan,Great Lakes
19,Ohio...................................,"468,707","470,640 462,015","477,699",3.4,3.3 3.3,3.3,"470,640","462,015",3.3,3.3,Ohio,Great Lakes
20,Wisconsin..........................,"237,160","239,150 239,613","248,265",1.7,1.7 1.7,1.7,"239,150","239,613",1.7,1.7,Wisconsin,Great Lakes
21,Plains..................................,"889,072","919,248 911,352","948,287",6.4,6.4 6.5,6.5,"919,248","911,352",6.4,6.5,Plains,NaN
22,Iowa...................................,"134,410","134,959 136,062","142,698",1.0,0.9 1.0,1.0,"134,959","136,062",0.9,1.0,Iowa,Plains
23,Kansas...............................,"121,268","125,333 122,544","127,170",0.9,0.9 0.9,0.9,"125,333","122,544",0.9,0.9,Kansas,Plains
24,Minnesota..........................,"254,567","262,758 258,499","270,039",1.8,1.8 1.8,1.9,"262,758","258,499",1.8,1.8,Minnesota,Plains
25,Missouri.............................,"233,008","241,344 237,955","244,016",1.7,1.7 1.7,1.7,"241,344","237,955",1.7,1.7,Missouri,Plains
26,Nebraska...........................,"82,185","84,884 86,411","89,786",0.6,0.6 0.6,0.6,"84,884","86,411",0.6,0.6,Nebraska,Plains
27,North Dakota.....................,"28,552","31,677 31,626","34,685",0.2,0.2 0.2,0.2,"31,677","31,626",0.2,0.2,North Dakota,Plains
28,South Dakota.....................,"35,082","38,293 38,255","39,893",0.3,0.3 0.3,0.3,"38,293","38,255",0.3,0.3,South Dakota,Plains
29,Southeast...........................,"3,118,542","3,161,091 3,128,268","3,238,209",22.3,22.2 22.3,22.3,"3,161,091","3,128,268",22.2,22.3,Southeast,NaN
30,Alabama............................,"165,981","169,694 166,819","172,567",1.2,1.2 1.2,1.2,"169,694","166,819",1.2,1.2,Alabama,Southeast
31,Arkansas............................,"97,187","99,497 98,795","102,566",0.7,0.7 0.7,0.7,"99,497","98,795",0.7,0.7,Arkansas,Southeast
32,Florida................................,"759,572","747,770 732,782","747,735",5.4,5.2 5.2,5.1,"747,770","732,782",5.2,5.2,Florida,Southeast
33,Georgia..............................,"400,331","405,269 394,117","403,070",2.9,2.8 2.8,2.8,"405,269","394,117",2.8,2.8,Georgia,Southeast
34,Kentucky............................,"151,506","155,592 155,789","163,269",1.1,1.1 1.1,1.1,"155,592","155,789",1.1,1.1,Kentucky,Southeast
35,Louisiana...........................,"205,758","213,441 205,117","218,853",1.5,1.5 1.5,1.5,"213,441","205,117",1.5,1.5,Louisiana,Southeast
36,Mississippi.........................,"93,194","96,713 94,406","97,461",0.7,0.7 0.7,0.7,"96,713","94,406",0.7,0.7,Mississippi,Southeast
37,North Carolina...................,"397,975","403,927 407,032","424,935",2.8,2.8 2.9,2.9,"403,927","407,032",2.8,2.9,North Carolina,Southeast
38,South Carolina...................,"158,041","159,500 158,786","164,445",1.1,1.1 1.1,1.1,"159,500","158,786",1.1,1.1,South Carolina,Southeast
39,Tennessee.........................,"242,678","247,796 243,849","254,806",1.7,1.7 1.7,1.8,"247,796","243,849",1.7,1.7,Tennessee,Southeast
40,Virginia...............................,"389,319","402,853 409,732","423,860",2.8,2.8 2.9,2.9,"402,853","409,732",2.8,2.9,Virginia,Southeast
41,West Virginia.....................,"57,001","59,039 61,043","64,642",0.4,0.4 0.4,0.4,"59,039","61,043",0.4,0.4,West Virginia,Southeast
42,Southwest..........................,"1,622,669","1,691,577 1,615,618","1,688,324",11.6,11.9 11.5,11.6,"1,691,577","1,615,618",11.9,11.5,Southwest,NaN
43,Arizona..............................,"260,122","260,454 249,711","253,609",1.9,1.8 1.8,1.7,"260,454","249,711",1.8,1.8,Arizona,Southwest
44,New Mexico.......................,"74,393","77,168 76,871","79,678",0.5,0.5 0.5,0.5,"77,168","76,871",0.5,0.5,New Mexico,Southwest
45,Oklahoma..........................,"140,183","151,850 142,388","147,543",1.0,1.1 1.0,1.0,"151,850","142,388",1.1,1.0,Oklahoma,Southwest
46,Texas.................................,"1,147,970","1,202,104 1,146,647","1,207,494",8.2,8.4 8.2,8.3,"1,202,104","1,146,647",8.4,8.2,Texas,Southwest
47,Rocky Mountain.................,"474,833","496,537 487,384","502,207",3.4,3.5 3.5,3.5,"496,537","487,384",3.5,3.5,Rocky Mountain,NaN
48,Colorado............................,"242,900","254,218 250,664","257,641",1.7,1.8 1.8,1.8,"254,218","250,664",1.8,1.8,Colorado,Rocky Mountain
49,Idaho..................................,"54,344","55,212 53,661","55,435",0.4,0.4 0.4,0.4,"55,212","53,661",0.4,0.4,Idaho,Rocky Mountain
50,Montana.............................,"35,100","35,838 34,999","36,067",0.3,0.3 0.2,0.2,"35,838","34,999",0.3,0.2,Montana,Rocky Mountain
51,Utah...................................,"108,815","112,353 111,301","114,538",0.8,0.8 0.8,0.8,"112,353","111,301",0.8,0.8,Utah,Rocky Mountain
52,Wyoming............................,"33,674","38,917 36,760","38,527",0.2,0.3 0.3,0.3,"38,917","36,760",0.3,0.3,Wyoming,Rocky Mountain
53,Far West.............................,"2,609,491","2,668,247 2,582,493","2,657,228",18.7,18.7 18.4,18.3,"2,668,247","2,582,493",18.7,18.4,Far West,NaN
54,Alaska................................,"44,587","49,186 45,861","49,120",0.3,0.3 0.3,0.3,"49,186","45,861",0.3,0.3,Alaska,Far West
55,California...........................,"1,874,783","1,911,741 1,847,048","1,901,088",13.4,13.4 13.2,13.1,"1,911,741","1,847,048",13.4,13.2,California,Far West
56,Hawaii................................,"64,212","66,119 65,428","66,760",0.5,0.5 0.5,0.5,"66,119","65,428",0.5,0.5,Hawaii,Far West
57,Nevada..............................,"133,782","132,270 125,037","125,650",1.0,0.9 0.9,0.9,"132,270","125,037",0.9,0.9,Nevada,Far West
58,Oregon...............................,"167,016","174,454 167,481","174,151",1.2,1.2 1.2,1.2,"174,454","167,481",1.2,1.2,Oregon,Far West
59,Washington........................,"325,112","334,477 331,639","340,460",2.3,2.3 2.4,2.3,"334,477","331,639",2.3,2.4,Washington,Far West

In [37]:
GDP07_09.restructureDataFrame('Cleaned Area')

     year          state current dollars        GDP        GDP_area
0    2007         Alaska            2010    44587.0        Far West
1    2007        Alabama            2010   165981.0       Southeast
2    2007       Arkansas            2010    97187.0       Southeast
3    2007        Arizona            2010   260122.0       Southwest
4    2007     California            2010  1874783.0        Far West
..    ...            ...             ...        ...             ...
148  2009        Vermont            2010    24625.0     New England
149  2009     Washington            2010   331639.0        Far West
150  2009      Wisconsin            2010   239613.0     Great Lakes
151  2009  West Virginia            2010    61043.0       Southeast
152  2009        Wyoming            2010    36760.0  Rocky Mountain

[153 rows x 5 columns]

# GDP 10-12 Data

In [38]:
# create instance of yearly GDP data
GDP10_12 = YearlyGDP('GDP2010-2012.pdf', 10, 2010, 2012, '2013')

In [39]:
# testing that it was initialized with an empty DataFrame
GDP10_12.df

Empty DataFrame
Columns: []
Index: []

In [40]:
# initializeDataFrame() method reads in the PDF, assigns the first DataFrame in the 
# list as the df (only one table per page), and renames the columns. Lastly, it returns 
# the DataFrame for viewing
GDP10_12.initializeDataFrame()

,Area,2010,2011 2012,2013,2010.0,2011 2012,2013
0,United States/1/...............,"14,862,637","15,431,583 16,141,152","16,701,415",100.0,100.0 100.0,100.0
1,New England ...............,"823,311","842,182 874,201","900,870",5.5,5.5 5.4,5.4
2,Connecticut ...............,"233,781","235,121 242,930","249,251",1.6,1.5 1.5,1.5
3,Maine .......................,"51,470","51,756 53,235","54,755",0.3,0.3 0.3,0.3
4,Massachusetts ...........,"399,603","413,716 431,937","446,323",2.7,2.7 2.7,2.7
5,New Hampshire .........,"62,622","64,122 66,111","67,848",0.4,0.4 0.4,0.4
6,Rhode Island .............,"49,265","49,921 51,566","53,184",0.3,0.3 0.3,0.3
7,Vermont ....................,"26,570","27,545 28,422","29,509",0.2,0.2 0.2,0.2
8,Mideast ......................,"2,766,975","2,841,050 2,948,377","3,017,145",18.6,18.4 18.3,18.1
9,Delaware ..................,"57,628","58,612 60,650","62,703",0.4,0.4 0.4,0.4
10,District of Columbia .....,"106,615","110,702 111,870","113,362",0.7,0.7 0.7,0.7
11,Maryland ..................,"316,164","326,237 336,481","342,382",2.1,2.1 2.1,2.1
12,New Jersey ...............,"497,733","504,078 528,788","543,071",3.3,3.3 3.3,3.3
13,New York ..................,"1,198,004","1,231,470 1,280,737","1,310,712",8.1,8.0 7.9,7.8
14,Pennsylvania .............,"590,830","609,952 629,851","644,915",4.0,4.0 3.9,3.9
15,Great Lakes ................,"2,072,637","2,152,025 2,248,357","2,318,125",13.9,13.9 13.9,13.9
16,Illinois ......................,"652,681","676,911 704,138","720,692",4.4,4.4 4.4,4.3
17,Indiana .....................,"283,289","292,032 306,838","317,102",1.9,1.9 1.9,1.9
18,Michigan ...................,"387,730","400,924 416,769","432,573",2.6,2.6 2.6,2.6
19,Ohio ........................,"494,695","519,082 548,526","565,272",3.3,3.4 3.4,3.4
20,Wisconsin .................,"254,242","263,076 272,086","282,486",1.7,1.7 1.7,1.7
21,Plains ........................,"963,883","1,011,093 1,059,521","1,110,930",6.5,6.6 6.6,6.7
22,Iowa ........................,"141,814","148,997 156,606","165,767",1.0,1.0 1.0,1.0
23,Kansas ....................,"126,347","135,336 138,958","144,062",0.9,0.9 0.9,0.9
24,Minnesota .................,"272,244","285,669 298,272","312,081",1.8,1.9 1.8,1.9
25,Missouri ....................,"257,924","259,894 269,356","276,345",1.7,1.7 1.7,1.7
26,Nebraska ..................,"91,131","98,237 103,062","109,614",0.6,0.6 0.6,0.7
27,North Dakota ...............,"35,482","40,508 49,509","56,329",0.2,0.3 0.3,0.3
28,South Dakota .............,"38,940","42,453 43,758","46,732",0.3,0.3 0.3,0.3
29,Southeast ...................,"3,246,604","3,332,594 3,472,380","3,584,035",21.8,21.6 21.5,21.5
30,Alabama ...................,"175,734","181,848 189,542","193,566",1.2,1.2 1.2,1.2
31,Arkansas ..................,"111,355","115,582 118,993","124,218",0.7,0.7 0.7,0.7
32,Florida ......................,"728,604","736,347 769,007","800,492",4.9,4.8 4.8,4.8
33,Georgia ....................,"410,902","421,564 438,324","454,532",2.8,2.7 2.7,2.7
34,Kentucky ..................,"166,344","172,517 177,967","183,373",1.1,1.1 1.1,1.1
35,Louisiana ..................,"232,879","242,666 251,369","253,576",1.6,1.6 1.6,1.5
36,Mississippi ................,"94,649","96,224 101,549","105,163",0.6,0.6 0.6,0.6
37,North Carolina ............,"420,876","429,793 452,358","471,365",2.8,2.8 2.8,2.8
38,South Carolina ............,"163,836","171,546 177,985","183,561",1.1,1.1 1.1,1.1
39,Tennessee ................,"253,987","264,940 280,485","287,633",1.7,1.7 1.7,1.7
40,Virginia .....................,"421,325","430,103 445,090","452,585",2.8,2.8 2.8,2.7
41,West Virginia .............,"66,111","69,463 69,711","73,970",0.4,0.5 0.4,0.4
42,Southwest ..................,"1,734,123","1,868,243 1,995,143","2,085,978",11.7,12.1 12.4,12.5
43,Arizona .....................,"247,752","258,187 271,503","279,024",1.7,1.7 1.7,1.7
44,New Mexico ...............,"83,798","87,334 89,188","92,245",0.6,0.6 0.6,0.6
45,Oklahoma ..................,"154,062","165,424 171,432","182,086",1.0,1.1 1.1,1.1
46,Texas ........................,"1,248,511","1,357,298 1,463,021","1,532,623",8.4,8.8 9.1,9.2
47,Rocky Mountain ...........,"509,098","532,381 555,243","587,402",3.4,3.4 3.4,3.5
48,Colorado ...................,"256,628","266,243 278,551","294,443",1.7,1.7 1.7,1.8
49,Idaho ........................,"55,427","56,956 58,231","62,247",0.4,0.4 0.4,0.4
50,Montana ...................,"37,520","40,250 42,140","44,040",0.3,0.3 0.3,0.3
51,Utah ........................,"119,249","125,754 134,483","141,240",0.8,0.8 0.8,0.8
52,Wyoming ..................,"40,274","43,178 41,839","45,432",0.3,0.3 0.3,0.3
53,Far West .....................,"2,746,006","2,852,015 2,987,928","3,096,931",18.5,18.5 18.5,18.5
54,Alaska ......................,"53,251","58,581 59,643","59,355",0.4,0.4 0.4,0.4
55,California ..................,"1,953,411","2,030,468 2,125,717","2,202,678",13.1,13.2 13.2,13.2
56,Hawaii ......................,"67,285","69,755 72,512","75,235",0.5,0.5 0.4,0.5
57,Nevada .....................,"120,579","123,365 128,896","132,024",0.8,0.8 0.8,0.8
58,Oregon .....................,"190,800","199,488 210,242","219,590",1.3,1.3 1.3,1.3
59,Washington ...............,"360,680","370,359 390,918","408,049",2.4,2.4 2.4,2.4

In [41]:
GDP10_12.splitColumns(2, '2011', '2012')

,Area,2010,2011 2012,2013,2010.0,2011 2012,2013,2011,2012
0,United States/1/...............,"14,862,637","15,431,583 16,141,152","16,701,415",100.0,100.0 100.0,100.0,"15,431,583","16,141,152"
1,New England ...............,"823,311","842,182 874,201","900,870",5.5,5.5 5.4,5.4,"842,182","874,201"
2,Connecticut ...............,"233,781","235,121 242,930","249,251",1.6,1.5 1.5,1.5,"235,121","242,930"
3,Maine .......................,"51,470","51,756 53,235","54,755",0.3,0.3 0.3,0.3,"51,756","53,235"
4,Massachusetts ...........,"399,603","413,716 431,937","446,323",2.7,2.7 2.7,2.7,"413,716","431,937"
5,New Hampshire .........,"62,622","64,122 66,111","67,848",0.4,0.4 0.4,0.4,"64,122","66,111"
6,Rhode Island .............,"49,265","49,921 51,566","53,184",0.3,0.3 0.3,0.3,"49,921","51,566"
7,Vermont ....................,"26,570","27,545 28,422","29,509",0.2,0.2 0.2,0.2,"27,545","28,422"
8,Mideast ......................,"2,766,975","2,841,050 2,948,377","3,017,145",18.6,18.4 18.3,18.1,"2,841,050","2,948,377"
9,Delaware ..................,"57,628","58,612 60,650","62,703",0.4,0.4 0.4,0.4,"58,612","60,650"
10,District of Columbia .....,"106,615","110,702 111,870","113,362",0.7,0.7 0.7,0.7,"110,702","111,870"
11,Maryland ..................,"316,164","326,237 336,481","342,382",2.1,2.1 2.1,2.1,"326,237","336,481"
12,New Jersey ...............,"497,733","504,078 528,788","543,071",3.3,3.3 3.3,3.3,"504,078","528,788"
13,New York ..................,"1,198,004","1,231,470 1,280,737","1,310,712",8.1,8.0 7.9,7.8,"1,231,470","1,280,737"
14,Pennsylvania .............,"590,830","609,952 629,851","644,915",4.0,4.0 3.9,3.9,"609,952","629,851"
15,Great Lakes ................,"2,072,637","2,152,025 2,248,357","2,318,125",13.9,13.9 13.9,13.9,"2,152,025","2,248,357"
16,Illinois ......................,"652,681","676,911 704,138","720,692",4.4,4.4 4.4,4.3,"676,911","704,138"
17,Indiana .....................,"283,289","292,032 306,838","317,102",1.9,1.9 1.9,1.9,"292,032","306,838"
18,Michigan ...................,"387,730","400,924 416,769","432,573",2.6,2.6 2.6,2.6,"400,924","416,769"
19,Ohio ........................,"494,695","519,082 548,526","565,272",3.3,3.4 3.4,3.4,"519,082","548,526"
20,Wisconsin .................,"254,242","263,076 272,086","282,486",1.7,1.7 1.7,1.7,"263,076","272,086"
21,Plains ........................,"963,883","1,011,093 1,059,521","1,110,930",6.5,6.6 6.6,6.7,"1,011,093","1,059,521"
22,Iowa ........................,"141,814","148,997 156,606","165,767",1.0,1.0 1.0,1.0,"148,997","156,606"
23,Kansas ....................,"126,347","135,336 138,958","144,062",0.9,0.9 0.9,0.9,"135,336","138,958"
24,Minnesota .................,"272,244","285,669 298,272","312,081",1.8,1.9 1.8,1.9,"285,669","298,272"
25,Missouri ....................,"257,924","259,894 269,356","276,345",1.7,1.7 1.7,1.7,"259,894","269,356"
26,Nebraska ..................,"91,131","98,237 103,062","109,614",0.6,0.6 0.6,0.7,"98,237","103,062"
27,North Dakota ...............,"35,482","40,508 49,509","56,329",0.2,0.3 0.3,0.3,"40,508","49,509"
28,South Dakota .............,"38,940","42,453 43,758","46,732",0.3,0.3 0.3,0.3,"42,453","43,758"
29,Southeast ...................,"3,246,604","3,332,594 3,472,380","3,584,035",21.8,21.6 21.5,21.5,"3,332,594","3,472,380"
30,Alabama ...................,"175,734","181,848 189,542","193,566",1.2,1.2 1.2,1.2,"181,848","189,542"
31,Arkansas ..................,"111,355","115,582 118,993","124,218",0.7,0.7 0.7,0.7,"115,582","118,993"
32,Florida ......................,"728,604","736,347 769,007","800,492",4.9,4.8 4.8,4.8,"736,347","769,007"
33,Georgia ....................,"410,902","421,564 438,324","454,532",2.8,2.7 2.7,2.7,"421,564","438,324"
34,Kentucky ..................,"166,344","172,517 177,967","183,373",1.1,1.1 1.1,1.1,"172,517","177,967"
35,Louisiana ..................,"232,879","242,666 251,369","253,576",1.6,1.6 1.6,1.5,"242,666","251,369"
36,Mississippi ................,"94,649","96,224 101,549","105,163",0.6,0.6 0.6,0.6,"96,224","101,549"
37,North Carolina ............,"420,876","429,793 452,358","471,365",2.8,2.8 2.8,2.8,"429,793","452,358"
38,South Carolina ............,"163,836","171,546 177,985","183,561",1.1,1.1 1.1,1.1,"171,546","177,985"
39,Tennessee ................,"253,987","264,940 280,485","287,633",1.7,1.7 1.7,1.7,"264,940","280,485"
40,Virginia .....................,"421,325","430,103 445,090","452,585",2.8,2.8 2.8,2.7,"430,103","445,090"
41,West Virginia .............,"66,111","69,463 69,711","73,970",0.4,0.5 0.4,0.4,"69,463","69,711"
42,Southwest ..................,"1,734,123","1,868,243 1,995,143","2,085,978",11.7,12.1 12.4,12.5,"1,868,243","1,995,143"
43,Arizona .....................,"247,752","258,187 271,503","279,024",1.7,1.7 1.7,1.7,"258,187","271,503"
44,New Mexico ...............,"83,798","87,334 89,188","92,245",0.6,0.6 0.6,0.6,"87,334","89,188"
45,Oklahoma ..................,"154,062","165,424 171,432","182,086",1.0,1.1 1.1,1.1,"165,424","171,432"
46,Texas ........................,"1,248,511","1,357,298 1,463,021","1,532,623",8.4,8.8 9.1,9.2,"1,357,298","1,463,021"
47,Rocky Mountain ...........,"509,098","532,381 555,243","587,402",3.4,3.4 3.4,3.5,"532,381","555,243"
48,Colorado ...................,"256,628","266,243 278,551","294,443",1.7,1.7 1.7,1.8,"266,243","278,551"
49,Idaho ........................,"55,427","56,956 58,231","62,247",0.4,0.4 0.4,0.4,"56,956","58,231"
50,Montana ...................,"37,520","40,250 42,140","44,040",0.3,0.3 0.3,0.3,"40,250","42,140"
51,Utah ........................,"119,249","125,754 134,483","141,240",0.8,0.8 0.8,0.8,"125,754","134,483"
52,Wyoming ..................,"40,274","43,178 41,839","45,432",0.3,0.3 0.3,0.3,"43,178","41,839"
53,Far West .....................,"2,746,006","2,852,015 2,987,928","3,096,931",18.5,18.5 18.5,18.5,"2,852,015","2,987,928"
54,Alaska ......................,"53,251","58,581 59,643","59,355",0.4,0.4 0.4,0.4,"58,581","59,643"
55,California ..................,"1,953,411","2,030,468 2,125,717","2,202,678",13.1,13.2 13.2,13.2,"2,030,468","2,125,717"
56,Hawaii ......................,"67,285","69,755 72,512","75,235",0.5,0.5 0.4,0.5,"69,755","72,512"
57,Nevada .....................,"120,579","123,365 128,896","132,024",0.8,0.8 0.8,0.8,"123,365","128,896"
58,Oregon .....................,"190,800","199,488 210,242","219,590",1.3,1.3 1.3,1.3,"199,488","210,242"
59,Washington ...............,"360,680","370,359 390,918","408,049",2.4,2.4 2.4,2.4,"370,359","390,918"

In [42]:
GDP10_12.splitColumns(5, '2011 %', '2012 %')

,Area,2010,2011 2012,2013,2010.0,2011 2012,2013,2011,2012,2011 %,2012 %
0,United States/1/...............,"14,862,637","15,431,583 16,141,152","16,701,415",100.0,100.0 100.0,100.0,"15,431,583","16,141,152",100.0,100.0
1,New England ...............,"823,311","842,182 874,201","900,870",5.5,5.5 5.4,5.4,"842,182","874,201",5.5,5.4
2,Connecticut ...............,"233,781","235,121 242,930","249,251",1.6,1.5 1.5,1.5,"235,121","242,930",1.5,1.5
3,Maine .......................,"51,470","51,756 53,235","54,755",0.3,0.3 0.3,0.3,"51,756","53,235",0.3,0.3
4,Massachusetts ...........,"399,603","413,716 431,937","446,323",2.7,2.7 2.7,2.7,"413,716","431,937",2.7,2.7
5,New Hampshire .........,"62,622","64,122 66,111","67,848",0.4,0.4 0.4,0.4,"64,122","66,111",0.4,0.4
6,Rhode Island .............,"49,265","49,921 51,566","53,184",0.3,0.3 0.3,0.3,"49,921","51,566",0.3,0.3
7,Vermont ....................,"26,570","27,545 28,422","29,509",0.2,0.2 0.2,0.2,"27,545","28,422",0.2,0.2
8,Mideast ......................,"2,766,975","2,841,050 2,948,377","3,017,145",18.6,18.4 18.3,18.1,"2,841,050","2,948,377",18.4,18.3
9,Delaware ..................,"57,628","58,612 60,650","62,703",0.4,0.4 0.4,0.4,"58,612","60,650",0.4,0.4
10,District of Columbia .....,"106,615","110,702 111,870","113,362",0.7,0.7 0.7,0.7,"110,702","111,870",0.7,0.7
11,Maryland ..................,"316,164","326,237 336,481","342,382",2.1,2.1 2.1,2.1,"326,237","336,481",2.1,2.1
12,New Jersey ...............,"497,733","504,078 528,788","543,071",3.3,3.3 3.3,3.3,"504,078","528,788",3.3,3.3
13,New York ..................,"1,198,004","1,231,470 1,280,737","1,310,712",8.1,8.0 7.9,7.8,"1,231,470","1,280,737",8.0,7.9
14,Pennsylvania .............,"590,830","609,952 629,851","644,915",4.0,4.0 3.9,3.9,"609,952","629,851",4.0,3.9
15,Great Lakes ................,"2,072,637","2,152,025 2,248,357","2,318,125",13.9,13.9 13.9,13.9,"2,152,025","2,248,357",13.9,13.9
16,Illinois ......................,"652,681","676,911 704,138","720,692",4.4,4.4 4.4,4.3,"676,911","704,138",4.4,4.4
17,Indiana .....................,"283,289","292,032 306,838","317,102",1.9,1.9 1.9,1.9,"292,032","306,838",1.9,1.9
18,Michigan ...................,"387,730","400,924 416,769","432,573",2.6,2.6 2.6,2.6,"400,924","416,769",2.6,2.6
19,Ohio ........................,"494,695","519,082 548,526","565,272",3.3,3.4 3.4,3.4,"519,082","548,526",3.4,3.4
20,Wisconsin .................,"254,242","263,076 272,086","282,486",1.7,1.7 1.7,1.7,"263,076","272,086",1.7,1.7
21,Plains ........................,"963,883","1,011,093 1,059,521","1,110,930",6.5,6.6 6.6,6.7,"1,011,093","1,059,521",6.6,6.6
22,Iowa ........................,"141,814","148,997 156,606","165,767",1.0,1.0 1.0,1.0,"148,997","156,606",1.0,1.0
23,Kansas ....................,"126,347","135,336 138,958","144,062",0.9,0.9 0.9,0.9,"135,336","138,958",0.9,0.9
24,Minnesota .................,"272,244","285,669 298,272","312,081",1.8,1.9 1.8,1.9,"285,669","298,272",1.9,1.8
25,Missouri ....................,"257,924","259,894 269,356","276,345",1.7,1.7 1.7,1.7,"259,894","269,356",1.7,1.7
26,Nebraska ..................,"91,131","98,237 103,062","109,614",0.6,0.6 0.6,0.7,"98,237","103,062",0.6,0.6
27,North Dakota ...............,"35,482","40,508 49,509","56,329",0.2,0.3 0.3,0.3,"40,508","49,509",0.3,0.3
28,South Dakota .............,"38,940","42,453 43,758","46,732",0.3,0.3 0.3,0.3,"42,453","43,758",0.3,0.3
29,Southeast ...................,"3,246,604","3,332,594 3,472,380","3,584,035",21.8,21.6 21.5,21.5,"3,332,594","3,472,380",21.6,21.5
30,Alabama ...................,"175,734","181,848 189,542","193,566",1.2,1.2 1.2,1.2,"181,848","189,542",1.2,1.2
31,Arkansas ..................,"111,355","115,582 118,993","124,218",0.7,0.7 0.7,0.7,"115,582","118,993",0.7,0.7
32,Florida ......................,"728,604","736,347 769,007","800,492",4.9,4.8 4.8,4.8,"736,347","769,007",4.8,4.8
33,Georgia ....................,"410,902","421,564 438,324","454,532",2.8,2.7 2.7,2.7,"421,564","438,324",2.7,2.7
34,Kentucky ..................,"166,344","172,517 177,967","183,373",1.1,1.1 1.1,1.1,"172,517","177,967",1.1,1.1
35,Louisiana ..................,"232,879","242,666 251,369","253,576",1.6,1.6 1.6,1.5,"242,666","251,369",1.6,1.6
36,Mississippi ................,"94,649","96,224 101,549","105,163",0.6,0.6 0.6,0.6,"96,224","101,549",0.6,0.6
37,North Carolina ............,"420,876","429,793 452,358","471,365",2.8,2.8 2.8,2.8,"429,793","452,358",2.8,2.8
38,South Carolina ............,"163,836","171,546 177,985","183,561",1.1,1.1 1.1,1.1,"171,546","177,985",1.1,1.1
39,Tennessee ................,"253,987","264,940 280,485","287,633",1.7,1.7 1.7,1.7,"264,940","280,485",1.7,1.7
40,Virginia .....................,"421,325","430,103 445,090","452,585",2.8,2.8 2.8,2.7,"430,103","445,090",2.8,2.8
41,West Virginia .............,"66,111","69,463 69,711","73,970",0.4,0.5 0.4,0.4,"69,463","69,711",0.5,0.4
42,Southwest ..................,"1,734,123","1,868,243 1,995,143","2,085,978",11.7,12.1 12.4,12.5,"1,868,243","1,995,143",12.1,12.4
43,Arizona .....................,"247,752","258,187 271,503","279,024",1.7,1.7 1.7,1.7,"258,187","271,503",1.7,1.7
44,New Mexico ...............,"83,798","87,334 89,188","92,245",0.6,0.6 0.6,0.6,"87,334","89,188",0.6,0.6
45,Oklahoma ..................,"154,062","165,424 171,432","182,086",1.0,1.1 1.1,1.1,"165,424","171,432",1.1,1.1
46,Texas ........................,"1,248,511","1,357,298 1,463,021","1,532,623",8.4,8.8 9.1,9.2,"1,357,298","1,463,021",8.8,9.1
47,Rocky Mountain ...........,"509,098","532,381 555,243","587,402",3.4,3.4 3.4,3.5,"532,381","555,243",3.4,3.4
48,Colorado ...................,"256,628","266,243 278,551","294,443",1.7,1.7 1.7,1.8,"266,243","278,551",1.7,1.7
49,Idaho ........................,"55,427","56,956 58,231","62,247",0.4,0.4 0.4,0.4,"56,956","58,231",0.4,0.4
50,Montana ...................,"37,520","40,250 42,140","44,040",0.3,0.3 0.3,0.3,"40,250","42,140",0.3,0.3
51,Utah ........................,"119,249","125,754 134,483","141,240",0.8,0.8 0.8,0.8,"125,754","134,483",0.8,0.8
52,Wyoming ..................,"40,274","43,178 41,839","45,432",0.3,0.3 0.3,0.3,"43,178","41,839",0.3,0.3
53,Far West .....................,"2,746,006","2,852,015 2,987,928","3,096,931",18.5,18.5 18.5,18.5,"2,852,015","2,987,928",18.5,18.5
54,Alaska ......................,"53,251","58,581 59,643","59,355",0.4,0.4 0.4,0.4,"58,581","59,643",0.4,0.4
55,California ..................,"1,953,411","2,030,468 2,125,717","2,202,678",13.1,13.2 13.2,13.2,"2,030,468","2,125,717",13.2,13.2
56,Hawaii ......................,"67,285","69,755 72,512","75,235",0.5,0.5 0.4,0.5,"69,755","72,512",0.5,0.4
57,Nevada .....................,"120,579","123,365 128,896","132,024",0.8,0.8 0.8,0.8,"123,365","128,896",0.8,0.8
58,Oregon .....................,"190,800","199,488 210,242","219,590",1.3,1.3 1.3,1.3,"199,488","210,242",1.3,1.3
59,Washington ...............,"360,680","370,359 390,918","408,049",2.4,2.4 2.4,2.4,"370,359","390,918",2.4,2.4

In [43]:
GDP10_12.cleanStates('Area')

,Area,2010,2011 2012,2013,2010.0,2011 2012,2013,2011,2012,2011 %,2012 %,Cleaned Area
0,United States/1/...............,"14,862,637","15,431,583 16,141,152","16,701,415",100.0,100.0 100.0,100.0,"15,431,583","16,141,152",100.0,100.0,United States
1,New England ...............,"823,311","842,182 874,201","900,870",5.5,5.5 5.4,5.4,"842,182","874,201",5.5,5.4,New England
2,Connecticut ...............,"233,781","235,121 242,930","249,251",1.6,1.5 1.5,1.5,"235,121","242,930",1.5,1.5,Connecticut
3,Maine .......................,"51,470","51,756 53,235","54,755",0.3,0.3 0.3,0.3,"51,756","53,235",0.3,0.3,Maine
4,Massachusetts ...........,"399,603","413,716 431,937","446,323",2.7,2.7 2.7,2.7,"413,716","431,937",2.7,2.7,Massachusetts
5,New Hampshire .........,"62,622","64,122 66,111","67,848",0.4,0.4 0.4,0.4,"64,122","66,111",0.4,0.4,New Hampshire
6,Rhode Island .............,"49,265","49,921 51,566","53,184",0.3,0.3 0.3,0.3,"49,921","51,566",0.3,0.3,Rhode Island
7,Vermont ....................,"26,570","27,545 28,422","29,509",0.2,0.2 0.2,0.2,"27,545","28,422",0.2,0.2,Vermont
8,Mideast ......................,"2,766,975","2,841,050 2,948,377","3,017,145",18.6,18.4 18.3,18.1,"2,841,050","2,948,377",18.4,18.3,Mideast
9,Delaware ..................,"57,628","58,612 60,650","62,703",0.4,0.4 0.4,0.4,"58,612","60,650",0.4,0.4,Delaware
10,District of Columbia .....,"106,615","110,702 111,870","113,362",0.7,0.7 0.7,0.7,"110,702","111,870",0.7,0.7,District of Columbia
11,Maryland ..................,"316,164","326,237 336,481","342,382",2.1,2.1 2.1,2.1,"326,237","336,481",2.1,2.1,Maryland
12,New Jersey ...............,"497,733","504,078 528,788","543,071",3.3,3.3 3.3,3.3,"504,078","528,788",3.3,3.3,New Jersey
13,New York ..................,"1,198,004","1,231,470 1,280,737","1,310,712",8.1,8.0 7.9,7.8,"1,231,470","1,280,737",8.0,7.9,New York
14,Pennsylvania .............,"590,830","609,952 629,851","644,915",4.0,4.0 3.9,3.9,"609,952","629,851",4.0,3.9,Pennsylvania
15,Great Lakes ................,"2,072,637","2,152,025 2,248,357","2,318,125",13.9,13.9 13.9,13.9,"2,152,025","2,248,357",13.9,13.9,Great Lakes
16,Illinois ......................,"652,681","676,911 704,138","720,692",4.4,4.4 4.4,4.3,"676,911","704,138",4.4,4.4,Illinois
17,Indiana .....................,"283,289","292,032 306,838","317,102",1.9,1.9 1.9,1.9,"292,032","306,838",1.9,1.9,Indiana
18,Michigan ...................,"387,730","400,924 416,769","432,573",2.6,2.6 2.6,2.6,"400,924","416,769",2.6,2.6,Michigan
19,Ohio ........................,"494,695","519,082 548,526","565,272",3.3,3.4 3.4,3.4,"519,082","548,526",3.4,3.4,Ohio
20,Wisconsin .................,"254,242","263,076 272,086","282,486",1.7,1.7 1.7,1.7,"263,076","272,086",1.7,1.7,Wisconsin
21,Plains ........................,"963,883","1,011,093 1,059,521","1,110,930",6.5,6.6 6.6,6.7,"1,011,093","1,059,521",6.6,6.6,Plains
22,Iowa ........................,"141,814","148,997 156,606","165,767",1.0,1.0 1.0,1.0,"148,997","156,606",1.0,1.0,Iowa
23,Kansas ....................,"126,347","135,336 138,958","144,062",0.9,0.9 0.9,0.9,"135,336","138,958",0.9,0.9,Kansas
24,Minnesota .................,"272,244","285,669 298,272","312,081",1.8,1.9 1.8,1.9,"285,669","298,272",1.9,1.8,Minnesota
25,Missouri ....................,"257,924","259,894 269,356","276,345",1.7,1.7 1.7,1.7,"259,894","269,356",1.7,1.7,Missouri
26,Nebraska ..................,"91,131","98,237 103,062","109,614",0.6,0.6 0.6,0.7,"98,237","103,062",0.6,0.6,Nebraska
27,North Dakota ...............,"35,482","40,508 49,509","56,329",0.2,0.3 0.3,0.3,"40,508","49,509",0.3,0.3,North Dakota
28,South Dakota .............,"38,940","42,453 43,758","46,732",0.3,0.3 0.3,0.3,"42,453","43,758",0.3,0.3,South Dakota
29,Southeast ...................,"3,246,604","3,332,594 3,472,380","3,584,035",21.8,21.6 21.5,21.5,"3,332,594","3,472,380",21.6,21.5,Southeast
30,Alabama ...................,"175,734","181,848 189,542","193,566",1.2,1.2 1.2,1.2,"181,848","189,542",1.2,1.2,Alabama
31,Arkansas ..................,"111,355","115,582 118,993","124,218",0.7,0.7 0.7,0.7,"115,582","118,993",0.7,0.7,Arkansas
32,Florida ......................,"728,604","736,347 769,007","800,492",4.9,4.8 4.8,4.8,"736,347","769,007",4.8,4.8,Florida
33,Georgia ....................,"410,902","421,564 438,324","454,532",2.8,2.7 2.7,2.7,"421,564","438,324",2.7,2.7,Georgia
34,Kentucky ..................,"166,344","172,517 177,967","183,373",1.1,1.1 1.1,1.1,"172,517","177,967",1.1,1.1,Kentucky
35,Louisiana ..................,"232,879","242,666 251,369","253,576",1.6,1.6 1.6,1.5,"242,666","251,369",1.6,1.6,Louisiana
36,Mississippi ................,"94,649","96,224 101,549","105,163",0.6,0.6 0.6,0.6,"96,224","101,549",0.6,0.6,Mississippi
37,North Carolina ............,"420,876","429,793 452,358","471,365",2.8,2.8 2.8,2.8,"429,793","452,358",2.8,2.8,North Carolina
38,South Carolina ............,"163,836","171,546 177,985","183,561",1.1,1.1 1.1,1.1,"171,546","177,985",1.1,1.1,South Carolina
39,Tennessee ................,"253,987","264,940 280,485","287,633",1.7,1.7 1.7,1.7,"264,940","280,485",1.7,1.7,Tennessee
40,Virginia .....................,"421,325","430,103 445,090","452,585",2.8,2.8 2.8,2.7,"430,103","445,090",2.8,2.8,Virginia
41,West Virginia .............,"66,111","69,463 69,711","73,970",0.4,0.5 0.4,0.4,"69,463","69,711",0.5,0.4,West Virginia
42,Southwest ..................,"1,734,123","1,868,243 1,995,143","2,085,978",11.7,12.1 12.4,12.5,"1,868,243","1,995,143",12.1,12.4,Southwest
43,Arizona .....................,"247,752","258,187 271,503","279,024",1.7,1.7 1.7,1.7,"258,187","271,503",1.7,1.7,Arizona
44,New Mexico ...............,"83,798","87,334 89,188","92,245",0.6,0.6 0.6,0.6,"87,334","89,188",0.6,0.6,New Mexico
45,Oklahoma ..................,"154,062","165,424 171,432","182,086",1.0,1.1 1.1,1.1,"165,424","171,432",1.1,1.1,Oklahoma
46,Texas ........................,"1,248,511","1,357,298 1,463,021","1,532,623",8.4,8.8 9.1,9.2,"1,357,298","1,463,021",8.8,9.1,Texas
47,Rocky Mountain ...........,"509,098","532,381 555,243","587,402",3.4,3.4 3.4,3.5,"532,381","555,243",3.4,3.4,Rocky Mountain
48,Colorado ...................,"256,628","266,243 278,551","294,443",1.7,1.7 1.7,1.8,"266,243","278,551",1.7,1.7,Colorado
49,Idaho ........................,"55,427","56,956 58,231","62,247",0.4,0.4 0.4,0.4,"56,956","58,231",0.4,0.4,Idaho
50,Montana ...................,"37,520","40,250 42,140","44,040",0.3,0.3 0.3,0.3,"40,250","42,140",0.3,0.3,Montana
51,Utah ........................,"119,249","125,754 134,483","141,240",0.8,0.8 0.8,0.8,"125,754","134,483",0.8,0.8,Utah
52,Wyoming ..................,"40,274","43,178 41,839","45,432",0.3,0.3 0.3,0.3,"43,178","41,839",0.3,0.3,Wyoming
53,Far West .....................,"2,746,006","2,852,015 2,987,928","3,096,931",18.5,18.5 18.5,18.5,"2,852,015","2,987,928",18.5,18.5,Far West
54,Alaska ......................,"53,251","58,581 59,643","59,355",0.4,0.4 0.4,0.4,"58,581","59,643",0.4,0.4,Alaska
55,California ..................,"1,953,411","2,030,468 2,125,717","2,202,678",13.1,13.2 13.2,13.2,"2,030,468","2,125,717",13.2,13.2,California
56,Hawaii ......................,"67,285","69,755 72,512","75,235",0.5,0.5 0.4,0.5,"69,755","72,512",0.5,0.4,Hawaii
57,Nevada .....................,"120,579","123,365 128,896","132,024",0.8,0.8 0.8,0.8,"123,365","128,896",0.8,0.8,Nevada
58,Oregon .....................,"190,800","199,488 210,242","219,590",1.3,1.3 1.3,1.3,"199,488","210,242",1.3,1.3,Oregon
59,Washington ...............,"360,680","370,359 390,918","408,049",2.4,2.4 2.4,2.4,"370,359","390,918",2.4,2.4,Washington

In [44]:
GDP10_12.addGeoLocColumn('Cleaned Area')

,Area,2010,2011 2012,2013,2010.0,2011 2012,2013,2011,2012,2011 %,2012 %,Cleaned Area,Geo Loc
0,United States/1/...............,"14,862,637","15,431,583 16,141,152","16,701,415",100.0,100.0 100.0,100.0,"15,431,583","16,141,152",100.0,100.0,United States,NaN
1,New England ...............,"823,311","842,182 874,201","900,870",5.5,5.5 5.4,5.4,"842,182","874,201",5.5,5.4,New England,NaN
2,Connecticut ...............,"233,781","235,121 242,930","249,251",1.6,1.5 1.5,1.5,"235,121","242,930",1.5,1.5,Connecticut,New England
3,Maine .......................,"51,470","51,756 53,235","54,755",0.3,0.3 0.3,0.3,"51,756","53,235",0.3,0.3,Maine,New England
4,Massachusetts ...........,"399,603","413,716 431,937","446,323",2.7,2.7 2.7,2.7,"413,716","431,937",2.7,2.7,Massachusetts,New England
5,New Hampshire .........,"62,622","64,122 66,111","67,848",0.4,0.4 0.4,0.4,"64,122","66,111",0.4,0.4,New Hampshire,New England
6,Rhode Island .............,"49,265","49,921 51,566","53,184",0.3,0.3 0.3,0.3,"49,921","51,566",0.3,0.3,Rhode Island,New England
7,Vermont ....................,"26,570","27,545 28,422","29,509",0.2,0.2 0.2,0.2,"27,545","28,422",0.2,0.2,Vermont,New England
8,Mideast ......................,"2,766,975","2,841,050 2,948,377","3,017,145",18.6,18.4 18.3,18.1,"2,841,050","2,948,377",18.4,18.3,Mideast,NaN
9,Delaware ..................,"57,628","58,612 60,650","62,703",0.4,0.4 0.4,0.4,"58,612","60,650",0.4,0.4,Delaware,Mideast
10,District of Columbia .....,"106,615","110,702 111,870","113,362",0.7,0.7 0.7,0.7,"110,702","111,870",0.7,0.7,District of Columbia,Mideast
11,Maryland ..................,"316,164","326,237 336,481","342,382",2.1,2.1 2.1,2.1,"326,237","336,481",2.1,2.1,Maryland,Mideast
12,New Jersey ...............,"497,733","504,078 528,788","543,071",3.3,3.3 3.3,3.3,"504,078","528,788",3.3,3.3,New Jersey,Mideast
13,New York ..................,"1,198,004","1,231,470 1,280,737","1,310,712",8.1,8.0 7.9,7.8,"1,231,470","1,280,737",8.0,7.9,New York,Mideast
14,Pennsylvania .............,"590,830","609,952 629,851","644,915",4.0,4.0 3.9,3.9,"609,952","629,851",4.0,3.9,Pennsylvania,Mideast
15,Great Lakes ................,"2,072,637","2,152,025 2,248,357","2,318,125",13.9,13.9 13.9,13.9,"2,152,025","2,248,357",13.9,13.9,Great Lakes,NaN
16,Illinois ......................,"652,681","676,911 704,138","720,692",4.4,4.4 4.4,4.3,"676,911","704,138",4.4,4.4,Illinois,Great Lakes
17,Indiana .....................,"283,289","292,032 306,838","317,102",1.9,1.9 1.9,1.9,"292,032","306,838",1.9,1.9,Indiana,Great Lakes
18,Michigan ...................,"387,730","400,924 416,769","432,573",2.6,2.6 2.6,2.6,"400,924","416,769",2.6,2.6,Michigan,Great Lakes
19,Ohio ........................,"494,695","519,082 548,526","565,272",3.3,3.4 3.4,3.4,"519,082","548,526",3.4,3.4,Ohio,Great Lakes
20,Wisconsin .................,"254,242","263,076 272,086","282,486",1.7,1.7 1.7,1.7,"263,076","272,086",1.7,1.7,Wisconsin,Great Lakes
21,Plains ........................,"963,883","1,011,093 1,059,521","1,110,930",6.5,6.6 6.6,6.7,"1,011,093","1,059,521",6.6,6.6,Plains,NaN
22,Iowa ........................,"141,814","148,997 156,606","165,767",1.0,1.0 1.0,1.0,"148,997","156,606",1.0,1.0,Iowa,Plains
23,Kansas ....................,"126,347","135,336 138,958","144,062",0.9,0.9 0.9,0.9,"135,336","138,958",0.9,0.9,Kansas,Plains
24,Minnesota .................,"272,244","285,669 298,272","312,081",1.8,1.9 1.8,1.9,"285,669","298,272",1.9,1.8,Minnesota,Plains
25,Missouri ....................,"257,924","259,894 269,356","276,345",1.7,1.7 1.7,1.7,"259,894","269,356",1.7,1.7,Missouri,Plains
26,Nebraska ..................,"91,131","98,237 103,062","109,614",0.6,0.6 0.6,0.7,"98,237","103,062",0.6,0.6,Nebraska,Plains
27,North Dakota ...............,"35,482","40,508 49,509","56,329",0.2,0.3 0.3,0.3,"40,508","49,509",0.3,0.3,North Dakota,Plains
28,South Dakota .............,"38,940","42,453 43,758","46,732",0.3,0.3 0.3,0.3,"42,453","43,758",0.3,0.3,South Dakota,Plains
29,Southeast ...................,"3,246,604","3,332,594 3,472,380","3,584,035",21.8,21.6 21.5,21.5,"3,332,594","3,472,380",21.6,21.5,Southeast,NaN
30,Alabama ...................,"175,734","181,848 189,542","193,566",1.2,1.2 1.2,1.2,"181,848","189,542",1.2,1.2,Alabama,Southeast
31,Arkansas ..................,"111,355","115,582 118,993","124,218",0.7,0.7 0.7,0.7,"115,582","118,993",0.7,0.7,Arkansas,Southeast
32,Florida ......................,"728,604","736,347 769,007","800,492",4.9,4.8 4.8,4.8,"736,347","769,007",4.8,4.8,Florida,Southeast
33,Georgia ....................,"410,902","421,564 438,324","454,532",2.8,2.7 2.7,2.7,"421,564","438,324",2.7,2.7,Georgia,Southeast
34,Kentucky ..................,"166,344","172,517 177,967","183,373",1.1,1.1 1.1,1.1,"172,517","177,967",1.1,1.1,Kentucky,Southeast
35,Louisiana ..................,"232,879","242,666 251,369","253,576",1.6,1.6 1.6,1.5,"242,666","251,369",1.6,1.6,Louisiana,Southeast
36,Mississippi ................,"94,649","96,224 101,549","105,163",0.6,0.6 0.6,0.6,"96,224","101,549",0.6,0.6,Mississippi,Southeast
37,North Carolina ............,"420,876","429,793 452,358","471,365",2.8,2.8 2.8,2.8,"429,793","452,358",2.8,2.8,North Carolina,Southeast
38,South Carolina ............,"163,836","171,546 177,985","183,561",1.1,1.1 1.1,1.1,"171,546","177,985",1.1,1.1,South Carolina,Southeast
39,Tennessee ................,"253,987","264,940 280,485","287,633",1.7,1.7 1.7,1.7,"264,940","280,485",1.7,1.7,Tennessee,Southeast
40,Virginia .....................,"421,325","430,103 445,090","452,585",2.8,2.8 2.8,2.7,"430,103","445,090",2.8,2.8,Virginia,Southeast
41,West Virginia .............,"66,111","69,463 69,711","73,970",0.4,0.5 0.4,0.4,"69,463","69,711",0.5,0.4,West Virginia,Southeast
42,Southwest ..................,"1,734,123","1,868,243 1,995,143","2,085,978",11.7,12.1 12.4,12.5,"1,868,243","1,995,143",12.1,12.4,Southwest,NaN
43,Arizona .....................,"247,752","258,187 271,503","279,024",1.7,1.7 1.7,1.7,"258,187","271,503",1.7,1.7,Arizona,Southwest
44,New Mexico ...............,"83,798","87,334 89,188","92,245",0.6,0.6 0.6,0.6,"87,334","89,188",0.6,0.6,New Mexico,Southwest
45,Oklahoma ..................,"154,062","165,424 171,432","182,086",1.0,1.1 1.1,1.1,"165,424","171,432",1.1,1.1,Oklahoma,Southwest
46,Texas ........................,"1,248,511","1,357,298 1,463,021","1,532,623",8.4,8.8 9.1,9.2,"1,357,298","1,463,021",8.8,9.1,Texas,Southwest
47,Rocky Mountain ...........,"509,098","532,381 555,243","587,402",3.4,3.4 3.4,3.5,"532,381","555,243",3.4,3.4,Rocky Mountain,NaN
48,Colorado ...................,"256,628","266,243 278,551","294,443",1.7,1.7 1.7,1.8,"266,243","278,551",1.7,1.7,Colorado,Rocky Mountain
49,Idaho ........................,"55,427","56,956 58,231","62,247",0.4,0.4 0.4,0.4,"56,956","58,231",0.4,0.4,Idaho,Rocky Mountain
50,Montana ...................,"37,520","40,250 42,140","44,040",0.3,0.3 0.3,0.3,"40,250","42,140",0.3,0.3,Montana,Rocky Mountain
51,Utah ........................,"119,249","125,754 134,483","141,240",0.8,0.8 0.8,0.8,"125,754","134,483",0.8,0.8,Utah,Rocky Mountain
52,Wyoming ..................,"40,274","43,178 41,839","45,432",0.3,0.3 0.3,0.3,"43,178","41,839",0.3,0.3,Wyoming,Rocky Mountain
53,Far West .....................,"2,746,006","2,852,015 2,987,928","3,096,931",18.5,18.5 18.5,18.5,"2,852,015","2,987,928",18.5,18.5,Far West,NaN
54,Alaska ......................,"53,251","58,581 59,643","59,355",0.4,0.4 0.4,0.4,"58,581","59,643",0.4,0.4,Alaska,Far West
55,California ..................,"1,953,411","2,030,468 2,125,717","2,202,678",13.1,13.2 13.2,13.2,"2,030,468","2,125,717",13.2,13.2,California,Far West
56,Hawaii ......................,"67,285","69,755 72,512","75,235",0.5,0.5 0.4,0.5,"69,755","72,512",0.5,0.4,Hawaii,Far West
57,Nevada .....................,"120,579","123,365 128,896","132,024",0.8,0.8 0.8,0.8,"123,365","128,896",0.8,0.8,Nevada,Far West
58,Oregon .....................,"190,800","199,488 210,242","219,590",1.3,1.3 1.3,1.3,"199,488","210,242",1.3,1.3,Oregon,Far West
59,Washington ...............,"360,680","370,359 390,918","408,049",2.4,2.4 2.4,2.4,"370,359","390,918",2.4,2.4,Washington,Far West

In [45]:
GDP10_12.restructureDataFrame('Cleaned Area')

     year          state current dollars        GDP        GDP_area
0    2010         Alaska            2013    53251.0        Far West
1    2010        Alabama            2013   175734.0       Southeast
2    2010       Arkansas            2013   111355.0       Southeast
3    2010        Arizona            2013   247752.0       Southwest
4    2010     California            2013  1953411.0        Far West
..    ...            ...             ...        ...             ...
148  2012        Vermont            2013    28422.0     New England
149  2012     Washington            2013   390918.0        Far West
150  2012      Wisconsin            2013   272086.0     Great Lakes
151  2012  West Virginia            2013    69711.0       Southeast
152  2012        Wyoming            2013    41839.0  Rocky Mountain

[153 rows x 5 columns]

# GDP 11-13 Data

In [46]:
# create instance of yearly GDP data
GDP11_13 = YearlyGDP('GDP2011-2013.pdf', 9, 2013, 2013, '2014')

In [47]:
# testing that it was initialized with an empty DataFrame
GDP11_13.df

Empty DataFrame
Columns: []
Index: []

In [48]:
# initializeDataFrame() method reads in the PDF, assigns the first DataFrame in the 
# list as the df (only one table per page), and renames the columns. Lastly, it returns 
# the DataFrame for viewing
GDP11_13.initializeDataFrame()

,Area,2011,2012 2013,2014,2011.0,2012 2013,2014
0,United States1,"15,416,873","16,060,678 16,665,215","17,316,314",100.0,100.0 100.0,100.0
1,New England,"840,420","867,593 893,812","924,937",5.5,5.4 5.4,5.3
2,Connecticut,"233,960","239,878 246,897","253,036",1.5,1.5 1.5,1.5
3,Maine,"52,007","53,180 54,609","55,838",0.3,0.3 0.3,0.3
4,Massachusetts,"412,653","428,350 441,467","459,937",2.7,2.7 2.6,2.7
5,New Hampshire,"64,246","66,490 68,701","71,552",0.4,0.4 0.4,0.4
6,Rhode Island,"49,932","51,346 53,300","54,960",0.3,0.3 0.3,0.3
7,Vermont,"27,622","28,348 28,838","29,613",0.2,0.2 0.2,0.2
8,Mideast,"2,826,317","2,944,778 3,031,201","3,143,366",18.3,18.3 18.2,18.2
9,Delaware,"59,275","59,104 60,816","62,756",0.4,0.4 0.4,0.4
10,District of Columbia,"108,217","109,937 111,695","115,473",0.7,0.7 0.7,0.7
11,Maryland,"323,148","330,518 339,409","348,631",2.1,2.1 2.0,2.0
12,New Jersey,"498,918","523,275 537,396","549,099",3.2,3.3 3.2,3.2
13,New York,"1,234,073","1,302,527 1,341,591","1,404,518",8.0,8.1 8.1,8.1
14,Pennsylvania,"602,686","619,417 640,294","662,890",3.9,3.9 3.8,3.8
15,Great Lakes,"2,154,863","2,240,986 2,318,229","2,391,384",14.0,14.0 13.9,13.8
16,Illinois,"680,395","710,348 724,795","745,875",4.4,4.4 4.3,4.3
17,Indiana,"291,357","300,304 311,188","317,840",1.9,1.9 1.9,1.8
18,Michigan,"398,912","415,145 434,674","451,516",2.6,2.6 2.6,2.6
19,Ohio,"520,398","542,097 562,845","583,261",3.4,3.4 3.4,3.4
20,Wisconsin,"263,800","273,091 284,728","292,891",1.7,1.7 1.7,1.7
21,Plains,"1,012,181","1,057,797 1,098,306","1,131,518",6.6,6.6 6.6,6.5
22,Iowa,"150,289","159,660 166,787","170,613",1.0,1.0 1.0,1.0
23,Kansas,"136,613","140,441 142,449","147,075",0.9,0.9 0.9,0.8
24,Minnesota,"285,452","295,716 307,270","316,204",1.9,1.8 1.8,1.8
25,Missouri,"257,985","266,672 276,715","284,462",1.7,1.7 1.7,1.6
26,Nebraska,"98,997","102,823 109,364","112,159",0.6,0.6 0.7,0.6
27,North Dakota,"40,482","49,308 51,048","55,136",0.3,0.3 0.3,0.3
28,South Dakota,"42,362","43,177 44,673","45,867",0.3,0.3 0.3,0.3
29,Southeast,"3,338,113","3,454,443 3,569,920","3,695,095",21.7,21.5 21.4,21.3
30,Alabama,"182,395","186,960 194,671","199,440",1.2,1.2 1.2,1.2
31,Arkansas,"110,850","114,090 118,553","121,395",0.7,0.7 0.7,0.7
32,Florida,"736,890","766,259 800,697","839,944",4.8,4.8 4.8,4.9
33,Georgia,"424,494","438,801 456,483","476,483",2.8,2.7 2.7,2.8
34,Kentucky,"172,869","178,682 183,582","188,602",1.1,1.1 1.1,1.1
35,Louisiana,"241,845","250,689 246,660","251,397",1.6,1.6 1.5,1.5
36,Mississippi,"97,760","103,414 104,095","104,851",0.6,0.6 0.6,0.6
37,North Carolina,"433,311","445,720 467,075","483,126",2.8,2.8 2.8,2.8
38,South Carolina,"171,550","176,320 182,400","190,304",1.1,1.1 1.1,1.1
39,Tennessee,"264,052","280,169 290,125","300,604",1.7,1.7 1.7,1.7
40,Virginia,"432,206","444,617 454,984","463,613",2.8,2.8 2.7,2.7
41,West Virginia,"69,892","68,722 70,595","75,337",0.5,0.4 0.4,0.4
42,Southwest,"1,856,600","1,974,382 2,099,152","2,208,652",12.0,12.3 12.6,12.8
43,Arizona,"256,972","267,493 274,734","284,156",1.7,1.7 1.6,1.6
44,New Mexico,"86,737","88,212 90,828","92,959",0.6,0.5 0.5,0.5
45,Oklahoma,"162,118","169,346 176,398","183,501",1.1,1.1 1.1,1.1
46,Texas,"1,350,773","1,449,330 1,557,193","1,648,036",8.8,9.0 9.3,9.5
47,Rocky Mountain,"531,674","546,037 569,217","600,485",3.4,3.4 3.4,3.5
48,Colorado,"266,627","276,816 288,338","306,663",1.7,1.7 1.7,1.8
49,Idaho,"57,050","58,353 61,117","63,952",0.4,0.4 0.4,0.4
50,Montana,"40,193","41,941 43,006","44,269",0.3,0.3 0.3,0.3
51,Utah,"124,737","128,050 134,974","141,410",0.8,0.8 0.8,0.8
52,Wyoming,"43,067","40,877 41,782","44,190",0.3,0.3 0.3,0.3
53,Far West,"2,856,705","2,974,663 3,085,378","3,220,878",18.5,18.5 18.5,18.6
54,Alaska,"56,939","57,941 57,276","57,080",0.4,0.4 0.3,0.3
55,California,"2,033,990","2,125,135 2,212,991","2,311,616",13.2,13.2 13.3,13.3
56,Hawaii,"70,058","72,653 75,095","77,389",0.5,0.5 0.5,0.4
57,Nevada,"122,420","124,938 127,989","132,064",0.8,0.8 0.8,0.8
58,Oregon,"200,854","203,352 204,867","215,677",1.3,1.3 1.2,1.2
59,Washington,"372,444","390,643 407,160","427,052",2.4,2.4 2.4,2.5

In [49]:
GDP11_13.splitColumns(2, '2012', '2013')

,Area,2011,2012 2013,2014,2011.0,2012 2013,2014,2012,2013
0,United States1,"15,416,873","16,060,678 16,665,215","17,316,314",100.0,100.0 100.0,100.0,"16,060,678","16,665,215"
1,New England,"840,420","867,593 893,812","924,937",5.5,5.4 5.4,5.3,"867,593","893,812"
2,Connecticut,"233,960","239,878 246,897","253,036",1.5,1.5 1.5,1.5,"239,878","246,897"
3,Maine,"52,007","53,180 54,609","55,838",0.3,0.3 0.3,0.3,"53,180","54,609"
4,Massachusetts,"412,653","428,350 441,467","459,937",2.7,2.7 2.6,2.7,"428,350","441,467"
5,New Hampshire,"64,246","66,490 68,701","71,552",0.4,0.4 0.4,0.4,"66,490","68,701"
6,Rhode Island,"49,932","51,346 53,300","54,960",0.3,0.3 0.3,0.3,"51,346","53,300"
7,Vermont,"27,622","28,348 28,838","29,613",0.2,0.2 0.2,0.2,"28,348","28,838"
8,Mideast,"2,826,317","2,944,778 3,031,201","3,143,366",18.3,18.3 18.2,18.2,"2,944,778","3,031,201"
9,Delaware,"59,275","59,104 60,816","62,756",0.4,0.4 0.4,0.4,"59,104","60,816"
10,District of Columbia,"108,217","109,937 111,695","115,473",0.7,0.7 0.7,0.7,"109,937","111,695"
11,Maryland,"323,148","330,518 339,409","348,631",2.1,2.1 2.0,2.0,"330,518","339,409"
12,New Jersey,"498,918","523,275 537,396","549,099",3.2,3.3 3.2,3.2,"523,275","537,396"
13,New York,"1,234,073","1,302,527 1,341,591","1,404,518",8.0,8.1 8.1,8.1,"1,302,527","1,341,591"
14,Pennsylvania,"602,686","619,417 640,294","662,890",3.9,3.9 3.8,3.8,"619,417","640,294"
15,Great Lakes,"2,154,863","2,240,986 2,318,229","2,391,384",14.0,14.0 13.9,13.8,"2,240,986","2,318,229"
16,Illinois,"680,395","710,348 724,795","745,875",4.4,4.4 4.3,4.3,"710,348","724,795"
17,Indiana,"291,357","300,304 311,188","317,840",1.9,1.9 1.9,1.8,"300,304","311,188"
18,Michigan,"398,912","415,145 434,674","451,516",2.6,2.6 2.6,2.6,"415,145","434,674"
19,Ohio,"520,398","542,097 562,845","583,261",3.4,3.4 3.4,3.4,"542,097","562,845"
20,Wisconsin,"263,800","273,091 284,728","292,891",1.7,1.7 1.7,1.7,"273,091","284,728"
21,Plains,"1,012,181","1,057,797 1,098,306","1,131,518",6.6,6.6 6.6,6.5,"1,057,797","1,098,306"
22,Iowa,"150,289","159,660 166,787","170,613",1.0,1.0 1.0,1.0,"159,660","166,787"
23,Kansas,"136,613","140,441 142,449","147,075",0.9,0.9 0.9,0.8,"140,441","142,449"
24,Minnesota,"285,452","295,716 307,270","316,204",1.9,1.8 1.8,1.8,"295,716","307,270"
25,Missouri,"257,985","266,672 276,715","284,462",1.7,1.7 1.7,1.6,"266,672","276,715"
26,Nebraska,"98,997","102,823 109,364","112,159",0.6,0.6 0.7,0.6,"102,823","109,364"
27,North Dakota,"40,482","49,308 51,048","55,136",0.3,0.3 0.3,0.3,"49,308","51,048"
28,South Dakota,"42,362","43,177 44,673","45,867",0.3,0.3 0.3,0.3,"43,177","44,673"
29,Southeast,"3,338,113","3,454,443 3,569,920","3,695,095",21.7,21.5 21.4,21.3,"3,454,443","3,569,920"
30,Alabama,"182,395","186,960 194,671","199,440",1.2,1.2 1.2,1.2,"186,960","194,671"
31,Arkansas,"110,850","114,090 118,553","121,395",0.7,0.7 0.7,0.7,"114,090","118,553"
32,Florida,"736,890","766,259 800,697","839,944",4.8,4.8 4.8,4.9,"766,259","800,697"
33,Georgia,"424,494","438,801 456,483","476,483",2.8,2.7 2.7,2.8,"438,801","456,483"
34,Kentucky,"172,869","178,682 183,582","188,602",1.1,1.1 1.1,1.1,"178,682","183,582"
35,Louisiana,"241,845","250,689 246,660","251,397",1.6,1.6 1.5,1.5,"250,689","246,660"
36,Mississippi,"97,760","103,414 104,095","104,851",0.6,0.6 0.6,0.6,"103,414","104,095"
37,North Carolina,"433,311","445,720 467,075","483,126",2.8,2.8 2.8,2.8,"445,720","467,075"
38,South Carolina,"171,550","176,320 182,400","190,304",1.1,1.1 1.1,1.1,"176,320","182,400"
39,Tennessee,"264,052","280,169 290,125","300,604",1.7,1.7 1.7,1.7,"280,169","290,125"
40,Virginia,"432,206","444,617 454,984","463,613",2.8,2.8 2.7,2.7,"444,617","454,984"
41,West Virginia,"69,892","68,722 70,595","75,337",0.5,0.4 0.4,0.4,"68,722","70,595"
42,Southwest,"1,856,600","1,974,382 2,099,152","2,208,652",12.0,12.3 12.6,12.8,"1,974,382","2,099,152"
43,Arizona,"256,972","267,493 274,734","284,156",1.7,1.7 1.6,1.6,"267,493","274,734"
44,New Mexico,"86,737","88,212 90,828","92,959",0.6,0.5 0.5,0.5,"88,212","90,828"
45,Oklahoma,"162,118","169,346 176,398","183,501",1.1,1.1 1.1,1.1,"169,346","176,398"
46,Texas,"1,350,773","1,449,330 1,557,193","1,648,036",8.8,9.0 9.3,9.5,"1,449,330","1,557,193"
47,Rocky Mountain,"531,674","546,037 569,217","600,485",3.4,3.4 3.4,3.5,"546,037","569,217"
48,Colorado,"266,627","276,816 288,338","306,663",1.7,1.7 1.7,1.8,"276,816","288,338"
49,Idaho,"57,050","58,353 61,117","63,952",0.4,0.4 0.4,0.4,"58,353","61,117"
50,Montana,"40,193","41,941 43,006","44,269",0.3,0.3 0.3,0.3,"41,941","43,006"
51,Utah,"124,737","128,050 134,974","141,410",0.8,0.8 0.8,0.8,"128,050","134,974"
52,Wyoming,"43,067","40,877 41,782","44,190",0.3,0.3 0.3,0.3,"40,877","41,782"
53,Far West,"2,856,705","2,974,663 3,085,378","3,220,878",18.5,18.5 18.5,18.6,"2,974,663","3,085,378"
54,Alaska,"56,939","57,941 57,276","57,080",0.4,0.4 0.3,0.3,"57,941","57,276"
55,California,"2,033,990","2,125,135 2,212,991","2,311,616",13.2,13.2 13.3,13.3,"2,125,135","2,212,991"
56,Hawaii,"70,058","72,653 75,095","77,389",0.5,0.5 0.5,0.4,"72,653","75,095"
57,Nevada,"122,420","124,938 127,989","132,064",0.8,0.8 0.8,0.8,"124,938","127,989"
58,Oregon,"200,854","203,352 204,867","215,677",1.3,1.3 1.2,1.2,"203,352","204,867"
59,Washington,"372,444","390,643 407,160","427,052",2.4,2.4 2.4,2.5,"390,643","407,160"

In [50]:
GDP11_13.splitColumns(5, '2012 %', '2013 %')

,Area,2011,2012 2013,2014,2011.0,2012 2013,2014,2012,2013,2012 %,2013 %
0,United States1,"15,416,873","16,060,678 16,665,215","17,316,314",100.0,100.0 100.0,100.0,"16,060,678","16,665,215",100.0,100.0
1,New England,"840,420","867,593 893,812","924,937",5.5,5.4 5.4,5.3,"867,593","893,812",5.4,5.4
2,Connecticut,"233,960","239,878 246,897","253,036",1.5,1.5 1.5,1.5,"239,878","246,897",1.5,1.5
3,Maine,"52,007","53,180 54,609","55,838",0.3,0.3 0.3,0.3,"53,180","54,609",0.3,0.3
4,Massachusetts,"412,653","428,350 441,467","459,937",2.7,2.7 2.6,2.7,"428,350","441,467",2.7,2.6
5,New Hampshire,"64,246","66,490 68,701","71,552",0.4,0.4 0.4,0.4,"66,490","68,701",0.4,0.4
6,Rhode Island,"49,932","51,346 53,300","54,960",0.3,0.3 0.3,0.3,"51,346","53,300",0.3,0.3
7,Vermont,"27,622","28,348 28,838","29,613",0.2,0.2 0.2,0.2,"28,348","28,838",0.2,0.2
8,Mideast,"2,826,317","2,944,778 3,031,201","3,143,366",18.3,18.3 18.2,18.2,"2,944,778","3,031,201",18.3,18.2
9,Delaware,"59,275","59,104 60,816","62,756",0.4,0.4 0.4,0.4,"59,104","60,816",0.4,0.4
10,District of Columbia,"108,217","109,937 111,695","115,473",0.7,0.7 0.7,0.7,"109,937","111,695",0.7,0.7
11,Maryland,"323,148","330,518 339,409","348,631",2.1,2.1 2.0,2.0,"330,518","339,409",2.1,2.0
12,New Jersey,"498,918","523,275 537,396","549,099",3.2,3.3 3.2,3.2,"523,275","537,396",3.3,3.2
13,New York,"1,234,073","1,302,527 1,341,591","1,404,518",8.0,8.1 8.1,8.1,"1,302,527","1,341,591",8.1,8.1
14,Pennsylvania,"602,686","619,417 640,294","662,890",3.9,3.9 3.8,3.8,"619,417","640,294",3.9,3.8
15,Great Lakes,"2,154,863","2,240,986 2,318,229","2,391,384",14.0,14.0 13.9,13.8,"2,240,986","2,318,229",14.0,13.9
16,Illinois,"680,395","710,348 724,795","745,875",4.4,4.4 4.3,4.3,"710,348","724,795",4.4,4.3
17,Indiana,"291,357","300,304 311,188","317,840",1.9,1.9 1.9,1.8,"300,304","311,188",1.9,1.9
18,Michigan,"398,912","415,145 434,674","451,516",2.6,2.6 2.6,2.6,"415,145","434,674",2.6,2.6
19,Ohio,"520,398","542,097 562,845","583,261",3.4,3.4 3.4,3.4,"542,097","562,845",3.4,3.4
20,Wisconsin,"263,800","273,091 284,728","292,891",1.7,1.7 1.7,1.7,"273,091","284,728",1.7,1.7
21,Plains,"1,012,181","1,057,797 1,098,306","1,131,518",6.6,6.6 6.6,6.5,"1,057,797","1,098,306",6.6,6.6
22,Iowa,"150,289","159,660 166,787","170,613",1.0,1.0 1.0,1.0,"159,660","166,787",1.0,1.0
23,Kansas,"136,613","140,441 142,449","147,075",0.9,0.9 0.9,0.8,"140,441","142,449",0.9,0.9
24,Minnesota,"285,452","295,716 307,270","316,204",1.9,1.8 1.8,1.8,"295,716","307,270",1.8,1.8
25,Missouri,"257,985","266,672 276,715","284,462",1.7,1.7 1.7,1.6,"266,672","276,715",1.7,1.7
26,Nebraska,"98,997","102,823 109,364","112,159",0.6,0.6 0.7,0.6,"102,823","109,364",0.6,0.7
27,North Dakota,"40,482","49,308 51,048","55,136",0.3,0.3 0.3,0.3,"49,308","51,048",0.3,0.3
28,South Dakota,"42,362","43,177 44,673","45,867",0.3,0.3 0.3,0.3,"43,177","44,673",0.3,0.3
29,Southeast,"3,338,113","3,454,443 3,569,920","3,695,095",21.7,21.5 21.4,21.3,"3,454,443","3,569,920",21.5,21.4
30,Alabama,"182,395","186,960 194,671","199,440",1.2,1.2 1.2,1.2,"186,960","194,671",1.2,1.2
31,Arkansas,"110,850","114,090 118,553","121,395",0.7,0.7 0.7,0.7,"114,090","118,553",0.7,0.7
32,Florida,"736,890","766,259 800,697","839,944",4.8,4.8 4.8,4.9,"766,259","800,697",4.8,4.8
33,Georgia,"424,494","438,801 456,483","476,483",2.8,2.7 2.7,2.8,"438,801","456,483",2.7,2.7
34,Kentucky,"172,869","178,682 183,582","188,602",1.1,1.1 1.1,1.1,"178,682","183,582",1.1,1.1
35,Louisiana,"241,845","250,689 246,660","251,397",1.6,1.6 1.5,1.5,"250,689","246,660",1.6,1.5
36,Mississippi,"97,760","103,414 104,095","104,851",0.6,0.6 0.6,0.6,"103,414","104,095",0.6,0.6
37,North Carolina,"433,311","445,720 467,075","483,126",2.8,2.8 2.8,2.8,"445,720","467,075",2.8,2.8
38,South Carolina,"171,550","176,320 182,400","190,304",1.1,1.1 1.1,1.1,"176,320","182,400",1.1,1.1
39,Tennessee,"264,052","280,169 290,125","300,604",1.7,1.7 1.7,1.7,"280,169","290,125",1.7,1.7
40,Virginia,"432,206","444,617 454,984","463,613",2.8,2.8 2.7,2.7,"444,617","454,984",2.8,2.7
41,West Virginia,"69,892","68,722 70,595","75,337",0.5,0.4 0.4,0.4,"68,722","70,595",0.4,0.4
42,Southwest,"1,856,600","1,974,382 2,099,152","2,208,652",12.0,12.3 12.6,12.8,"1,974,382","2,099,152",12.3,12.6
43,Arizona,"256,972","267,493 274,734","284,156",1.7,1.7 1.6,1.6,"267,493","274,734",1.7,1.6
44,New Mexico,"86,737","88,212 90,828","92,959",0.6,0.5 0.5,0.5,"88,212","90,828",0.5,0.5
45,Oklahoma,"162,118","169,346 176,398","183,501",1.1,1.1 1.1,1.1,"169,346","176,398",1.1,1.1
46,Texas,"1,350,773","1,449,330 1,557,193","1,648,036",8.8,9.0 9.3,9.5,"1,449,330","1,557,193",9.0,9.3
47,Rocky Mountain,"531,674","546,037 569,217","600,485",3.4,3.4 3.4,3.5,"546,037","569,217",3.4,3.4
48,Colorado,"266,627","276,816 288,338","306,663",1.7,1.7 1.7,1.8,"276,816","288,338",1.7,1.7
49,Idaho,"57,050","58,353 61,117","63,952",0.4,0.4 0.4,0.4,"58,353","61,117",0.4,0.4
50,Montana,"40,193","41,941 43,006","44,269",0.3,0.3 0.3,0.3,"41,941","43,006",0.3,0.3
51,Utah,"124,737","128,050 134,974","141,410",0.8,0.8 0.8,0.8,"128,050","134,974",0.8,0.8
52,Wyoming,"43,067","40,877 41,782","44,190",0.3,0.3 0.3,0.3,"40,877","41,782",0.3,0.3
53,Far West,"2,856,705","2,974,663 3,085,378","3,220,878",18.5,18.5 18.5,18.6,"2,974,663","3,085,378",18.5,18.5
54,Alaska,"56,939","57,941 57,276","57,080",0.4,0.4 0.3,0.3,"57,941","57,276",0.4,0.3
55,California,"2,033,990","2,125,135 2,212,991","2,311,616",13.2,13.2 13.3,13.3,"2,125,135","2,212,991",13.2,13.3
56,Hawaii,"70,058","72,653 75,095","77,389",0.5,0.5 0.5,0.4,"72,653","75,095",0.5,0.5
57,Nevada,"122,420","124,938 127,989","132,064",0.8,0.8 0.8,0.8,"124,938","127,989",0.8,0.8
58,Oregon,"200,854","203,352 204,867","215,677",1.3,1.3 1.2,1.2,"203,352","204,867",1.3,1.2
59,Washington,"372,444","390,643 407,160","427,052",2.4,2.4 2.4,2.5,"390,643","407,160",2.4,2.4

In [51]:
GDP11_13.cleanStates('Area')

,Area,2011,2012 2013,2014,2011.0,2012 2013,2014,2012,2013,2012 %,2013 %,Cleaned Area
0,United States1,"15,416,873","16,060,678 16,665,215","17,316,314",100.0,100.0 100.0,100.0,"16,060,678","16,665,215",100.0,100.0,United States
1,New England,"840,420","867,593 893,812","924,937",5.5,5.4 5.4,5.3,"867,593","893,812",5.4,5.4,New England
2,Connecticut,"233,960","239,878 246,897","253,036",1.5,1.5 1.5,1.5,"239,878","246,897",1.5,1.5,Connecticut
3,Maine,"52,007","53,180 54,609","55,838",0.3,0.3 0.3,0.3,"53,180","54,609",0.3,0.3,Maine
4,Massachusetts,"412,653","428,350 441,467","459,937",2.7,2.7 2.6,2.7,"428,350","441,467",2.7,2.6,Massachusetts
5,New Hampshire,"64,246","66,490 68,701","71,552",0.4,0.4 0.4,0.4,"66,490","68,701",0.4,0.4,New Hampshire
6,Rhode Island,"49,932","51,346 53,300","54,960",0.3,0.3 0.3,0.3,"51,346","53,300",0.3,0.3,Rhode Island
7,Vermont,"27,622","28,348 28,838","29,613",0.2,0.2 0.2,0.2,"28,348","28,838",0.2,0.2,Vermont
8,Mideast,"2,826,317","2,944,778 3,031,201","3,143,366",18.3,18.3 18.2,18.2,"2,944,778","3,031,201",18.3,18.2,Mideast
9,Delaware,"59,275","59,104 60,816","62,756",0.4,0.4 0.4,0.4,"59,104","60,816",0.4,0.4,Delaware
10,District of Columbia,"108,217","109,937 111,695","115,473",0.7,0.7 0.7,0.7,"109,937","111,695",0.7,0.7,District of Columbia
11,Maryland,"323,148","330,518 339,409","348,631",2.1,2.1 2.0,2.0,"330,518","339,409",2.1,2.0,Maryland
12,New Jersey,"498,918","523,275 537,396","549,099",3.2,3.3 3.2,3.2,"523,275","537,396",3.3,3.2,New Jersey
13,New York,"1,234,073","1,302,527 1,341,591","1,404,518",8.0,8.1 8.1,8.1,"1,302,527","1,341,591",8.1,8.1,New York
14,Pennsylvania,"602,686","619,417 640,294","662,890",3.9,3.9 3.8,3.8,"619,417","640,294",3.9,3.8,Pennsylvania
15,Great Lakes,"2,154,863","2,240,986 2,318,229","2,391,384",14.0,14.0 13.9,13.8,"2,240,986","2,318,229",14.0,13.9,Great Lakes
16,Illinois,"680,395","710,348 724,795","745,875",4.4,4.4 4.3,4.3,"710,348","724,795",4.4,4.3,Illinois
17,Indiana,"291,357","300,304 311,188","317,840",1.9,1.9 1.9,1.8,"300,304","311,188",1.9,1.9,Indiana
18,Michigan,"398,912","415,145 434,674","451,516",2.6,2.6 2.6,2.6,"415,145","434,674",2.6,2.6,Michigan
19,Ohio,"520,398","542,097 562,845","583,261",3.4,3.4 3.4,3.4,"542,097","562,845",3.4,3.4,Ohio
20,Wisconsin,"263,800","273,091 284,728","292,891",1.7,1.7 1.7,1.7,"273,091","284,728",1.7,1.7,Wisconsin
21,Plains,"1,012,181","1,057,797 1,098,306","1,131,518",6.6,6.6 6.6,6.5,"1,057,797","1,098,306",6.6,6.6,Plains
22,Iowa,"150,289","159,660 166,787","170,613",1.0,1.0 1.0,1.0,"159,660","166,787",1.0,1.0,Iowa
23,Kansas,"136,613","140,441 142,449","147,075",0.9,0.9 0.9,0.8,"140,441","142,449",0.9,0.9,Kansas
24,Minnesota,"285,452","295,716 307,270","316,204",1.9,1.8 1.8,1.8,"295,716","307,270",1.8,1.8,Minnesota
25,Missouri,"257,985","266,672 276,715","284,462",1.7,1.7 1.7,1.6,"266,672","276,715",1.7,1.7,Missouri
26,Nebraska,"98,997","102,823 109,364","112,159",0.6,0.6 0.7,0.6,"102,823","109,364",0.6,0.7,Nebraska
27,North Dakota,"40,482","49,308 51,048","55,136",0.3,0.3 0.3,0.3,"49,308","51,048",0.3,0.3,North Dakota
28,South Dakota,"42,362","43,177 44,673","45,867",0.3,0.3 0.3,0.3,"43,177","44,673",0.3,0.3,South Dakota
29,Southeast,"3,338,113","3,454,443 3,569,920","3,695,095",21.7,21.5 21.4,21.3,"3,454,443","3,569,920",21.5,21.4,Southeast
30,Alabama,"182,395","186,960 194,671","199,440",1.2,1.2 1.2,1.2,"186,960","194,671",1.2,1.2,Alabama
31,Arkansas,"110,850","114,090 118,553","121,395",0.7,0.7 0.7,0.7,"114,090","118,553",0.7,0.7,Arkansas
32,Florida,"736,890","766,259 800,697","839,944",4.8,4.8 4.8,4.9,"766,259","800,697",4.8,4.8,Florida
33,Georgia,"424,494","438,801 456,483","476,483",2.8,2.7 2.7,2.8,"438,801","456,483",2.7,2.7,Georgia
34,Kentucky,"172,869","178,682 183,582","188,602",1.1,1.1 1.1,1.1,"178,682","183,582",1.1,1.1,Kentucky
35,Louisiana,"241,845","250,689 246,660","251,397",1.6,1.6 1.5,1.5,"250,689","246,660",1.6,1.5,Louisiana
36,Mississippi,"97,760","103,414 104,095","104,851",0.6,0.6 0.6,0.6,"103,414","104,095",0.6,0.6,Mississippi
37,North Carolina,"433,311","445,720 467,075","483,126",2.8,2.8 2.8,2.8,"445,720","467,075",2.8,2.8,North Carolina
38,South Carolina,"171,550","176,320 182,400","190,304",1.1,1.1 1.1,1.1,"176,320","182,400",1.1,1.1,South Carolina
39,Tennessee,"264,052","280,169 290,125","300,604",1.7,1.7 1.7,1.7,"280,169","290,125",1.7,1.7,Tennessee
40,Virginia,"432,206","444,617 454,984","463,613",2.8,2.8 2.7,2.7,"444,617","454,984",2.8,2.7,Virginia
41,West Virginia,"69,892","68,722 70,595","75,337",0.5,0.4 0.4,0.4,"68,722","70,595",0.4,0.4,West Virginia
42,Southwest,"1,856,600","1,974,382 2,099,152","2,208,652",12.0,12.3 12.6,12.8,"1,974,382","2,099,152",12.3,12.6,Southwest
43,Arizona,"256,972","267,493 274,734","284,156",1.7,1.7 1.6,1.6,"267,493","274,734",1.7,1.6,Arizona
44,New Mexico,"86,737","88,212 90,828","92,959",0.6,0.5 0.5,0.5,"88,212","90,828",0.5,0.5,New Mexico
45,Oklahoma,"162,118","169,346 176,398","183,501",1.1,1.1 1.1,1.1,"169,346","176,398",1.1,1.1,Oklahoma
46,Texas,"1,350,773","1,449,330 1,557,193","1,648,036",8.8,9.0 9.3,9.5,"1,449,330","1,557,193",9.0,9.3,Texas
47,Rocky Mountain,"531,674","546,037 569,217","600,485",3.4,3.4 3.4,3.5,"546,037","569,217",3.4,3.4,Rocky Mountain
48,Colorado,"266,627","276,816 288,338","306,663",1.7,1.7 1.7,1.8,"276,816","288,338",1.7,1.7,Colorado
49,Idaho,"57,050","58,353 61,117","63,952",0.4,0.4 0.4,0.4,"58,353","61,117",0.4,0.4,Idaho
50,Montana,"40,193","41,941 43,006","44,269",0.3,0.3 0.3,0.3,"41,941","43,006",0.3,0.3,Montana
51,Utah,"124,737","128,050 134,974","141,410",0.8,0.8 0.8,0.8,"128,050","134,974",0.8,0.8,Utah
52,Wyoming,"43,067","40,877 41,782","44,190",0.3,0.3 0.3,0.3,"40,877","41,782",0.3,0.3,Wyoming
53,Far West,"2,856,705","2,974,663 3,085,378","3,220,878",18.5,18.5 18.5,18.6,"2,974,663","3,085,378",18.5,18.5,Far West
54,Alaska,"56,939","57,941 57,276","57,080",0.4,0.4 0.3,0.3,"57,941","57,276",0.4,0.3,Alaska
55,California,"2,033,990","2,125,135 2,212,991","2,311,616",13.2,13.2 13.3,13.3,"2,125,135","2,212,991",13.2,13.3,California
56,Hawaii,"70,058","72,653 75,095","77,389",0.5,0.5 0.5,0.4,"72,653","75,095",0.5,0.5,Hawaii
57,Nevada,"122,420","124,938 127,989","132,064",0.8,0.8 0.8,0.8,"124,938","127,989",0.8,0.8,Nevada
58,Oregon,"200,854","203,352 204,867","215,677",1.3,1.3 1.2,1.2,"203,352","204,867",1.3,1.2,Oregon
59,Washington,"372,444","390,643 407,160","427,052",2.4,2.4 2.4,2.5,"390,643","407,160",2.4,2.4,Washington

In [52]:
GDP11_13.addGeoLocColumn('Cleaned Area')

,Area,2011,2012 2013,2014,2011.0,2012 2013,2014,2012,2013,2012 %,2013 %,Cleaned Area,Geo Loc
0,United States1,"15,416,873","16,060,678 16,665,215","17,316,314",100.0,100.0 100.0,100.0,"16,060,678","16,665,215",100.0,100.0,United States,NaN
1,New England,"840,420","867,593 893,812","924,937",5.5,5.4 5.4,5.3,"867,593","893,812",5.4,5.4,New England,NaN
2,Connecticut,"233,960","239,878 246,897","253,036",1.5,1.5 1.5,1.5,"239,878","246,897",1.5,1.5,Connecticut,New England
3,Maine,"52,007","53,180 54,609","55,838",0.3,0.3 0.3,0.3,"53,180","54,609",0.3,0.3,Maine,New England
4,Massachusetts,"412,653","428,350 441,467","459,937",2.7,2.7 2.6,2.7,"428,350","441,467",2.7,2.6,Massachusetts,New England
5,New Hampshire,"64,246","66,490 68,701","71,552",0.4,0.4 0.4,0.4,"66,490","68,701",0.4,0.4,New Hampshire,New England
6,Rhode Island,"49,932","51,346 53,300","54,960",0.3,0.3 0.3,0.3,"51,346","53,300",0.3,0.3,Rhode Island,New England
7,Vermont,"27,622","28,348 28,838","29,613",0.2,0.2 0.2,0.2,"28,348","28,838",0.2,0.2,Vermont,New England
8,Mideast,"2,826,317","2,944,778 3,031,201","3,143,366",18.3,18.3 18.2,18.2,"2,944,778","3,031,201",18.3,18.2,Mideast,NaN
9,Delaware,"59,275","59,104 60,816","62,756",0.4,0.4 0.4,0.4,"59,104","60,816",0.4,0.4,Delaware,Mideast
10,District of Columbia,"108,217","109,937 111,695","115,473",0.7,0.7 0.7,0.7,"109,937","111,695",0.7,0.7,District of Columbia,Mideast
11,Maryland,"323,148","330,518 339,409","348,631",2.1,2.1 2.0,2.0,"330,518","339,409",2.1,2.0,Maryland,Mideast
12,New Jersey,"498,918","523,275 537,396","549,099",3.2,3.3 3.2,3.2,"523,275","537,396",3.3,3.2,New Jersey,Mideast
13,New York,"1,234,073","1,302,527 1,341,591","1,404,518",8.0,8.1 8.1,8.1,"1,302,527","1,341,591",8.1,8.1,New York,Mideast
14,Pennsylvania,"602,686","619,417 640,294","662,890",3.9,3.9 3.8,3.8,"619,417","640,294",3.9,3.8,Pennsylvania,Mideast
15,Great Lakes,"2,154,863","2,240,986 2,318,229","2,391,384",14.0,14.0 13.9,13.8,"2,240,986","2,318,229",14.0,13.9,Great Lakes,NaN
16,Illinois,"680,395","710,348 724,795","745,875",4.4,4.4 4.3,4.3,"710,348","724,795",4.4,4.3,Illinois,Great Lakes
17,Indiana,"291,357","300,304 311,188","317,840",1.9,1.9 1.9,1.8,"300,304","311,188",1.9,1.9,Indiana,Great Lakes
18,Michigan,"398,912","415,145 434,674","451,516",2.6,2.6 2.6,2.6,"415,145","434,674",2.6,2.6,Michigan,Great Lakes
19,Ohio,"520,398","542,097 562,845","583,261",3.4,3.4 3.4,3.4,"542,097","562,845",3.4,3.4,Ohio,Great Lakes
20,Wisconsin,"263,800","273,091 284,728","292,891",1.7,1.7 1.7,1.7,"273,091","284,728",1.7,1.7,Wisconsin,Great Lakes
21,Plains,"1,012,181","1,057,797 1,098,306","1,131,518",6.6,6.6 6.6,6.5,"1,057,797","1,098,306",6.6,6.6,Plains,NaN
22,Iowa,"150,289","159,660 166,787","170,613",1.0,1.0 1.0,1.0,"159,660","166,787",1.0,1.0,Iowa,Plains
23,Kansas,"136,613","140,441 142,449","147,075",0.9,0.9 0.9,0.8,"140,441","142,449",0.9,0.9,Kansas,Plains
24,Minnesota,"285,452","295,716 307,270","316,204",1.9,1.8 1.8,1.8,"295,716","307,270",1.8,1.8,Minnesota,Plains
25,Missouri,"257,985","266,672 276,715","284,462",1.7,1.7 1.7,1.6,"266,672","276,715",1.7,1.7,Missouri,Plains
26,Nebraska,"98,997","102,823 109,364","112,159",0.6,0.6 0.7,0.6,"102,823","109,364",0.6,0.7,Nebraska,Plains
27,North Dakota,"40,482","49,308 51,048","55,136",0.3,0.3 0.3,0.3,"49,308","51,048",0.3,0.3,North Dakota,Plains
28,South Dakota,"42,362","43,177 44,673","45,867",0.3,0.3 0.3,0.3,"43,177","44,673",0.3,0.3,South Dakota,Plains
29,Southeast,"3,338,113","3,454,443 3,569,920","3,695,095",21.7,21.5 21.4,21.3,"3,454,443","3,569,920",21.5,21.4,Southeast,NaN
30,Alabama,"182,395","186,960 194,671","199,440",1.2,1.2 1.2,1.2,"186,960","194,671",1.2,1.2,Alabama,Southeast
31,Arkansas,"110,850","114,090 118,553","121,395",0.7,0.7 0.7,0.7,"114,090","118,553",0.7,0.7,Arkansas,Southeast
32,Florida,"736,890","766,259 800,697","839,944",4.8,4.8 4.8,4.9,"766,259","800,697",4.8,4.8,Florida,Southeast
33,Georgia,"424,494","438,801 456,483","476,483",2.8,2.7 2.7,2.8,"438,801","456,483",2.7,2.7,Georgia,Southeast
34,Kentucky,"172,869","178,682 183,582","188,602",1.1,1.1 1.1,1.1,"178,682","183,582",1.1,1.1,Kentucky,Southeast
35,Louisiana,"241,845","250,689 246,660","251,397",1.6,1.6 1.5,1.5,"250,689","246,660",1.6,1.5,Louisiana,Southeast
36,Mississippi,"97,760","103,414 104,095","104,851",0.6,0.6 0.6,0.6,"103,414","104,095",0.6,0.6,Mississippi,Southeast
37,North Carolina,"433,311","445,720 467,075","483,126",2.8,2.8 2.8,2.8,"445,720","467,075",2.8,2.8,North Carolina,Southeast
38,South Carolina,"171,550","176,320 182,400","190,304",1.1,1.1 1.1,1.1,"176,320","182,400",1.1,1.1,South Carolina,Southeast
39,Tennessee,"264,052","280,169 290,125","300,604",1.7,1.7 1.7,1.7,"280,169","290,125",1.7,1.7,Tennessee,Southeast
40,Virginia,"432,206","444,617 454,984","463,613",2.8,2.8 2.7,2.7,"444,617","454,984",2.8,2.7,Virginia,Southeast
41,West Virginia,"69,892","68,722 70,595","75,337",0.5,0.4 0.4,0.4,"68,722","70,595",0.4,0.4,West Virginia,Southeast
42,Southwest,"1,856,600","1,974,382 2,099,152","2,208,652",12.0,12.3 12.6,12.8,"1,974,382","2,099,152",12.3,12.6,Southwest,NaN
43,Arizona,"256,972","267,493 274,734","284,156",1.7,1.7 1.6,1.6,"267,493","274,734",1.7,1.6,Arizona,Southwest
44,New Mexico,"86,737","88,212 90,828","92,959",0.6,0.5 0.5,0.5,"88,212","90,828",0.5,0.5,New Mexico,Southwest
45,Oklahoma,"162,118","169,346 176,398","183,501",1.1,1.1 1.1,1.1,"169,346","176,398",1.1,1.1,Oklahoma,Southwest
46,Texas,"1,350,773","1,449,330 1,557,193","1,648,036",8.8,9.0 9.3,9.5,"1,449,330","1,557,193",9.0,9.3,Texas,Southwest
47,Rocky Mountain,"531,674","546,037 569,217","600,485",3.4,3.4 3.4,3.5,"546,037","569,217",3.4,3.4,Rocky Mountain,NaN
48,Colorado,"266,627","276,816 288,338","306,663",1.7,1.7 1.7,1.8,"276,816","288,338",1.7,1.7,Colorado,Rocky Mountain
49,Idaho,"57,050","58,353 61,117","63,952",0.4,0.4 0.4,0.4,"58,353","61,117",0.4,0.4,Idaho,Rocky Mountain
50,Montana,"40,193","41,941 43,006","44,269",0.3,0.3 0.3,0.3,"41,941","43,006",0.3,0.3,Montana,Rocky Mountain
51,Utah,"124,737","128,050 134,974","141,410",0.8,0.8 0.8,0.8,"128,050","134,974",0.8,0.8,Utah,Rocky Mountain
52,Wyoming,"43,067","40,877 41,782","44,190",0.3,0.3 0.3,0.3,"40,877","41,782",0.3,0.3,Wyoming,Rocky Mountain
53,Far West,"2,856,705","2,974,663 3,085,378","3,220,878",18.5,18.5 18.5,18.6,"2,974,663","3,085,378",18.5,18.5,Far West,NaN
54,Alaska,"56,939","57,941 57,276","57,080",0.4,0.4 0.3,0.3,"57,941","57,276",0.4,0.3,Alaska,Far West
55,California,"2,033,990","2,125,135 2,212,991","2,311,616",13.2,13.2 13.3,13.3,"2,125,135","2,212,991",13.2,13.3,California,Far West
56,Hawaii,"70,058","72,653 75,095","77,389",0.5,0.5 0.5,0.4,"72,653","75,095",0.5,0.5,Hawaii,Far West
57,Nevada,"122,420","124,938 127,989","132,064",0.8,0.8 0.8,0.8,"124,938","127,989",0.8,0.8,Nevada,Far West
58,Oregon,"200,854","203,352 204,867","215,677",1.3,1.3 1.2,1.2,"203,352","204,867",1.3,1.2,Oregon,Far West
59,Washington,"372,444","390,643 407,160","427,052",2.4,2.4 2.4,2.5,"390,643","407,160",2.4,2.4,Washington,Far West

In [53]:
GDP11_13.restructureDataFrame('Cleaned Area')

    year                 state current dollars        GDP        GDP_area
0   2013                Alaska            2014    57276.0        Far West
1   2013               Alabama            2014   194671.0       Southeast
2   2013              Arkansas            2014   118553.0       Southeast
3   2013               Arizona            2014   274734.0       Southwest
4   2013            California            2014  2212991.0        Far West
5   2013              Colorado            2014   288338.0  Rocky Mountain
6   2013           Connecticut            2014   246897.0     New England
7   2013  District of Columbia            2014   111695.0         Mideast
8   2013              Delaware            2014    60816.0         Mideast
9   2013               Florida            2014   800697.0       Southeast
10  2013               Georgia            2014   456483.0       Southeast
11  2013                Hawaii            2014    75095.0        Far West
12  2013                  Iowa            2014   166787.0          Plains
13  2013                 Idaho            2014    61117.0  Rocky Mountain
14  2013              Illinois            2014   724795.0     Great Lakes
15  2013               Indiana            2014   311188.0     Great Lakes
16  2013                Kansas            2014   142449.0          Plains
17  2013              Kentucky            2014   183582.0       Southeast
18  2013             Louisiana            2014   246660.0       Southeast
19  2013         Massachusetts            2014   441467.0     New England
20  2013              Maryland            2014   339409.0         Mideast
21  2013                 Maine            2014    54609.0     New England
22  2013              Michigan            2014   434674.0     Great Lakes
23  2013             Minnesota            2014   307270.0          Plains
24  2013              Missouri            2014   276715.0          Plains
25  2013           Mississippi            2014   104095.0       Southeast
26  2013               Montana            2014    43006.0  Rocky Mountain
27  2013        North Carolina            2014   467075.0       Southeast
28  2013          North Dakota            2014    51048.0          Plains
29  2013              Nebraska            2014   109364.0          Plains
30  2013         New Hampshire            2014    68701.0     New England
31  2013            New Jersey            2014   537396.0         Mideast
32  2013            New Mexico            2014    90828.0       Southwest
33  2013                Nevada            2014   127989.0        Far West
34  2013              New York            2014  1341591.0         Mideast
35  2013                  Ohio            2014   562845.0     Great Lakes
36  2013              Oklahoma            2014   176398.0       Southwest
37  2013                Oregon            2014   204867.0        Far West
38  2013          Pennsylvania            2014   640294.0         Mideast
39  2013          Rhode Island            2014    53300.0     New England
40  2013        South Carolina            2014   182400.0       Southeast
41  2013          South Dakota            2014    44673.0          Plains
42  2013             Tennessee            2014   290125.0       Southeast
43  2013                 Texas            2014  1557193.0       Southwest
44  2013                  Utah            2014   134974.0  Rocky Mountain
45  2013              Virginia            2014   454984.0       Southeast
46  2013               Vermont            2014    28838.0     New England
47  2013            Washington            2014   407160.0        Far West
48  2013             Wisconsin            2014   284728.0     Great Lakes
49  2013         West Virginia            2014    70595.0       Southeast
50  2013               Wyoming            2014    41782.0  Rocky Mountain

# 2014 Quarterly Data

In [54]:
GDP2014 = tabula.read_pdf('GDP2014_quarterly.pdf', pages = 7, stream = True)
GDP2014

[                       Unnamed: 0  Unnamed: 1  Unnamed: 2  \
 0                             NaN         NaN         NaN
 1                             NaN        2014         NaN
 2                             NaN         NaN           I
 3   United States1 ..............  17,316,314  16,941,430
 4     New England ...............     924,937     911,347
 ..                            ...         ...         ...
 58  California ..................   2,311,616   2,254,347
 59   Hawaii .....................      77,389      76,067
 60      Nevada ..................     132,064     130,191
 61   Oregon .....................     215,677     208,459
 62     Washington ...............     427,052     418,329

                     Millions of dollars  Unnamed: 3  Unnamed: 4 Unnamed: 5  \
 0   Seasonally adjusted at annual rates         NaN         NaN        NaN
 1                                  2014         NaN      2014.0        NaN
 2                             II III IV         NaN         NaN          I
 3      17,225,767 17,497,215 17,600,843         NaN       100.0        NaN
 4               919,972 929,812 938,616         NaN         5.3        NaN
 ..                                  ...         ...         ...        ...
 58        2,292,655 2,341,652 2,357,810         NaN        13.3        NaN
 59                 77,104 77,758 78,629         NaN         0.4        NaN
 60              131,057 133,104 133,905         NaN         0.8        NaN
 61              213,520 218,898 221,829         NaN         1.2        NaN
 62              425,517 429,364 434,997         NaN         2.5        NaN

                     Percent of the U.S. Unnamed: 6  Unnamed: 7
 0   Seasonally adjusted at annual rates        NaN         NaN
 1                                  2014        NaN         NaN
 2                                II III         IV         NaN
 3                     100.0 100.0 100.0        NaN       100.0
 4                           5.4 5.3 5.3        NaN         5.3
 ..                                  ...        ...         ...
 58                       13.3 13.3 13.4        NaN        13.4
 59                          0.4 0.4 0.4        NaN         0.4
 60                          0.8 0.8 0.8        NaN         0.8
 61                          1.2 1.2 1.3        NaN         1.3
 62                          2.5 2.5 2.5        NaN         2.5

 [63 rows x 10 columns]]

In [55]:
GDP2014 = pd.concat(GDP2014, ignore_index = True)

In [56]:
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Millions of dollars,Unnamed: 3,Unnamed: 4,Unnamed: 5,Percent of the U.S.,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,Seasonally adjusted at annual rates,NaN,NaN,NaN,Seasonally adjusted at annual rates,NaN,NaN
1,NaN,2014,NaN,2014,NaN,2014.0,NaN,2014,NaN,NaN
2,NaN,NaN,I,II III IV,NaN,NaN,I,II III,IV,NaN
3,United States1 ..............,"17,316,314","16,941,430","17,225,767 17,497,215 17,600,843",NaN,100.0,NaN,100.0 100.0 100.0,NaN,100.0
4,New England ...............,"924,937","911,347","919,972 929,812 938,616",NaN,5.3,NaN,5.4 5.3 5.3,NaN,5.3
...,...,...,...,...,...,...,...,...,...,...
58,California ..................,"2,311,616","2,254,347","2,292,655 2,341,652 2,357,810",NaN,13.3,NaN,13.3 13.3 13.4,NaN,13.4
59,Hawaii .....................,"77,389","76,067","77,104 77,758 78,629",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
60,Nevada ..................,"132,064","130,191","131,057 133,104 133,905",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8
61,Oregon .....................,"215,677","208,459","213,520 218,898 221,829",NaN,1.2,NaN,1.2 1.2 1.3,NaN,1.3
62,Washington ...............,"427,052","418,329","425,517 429,364 434,997",NaN,2.5,NaN,2.5 2.5 2.5,NaN,2.5

In [57]:
GDP2014 = GDP2014.drop(GDP2014.index[0]).reset_index(drop = True)
GDP2014 = GDP2014.drop(GDP2014.index[0]).reset_index(drop = True)
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Millions of dollars,Unnamed: 3,Unnamed: 4,Unnamed: 5,Percent of the U.S.,Unnamed: 6,Unnamed: 7
0,NaN,NaN,I,II III IV,NaN,NaN,I,II III,IV,NaN
1,United States1 ..............,"17,316,314","16,941,430","17,225,767 17,497,215 17,600,843",NaN,100.0,NaN,100.0 100.0 100.0,NaN,100.0
2,New England ...............,"924,937","911,347","919,972 929,812 938,616",NaN,5.3,NaN,5.4 5.3 5.3,NaN,5.3
3,Connecticut ...............,"253,036","249,336","252,980 253,856 255,972",NaN,1.5,NaN,1.5 1.5 1.5,NaN,1.5
4,Maine .....................,"55,838","54,800","55,588 56,240 56,726",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
...,...,...,...,...,...,...,...,...,...,...
56,California ..................,"2,311,616","2,254,347","2,292,655 2,341,652 2,357,810",NaN,13.3,NaN,13.3 13.3 13.4,NaN,13.4
57,Hawaii .....................,"77,389","76,067","77,104 77,758 78,629",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
58,Nevada ..................,"132,064","130,191","131,057 133,104 133,905",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8
59,Oregon .....................,"215,677","208,459","213,520 218,898 221,829",NaN,1.2,NaN,1.2 1.2 1.3,NaN,1.3
60,Washington ...............,"427,052","418,329","425,517 429,364 434,997",NaN,2.5,NaN,2.5 2.5 2.5,NaN,2.5

In [58]:
GDP2014 = GDP2014.drop(GDP2014.index[0]).reset_index(drop = True)
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Millions of dollars,Unnamed: 3,Unnamed: 4,Unnamed: 5,Percent of the U.S.,Unnamed: 6,Unnamed: 7
0,United States1 ..............,"17,316,314","16,941,430","17,225,767 17,497,215 17,600,843",NaN,100.0,NaN,100.0 100.0 100.0,NaN,100.0
1,New England ...............,"924,937","911,347","919,972 929,812 938,616",NaN,5.3,NaN,5.4 5.3 5.3,NaN,5.3
2,Connecticut ...............,"253,036","249,336","252,980 253,856 255,972",NaN,1.5,NaN,1.5 1.5 1.5,NaN,1.5
3,Maine .....................,"55,838","54,800","55,588 56,240 56,726",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
4,Massachusetts .........,"459,937","454,249","455,425 462,636 467,436",NaN,2.7,NaN,2.7 2.6 2.6,NaN,2.7
5,New Hampshire .........,"71,552","69,842","71,895 71,929 72,542",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
6,Rhode Island ............,"54,960","54,103","54,795 55,245 55,697",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
7,Vermont ..................,"29,613","29,016","29,289 29,905 30,244",NaN,0.2,NaN,0.2 0.2 0.2,NaN,0.2
8,Mideast .....................,"3,143,366","3,087,518","3,124,845 3,172,793 3,188,307",NaN,18.2,NaN,18.2 18.1 18.1,NaN,18.1
9,Delaware ..................,"62,756","61,094","62,375 63,646 63,908",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
10,District of Columbia ...,"115,473","115,482","114,998 115,136 116,273",NaN,0.7,NaN,0.7 0.7 0.7,NaN,0.7
11,Maryland ..................,"348,631","341,031","347,513 351,349 354,629",NaN,2.0,NaN,2.0 2.0 2.0,NaN,2.0
12,New Jersey ...............,"549,099","539,958","546,906 552,068 557,465",NaN,3.2,NaN,3.2 3.2 3.2,NaN,3.2
13,New York ..................,"1,404,518","1,378,213","1,393,589 1,422,242 1,424,029",NaN,8.1,NaN,8.1 8.1 8.1,NaN,8.1
14,Pennsylvania ............,"662,890","651,740","659,464 668,352 672,003",NaN,3.8,NaN,3.8 3.8 3.8,NaN,3.8
15,Great Lakes ...............,"2,391,384","2,341,059","2,379,809 2,413,833 2,430,835",NaN,13.8,NaN,13.8 13.8 13.8,NaN,13.8
16,Illinois .....................,"745,875","731,827","742,805 751,601 757,269",NaN,4.3,NaN,4.3 4.3 4.3,NaN,4.3
17,Indiana .....................,"317,840","311,837","315,952 320,434 323,139",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8
18,Michigan ..................,"451,516","441,951","450,755 454,491 458,866",NaN,2.6,NaN,2.6 2.6 2.6,NaN,2.6
19,Ohio ........................,"583,261","569,274","578,218 592,046 593,508",NaN,3.4,NaN,3.4 3.4 3.4,NaN,3.4
20,Wisconsin ...............,"292,891","286,169","292,079 295,262 298,053",NaN,1.7,NaN,1.7 1.7 1.7,NaN,1.7
21,Plains ........................,"1,131,518","1,100,382","1,128,959 1,144,482 1,152,247",NaN,6.5,NaN,6.5 6.6 6.5,NaN,6.5
22,Iowa ........................,"170,613","163,845","171,071 173,281 174,256",NaN,1.0,NaN,1.0 1.0 1.0,NaN,1.0
23,Kansas .....................,"147,075","143,510","146,670 148,403 149,718",NaN,0.8,NaN,0.8 0.9 0.8,NaN,0.9
24,Minnesota ...............,"316,204","309,764","312,677 320,114 322,264",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8
25,Missouri ..................,"284,462","277,624","283,834 286,961 289,431",NaN,1.6,NaN,1.6 1.6 1.6,NaN,1.6
26,Nebraska ..................,"112,159","108,006","113,017 113,402 114,213",NaN,0.6,NaN,0.6 0.7 0.6,NaN,0.6
27,North Dakota ............,"55,136","53,026","55,649 56,012 55,858",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
28,South Dakota ............,"45,867","44,607","46,042 46,310 46,508",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
29,Southeast ..................,"3,695,095","3,611,976","3,678,954 3,728,938 3,760,513",NaN,21.3,NaN,21.3 21.4 21.3,NaN,21.4
30,Alabama ..................,"199,440","195,091","197,789 201,541 203,338",NaN,1.2,NaN,1.2 1.1 1.2,NaN,1.2
31,Arkansas ..................,"121,395","119,172","121,242 122,108 123,060",NaN,0.7,NaN,0.7 0.7 0.7,NaN,0.7
32,Florida .....................,"839,944","820,194","835,308 846,535 857,738",NaN,4.9,NaN,4.8 4.8 4.8,NaN,4.9
33,Georgia ..................,"476,483","464,398","472,890 482,335 486,308",NaN,2.8,NaN,2.7 2.7 2.8,NaN,2.8
34,Kentucky ..................,"188,602","184,763","188,758 189,951 190,936",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.1
35,Louisiana ..................,"251,397","244,942","250,163 255,368 255,113",NaN,1.5,NaN,1.4 1.5 1.5,NaN,1.4
36,Mississippi ...............,"104,851","103,016","105,377 105,184 105,829",NaN,0.6,NaN,0.6 0.6 0.6,NaN,0.6
37,North Carolina .........,"483,126","474,030","478,625 488,209 491,637",NaN,2.8,NaN,2.8 2.8 2.8,NaN,2.8
38,South Carolina .........,"190,304","184,447","190,658 191,892 194,220",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.1
39,Tennessee ...............,"300,604","293,594","299,506 303,206 306,109",NaN,1.7,NaN,1.7 1.7 1.7,NaN,1.7
40,Virginia .....................,"463,613","455,777","463,004 465,780 469,891",NaN,2.7,NaN,2.7 2.7 2.7,NaN,2.7
41,West Virginia ............,"75,337","72,551","75,635 76,828 76,333",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
42,Southwest ..................,"2,208,652","2,158,213","2,197,472 2,241,598 2,237,326",NaN,12.8,NaN,12.7 12.8 12.8,NaN,12.7
43,Arizona .....................,"284,156","279,983","281,409 286,590 288,644",NaN,1.6,NaN,1.7 1.6 1.6,NaN,1.6
44,New Mexico ...............,"92,959","91,326","92,715 93,817 93,977",NaN,0.5,NaN,0.5 0.5 0.5,NaN,0.5
45,Oklahoma ...............,"183,501","179,582","182,935 186,687 184,799",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.0
46,Texas .....................,"1,648,036","1,607,322","1,640,414 1,674,503 1,669,905",NaN,9.5,NaN,9.5 9.5 9.6,NaN,9.5
47,Rocky Mountain .........,"600,485","586,172","597,652 607,987 610,129",NaN,3.5,NaN,3.5 3.5 3.5,NaN,3.5
48,Colorado ..................,"306,663","297,603","304,561 311,506 312,981",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8
49,Idaho .....................,"63,952","62,850","63,818 64,264 64,878",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
50,Montana ..................,"44,269","43,560","44,273 44,569 44,674",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
51,Utah ........................,"141,410","138,911","140,214 142,686 143,830",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8
52,Wyoming ..................,"44,190","43,247","44,786 44,962 43,765",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.2
53,Far West .....................,"3,220,878","3,144,765","3,198,105 3,257,772 3,282,871",NaN,18.6,NaN,18.6 18.6 18.6,NaN,18.7
54,Alaska .....................,"57,080","57,371","58,253 56,996 55,700",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3
55,California ..................,"2,311,616","2,254,347","2,292,655 2,341,652 2,357,810",NaN,13.3,NaN,13.3 13.3 13.4,NaN,13.4
56,Hawaii .....................,"77,389","76,067","77,104 77,758 78,629",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4
57,Nevada ..................,"132,064","130,191","131,057 133,104 133,905",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8
58,Oregon .....................,"215,677","208,459","213,520 218,898 221,829",NaN,1.2,NaN,1.2 1.2 1.3,NaN,1.3
59,Washington ...............,"427,052","418,329","425,517 429,364 434,997",NaN,2.5,NaN,2.5 2.5 2.5,NaN,2.5

In [59]:
for i in GDP2014['Millions of dollars'].index:
    splitList = GDP2014.loc[i, 'Millions of dollars'].split(" ")
    GDP2014.loc[i, '2014 Q2'] = splitList[0]
    GDP2014.loc[i, '2014 Q3'] = splitList[1]
    GDP2014.loc[i, '2014 Q4'] = splitList[2]
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Millions of dollars,Unnamed: 3,Unnamed: 4,Unnamed: 5,Percent of the U.S.,Unnamed: 6,Unnamed: 7,2014 Q2,2014 Q3,2014 Q4
0,United States1 ..............,"17,316,314","16,941,430","17,225,767 17,497,215 17,600,843",NaN,100.0,NaN,100.0 100.0 100.0,NaN,100.0,"17,225,767","17,497,215","17,600,843"
1,New England ...............,"924,937","911,347","919,972 929,812 938,616",NaN,5.3,NaN,5.4 5.3 5.3,NaN,5.3,"919,972","929,812","938,616"
2,Connecticut ...............,"253,036","249,336","252,980 253,856 255,972",NaN,1.5,NaN,1.5 1.5 1.5,NaN,1.5,"252,980","253,856","255,972"
3,Maine .....................,"55,838","54,800","55,588 56,240 56,726",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"55,588","56,240","56,726"
4,Massachusetts .........,"459,937","454,249","455,425 462,636 467,436",NaN,2.7,NaN,2.7 2.6 2.6,NaN,2.7,"455,425","462,636","467,436"
5,New Hampshire .........,"71,552","69,842","71,895 71,929 72,542",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"71,895","71,929","72,542"
6,Rhode Island ............,"54,960","54,103","54,795 55,245 55,697",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"54,795","55,245","55,697"
7,Vermont ..................,"29,613","29,016","29,289 29,905 30,244",NaN,0.2,NaN,0.2 0.2 0.2,NaN,0.2,"29,289","29,905","30,244"
8,Mideast .....................,"3,143,366","3,087,518","3,124,845 3,172,793 3,188,307",NaN,18.2,NaN,18.2 18.1 18.1,NaN,18.1,"3,124,845","3,172,793","3,188,307"
9,Delaware ..................,"62,756","61,094","62,375 63,646 63,908",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"62,375","63,646","63,908"
10,District of Columbia ...,"115,473","115,482","114,998 115,136 116,273",NaN,0.7,NaN,0.7 0.7 0.7,NaN,0.7,"114,998","115,136","116,273"
11,Maryland ..................,"348,631","341,031","347,513 351,349 354,629",NaN,2.0,NaN,2.0 2.0 2.0,NaN,2.0,"347,513","351,349","354,629"
12,New Jersey ...............,"549,099","539,958","546,906 552,068 557,465",NaN,3.2,NaN,3.2 3.2 3.2,NaN,3.2,"546,906","552,068","557,465"
13,New York ..................,"1,404,518","1,378,213","1,393,589 1,422,242 1,424,029",NaN,8.1,NaN,8.1 8.1 8.1,NaN,8.1,"1,393,589","1,422,242","1,424,029"
14,Pennsylvania ............,"662,890","651,740","659,464 668,352 672,003",NaN,3.8,NaN,3.8 3.8 3.8,NaN,3.8,"659,464","668,352","672,003"
15,Great Lakes ...............,"2,391,384","2,341,059","2,379,809 2,413,833 2,430,835",NaN,13.8,NaN,13.8 13.8 13.8,NaN,13.8,"2,379,809","2,413,833","2,430,835"
16,Illinois .....................,"745,875","731,827","742,805 751,601 757,269",NaN,4.3,NaN,4.3 4.3 4.3,NaN,4.3,"742,805","751,601","757,269"
17,Indiana .....................,"317,840","311,837","315,952 320,434 323,139",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8,"315,952","320,434","323,139"
18,Michigan ..................,"451,516","441,951","450,755 454,491 458,866",NaN,2.6,NaN,2.6 2.6 2.6,NaN,2.6,"450,755","454,491","458,866"
19,Ohio ........................,"583,261","569,274","578,218 592,046 593,508",NaN,3.4,NaN,3.4 3.4 3.4,NaN,3.4,"578,218","592,046","593,508"
20,Wisconsin ...............,"292,891","286,169","292,079 295,262 298,053",NaN,1.7,NaN,1.7 1.7 1.7,NaN,1.7,"292,079","295,262","298,053"
21,Plains ........................,"1,131,518","1,100,382","1,128,959 1,144,482 1,152,247",NaN,6.5,NaN,6.5 6.6 6.5,NaN,6.5,"1,128,959","1,144,482","1,152,247"
22,Iowa ........................,"170,613","163,845","171,071 173,281 174,256",NaN,1.0,NaN,1.0 1.0 1.0,NaN,1.0,"171,071","173,281","174,256"
23,Kansas .....................,"147,075","143,510","146,670 148,403 149,718",NaN,0.8,NaN,0.8 0.9 0.8,NaN,0.9,"146,670","148,403","149,718"
24,Minnesota ...............,"316,204","309,764","312,677 320,114 322,264",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8,"312,677","320,114","322,264"
25,Missouri ..................,"284,462","277,624","283,834 286,961 289,431",NaN,1.6,NaN,1.6 1.6 1.6,NaN,1.6,"283,834","286,961","289,431"
26,Nebraska ..................,"112,159","108,006","113,017 113,402 114,213",NaN,0.6,NaN,0.6 0.7 0.6,NaN,0.6,"113,017","113,402","114,213"
27,North Dakota ............,"55,136","53,026","55,649 56,012 55,858",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"55,649","56,012","55,858"
28,South Dakota ............,"45,867","44,607","46,042 46,310 46,508",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"46,042","46,310","46,508"
29,Southeast ..................,"3,695,095","3,611,976","3,678,954 3,728,938 3,760,513",NaN,21.3,NaN,21.3 21.4 21.3,NaN,21.4,"3,678,954","3,728,938","3,760,513"
30,Alabama ..................,"199,440","195,091","197,789 201,541 203,338",NaN,1.2,NaN,1.2 1.1 1.2,NaN,1.2,"197,789","201,541","203,338"
31,Arkansas ..................,"121,395","119,172","121,242 122,108 123,060",NaN,0.7,NaN,0.7 0.7 0.7,NaN,0.7,"121,242","122,108","123,060"
32,Florida .....................,"839,944","820,194","835,308 846,535 857,738",NaN,4.9,NaN,4.8 4.8 4.8,NaN,4.9,"835,308","846,535","857,738"
33,Georgia ..................,"476,483","464,398","472,890 482,335 486,308",NaN,2.8,NaN,2.7 2.7 2.8,NaN,2.8,"472,890","482,335","486,308"
34,Kentucky ..................,"188,602","184,763","188,758 189,951 190,936",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.1,"188,758","189,951","190,936"
35,Louisiana ..................,"251,397","244,942","250,163 255,368 255,113",NaN,1.5,NaN,1.4 1.5 1.5,NaN,1.4,"250,163","255,368","255,113"
36,Mississippi ...............,"104,851","103,016","105,377 105,184 105,829",NaN,0.6,NaN,0.6 0.6 0.6,NaN,0.6,"105,377","105,184","105,829"
37,North Carolina .........,"483,126","474,030","478,625 488,209 491,637",NaN,2.8,NaN,2.8 2.8 2.8,NaN,2.8,"478,625","488,209","491,637"
38,South Carolina .........,"190,304","184,447","190,658 191,892 194,220",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.1,"190,658","191,892","194,220"
39,Tennessee ...............,"300,604","293,594","299,506 303,206 306,109",NaN,1.7,NaN,1.7 1.7 1.7,NaN,1.7,"299,506","303,206","306,109"
40,Virginia .....................,"463,613","455,777","463,004 465,780 469,891",NaN,2.7,NaN,2.7 2.7 2.7,NaN,2.7,"463,004","465,780","469,891"
41,West Virginia ............,"75,337","72,551","75,635 76,828 76,333",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"75,635","76,828","76,333"
42,Southwest ..................,"2,208,652","2,158,213","2,197,472 2,241,598 2,237,326",NaN,12.8,NaN,12.7 12.8 12.8,NaN,12.7,"2,197,472","2,241,598","2,237,326"
43,Arizona .....................,"284,156","279,983","281,409 286,590 288,644",NaN,1.6,NaN,1.7 1.6 1.6,NaN,1.6,"281,409","286,590","288,644"
44,New Mexico ...............,"92,959","91,326","92,715 93,817 93,977",NaN,0.5,NaN,0.5 0.5 0.5,NaN,0.5,"92,715","93,817","93,977"
45,Oklahoma ...............,"183,501","179,582","182,935 186,687 184,799",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.0,"182,935","186,687","184,799"
46,Texas .....................,"1,648,036","1,607,322","1,640,414 1,674,503 1,669,905",NaN,9.5,NaN,9.5 9.5 9.6,NaN,9.5,"1,640,414","1,674,503","1,669,905"
47,Rocky Mountain .........,"600,485","586,172","597,652 607,987 610,129",NaN,3.5,NaN,3.5 3.5 3.5,NaN,3.5,"597,652","607,987","610,129"
48,Colorado ..................,"306,663","297,603","304,561 311,506 312,981",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8,"304,561","311,506","312,981"
49,Idaho .....................,"63,952","62,850","63,818 64,264 64,878",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"63,818","64,264","64,878"
50,Montana ..................,"44,269","43,560","44,273 44,569 44,674",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"44,273","44,569","44,674"
51,Utah ........................,"141,410","138,911","140,214 142,686 143,830",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8,"140,214","142,686","143,830"
52,Wyoming ..................,"44,190","43,247","44,786 44,962 43,765",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.2,"44,786","44,962","43,765"
53,Far West .....................,"3,220,878","3,144,765","3,198,105 3,257,772 3,282,871",NaN,18.6,NaN,18.6 18.6 18.6,NaN,18.7,"3,198,105","3,257,772","3,282,871"
54,Alaska .....................,"57,080","57,371","58,253 56,996 55,700",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"58,253","56,996","55,700"
55,California ..................,"2,311,616","2,254,347","2,292,655 2,341,652 2,357,810",NaN,13.3,NaN,13.3 13.3 13.4,NaN,13.4,"2,292,655","2,341,652","2,357,810"
56,Hawaii .....................,"77,389","76,067","77,104 77,758 78,629",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"77,104","77,758","78,629"
57,Nevada ..................,"132,064","130,191","131,057 133,104 133,905",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8,"131,057","133,104","133,905"
58,Oregon .....................,"215,677","208,459","213,520 218,898 221,829",NaN,1.2,NaN,1.2 1.2 1.3,NaN,1.3,"213,520","218,898","221,829"
59,Washington ...............,"427,052","418,329","425,517 429,364 434,997",NaN,2.5,NaN,2.5 2.5 2.5,NaN,2.5,"425,517","429,364","434,997"

In [60]:
for i in GDP2014['Percent of the U.S.'].index:
    splitList = GDP2014.loc[i, 'Percent of the U.S.'].split(" ")
    GDP2014.loc[i, '2014 Q2 %'] = splitList[0]
    GDP2014.loc[i, '2014 Q3 %'] = splitList[1]
    GDP2014.loc[i, '2014 Q4 %'] = splitList[2]
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Millions of dollars,Unnamed: 3,Unnamed: 4,Unnamed: 5,Percent of the U.S.,Unnamed: 6,Unnamed: 7,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4 %
0,United States1 ..............,"17,316,314","16,941,430","17,225,767 17,497,215 17,600,843",NaN,100.0,NaN,100.0 100.0 100.0,NaN,100.0,"17,225,767","17,497,215","17,600,843",100.0,100.0,100.0
1,New England ...............,"924,937","911,347","919,972 929,812 938,616",NaN,5.3,NaN,5.4 5.3 5.3,NaN,5.3,"919,972","929,812","938,616",5.4,5.3,5.3
2,Connecticut ...............,"253,036","249,336","252,980 253,856 255,972",NaN,1.5,NaN,1.5 1.5 1.5,NaN,1.5,"252,980","253,856","255,972",1.5,1.5,1.5
3,Maine .....................,"55,838","54,800","55,588 56,240 56,726",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"55,588","56,240","56,726",0.3,0.3,0.3
4,Massachusetts .........,"459,937","454,249","455,425 462,636 467,436",NaN,2.7,NaN,2.7 2.6 2.6,NaN,2.7,"455,425","462,636","467,436",2.7,2.6,2.6
5,New Hampshire .........,"71,552","69,842","71,895 71,929 72,542",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"71,895","71,929","72,542",0.4,0.4,0.4
6,Rhode Island ............,"54,960","54,103","54,795 55,245 55,697",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"54,795","55,245","55,697",0.3,0.3,0.3
7,Vermont ..................,"29,613","29,016","29,289 29,905 30,244",NaN,0.2,NaN,0.2 0.2 0.2,NaN,0.2,"29,289","29,905","30,244",0.2,0.2,0.2
8,Mideast .....................,"3,143,366","3,087,518","3,124,845 3,172,793 3,188,307",NaN,18.2,NaN,18.2 18.1 18.1,NaN,18.1,"3,124,845","3,172,793","3,188,307",18.2,18.1,18.1
9,Delaware ..................,"62,756","61,094","62,375 63,646 63,908",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"62,375","63,646","63,908",0.4,0.4,0.4
10,District of Columbia ...,"115,473","115,482","114,998 115,136 116,273",NaN,0.7,NaN,0.7 0.7 0.7,NaN,0.7,"114,998","115,136","116,273",0.7,0.7,0.7
11,Maryland ..................,"348,631","341,031","347,513 351,349 354,629",NaN,2.0,NaN,2.0 2.0 2.0,NaN,2.0,"347,513","351,349","354,629",2.0,2.0,2.0
12,New Jersey ...............,"549,099","539,958","546,906 552,068 557,465",NaN,3.2,NaN,3.2 3.2 3.2,NaN,3.2,"546,906","552,068","557,465",3.2,3.2,3.2
13,New York ..................,"1,404,518","1,378,213","1,393,589 1,422,242 1,424,029",NaN,8.1,NaN,8.1 8.1 8.1,NaN,8.1,"1,393,589","1,422,242","1,424,029",8.1,8.1,8.1
14,Pennsylvania ............,"662,890","651,740","659,464 668,352 672,003",NaN,3.8,NaN,3.8 3.8 3.8,NaN,3.8,"659,464","668,352","672,003",3.8,3.8,3.8
15,Great Lakes ...............,"2,391,384","2,341,059","2,379,809 2,413,833 2,430,835",NaN,13.8,NaN,13.8 13.8 13.8,NaN,13.8,"2,379,809","2,413,833","2,430,835",13.8,13.8,13.8
16,Illinois .....................,"745,875","731,827","742,805 751,601 757,269",NaN,4.3,NaN,4.3 4.3 4.3,NaN,4.3,"742,805","751,601","757,269",4.3,4.3,4.3
17,Indiana .....................,"317,840","311,837","315,952 320,434 323,139",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8,"315,952","320,434","323,139",1.8,1.8,1.8
18,Michigan ..................,"451,516","441,951","450,755 454,491 458,866",NaN,2.6,NaN,2.6 2.6 2.6,NaN,2.6,"450,755","454,491","458,866",2.6,2.6,2.6
19,Ohio ........................,"583,261","569,274","578,218 592,046 593,508",NaN,3.4,NaN,3.4 3.4 3.4,NaN,3.4,"578,218","592,046","593,508",3.4,3.4,3.4
20,Wisconsin ...............,"292,891","286,169","292,079 295,262 298,053",NaN,1.7,NaN,1.7 1.7 1.7,NaN,1.7,"292,079","295,262","298,053",1.7,1.7,1.7
21,Plains ........................,"1,131,518","1,100,382","1,128,959 1,144,482 1,152,247",NaN,6.5,NaN,6.5 6.6 6.5,NaN,6.5,"1,128,959","1,144,482","1,152,247",6.5,6.6,6.5
22,Iowa ........................,"170,613","163,845","171,071 173,281 174,256",NaN,1.0,NaN,1.0 1.0 1.0,NaN,1.0,"171,071","173,281","174,256",1.0,1.0,1.0
23,Kansas .....................,"147,075","143,510","146,670 148,403 149,718",NaN,0.8,NaN,0.8 0.9 0.8,NaN,0.9,"146,670","148,403","149,718",0.8,0.9,0.8
24,Minnesota ...............,"316,204","309,764","312,677 320,114 322,264",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8,"312,677","320,114","322,264",1.8,1.8,1.8
25,Missouri ..................,"284,462","277,624","283,834 286,961 289,431",NaN,1.6,NaN,1.6 1.6 1.6,NaN,1.6,"283,834","286,961","289,431",1.6,1.6,1.6
26,Nebraska ..................,"112,159","108,006","113,017 113,402 114,213",NaN,0.6,NaN,0.6 0.7 0.6,NaN,0.6,"113,017","113,402","114,213",0.6,0.7,0.6
27,North Dakota ............,"55,136","53,026","55,649 56,012 55,858",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"55,649","56,012","55,858",0.3,0.3,0.3
28,South Dakota ............,"45,867","44,607","46,042 46,310 46,508",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"46,042","46,310","46,508",0.3,0.3,0.3
29,Southeast ..................,"3,695,095","3,611,976","3,678,954 3,728,938 3,760,513",NaN,21.3,NaN,21.3 21.4 21.3,NaN,21.4,"3,678,954","3,728,938","3,760,513",21.3,21.4,21.3
30,Alabama ..................,"199,440","195,091","197,789 201,541 203,338",NaN,1.2,NaN,1.2 1.1 1.2,NaN,1.2,"197,789","201,541","203,338",1.2,1.1,1.2
31,Arkansas ..................,"121,395","119,172","121,242 122,108 123,060",NaN,0.7,NaN,0.7 0.7 0.7,NaN,0.7,"121,242","122,108","123,060",0.7,0.7,0.7
32,Florida .....................,"839,944","820,194","835,308 846,535 857,738",NaN,4.9,NaN,4.8 4.8 4.8,NaN,4.9,"835,308","846,535","857,738",4.8,4.8,4.8
33,Georgia ..................,"476,483","464,398","472,890 482,335 486,308",NaN,2.8,NaN,2.7 2.7 2.8,NaN,2.8,"472,890","482,335","486,308",2.7,2.7,2.8
34,Kentucky ..................,"188,602","184,763","188,758 189,951 190,936",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.1,"188,758","189,951","190,936",1.1,1.1,1.1
35,Louisiana ..................,"251,397","244,942","250,163 255,368 255,113",NaN,1.5,NaN,1.4 1.5 1.5,NaN,1.4,"250,163","255,368","255,113",1.4,1.5,1.5
36,Mississippi ...............,"104,851","103,016","105,377 105,184 105,829",NaN,0.6,NaN,0.6 0.6 0.6,NaN,0.6,"105,377","105,184","105,829",0.6,0.6,0.6
37,North Carolina .........,"483,126","474,030","478,625 488,209 491,637",NaN,2.8,NaN,2.8 2.8 2.8,NaN,2.8,"478,625","488,209","491,637",2.8,2.8,2.8
38,South Carolina .........,"190,304","184,447","190,658 191,892 194,220",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.1,"190,658","191,892","194,220",1.1,1.1,1.1
39,Tennessee ...............,"300,604","293,594","299,506 303,206 306,109",NaN,1.7,NaN,1.7 1.7 1.7,NaN,1.7,"299,506","303,206","306,109",1.7,1.7,1.7
40,Virginia .....................,"463,613","455,777","463,004 465,780 469,891",NaN,2.7,NaN,2.7 2.7 2.7,NaN,2.7,"463,004","465,780","469,891",2.7,2.7,2.7
41,West Virginia ............,"75,337","72,551","75,635 76,828 76,333",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"75,635","76,828","76,333",0.4,0.4,0.4
42,Southwest ..................,"2,208,652","2,158,213","2,197,472 2,241,598 2,237,326",NaN,12.8,NaN,12.7 12.8 12.8,NaN,12.7,"2,197,472","2,241,598","2,237,326",12.7,12.8,12.8
43,Arizona .....................,"284,156","279,983","281,409 286,590 288,644",NaN,1.6,NaN,1.7 1.6 1.6,NaN,1.6,"281,409","286,590","288,644",1.7,1.6,1.6
44,New Mexico ...............,"92,959","91,326","92,715 93,817 93,977",NaN,0.5,NaN,0.5 0.5 0.5,NaN,0.5,"92,715","93,817","93,977",0.5,0.5,0.5
45,Oklahoma ...............,"183,501","179,582","182,935 186,687 184,799",NaN,1.1,NaN,1.1 1.1 1.1,NaN,1.0,"182,935","186,687","184,799",1.1,1.1,1.1
46,Texas .....................,"1,648,036","1,607,322","1,640,414 1,674,503 1,669,905",NaN,9.5,NaN,9.5 9.5 9.6,NaN,9.5,"1,640,414","1,674,503","1,669,905",9.5,9.5,9.6
47,Rocky Mountain .........,"600,485","586,172","597,652 607,987 610,129",NaN,3.5,NaN,3.5 3.5 3.5,NaN,3.5,"597,652","607,987","610,129",3.5,3.5,3.5
48,Colorado ..................,"306,663","297,603","304,561 311,506 312,981",NaN,1.8,NaN,1.8 1.8 1.8,NaN,1.8,"304,561","311,506","312,981",1.8,1.8,1.8
49,Idaho .....................,"63,952","62,850","63,818 64,264 64,878",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"63,818","64,264","64,878",0.4,0.4,0.4
50,Montana ..................,"44,269","43,560","44,273 44,569 44,674",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"44,273","44,569","44,674",0.3,0.3,0.3
51,Utah ........................,"141,410","138,911","140,214 142,686 143,830",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8,"140,214","142,686","143,830",0.8,0.8,0.8
52,Wyoming ..................,"44,190","43,247","44,786 44,962 43,765",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.2,"44,786","44,962","43,765",0.3,0.3,0.3
53,Far West .....................,"3,220,878","3,144,765","3,198,105 3,257,772 3,282,871",NaN,18.6,NaN,18.6 18.6 18.6,NaN,18.7,"3,198,105","3,257,772","3,282,871",18.6,18.6,18.6
54,Alaska .....................,"57,080","57,371","58,253 56,996 55,700",NaN,0.3,NaN,0.3 0.3 0.3,NaN,0.3,"58,253","56,996","55,700",0.3,0.3,0.3
55,California ..................,"2,311,616","2,254,347","2,292,655 2,341,652 2,357,810",NaN,13.3,NaN,13.3 13.3 13.4,NaN,13.4,"2,292,655","2,341,652","2,357,810",13.3,13.3,13.4
56,Hawaii .....................,"77,389","76,067","77,104 77,758 78,629",NaN,0.4,NaN,0.4 0.4 0.4,NaN,0.4,"77,104","77,758","78,629",0.4,0.4,0.4
57,Nevada ..................,"132,064","130,191","131,057 133,104 133,905",NaN,0.8,NaN,0.8 0.8 0.8,NaN,0.8,"131,057","133,104","133,905",0.8,0.8,0.8
58,Oregon .....................,"215,677","208,459","213,520 218,898 221,829",NaN,1.2,NaN,1.2 1.2 1.3,NaN,1.3,"213,520","218,898","221,829",1.2,1.2,1.3
59,Washington ...............,"427,052","418,329","425,517 429,364 434,997",NaN,2.5,NaN,2.5 2.5 2.5,NaN,2.5,"425,517","429,364","434,997",2.5,2.5,2.5

In [61]:
GDP2014 = GDP2014.drop(['Millions of dollars', 'Percent of the U.S.'], axis = 1)
GDP2014 = GDP2014.drop(['Unnamed: 3', 'Unnamed: 5', 'Unnamed: 6'], axis = 1)
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 7,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4 %
0,United States1 ..............,"17,316,314","16,941,430",100.0,100.0,"17,225,767","17,497,215","17,600,843",100.0,100.0,100.0
1,New England ...............,"924,937","911,347",5.3,5.3,"919,972","929,812","938,616",5.4,5.3,5.3
2,Connecticut ...............,"253,036","249,336",1.5,1.5,"252,980","253,856","255,972",1.5,1.5,1.5
3,Maine .....................,"55,838","54,800",0.3,0.3,"55,588","56,240","56,726",0.3,0.3,0.3
4,Massachusetts .........,"459,937","454,249",2.7,2.7,"455,425","462,636","467,436",2.7,2.6,2.6
5,New Hampshire .........,"71,552","69,842",0.4,0.4,"71,895","71,929","72,542",0.4,0.4,0.4
6,Rhode Island ............,"54,960","54,103",0.3,0.3,"54,795","55,245","55,697",0.3,0.3,0.3
7,Vermont ..................,"29,613","29,016",0.2,0.2,"29,289","29,905","30,244",0.2,0.2,0.2
8,Mideast .....................,"3,143,366","3,087,518",18.2,18.1,"3,124,845","3,172,793","3,188,307",18.2,18.1,18.1
9,Delaware ..................,"62,756","61,094",0.4,0.4,"62,375","63,646","63,908",0.4,0.4,0.4
10,District of Columbia ...,"115,473","115,482",0.7,0.7,"114,998","115,136","116,273",0.7,0.7,0.7
11,Maryland ..................,"348,631","341,031",2.0,2.0,"347,513","351,349","354,629",2.0,2.0,2.0
12,New Jersey ...............,"549,099","539,958",3.2,3.2,"546,906","552,068","557,465",3.2,3.2,3.2
13,New York ..................,"1,404,518","1,378,213",8.1,8.1,"1,393,589","1,422,242","1,424,029",8.1,8.1,8.1
14,Pennsylvania ............,"662,890","651,740",3.8,3.8,"659,464","668,352","672,003",3.8,3.8,3.8
15,Great Lakes ...............,"2,391,384","2,341,059",13.8,13.8,"2,379,809","2,413,833","2,430,835",13.8,13.8,13.8
16,Illinois .....................,"745,875","731,827",4.3,4.3,"742,805","751,601","757,269",4.3,4.3,4.3
17,Indiana .....................,"317,840","311,837",1.8,1.8,"315,952","320,434","323,139",1.8,1.8,1.8
18,Michigan ..................,"451,516","441,951",2.6,2.6,"450,755","454,491","458,866",2.6,2.6,2.6
19,Ohio ........................,"583,261","569,274",3.4,3.4,"578,218","592,046","593,508",3.4,3.4,3.4
20,Wisconsin ...............,"292,891","286,169",1.7,1.7,"292,079","295,262","298,053",1.7,1.7,1.7
21,Plains ........................,"1,131,518","1,100,382",6.5,6.5,"1,128,959","1,144,482","1,152,247",6.5,6.6,6.5
22,Iowa ........................,"170,613","163,845",1.0,1.0,"171,071","173,281","174,256",1.0,1.0,1.0
23,Kansas .....................,"147,075","143,510",0.8,0.9,"146,670","148,403","149,718",0.8,0.9,0.8
24,Minnesota ...............,"316,204","309,764",1.8,1.8,"312,677","320,114","322,264",1.8,1.8,1.8
25,Missouri ..................,"284,462","277,624",1.6,1.6,"283,834","286,961","289,431",1.6,1.6,1.6
26,Nebraska ..................,"112,159","108,006",0.6,0.6,"113,017","113,402","114,213",0.6,0.7,0.6
27,North Dakota ............,"55,136","53,026",0.3,0.3,"55,649","56,012","55,858",0.3,0.3,0.3
28,South Dakota ............,"45,867","44,607",0.3,0.3,"46,042","46,310","46,508",0.3,0.3,0.3
29,Southeast ..................,"3,695,095","3,611,976",21.3,21.4,"3,678,954","3,728,938","3,760,513",21.3,21.4,21.3
30,Alabama ..................,"199,440","195,091",1.2,1.2,"197,789","201,541","203,338",1.2,1.1,1.2
31,Arkansas ..................,"121,395","119,172",0.7,0.7,"121,242","122,108","123,060",0.7,0.7,0.7
32,Florida .....................,"839,944","820,194",4.9,4.9,"835,308","846,535","857,738",4.8,4.8,4.8
33,Georgia ..................,"476,483","464,398",2.8,2.8,"472,890","482,335","486,308",2.7,2.7,2.8
34,Kentucky ..................,"188,602","184,763",1.1,1.1,"188,758","189,951","190,936",1.1,1.1,1.1
35,Louisiana ..................,"251,397","244,942",1.5,1.4,"250,163","255,368","255,113",1.4,1.5,1.5
36,Mississippi ...............,"104,851","103,016",0.6,0.6,"105,377","105,184","105,829",0.6,0.6,0.6
37,North Carolina .........,"483,126","474,030",2.8,2.8,"478,625","488,209","491,637",2.8,2.8,2.8
38,South Carolina .........,"190,304","184,447",1.1,1.1,"190,658","191,892","194,220",1.1,1.1,1.1
39,Tennessee ...............,"300,604","293,594",1.7,1.7,"299,506","303,206","306,109",1.7,1.7,1.7
40,Virginia .....................,"463,613","455,777",2.7,2.7,"463,004","465,780","469,891",2.7,2.7,2.7
41,West Virginia ............,"75,337","72,551",0.4,0.4,"75,635","76,828","76,333",0.4,0.4,0.4
42,Southwest ..................,"2,208,652","2,158,213",12.8,12.7,"2,197,472","2,241,598","2,237,326",12.7,12.8,12.8
43,Arizona .....................,"284,156","279,983",1.6,1.6,"281,409","286,590","288,644",1.7,1.6,1.6
44,New Mexico ...............,"92,959","91,326",0.5,0.5,"92,715","93,817","93,977",0.5,0.5,0.5
45,Oklahoma ...............,"183,501","179,582",1.1,1.0,"182,935","186,687","184,799",1.1,1.1,1.1
46,Texas .....................,"1,648,036","1,607,322",9.5,9.5,"1,640,414","1,674,503","1,669,905",9.5,9.5,9.6
47,Rocky Mountain .........,"600,485","586,172",3.5,3.5,"597,652","607,987","610,129",3.5,3.5,3.5
48,Colorado ..................,"306,663","297,603",1.8,1.8,"304,561","311,506","312,981",1.8,1.8,1.8
49,Idaho .....................,"63,952","62,850",0.4,0.4,"63,818","64,264","64,878",0.4,0.4,0.4
50,Montana ..................,"44,269","43,560",0.3,0.3,"44,273","44,569","44,674",0.3,0.3,0.3
51,Utah ........................,"141,410","138,911",0.8,0.8,"140,214","142,686","143,830",0.8,0.8,0.8
52,Wyoming ..................,"44,190","43,247",0.3,0.2,"44,786","44,962","43,765",0.3,0.3,0.3
53,Far West .....................,"3,220,878","3,144,765",18.6,18.7,"3,198,105","3,257,772","3,282,871",18.6,18.6,18.6
54,Alaska .....................,"57,080","57,371",0.3,0.3,"58,253","56,996","55,700",0.3,0.3,0.3
55,California ..................,"2,311,616","2,254,347",13.3,13.4,"2,292,655","2,341,652","2,357,810",13.3,13.3,13.4
56,Hawaii .....................,"77,389","76,067",0.4,0.4,"77,104","77,758","78,629",0.4,0.4,0.4
57,Nevada ..................,"132,064","130,191",0.8,0.8,"131,057","133,104","133,905",0.8,0.8,0.8
58,Oregon .....................,"215,677","208,459",1.2,1.3,"213,520","218,898","221,829",1.2,1.2,1.3
59,Washington ...............,"427,052","418,329",2.5,2.5,"425,517","429,364","434,997",2.5,2.5,2.5

In [62]:
for column in GDP2014.columns:
    if column == 'Unnamed: 0':
        pass
    else:
        for i in GDP2014[column].index:
            if isinstance(GDP2014.loc[i, column], float):
                pass
            else:
                GDP2014.loc[i, column] = GDP2014.loc[i, column].replace(',','')
GDP2014 = GDP2014.apply(pd.to_numeric, errors = 'ignore')
GDP2014

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 7,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4 %
0,United States1 ..............,17316314,16941430,100.0,100.0,17225767,17497215,17600843,100.0,100.0,100.0
1,New England ...............,924937,911347,5.3,5.3,919972,929812,938616,5.4,5.3,5.3
2,Connecticut ...............,253036,249336,1.5,1.5,252980,253856,255972,1.5,1.5,1.5
3,Maine .....................,55838,54800,0.3,0.3,55588,56240,56726,0.3,0.3,0.3
4,Massachusetts .........,459937,454249,2.7,2.7,455425,462636,467436,2.7,2.6,2.6
5,New Hampshire .........,71552,69842,0.4,0.4,71895,71929,72542,0.4,0.4,0.4
6,Rhode Island ............,54960,54103,0.3,0.3,54795,55245,55697,0.3,0.3,0.3
7,Vermont ..................,29613,29016,0.2,0.2,29289,29905,30244,0.2,0.2,0.2
8,Mideast .....................,3143366,3087518,18.2,18.1,3124845,3172793,3188307,18.2,18.1,18.1
9,Delaware ..................,62756,61094,0.4,0.4,62375,63646,63908,0.4,0.4,0.4
10,District of Columbia ...,115473,115482,0.7,0.7,114998,115136,116273,0.7,0.7,0.7
11,Maryland ..................,348631,341031,2.0,2.0,347513,351349,354629,2.0,2.0,2.0
12,New Jersey ...............,549099,539958,3.2,3.2,546906,552068,557465,3.2,3.2,3.2
13,New York ..................,1404518,1378213,8.1,8.1,1393589,1422242,1424029,8.1,8.1,8.1
14,Pennsylvania ............,662890,651740,3.8,3.8,659464,668352,672003,3.8,3.8,3.8
15,Great Lakes ...............,2391384,2341059,13.8,13.8,2379809,2413833,2430835,13.8,13.8,13.8
16,Illinois .....................,745875,731827,4.3,4.3,742805,751601,757269,4.3,4.3,4.3
17,Indiana .....................,317840,311837,1.8,1.8,315952,320434,323139,1.8,1.8,1.8
18,Michigan ..................,451516,441951,2.6,2.6,450755,454491,458866,2.6,2.6,2.6
19,Ohio ........................,583261,569274,3.4,3.4,578218,592046,593508,3.4,3.4,3.4
20,Wisconsin ...............,292891,286169,1.7,1.7,292079,295262,298053,1.7,1.7,1.7
21,Plains ........................,1131518,1100382,6.5,6.5,1128959,1144482,1152247,6.5,6.6,6.5
22,Iowa ........................,170613,163845,1.0,1.0,171071,173281,174256,1.0,1.0,1.0
23,Kansas .....................,147075,143510,0.8,0.9,146670,148403,149718,0.8,0.9,0.8
24,Minnesota ...............,316204,309764,1.8,1.8,312677,320114,322264,1.8,1.8,1.8
25,Missouri ..................,284462,277624,1.6,1.6,283834,286961,289431,1.6,1.6,1.6
26,Nebraska ..................,112159,108006,0.6,0.6,113017,113402,114213,0.6,0.7,0.6
27,North Dakota ............,55136,53026,0.3,0.3,55649,56012,55858,0.3,0.3,0.3
28,South Dakota ............,45867,44607,0.3,0.3,46042,46310,46508,0.3,0.3,0.3
29,Southeast ..................,3695095,3611976,21.3,21.4,3678954,3728938,3760513,21.3,21.4,21.3
30,Alabama ..................,199440,195091,1.2,1.2,197789,201541,203338,1.2,1.1,1.2
31,Arkansas ..................,121395,119172,0.7,0.7,121242,122108,123060,0.7,0.7,0.7
32,Florida .....................,839944,820194,4.9,4.9,835308,846535,857738,4.8,4.8,4.8
33,Georgia ..................,476483,464398,2.8,2.8,472890,482335,486308,2.7,2.7,2.8
34,Kentucky ..................,188602,184763,1.1,1.1,188758,189951,190936,1.1,1.1,1.1
35,Louisiana ..................,251397,244942,1.5,1.4,250163,255368,255113,1.4,1.5,1.5
36,Mississippi ...............,104851,103016,0.6,0.6,105377,105184,105829,0.6,0.6,0.6
37,North Carolina .........,483126,474030,2.8,2.8,478625,488209,491637,2.8,2.8,2.8
38,South Carolina .........,190304,184447,1.1,1.1,190658,191892,194220,1.1,1.1,1.1
39,Tennessee ...............,300604,293594,1.7,1.7,299506,303206,306109,1.7,1.7,1.7
40,Virginia .....................,463613,455777,2.7,2.7,463004,465780,469891,2.7,2.7,2.7
41,West Virginia ............,75337,72551,0.4,0.4,75635,76828,76333,0.4,0.4,0.4
42,Southwest ..................,2208652,2158213,12.8,12.7,2197472,2241598,2237326,12.7,12.8,12.8
43,Arizona .....................,284156,279983,1.6,1.6,281409,286590,288644,1.7,1.6,1.6
44,New Mexico ...............,92959,91326,0.5,0.5,92715,93817,93977,0.5,0.5,0.5
45,Oklahoma ...............,183501,179582,1.1,1.0,182935,186687,184799,1.1,1.1,1.1
46,Texas .....................,1648036,1607322,9.5,9.5,1640414,1674503,1669905,9.5,9.5,9.6
47,Rocky Mountain .........,600485,586172,3.5,3.5,597652,607987,610129,3.5,3.5,3.5
48,Colorado ..................,306663,297603,1.8,1.8,304561,311506,312981,1.8,1.8,1.8
49,Idaho .....................,63952,62850,0.4,0.4,63818,64264,64878,0.4,0.4,0.4
50,Montana ..................,44269,43560,0.3,0.3,44273,44569,44674,0.3,0.3,0.3
51,Utah ........................,141410,138911,0.8,0.8,140214,142686,143830,0.8,0.8,0.8
52,Wyoming ..................,44190,43247,0.3,0.2,44786,44962,43765,0.3,0.3,0.3
53,Far West .....................,3220878,3144765,18.6,18.7,3198105,3257772,3282871,18.6,18.6,18.6
54,Alaska .....................,57080,57371,0.3,0.3,58253,56996,55700,0.3,0.3,0.3
55,California ..................,2311616,2254347,13.3,13.4,2292655,2341652,2357810,13.3,13.3,13.4
56,Hawaii .....................,77389,76067,0.4,0.4,77104,77758,78629,0.4,0.4,0.4
57,Nevada ..................,132064,130191,0.8,0.8,131057,133104,133905,0.8,0.8,0.8
58,Oregon .....................,215677,208459,1.2,1.3,213520,218898,221829,1.2,1.2,1.3
59,Washington ...............,427052,418329,2.5,2.5,425517,429364,434997,2.5,2.5,2.5

In [63]:
GDP2014.columns = ['Area', '2014', '2014 Q1', '2014 %', '2014 Q1 %', '2014 Q2', '2014 Q3', '2014 Q4',
                 '2014 Q2 %', '2014 Q3 %', '2014 Q4%']
GDP2014

,Area,2014,2014 Q1,2014 %,2014 Q1 %,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4%
0,United States1 ..............,17316314,16941430,100.0,100.0,17225767,17497215,17600843,100.0,100.0,100.0
1,New England ...............,924937,911347,5.3,5.3,919972,929812,938616,5.4,5.3,5.3
2,Connecticut ...............,253036,249336,1.5,1.5,252980,253856,255972,1.5,1.5,1.5
3,Maine .....................,55838,54800,0.3,0.3,55588,56240,56726,0.3,0.3,0.3
4,Massachusetts .........,459937,454249,2.7,2.7,455425,462636,467436,2.7,2.6,2.6
5,New Hampshire .........,71552,69842,0.4,0.4,71895,71929,72542,0.4,0.4,0.4
6,Rhode Island ............,54960,54103,0.3,0.3,54795,55245,55697,0.3,0.3,0.3
7,Vermont ..................,29613,29016,0.2,0.2,29289,29905,30244,0.2,0.2,0.2
8,Mideast .....................,3143366,3087518,18.2,18.1,3124845,3172793,3188307,18.2,18.1,18.1
9,Delaware ..................,62756,61094,0.4,0.4,62375,63646,63908,0.4,0.4,0.4
10,District of Columbia ...,115473,115482,0.7,0.7,114998,115136,116273,0.7,0.7,0.7
11,Maryland ..................,348631,341031,2.0,2.0,347513,351349,354629,2.0,2.0,2.0
12,New Jersey ...............,549099,539958,3.2,3.2,546906,552068,557465,3.2,3.2,3.2
13,New York ..................,1404518,1378213,8.1,8.1,1393589,1422242,1424029,8.1,8.1,8.1
14,Pennsylvania ............,662890,651740,3.8,3.8,659464,668352,672003,3.8,3.8,3.8
15,Great Lakes ...............,2391384,2341059,13.8,13.8,2379809,2413833,2430835,13.8,13.8,13.8
16,Illinois .....................,745875,731827,4.3,4.3,742805,751601,757269,4.3,4.3,4.3
17,Indiana .....................,317840,311837,1.8,1.8,315952,320434,323139,1.8,1.8,1.8
18,Michigan ..................,451516,441951,2.6,2.6,450755,454491,458866,2.6,2.6,2.6
19,Ohio ........................,583261,569274,3.4,3.4,578218,592046,593508,3.4,3.4,3.4
20,Wisconsin ...............,292891,286169,1.7,1.7,292079,295262,298053,1.7,1.7,1.7
21,Plains ........................,1131518,1100382,6.5,6.5,1128959,1144482,1152247,6.5,6.6,6.5
22,Iowa ........................,170613,163845,1.0,1.0,171071,173281,174256,1.0,1.0,1.0
23,Kansas .....................,147075,143510,0.8,0.9,146670,148403,149718,0.8,0.9,0.8
24,Minnesota ...............,316204,309764,1.8,1.8,312677,320114,322264,1.8,1.8,1.8
25,Missouri ..................,284462,277624,1.6,1.6,283834,286961,289431,1.6,1.6,1.6
26,Nebraska ..................,112159,108006,0.6,0.6,113017,113402,114213,0.6,0.7,0.6
27,North Dakota ............,55136,53026,0.3,0.3,55649,56012,55858,0.3,0.3,0.3
28,South Dakota ............,45867,44607,0.3,0.3,46042,46310,46508,0.3,0.3,0.3
29,Southeast ..................,3695095,3611976,21.3,21.4,3678954,3728938,3760513,21.3,21.4,21.3
30,Alabama ..................,199440,195091,1.2,1.2,197789,201541,203338,1.2,1.1,1.2
31,Arkansas ..................,121395,119172,0.7,0.7,121242,122108,123060,0.7,0.7,0.7
32,Florida .....................,839944,820194,4.9,4.9,835308,846535,857738,4.8,4.8,4.8
33,Georgia ..................,476483,464398,2.8,2.8,472890,482335,486308,2.7,2.7,2.8
34,Kentucky ..................,188602,184763,1.1,1.1,188758,189951,190936,1.1,1.1,1.1
35,Louisiana ..................,251397,244942,1.5,1.4,250163,255368,255113,1.4,1.5,1.5
36,Mississippi ...............,104851,103016,0.6,0.6,105377,105184,105829,0.6,0.6,0.6
37,North Carolina .........,483126,474030,2.8,2.8,478625,488209,491637,2.8,2.8,2.8
38,South Carolina .........,190304,184447,1.1,1.1,190658,191892,194220,1.1,1.1,1.1
39,Tennessee ...............,300604,293594,1.7,1.7,299506,303206,306109,1.7,1.7,1.7
40,Virginia .....................,463613,455777,2.7,2.7,463004,465780,469891,2.7,2.7,2.7
41,West Virginia ............,75337,72551,0.4,0.4,75635,76828,76333,0.4,0.4,0.4
42,Southwest ..................,2208652,2158213,12.8,12.7,2197472,2241598,2237326,12.7,12.8,12.8
43,Arizona .....................,284156,279983,1.6,1.6,281409,286590,288644,1.7,1.6,1.6
44,New Mexico ...............,92959,91326,0.5,0.5,92715,93817,93977,0.5,0.5,0.5
45,Oklahoma ...............,183501,179582,1.1,1.0,182935,186687,184799,1.1,1.1,1.1
46,Texas .....................,1648036,1607322,9.5,9.5,1640414,1674503,1669905,9.5,9.5,9.6
47,Rocky Mountain .........,600485,586172,3.5,3.5,597652,607987,610129,3.5,3.5,3.5
48,Colorado ..................,306663,297603,1.8,1.8,304561,311506,312981,1.8,1.8,1.8
49,Idaho .....................,63952,62850,0.4,0.4,63818,64264,64878,0.4,0.4,0.4
50,Montana ..................,44269,43560,0.3,0.3,44273,44569,44674,0.3,0.3,0.3
51,Utah ........................,141410,138911,0.8,0.8,140214,142686,143830,0.8,0.8,0.8
52,Wyoming ..................,44190,43247,0.3,0.2,44786,44962,43765,0.3,0.3,0.3
53,Far West .....................,3220878,3144765,18.6,18.7,3198105,3257772,3282871,18.6,18.6,18.6
54,Alaska .....................,57080,57371,0.3,0.3,58253,56996,55700,0.3,0.3,0.3
55,California ..................,2311616,2254347,13.3,13.4,2292655,2341652,2357810,13.3,13.3,13.4
56,Hawaii .....................,77389,76067,0.4,0.4,77104,77758,78629,0.4,0.4,0.4
57,Nevada ..................,132064,130191,0.8,0.8,131057,133104,133905,0.8,0.8,0.8
58,Oregon .....................,215677,208459,1.2,1.3,213520,218898,221829,1.2,1.2,1.3
59,Washington ...............,427052,418329,2.5,2.5,425517,429364,434997,2.5,2.5,2.5

In [64]:
GDP_2014 = QuarterlyGDP('GDP2014_quarterly.pdf', 7, 2014, 2014, '2014')
GDP_2014.df = GDP2014
GDP_2014.df

,Area,2014,2014 Q1,2014 %,2014 Q1 %,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4%
0,United States1 ..............,17316314,16941430,100.0,100.0,17225767,17497215,17600843,100.0,100.0,100.0
1,New England ...............,924937,911347,5.3,5.3,919972,929812,938616,5.4,5.3,5.3
2,Connecticut ...............,253036,249336,1.5,1.5,252980,253856,255972,1.5,1.5,1.5
3,Maine .....................,55838,54800,0.3,0.3,55588,56240,56726,0.3,0.3,0.3
4,Massachusetts .........,459937,454249,2.7,2.7,455425,462636,467436,2.7,2.6,2.6
5,New Hampshire .........,71552,69842,0.4,0.4,71895,71929,72542,0.4,0.4,0.4
6,Rhode Island ............,54960,54103,0.3,0.3,54795,55245,55697,0.3,0.3,0.3
7,Vermont ..................,29613,29016,0.2,0.2,29289,29905,30244,0.2,0.2,0.2
8,Mideast .....................,3143366,3087518,18.2,18.1,3124845,3172793,3188307,18.2,18.1,18.1
9,Delaware ..................,62756,61094,0.4,0.4,62375,63646,63908,0.4,0.4,0.4
10,District of Columbia ...,115473,115482,0.7,0.7,114998,115136,116273,0.7,0.7,0.7
11,Maryland ..................,348631,341031,2.0,2.0,347513,351349,354629,2.0,2.0,2.0
12,New Jersey ...............,549099,539958,3.2,3.2,546906,552068,557465,3.2,3.2,3.2
13,New York ..................,1404518,1378213,8.1,8.1,1393589,1422242,1424029,8.1,8.1,8.1
14,Pennsylvania ............,662890,651740,3.8,3.8,659464,668352,672003,3.8,3.8,3.8
15,Great Lakes ...............,2391384,2341059,13.8,13.8,2379809,2413833,2430835,13.8,13.8,13.8
16,Illinois .....................,745875,731827,4.3,4.3,742805,751601,757269,4.3,4.3,4.3
17,Indiana .....................,317840,311837,1.8,1.8,315952,320434,323139,1.8,1.8,1.8
18,Michigan ..................,451516,441951,2.6,2.6,450755,454491,458866,2.6,2.6,2.6
19,Ohio ........................,583261,569274,3.4,3.4,578218,592046,593508,3.4,3.4,3.4
20,Wisconsin ...............,292891,286169,1.7,1.7,292079,295262,298053,1.7,1.7,1.7
21,Plains ........................,1131518,1100382,6.5,6.5,1128959,1144482,1152247,6.5,6.6,6.5
22,Iowa ........................,170613,163845,1.0,1.0,171071,173281,174256,1.0,1.0,1.0
23,Kansas .....................,147075,143510,0.8,0.9,146670,148403,149718,0.8,0.9,0.8
24,Minnesota ...............,316204,309764,1.8,1.8,312677,320114,322264,1.8,1.8,1.8
25,Missouri ..................,284462,277624,1.6,1.6,283834,286961,289431,1.6,1.6,1.6
26,Nebraska ..................,112159,108006,0.6,0.6,113017,113402,114213,0.6,0.7,0.6
27,North Dakota ............,55136,53026,0.3,0.3,55649,56012,55858,0.3,0.3,0.3
28,South Dakota ............,45867,44607,0.3,0.3,46042,46310,46508,0.3,0.3,0.3
29,Southeast ..................,3695095,3611976,21.3,21.4,3678954,3728938,3760513,21.3,21.4,21.3
30,Alabama ..................,199440,195091,1.2,1.2,197789,201541,203338,1.2,1.1,1.2
31,Arkansas ..................,121395,119172,0.7,0.7,121242,122108,123060,0.7,0.7,0.7
32,Florida .....................,839944,820194,4.9,4.9,835308,846535,857738,4.8,4.8,4.8
33,Georgia ..................,476483,464398,2.8,2.8,472890,482335,486308,2.7,2.7,2.8
34,Kentucky ..................,188602,184763,1.1,1.1,188758,189951,190936,1.1,1.1,1.1
35,Louisiana ..................,251397,244942,1.5,1.4,250163,255368,255113,1.4,1.5,1.5
36,Mississippi ...............,104851,103016,0.6,0.6,105377,105184,105829,0.6,0.6,0.6
37,North Carolina .........,483126,474030,2.8,2.8,478625,488209,491637,2.8,2.8,2.8
38,South Carolina .........,190304,184447,1.1,1.1,190658,191892,194220,1.1,1.1,1.1
39,Tennessee ...............,300604,293594,1.7,1.7,299506,303206,306109,1.7,1.7,1.7
40,Virginia .....................,463613,455777,2.7,2.7,463004,465780,469891,2.7,2.7,2.7
41,West Virginia ............,75337,72551,0.4,0.4,75635,76828,76333,0.4,0.4,0.4
42,Southwest ..................,2208652,2158213,12.8,12.7,2197472,2241598,2237326,12.7,12.8,12.8
43,Arizona .....................,284156,279983,1.6,1.6,281409,286590,288644,1.7,1.6,1.6
44,New Mexico ...............,92959,91326,0.5,0.5,92715,93817,93977,0.5,0.5,0.5
45,Oklahoma ...............,183501,179582,1.1,1.0,182935,186687,184799,1.1,1.1,1.1
46,Texas .....................,1648036,1607322,9.5,9.5,1640414,1674503,1669905,9.5,9.5,9.6
47,Rocky Mountain .........,600485,586172,3.5,3.5,597652,607987,610129,3.5,3.5,3.5
48,Colorado ..................,306663,297603,1.8,1.8,304561,311506,312981,1.8,1.8,1.8
49,Idaho .....................,63952,62850,0.4,0.4,63818,64264,64878,0.4,0.4,0.4
50,Montana ..................,44269,43560,0.3,0.3,44273,44569,44674,0.3,0.3,0.3
51,Utah ........................,141410,138911,0.8,0.8,140214,142686,143830,0.8,0.8,0.8
52,Wyoming ..................,44190,43247,0.3,0.2,44786,44962,43765,0.3,0.3,0.3
53,Far West .....................,3220878,3144765,18.6,18.7,3198105,3257772,3282871,18.6,18.6,18.6
54,Alaska .....................,57080,57371,0.3,0.3,58253,56996,55700,0.3,0.3,0.3
55,California ..................,2311616,2254347,13.3,13.4,2292655,2341652,2357810,13.3,13.3,13.4
56,Hawaii .....................,77389,76067,0.4,0.4,77104,77758,78629,0.4,0.4,0.4
57,Nevada ..................,132064,130191,0.8,0.8,131057,133104,133905,0.8,0.8,0.8
58,Oregon .....................,215677,208459,1.2,1.3,213520,218898,221829,1.2,1.2,1.3
59,Washington ...............,427052,418329,2.5,2.5,425517,429364,434997,2.5,2.5,2.5

In [65]:
GDP_2014.cleanStates()

,Area,2014,2014 Q1,2014 %,2014 Q1 %,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4%,Cleaned Area
0,United States1 ..............,17316314,16941430,100.0,100.0,17225767,17497215,17600843,100.0,100.0,100.0,United States
1,New England ...............,924937,911347,5.3,5.3,919972,929812,938616,5.4,5.3,5.3,New England
2,Connecticut ...............,253036,249336,1.5,1.5,252980,253856,255972,1.5,1.5,1.5,Connecticut
3,Maine .....................,55838,54800,0.3,0.3,55588,56240,56726,0.3,0.3,0.3,Maine
4,Massachusetts .........,459937,454249,2.7,2.7,455425,462636,467436,2.7,2.6,2.6,Massachusetts
5,New Hampshire .........,71552,69842,0.4,0.4,71895,71929,72542,0.4,0.4,0.4,New Hampshire
6,Rhode Island ............,54960,54103,0.3,0.3,54795,55245,55697,0.3,0.3,0.3,Rhode Island
7,Vermont ..................,29613,29016,0.2,0.2,29289,29905,30244,0.2,0.2,0.2,Vermont
8,Mideast .....................,3143366,3087518,18.2,18.1,3124845,3172793,3188307,18.2,18.1,18.1,Mideast
9,Delaware ..................,62756,61094,0.4,0.4,62375,63646,63908,0.4,0.4,0.4,Delaware
10,District of Columbia ...,115473,115482,0.7,0.7,114998,115136,116273,0.7,0.7,0.7,District of Columbia
11,Maryland ..................,348631,341031,2.0,2.0,347513,351349,354629,2.0,2.0,2.0,Maryland
12,New Jersey ...............,549099,539958,3.2,3.2,546906,552068,557465,3.2,3.2,3.2,New Jersey
13,New York ..................,1404518,1378213,8.1,8.1,1393589,1422242,1424029,8.1,8.1,8.1,New York
14,Pennsylvania ............,662890,651740,3.8,3.8,659464,668352,672003,3.8,3.8,3.8,Pennsylvania
15,Great Lakes ...............,2391384,2341059,13.8,13.8,2379809,2413833,2430835,13.8,13.8,13.8,Great Lakes
16,Illinois .....................,745875,731827,4.3,4.3,742805,751601,757269,4.3,4.3,4.3,Illinois
17,Indiana .....................,317840,311837,1.8,1.8,315952,320434,323139,1.8,1.8,1.8,Indiana
18,Michigan ..................,451516,441951,2.6,2.6,450755,454491,458866,2.6,2.6,2.6,Michigan
19,Ohio ........................,583261,569274,3.4,3.4,578218,592046,593508,3.4,3.4,3.4,Ohio
20,Wisconsin ...............,292891,286169,1.7,1.7,292079,295262,298053,1.7,1.7,1.7,Wisconsin
21,Plains ........................,1131518,1100382,6.5,6.5,1128959,1144482,1152247,6.5,6.6,6.5,Plains
22,Iowa ........................,170613,163845,1.0,1.0,171071,173281,174256,1.0,1.0,1.0,Iowa
23,Kansas .....................,147075,143510,0.8,0.9,146670,148403,149718,0.8,0.9,0.8,Kansas
24,Minnesota ...............,316204,309764,1.8,1.8,312677,320114,322264,1.8,1.8,1.8,Minnesota
25,Missouri ..................,284462,277624,1.6,1.6,283834,286961,289431,1.6,1.6,1.6,Missouri
26,Nebraska ..................,112159,108006,0.6,0.6,113017,113402,114213,0.6,0.7,0.6,Nebraska
27,North Dakota ............,55136,53026,0.3,0.3,55649,56012,55858,0.3,0.3,0.3,North Dakota
28,South Dakota ............,45867,44607,0.3,0.3,46042,46310,46508,0.3,0.3,0.3,South Dakota
29,Southeast ..................,3695095,3611976,21.3,21.4,3678954,3728938,3760513,21.3,21.4,21.3,Southeast
30,Alabama ..................,199440,195091,1.2,1.2,197789,201541,203338,1.2,1.1,1.2,Alabama
31,Arkansas ..................,121395,119172,0.7,0.7,121242,122108,123060,0.7,0.7,0.7,Arkansas
32,Florida .....................,839944,820194,4.9,4.9,835308,846535,857738,4.8,4.8,4.8,Florida
33,Georgia ..................,476483,464398,2.8,2.8,472890,482335,486308,2.7,2.7,2.8,Georgia
34,Kentucky ..................,188602,184763,1.1,1.1,188758,189951,190936,1.1,1.1,1.1,Kentucky
35,Louisiana ..................,251397,244942,1.5,1.4,250163,255368,255113,1.4,1.5,1.5,Louisiana
36,Mississippi ...............,104851,103016,0.6,0.6,105377,105184,105829,0.6,0.6,0.6,Mississippi
37,North Carolina .........,483126,474030,2.8,2.8,478625,488209,491637,2.8,2.8,2.8,North Carolina
38,South Carolina .........,190304,184447,1.1,1.1,190658,191892,194220,1.1,1.1,1.1,South Carolina
39,Tennessee ...............,300604,293594,1.7,1.7,299506,303206,306109,1.7,1.7,1.7,Tennessee
40,Virginia .....................,463613,455777,2.7,2.7,463004,465780,469891,2.7,2.7,2.7,Virginia
41,West Virginia ............,75337,72551,0.4,0.4,75635,76828,76333,0.4,0.4,0.4,West Virginia
42,Southwest ..................,2208652,2158213,12.8,12.7,2197472,2241598,2237326,12.7,12.8,12.8,Southwest
43,Arizona .....................,284156,279983,1.6,1.6,281409,286590,288644,1.7,1.6,1.6,Arizona
44,New Mexico ...............,92959,91326,0.5,0.5,92715,93817,93977,0.5,0.5,0.5,New Mexico
45,Oklahoma ...............,183501,179582,1.1,1.0,182935,186687,184799,1.1,1.1,1.1,Oklahoma
46,Texas .....................,1648036,1607322,9.5,9.5,1640414,1674503,1669905,9.5,9.5,9.6,Texas
47,Rocky Mountain .........,600485,586172,3.5,3.5,597652,607987,610129,3.5,3.5,3.5,Rocky Mountain
48,Colorado ..................,306663,297603,1.8,1.8,304561,311506,312981,1.8,1.8,1.8,Colorado
49,Idaho .....................,63952,62850,0.4,0.4,63818,64264,64878,0.4,0.4,0.4,Idaho
50,Montana ..................,44269,43560,0.3,0.3,44273,44569,44674,0.3,0.3,0.3,Montana
51,Utah ........................,141410,138911,0.8,0.8,140214,142686,143830,0.8,0.8,0.8,Utah
52,Wyoming ..................,44190,43247,0.3,0.2,44786,44962,43765,0.3,0.3,0.3,Wyoming
53,Far West .....................,3220878,3144765,18.6,18.7,3198105,3257772,3282871,18.6,18.6,18.6,Far West
54,Alaska .....................,57080,57371,0.3,0.3,58253,56996,55700,0.3,0.3,0.3,Alaska
55,California ..................,2311616,2254347,13.3,13.4,2292655,2341652,2357810,13.3,13.3,13.4,California
56,Hawaii .....................,77389,76067,0.4,0.4,77104,77758,78629,0.4,0.4,0.4,Hawaii
57,Nevada ..................,132064,130191,0.8,0.8,131057,133104,133905,0.8,0.8,0.8,Nevada
58,Oregon .....................,215677,208459,1.2,1.3,213520,218898,221829,1.2,1.2,1.3,Oregon
59,Washington ...............,427052,418329,2.5,2.5,425517,429364,434997,2.5,2.5,2.5,Washington

In [66]:
GDP_2014.addGeoLocColumn()

,Area,2014,2014 Q1,2014 %,2014 Q1 %,2014 Q2,2014 Q3,2014 Q4,2014 Q2 %,2014 Q3 %,2014 Q4%,Cleaned Area,Geo Loc
0,United States1 ..............,17316314,16941430,100.0,100.0,17225767,17497215,17600843,100.0,100.0,100.0,United States,NaN
1,New England ...............,924937,911347,5.3,5.3,919972,929812,938616,5.4,5.3,5.3,New England,NaN
2,Connecticut ...............,253036,249336,1.5,1.5,252980,253856,255972,1.5,1.5,1.5,Connecticut,New England
3,Maine .....................,55838,54800,0.3,0.3,55588,56240,56726,0.3,0.3,0.3,Maine,New England
4,Massachusetts .........,459937,454249,2.7,2.7,455425,462636,467436,2.7,2.6,2.6,Massachusetts,New England
5,New Hampshire .........,71552,69842,0.4,0.4,71895,71929,72542,0.4,0.4,0.4,New Hampshire,New England
6,Rhode Island ............,54960,54103,0.3,0.3,54795,55245,55697,0.3,0.3,0.3,Rhode Island,New England
7,Vermont ..................,29613,29016,0.2,0.2,29289,29905,30244,0.2,0.2,0.2,Vermont,New England
8,Mideast .....................,3143366,3087518,18.2,18.1,3124845,3172793,3188307,18.2,18.1,18.1,Mideast,NaN
9,Delaware ..................,62756,61094,0.4,0.4,62375,63646,63908,0.4,0.4,0.4,Delaware,Mideast
10,District of Columbia ...,115473,115482,0.7,0.7,114998,115136,116273,0.7,0.7,0.7,District of Columbia,Mideast
11,Maryland ..................,348631,341031,2.0,2.0,347513,351349,354629,2.0,2.0,2.0,Maryland,Mideast
12,New Jersey ...............,549099,539958,3.2,3.2,546906,552068,557465,3.2,3.2,3.2,New Jersey,Mideast
13,New York ..................,1404518,1378213,8.1,8.1,1393589,1422242,1424029,8.1,8.1,8.1,New York,Mideast
14,Pennsylvania ............,662890,651740,3.8,3.8,659464,668352,672003,3.8,3.8,3.8,Pennsylvania,Mideast
15,Great Lakes ...............,2391384,2341059,13.8,13.8,2379809,2413833,2430835,13.8,13.8,13.8,Great Lakes,NaN
16,Illinois .....................,745875,731827,4.3,4.3,742805,751601,757269,4.3,4.3,4.3,Illinois,Great Lakes
17,Indiana .....................,317840,311837,1.8,1.8,315952,320434,323139,1.8,1.8,1.8,Indiana,Great Lakes
18,Michigan ..................,451516,441951,2.6,2.6,450755,454491,458866,2.6,2.6,2.6,Michigan,Great Lakes
19,Ohio ........................,583261,569274,3.4,3.4,578218,592046,593508,3.4,3.4,3.4,Ohio,Great Lakes
20,Wisconsin ...............,292891,286169,1.7,1.7,292079,295262,298053,1.7,1.7,1.7,Wisconsin,Great Lakes
21,Plains ........................,1131518,1100382,6.5,6.5,1128959,1144482,1152247,6.5,6.6,6.5,Plains,NaN
22,Iowa ........................,170613,163845,1.0,1.0,171071,173281,174256,1.0,1.0,1.0,Iowa,Plains
23,Kansas .....................,147075,143510,0.8,0.9,146670,148403,149718,0.8,0.9,0.8,Kansas,Plains
24,Minnesota ...............,316204,309764,1.8,1.8,312677,320114,322264,1.8,1.8,1.8,Minnesota,Plains
25,Missouri ..................,284462,277624,1.6,1.6,283834,286961,289431,1.6,1.6,1.6,Missouri,Plains
26,Nebraska ..................,112159,108006,0.6,0.6,113017,113402,114213,0.6,0.7,0.6,Nebraska,Plains
27,North Dakota ............,55136,53026,0.3,0.3,55649,56012,55858,0.3,0.3,0.3,North Dakota,Plains
28,South Dakota ............,45867,44607,0.3,0.3,46042,46310,46508,0.3,0.3,0.3,South Dakota,Plains
29,Southeast ..................,3695095,3611976,21.3,21.4,3678954,3728938,3760513,21.3,21.4,21.3,Southeast,NaN
30,Alabama ..................,199440,195091,1.2,1.2,197789,201541,203338,1.2,1.1,1.2,Alabama,Southeast
31,Arkansas ..................,121395,119172,0.7,0.7,121242,122108,123060,0.7,0.7,0.7,Arkansas,Southeast
32,Florida .....................,839944,820194,4.9,4.9,835308,846535,857738,4.8,4.8,4.8,Florida,Southeast
33,Georgia ..................,476483,464398,2.8,2.8,472890,482335,486308,2.7,2.7,2.8,Georgia,Southeast
34,Kentucky ..................,188602,184763,1.1,1.1,188758,189951,190936,1.1,1.1,1.1,Kentucky,Southeast
35,Louisiana ..................,251397,244942,1.5,1.4,250163,255368,255113,1.4,1.5,1.5,Louisiana,Southeast
36,Mississippi ...............,104851,103016,0.6,0.6,105377,105184,105829,0.6,0.6,0.6,Mississippi,Southeast
37,North Carolina .........,483126,474030,2.8,2.8,478625,488209,491637,2.8,2.8,2.8,North Carolina,Southeast
38,South Carolina .........,190304,184447,1.1,1.1,190658,191892,194220,1.1,1.1,1.1,South Carolina,Southeast
39,Tennessee ...............,300604,293594,1.7,1.7,299506,303206,306109,1.7,1.7,1.7,Tennessee,Southeast
40,Virginia .....................,463613,455777,2.7,2.7,463004,465780,469891,2.7,2.7,2.7,Virginia,Southeast
41,West Virginia ............,75337,72551,0.4,0.4,75635,76828,76333,0.4,0.4,0.4,West Virginia,Southeast
42,Southwest ..................,2208652,2158213,12.8,12.7,2197472,2241598,2237326,12.7,12.8,12.8,Southwest,NaN
43,Arizona .....................,284156,279983,1.6,1.6,281409,286590,288644,1.7,1.6,1.6,Arizona,Southwest
44,New Mexico ...............,92959,91326,0.5,0.5,92715,93817,93977,0.5,0.5,0.5,New Mexico,Southwest
45,Oklahoma ...............,183501,179582,1.1,1.0,182935,186687,184799,1.1,1.1,1.1,Oklahoma,Southwest
46,Texas .....................,1648036,1607322,9.5,9.5,1640414,1674503,1669905,9.5,9.5,9.6,Texas,Southwest
47,Rocky Mountain .........,600485,586172,3.5,3.5,597652,607987,610129,3.5,3.5,3.5,Rocky Mountain,NaN
48,Colorado ..................,306663,297603,1.8,1.8,304561,311506,312981,1.8,1.8,1.8,Colorado,Rocky Mountain
49,Idaho .....................,63952,62850,0.4,0.4,63818,64264,64878,0.4,0.4,0.4,Idaho,Rocky Mountain
50,Montana ..................,44269,43560,0.3,0.3,44273,44569,44674,0.3,0.3,0.3,Montana,Rocky Mountain
51,Utah ........................,141410,138911,0.8,0.8,140214,142686,143830,0.8,0.8,0.8,Utah,Rocky Mountain
52,Wyoming ..................,44190,43247,0.3,0.2,44786,44962,43765,0.3,0.3,0.3,Wyoming,Rocky Mountain
53,Far West .....................,3220878,3144765,18.6,18.7,3198105,3257772,3282871,18.6,18.6,18.6,Far West,NaN
54,Alaska .....................,57080,57371,0.3,0.3,58253,56996,55700,0.3,0.3,0.3,Alaska,Far West
55,California ..................,2311616,2254347,13.3,13.4,2292655,2341652,2357810,13.3,13.3,13.4,California,Far West
56,Hawaii .....................,77389,76067,0.4,0.4,77104,77758,78629,0.4,0.4,0.4,Hawaii,Far West
57,Nevada ..................,132064,130191,0.8,0.8,131057,133104,133905,0.8,0.8,0.8,Nevada,Far West
58,Oregon .....................,215677,208459,1.2,1.3,213520,218898,221829,1.2,1.2,1.3,Oregon,Far West
59,Washington ...............,427052,418329,2.5,2.5,425517,429364,434997,2.5,2.5,2.5,Washington,Far West

In [67]:
states = ["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Connecticut", "District of Columbia",
          "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", 
          "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", 
          "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", 
          "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
          "Texas", "Utah", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]
        
        # empty DataFrame to hold the new columns
GDPdf = pd.DataFrame()
        # count variable to increase the index by one after each row is added
count = 0
        
        # for loop to iterate through the years specified by the instance
for year in range(GDP_2014.yearStart, GDP_2014.yearEnd + 1):
            # for each state in that year, add in the following columns
    for state in states:
        GDPdf.loc[count, 'year'] = str(year)
        GDPdf.loc[count, 'state'] = state
        GDPdf.loc[count, 'current dollars'] = GDP_2014.dollars
        GDPdf.loc[count, 'GDP'] = GDP_2014.df.loc[GDP_2014.df['Cleaned Area'] == state, str(year)].item()
        GDPdf.loc[count, 'GDP_area'] = GDP_2014.df.loc[GDP_2014.df['Cleaned Area'] == state, 'Geo Loc'].item()
        count += 1

GDP_2014.df = GDPdf
GDP_2014.df

    year                 state current dollars        GDP        GDP_area
0   2014                Alaska            2014    57080.0        Far West
1   2014               Alabama            2014   199440.0       Southeast
2   2014              Arkansas            2014   121395.0       Southeast
3   2014               Arizona            2014   284156.0       Southwest
4   2014            California            2014  2311616.0        Far West
5   2014              Colorado            2014   306663.0  Rocky Mountain
6   2014           Connecticut            2014   253036.0     New England
7   2014  District of Columbia            2014   115473.0         Mideast
8   2014              Delaware            2014    62756.0         Mideast
9   2014               Florida            2014   839944.0       Southeast
10  2014               Georgia            2014   476483.0       Southeast
11  2014                Hawaii            2014    77389.0        Far West
12  2014                  Iowa            2014   170613.0          Plains
13  2014                 Idaho            2014    63952.0  Rocky Mountain
14  2014              Illinois            2014   745875.0     Great Lakes
15  2014               Indiana            2014   317840.0     Great Lakes
16  2014                Kansas            2014   147075.0          Plains
17  2014              Kentucky            2014   188602.0       Southeast
18  2014             Louisiana            2014   251397.0       Southeast
19  2014         Massachusetts            2014   459937.0     New England
20  2014              Maryland            2014   348631.0         Mideast
21  2014                 Maine            2014    55838.0     New England
22  2014              Michigan            2014   451516.0     Great Lakes
23  2014             Minnesota            2014   316204.0          Plains
24  2014              Missouri            2014   284462.0          Plains
25  2014           Mississippi            2014   104851.0       Southeast
26  2014               Montana            2014    44269.0  Rocky Mountain
27  2014        North Carolina            2014   483126.0       Southeast
28  2014          North Dakota            2014    55136.0          Plains
29  2014              Nebraska            2014   112159.0          Plains
30  2014         New Hampshire            2014    71552.0     New England
31  2014            New Jersey            2014   549099.0         Mideast
32  2014            New Mexico            2014    92959.0       Southwest
33  2014                Nevada            2014   132064.0        Far West
34  2014              New York            2014  1404518.0         Mideast
35  2014                  Ohio            2014   583261.0     Great Lakes
36  2014              Oklahoma            2014   183501.0       Southwest
37  2014                Oregon            2014   215677.0        Far West
38  2014          Pennsylvania            2014   662890.0         Mideast
39  2014          Rhode Island            2014    54960.0     New England
40  2014        South Carolina            2014   190304.0       Southeast
41  2014          South Dakota            2014    45867.0          Plains
42  2014             Tennessee            2014   300604.0       Southeast
43  2014                 Texas            2014  1648036.0       Southwest
44  2014                  Utah            2014   141410.0  Rocky Mountain
45  2014              Virginia            2014   463613.0       Southeast
46  2014               Vermont            2014    29613.0     New England
47  2014            Washington            2014   427052.0        Far West
48  2014             Wisconsin            2014   292891.0     Great Lakes
49  2014         West Virginia            2014    75337.0       Southeast
50  2014               Wyoming            2014    44190.0  Rocky Mountain

# 2015 - 2016 Quarterly Data

In [68]:
GDP15_16 = tabula.read_pdf('GDP2015-2016_quarterly.pdf', pages = 10, stream = True)
GDP15_16

[                         Unnamed: 0                            Unnamed: 1  \
 0                               NaN                                   NaN
 1                               NaN                                   NaN
 2                               NaN                                    Q1
 3                                 1                                   NaN
 4                     United States  ..........................17,671,025
 ..                              ...                                   ...
 59  California ....................                             2,444,063
 60   Hawaii .......................                                79,538
 61    Nevada ......................                               137,533
 62   Oregon .......................                               212,763
 63      Washington ................                               438,475

     Unnamed: 2  Unnamed: 3  Unnamed: 4                           Unnamed: 5  \
 0          NaN         NaN         NaN  Seasonally adjusted at annual rates
 1          NaN      2015.0         NaN                                  NaN
 2           Q2         NaN          Q3                                Q4 Q1
 3          NaN         NaN         NaN                                  NaN
 4   17,886,695         NaN  18,030,967                18,111,878 18,170,091
 ..         ...         ...         ...                                  ...
 59   2,485,470         NaN   2,505,638                  2,531,304 2,545,953
 60      80,302         NaN      80,907                        81,650 82,904
 61     140,194         NaN     142,952                      143,602 143,572
 62     214,687         NaN     218,660                      219,979 224,181
 63     444,522         NaN     449,627                      453,045 465,779

     Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9 Unnamed: 10 Unnamed: 11  \
 0          NaN         NaN         NaN         NaN         NaN         NaN
 1          NaN      2016.0         NaN         NaN         NaN         NaN
 2           Q2         NaN          Q3          Q4          Q1          Q2
 3          NaN         NaN         NaN         NaN         NaN         NaN
 4   18,337,791         NaN  18,561,915  18,755,370       100.0       100.0
 ..         ...         ...         ...         ...         ...         ...
 59   2,581,572         NaN   2,627,083   2,656,080        13.8        13.9
 60      83,548         NaN      84,325      84,889         0.5         NaN
 61     145,068         NaN     149,913     151,348         0.8         NaN
 62     225,947         NaN     227,316     229,837         1.2         NaN
 63     465,556         NaN     471,073     476,550         2.5         NaN

     Unnamed: 12 Unnamed: 13 Percent of the U.S. Unnamed: 14  Unnamed: 15  \
 0           NaN         NaN                 NaN         NaN          NaN
 1        2015.0         NaN                 NaN         NaN       2016.0
 2           NaN          Q3               Q4 Q1          Q2          NaN
 3           NaN         NaN                 NaN         NaN          NaN
 4           NaN       100.0         100.0 100.0       100.0          NaN
 ..          ...         ...                 ...         ...          ...
 59          NaN        13.9           14.0 14.0        14.1          NaN
 60          0.4         0.4             0.5 0.5         NaN          0.5
 61          0.8         0.8             0.8 0.8         NaN          0.8
 62          1.2         1.2             1.2 1.2         NaN          1.2
 63          2.5         2.5             2.5 2.6         NaN          2.5

    Unnamed: 16 Unnamed: 17
 0          NaN         NaN
 1          NaN         NaN
 2           Q3          Q4
 3          NaN         NaN
 4        100.0       100.0
 ..         ...         ...
 59        14.2        14.2
 60         0.5         0.5
 61         0.8         0.8
 62         1.2         1.2
 63         2.5         2.5

 [64 rows x 19 columns]]

In [69]:
GDP15_16 = pd.concat(GDP15_16, ignore_index = True)
GDP15_16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Percent of the U.S.,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,Seasonally adjusted at annual rates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2015.0,NaN,NaN,NaN,2016.0,NaN,NaN,NaN,NaN,2015.0,NaN,NaN,NaN,2016.0,NaN,NaN
2,NaN,Q1,Q2,NaN,Q3,Q4 Q1,Q2,NaN,Q3,Q4,Q1,Q2,NaN,Q3,Q4 Q1,Q2,NaN,Q3,Q4
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,United States,"..........................17,671,025","17,886,695",NaN,"18,030,967","18,111,878 18,170,091","18,337,791",NaN,"18,561,915","18,755,370",100.0,100.0,NaN,100.0,100.0 100.0,100.0,NaN,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,California ....................,"2,444,063","2,485,470",NaN,"2,505,638","2,531,304 2,545,953","2,581,572",NaN,"2,627,083","2,656,080",13.8,13.9,NaN,13.9,14.0 14.0,14.1,NaN,14.2,14.2
60,Hawaii .......................,"79,538","80,302",NaN,"80,907","81,650 82,904","83,548",NaN,"84,325","84,889",0.5,NaN,0.4,0.4,0.5 0.5,NaN,0.5,0.5,0.5
61,Nevada ......................,"137,533","140,194",NaN,"142,952","143,602 143,572","145,068",NaN,"149,913","151,348",0.8,NaN,0.8,0.8,0.8 0.8,NaN,0.8,0.8,0.8
62,Oregon .......................,"212,763","214,687",NaN,"218,660","219,979 224,181","225,947",NaN,"227,316","229,837",1.2,NaN,1.2,1.2,1.2 1.2,NaN,1.2,1.2,1.2
63,Washington ................,"438,475","444,522",NaN,"449,627","453,045 465,779","465,556",NaN,"471,073","476,550",2.5,NaN,2.5,2.5,2.5 2.6,NaN,2.5,2.5,2.5

In [70]:
GDP15_16 = GDP15_16.drop(GDP15_16.index[0:4]).reset_index(drop = True)

In [71]:
GDP15_16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Percent of the U.S.,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,United States,"..........................17,671,025","17,886,695",NaN,"18,030,967","18,111,878 18,170,091","18,337,791",NaN,"18,561,915","18,755,370",100.0,100.0,NaN,100.0,100.0 100.0,100.0,NaN,100.0,100.0
1,New England .....................,"941,945","959,027",NaN,"964,703","982,152 983,200","990,080",NaN,"1,002,400","1,012,104",5.3,NaN,5.4,5.4,5.4 5.4,NaN,5.4,5.4,5.4
2,Connecticut ................,"250,628","256,514",NaN,"257,895","260,185 260,604","262,341",NaN,"263,973","266,597",1.4,NaN,1.4,1.4,1.4 1.4,NaN,1.4,1.4,1.4
3,Maine ........................,"55,930","57,230",NaN,"57,716","58,453 58,540","59,224",NaN,"59,478","59,857",0.3,NaN,0.3,0.3,0.3 0.3,NaN,0.3,0.3,0.3
4,Massachusetts ............,"478,320","485,938",NaN,"487,509","500,634 500,418","503,357",NaN,"511,392","516,483",2.7,NaN,2.7,2.7,2.8 2.8,NaN,2.7,2.8,2.8
5,New Hampshire ...........,"72,395","73,810",NaN,"75,038","75,833 76,737","77,201",NaN,"78,329","79,155",0.4,NaN,0.4,0.4,0.4 0.4,NaN,0.4,0.4,0.4
6,Rhode Island ..............,"54,858","55,401",NaN,"55,884","56,457 56,087","57,099",NaN,"58,017","58,527",0.3,NaN,0.3,0.3,0.3 0.3,NaN,0.3,0.3,0.3
7,Vermont .....................,"29,815","30,135",NaN,"30,660","30,591 30,814","30,859",NaN,"31,211","31,483",0.2,NaN,0.2,0.2,0.2 0.2,NaN,0.2,0.2,0.2
8,Mideast .......................,"3,223,326","3,270,682",NaN,"3,302,756","3,301,626 3,329,683","3,358,622",NaN,"3,381,370","3,408,478",18.2,18.3,NaN,18.3,18.2 18.3,18.3,NaN,18.2,18.2
9,Delaware ....................,"68,216","68,898",NaN,"69,086","69,256 68,952","69,747",NaN,"71,080","71,769",0.4,NaN,0.4,0.4,0.4 0.4,NaN,0.4,0.4,0.4
10,District of Columbia .....,"120,100","121,210",NaN,"121,295","121,870 125,356","126,100",NaN,"127,208","128,597",0.7,NaN,0.7,0.7,0.7 0.7,NaN,0.7,0.7,0.7
11,Maryland ....................,"361,870","363,936",NaN,"366,991","372,169 371,205","376,578",NaN,"380,950","384,386",2.0,NaN,2.0,2.0,2.1 2.0,NaN,2.1,2.1,2.0
12,New Jersey ................,"547,279","565,951",NaN,"571,204","573,006 574,277","577,703",NaN,"583,804","588,706",3.1,NaN,3.2,3.2,3.2 3.2,NaN,3.2,3.1,3.1
13,New York ...................,"1,427,065","1,445,357",NaN,"1,462,516","1,447,505 1,481,479","1,489,457",NaN,"1,486,075","1,494,981",8.1,NaN,8.1,8.1,8.0 8.2,NaN,8.1,8.0,8.0
14,Pennsylvania ...............,"698,796","705,330",NaN,"711,663","717,821 708,415","719,037",NaN,"732,252","740,039",4.0,NaN,3.9,3.9,4.0 3.9,NaN,3.9,3.9,3.9
15,Great Lakes .................,"2,448,105","2,473,845",NaN,"2,499,169","2,519,159 2,521,077","2,541,207",NaN,"2,568,564","2,593,179",13.9,13.8,NaN,13.9,13.9 13.9,13.9,NaN,13.8,13.8
16,Illinois .......................,"763,309","766,689",NaN,"778,688","780,040 788,510","787,470",NaN,"791,450","798,999",4.3,NaN,4.3,4.3,4.3 4.3,NaN,4.3,4.3,4.3
17,Indiana ......................,"327,996","333,135",NaN,"334,536","337,786 337,423","339,900",NaN,"343,721","346,591",1.9,NaN,1.9,1.9,1.9 1.9,NaN,1.9,1.9,1.8
18,Michigan ....................,"460,714","468,784",NaN,"473,861","479,085 477,634","485,680",NaN,"490,342","495,300",2.6,NaN,2.6,2.6,2.6 2.6,NaN,2.6,2.6,2.6
19,Ohio ..........................,"599,820","605,409",NaN,"608,502","615,575 612,191","621,138",NaN,"631,347","638,185",3.4,NaN,3.4,3.4,3.4 3.4,NaN,3.4,3.4,3.4
20,Wisconsin ..................,"296,267","299,828",NaN,"303,582","306,673 305,319","307,019",NaN,"311,704","314,104",1.7,NaN,1.7,1.7,1.7 1.7,NaN,1.7,1.7,1.7
21,Plains ..........................,"1,147,993","1,161,066",NaN,"1,171,307","1,174,283 1,167,069","1,177,073",NaN,"1,190,606","1,199,789",6.5,NaN,6.5,6.5,6.5 6.4,NaN,6.4,6.4,6.4
22,Iowa ..........................,"172,410","175,098",NaN,"177,491","178,238 176,443","177,667",NaN,"179,944","181,007",1.0,NaN,1.0,1.0,1.0 1.0,NaN,1.0,1.0,1.0
23,Kansas ......................,"148,490","152,674",NaN,"153,489","152,725 151,833","152,822",NaN,"153,801","154,574",0.8,NaN,0.9,0.9,0.8 0.8,NaN,0.8,0.8,0.8
24,Minnesota ..................,"324,022","324,510",NaN,"326,873","331,926 329,008","331,958",NaN,"338,304","341,318",1.8,NaN,1.8,1.8,1.8 1.8,NaN,1.8,1.8,1.8
25,Missouri .....................,"288,381","292,194",NaN,"294,997","295,298 297,412","299,897",NaN,"301,824","304,431",1.6,NaN,1.6,1.6,1.6 1.6,NaN,1.6,1.6,1.6
26,Nebraska ...................,"111,411","113,604",NaN,"114,836","113,982 113,782","114,805",NaN,"116,025","116,769",0.6,NaN,0.6,0.6,0.6 0.6,NaN,0.6,0.6,0.6
27,North Dakota ...............,"57,402","56,560",NaN,"55,719","54,027 51,450","52,015",NaN,"52,096","52,796",0.3,NaN,0.3,0.3,0.3 0.3,NaN,0.3,0.3,0.3
28,South Dakota ..............,"45,878","46,426",NaN,"47,903","48,086 47,142","47,908",NaN,"48,612","48,893",0.3,NaN,0.3,0.3,0.3 0.3,NaN,0.3,0.3,0.3
29,Southeast .....................,"3,745,076","3,794,648",NaN,"3,840,495","3,872,660 3,881,685","3,914,726",NaN,"3,964,744","4,005,534",21.2,21.2,NaN,21.3,21.4 21.4,21.3,NaN,21.4,21.4
30,Alabama ....................,"196,820","199,677",NaN,"201,498","201,926 202,298","204,232",NaN,"205,307","207,608",1.1,NaN,1.1,1.1,1.1 1.1,NaN,1.1,1.1,1.1
31,Arkansas ...................,"117,064","118,592",NaN,"119,560","119,492 119,920","120,704",NaN,"120,683","121,448",0.7,NaN,0.7,0.7,0.7 0.7,NaN,0.7,0.7,0.6
32,Florida ........................,"866,212","875,944",NaN,"889,512","903,778 906,448","917,885",NaN,"935,927","947,007",4.9,NaN,4.9,4.9,5.0 5.0,NaN,5.0,5.0,5.0
33,Georgia .....................,"491,481","498,673",NaN,"505,437","510,496 520,453","520,479",NaN,"527,705","532,805",2.8,NaN,2.8,2.8,2.8 2.9,NaN,2.8,2.8,2.8
34,Kentucky ...................,"188,148","191,427",NaN,"193,072","194,942 191,394","195,685",NaN,"199,550","201,545",1.1,NaN,1.1,1.1,1.1 1.1,NaN,1.1,1.1,1.1
35,Louisiana ....................,"239,704","239,172",NaN,"238,492","234,932 233,388","234,573",NaN,"234,905","237,569",1.4,NaN,1.3,1.3,1.3 1.3,NaN,1.3,1.3,1.3
36,Mississippi .................,"104,325","105,635",NaN,"106,684","106,841 107,425","107,397",NaN,"107,683","108,215",0.6,NaN,0.6,0.6,0.6 0.6,NaN,0.6,0.6,0.6
37,North Carolina ..............,"490,176","496,874",NaN,"503,657","508,257 509,358","514,182",NaN,"521,265","526,809",2.8,NaN,2.8,2.8,2.8 2.8,NaN,2.8,2.8,2.8
38,South Carolina ............,"197,475","200,135",NaN,"203,438","206,274 206,715","209,032",NaN,"210,589","212,529",1.1,NaN,1.1,1.1,1.1 1.1,NaN,1.1,1.1,1.1
39,Tennessee ..................,"309,207","314,661",NaN,"319,867","322,900 323,864","326,262",NaN,"330,988","333,966",1.7,NaN,1.8,1.8,1.8 1.8,NaN,1.8,1.8,1.8
40,Virginia .......................,"471,999","479,776",NaN,"485,306","489,805 488,650","491,669",NaN,"496,244","500,833",2.7,NaN,2.7,2.7,2.7 2.7,NaN,2.7,2.7,2.7
41,West Virginia ..............,"72,465","74,081",NaN,"73,971","73,019 71,772","72,625",NaN,"73,898","75,199",0.4,NaN,0.4,0.4,0.4 0.4,NaN,0.4,0.4,0.4
42,Southwest ....................,"2,192,658","2,194,494",NaN,"2,185,231","2,163,126 2,155,605","2,178,893",NaN,"2,207,112","2,242,336",12.4,12.3,NaN,12.1,11.9 11.9,11.9,NaN,11.9,12.0
43,Arizona .......................,"287,190","290,463",NaN,"292,540","295,597 296,314","299,626",NaN,"306,764","309,103",1.6,NaN,1.6,1.6,1.6 1.6,NaN,1.6,1.7,1.6
44,New Mexico ................,"93,025","93,799",NaN,"93,713","92,383 91,496","92,931",NaN,"93,784","94,974",0.5,NaN,0.5,0.5,0.5 0.5,NaN,0.5,0.5,0.5
45,Oklahoma ...................,"191,872","189,264",NaN,"187,795","183,112 180,399","182,688",NaN,"183,061","185,602",1.1,NaN,1.1,1.0,1.0 1.0,NaN,1.0,1.0,1.0
46,Texas .........................,"1,620,571","1,620,968",NaN,"1,611,183","1,592,033 1,587,395","1,603,648",NaN,"1,623,503","1,652,657",9.2,NaN,9.1,8.9,8.8 8.7,NaN,8.7,8.7,8.8
47,Rocky Mountain ............,"605,555","613,147",NaN,"616,369","617,524 619,325","624,954",NaN,"636,667","643,739",3.4,NaN,3.4,3.4,3.4 3.4,NaN,3.4,3.4,3.4
48,Colorado ....................,"309,993","313,303",NaN,"314,546","315,475 316,481","320,634",NaN,"327,333","330,319",1.8,NaN,1.8,1.7,1.7 1.7,NaN,1.7,1.8,1.8
49,Idaho ..........................,"64,856","65,342",NaN,"65,884","65,760 66,010","66,927",NaN,"67,714","68,450",0.4,NaN,0.4,0.4,0.4 0.4,NaN,0.4,0.4,0.4
50,Montana .....................,"45,186","46,207",NaN,"46,119","45,868 45,789","45,642",NaN,"46,041","46,506",0.3,NaN,0.3,0.3,0.3 0.3,NaN,0.2,0.2,0.2
51,Utah ..........................,"145,982","148,314",NaN,"150,215","151,884 153,422","154,182",NaN,"157,802","160,002",0.8,NaN,0.8,0.8,0.8 0.8,NaN,0.8,0.9,0.9
52,Wyoming ....................,"39,538","39,981",NaN,"39,604","38,537 37,622","37,569",NaN,"37,777","38,463",0.2,NaN,0.2,0.2,0.2 0.2,NaN,0.2,0.2,0.2
53,Far West ......................,"3,366,368","3,419,789",NaN,"3,450,939","3,481,350 3,512,447","3,552,236",NaN,"3,610,452","3,650,211",19.1,19.1,NaN,19.1,19.2 19.3,19.4,NaN,19.5,19.5
54,Alaska ........................,"53,997","54,615",NaN,"53,155","51,770 50,059","50,545",NaN,"50,742","51,506",0.3,NaN,0.3,0.3,0.3 0.3,NaN,0.3,0.3,0.3
55,California ....................,"2,444,063","2,485,470",NaN,"2,505,638","2,531,304 2,545,953","2,581,572",NaN,"2,627,083","2,656,080",13.8,13.9,NaN,13.9,14.0 14.0,14.1,NaN,14.2,14.2
56,Hawaii .......................,"79,538","80,302",NaN,"80,907","81,650 82,904","83,548",NaN,"84,325","84,889",0.5,NaN,0.4,0.4,0.5 0.5,NaN,0.5,0.5,0.5
57,Nevada ......................,"137,533","140,194",NaN,"142,952","143,602 143,572","145,068",NaN,"149,913","151,348",0.8,NaN,0.8,0.8,0.8 0.8,NaN,0.8,0.8,0.8
58,Oregon .......................,"212,763","214,687",NaN,"218,660","219,979 224,181","225,947",NaN,"227,316","229,837",1.2,NaN,1.2,1.2,1.2 1.2,NaN,1.2,1.2,1.2
59,Washington ................,"438,475","444,522",NaN,"449,627","453,045 465,779","465,556",NaN,"471,073","476,550",2.5,NaN,2.5,2.5,2.5 2.6,NaN,2.5,2.5,2.5

In [72]:
GDP15_16 = GDP15_16.drop(['Unnamed: 3', 'Unnamed: 7','Unnamed: 11', 'Unnamed: 14'], axis = 1)
GDP15_16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 12,Unnamed: 13,Percent of the U.S.,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,United States,"..........................17,671,025","17,886,695","18,030,967","18,111,878 18,170,091","18,337,791","18,561,915","18,755,370",100.0,NaN,100.0,100.0 100.0,NaN,100.0,100.0
1,New England .....................,"941,945","959,027","964,703","982,152 983,200","990,080","1,002,400","1,012,104",5.3,5.4,5.4,5.4 5.4,5.4,5.4,5.4
2,Connecticut ................,"250,628","256,514","257,895","260,185 260,604","262,341","263,973","266,597",1.4,1.4,1.4,1.4 1.4,1.4,1.4,1.4
3,Maine ........................,"55,930","57,230","57,716","58,453 58,540","59,224","59,478","59,857",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3
4,Massachusetts ............,"478,320","485,938","487,509","500,634 500,418","503,357","511,392","516,483",2.7,2.7,2.7,2.8 2.8,2.7,2.8,2.8
5,New Hampshire ...........,"72,395","73,810","75,038","75,833 76,737","77,201","78,329","79,155",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4
6,Rhode Island ..............,"54,858","55,401","55,884","56,457 56,087","57,099","58,017","58,527",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3
7,Vermont .....................,"29,815","30,135","30,660","30,591 30,814","30,859","31,211","31,483",0.2,0.2,0.2,0.2 0.2,0.2,0.2,0.2
8,Mideast .......................,"3,223,326","3,270,682","3,302,756","3,301,626 3,329,683","3,358,622","3,381,370","3,408,478",18.2,NaN,18.3,18.2 18.3,NaN,18.2,18.2
9,Delaware ....................,"68,216","68,898","69,086","69,256 68,952","69,747","71,080","71,769",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4
10,District of Columbia .....,"120,100","121,210","121,295","121,870 125,356","126,100","127,208","128,597",0.7,0.7,0.7,0.7 0.7,0.7,0.7,0.7
11,Maryland ....................,"361,870","363,936","366,991","372,169 371,205","376,578","380,950","384,386",2.0,2.0,2.0,2.1 2.0,2.1,2.1,2.0
12,New Jersey ................,"547,279","565,951","571,204","573,006 574,277","577,703","583,804","588,706",3.1,3.2,3.2,3.2 3.2,3.2,3.1,3.1
13,New York ...................,"1,427,065","1,445,357","1,462,516","1,447,505 1,481,479","1,489,457","1,486,075","1,494,981",8.1,8.1,8.1,8.0 8.2,8.1,8.0,8.0
14,Pennsylvania ...............,"698,796","705,330","711,663","717,821 708,415","719,037","732,252","740,039",4.0,3.9,3.9,4.0 3.9,3.9,3.9,3.9
15,Great Lakes .................,"2,448,105","2,473,845","2,499,169","2,519,159 2,521,077","2,541,207","2,568,564","2,593,179",13.9,NaN,13.9,13.9 13.9,NaN,13.8,13.8
16,Illinois .......................,"763,309","766,689","778,688","780,040 788,510","787,470","791,450","798,999",4.3,4.3,4.3,4.3 4.3,4.3,4.3,4.3
17,Indiana ......................,"327,996","333,135","334,536","337,786 337,423","339,900","343,721","346,591",1.9,1.9,1.9,1.9 1.9,1.9,1.9,1.8
18,Michigan ....................,"460,714","468,784","473,861","479,085 477,634","485,680","490,342","495,300",2.6,2.6,2.6,2.6 2.6,2.6,2.6,2.6
19,Ohio ..........................,"599,820","605,409","608,502","615,575 612,191","621,138","631,347","638,185",3.4,3.4,3.4,3.4 3.4,3.4,3.4,3.4
20,Wisconsin ..................,"296,267","299,828","303,582","306,673 305,319","307,019","311,704","314,104",1.7,1.7,1.7,1.7 1.7,1.7,1.7,1.7
21,Plains ..........................,"1,147,993","1,161,066","1,171,307","1,174,283 1,167,069","1,177,073","1,190,606","1,199,789",6.5,6.5,6.5,6.5 6.4,6.4,6.4,6.4
22,Iowa ..........................,"172,410","175,098","177,491","178,238 176,443","177,667","179,944","181,007",1.0,1.0,1.0,1.0 1.0,1.0,1.0,1.0
23,Kansas ......................,"148,490","152,674","153,489","152,725 151,833","152,822","153,801","154,574",0.8,0.9,0.9,0.8 0.8,0.8,0.8,0.8
24,Minnesota ..................,"324,022","324,510","326,873","331,926 329,008","331,958","338,304","341,318",1.8,1.8,1.8,1.8 1.8,1.8,1.8,1.8
25,Missouri .....................,"288,381","292,194","294,997","295,298 297,412","299,897","301,824","304,431",1.6,1.6,1.6,1.6 1.6,1.6,1.6,1.6
26,Nebraska ...................,"111,411","113,604","114,836","113,982 113,782","114,805","116,025","116,769",0.6,0.6,0.6,0.6 0.6,0.6,0.6,0.6
27,North Dakota ...............,"57,402","56,560","55,719","54,027 51,450","52,015","52,096","52,796",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3
28,South Dakota ..............,"45,878","46,426","47,903","48,086 47,142","47,908","48,612","48,893",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3
29,Southeast .....................,"3,745,076","3,794,648","3,840,495","3,872,660 3,881,685","3,914,726","3,964,744","4,005,534",21.2,NaN,21.3,21.4 21.4,NaN,21.4,21.4
30,Alabama ....................,"196,820","199,677","201,498","201,926 202,298","204,232","205,307","207,608",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1
31,Arkansas ...................,"117,064","118,592","119,560","119,492 119,920","120,704","120,683","121,448",0.7,0.7,0.7,0.7 0.7,0.7,0.7,0.6
32,Florida ........................,"866,212","875,944","889,512","903,778 906,448","917,885","935,927","947,007",4.9,4.9,4.9,5.0 5.0,5.0,5.0,5.0
33,Georgia .....................,"491,481","498,673","505,437","510,496 520,453","520,479","527,705","532,805",2.8,2.8,2.8,2.8 2.9,2.8,2.8,2.8
34,Kentucky ...................,"188,148","191,427","193,072","194,942 191,394","195,685","199,550","201,545",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1
35,Louisiana ....................,"239,704","239,172","238,492","234,932 233,388","234,573","234,905","237,569",1.4,1.3,1.3,1.3 1.3,1.3,1.3,1.3
36,Mississippi .................,"104,325","105,635","106,684","106,841 107,425","107,397","107,683","108,215",0.6,0.6,0.6,0.6 0.6,0.6,0.6,0.6
37,North Carolina ..............,"490,176","496,874","503,657","508,257 509,358","514,182","521,265","526,809",2.8,2.8,2.8,2.8 2.8,2.8,2.8,2.8
38,South Carolina ............,"197,475","200,135","203,438","206,274 206,715","209,032","210,589","212,529",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1
39,Tennessee ..................,"309,207","314,661","319,867","322,900 323,864","326,262","330,988","333,966",1.7,1.8,1.8,1.8 1.8,1.8,1.8,1.8
40,Virginia .......................,"471,999","479,776","485,306","489,805 488,650","491,669","496,244","500,833",2.7,2.7,2.7,2.7 2.7,2.7,2.7,2.7
41,West Virginia ..............,"72,465","74,081","73,971","73,019 71,772","72,625","73,898","75,199",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4
42,Southwest ....................,"2,192,658","2,194,494","2,185,231","2,163,126 2,155,605","2,178,893","2,207,112","2,242,336",12.4,NaN,12.1,11.9 11.9,NaN,11.9,12.0
43,Arizona .......................,"287,190","290,463","292,540","295,597 296,314","299,626","306,764","309,103",1.6,1.6,1.6,1.6 1.6,1.6,1.7,1.6
44,New Mexico ................,"93,025","93,799","93,713","92,383 91,496","92,931","93,784","94,974",0.5,0.5,0.5,0.5 0.5,0.5,0.5,0.5
45,Oklahoma ...................,"191,872","189,264","187,795","183,112 180,399","182,688","183,061","185,602",1.1,1.1,1.0,1.0 1.0,1.0,1.0,1.0
46,Texas .........................,"1,620,571","1,620,968","1,611,183","1,592,033 1,587,395","1,603,648","1,623,503","1,652,657",9.2,9.1,8.9,8.8 8.7,8.7,8.7,8.8
47,Rocky Mountain ............,"605,555","613,147","616,369","617,524 619,325","624,954","636,667","643,739",3.4,3.4,3.4,3.4 3.4,3.4,3.4,3.4
48,Colorado ....................,"309,993","313,303","314,546","315,475 316,481","320,634","327,333","330,319",1.8,1.8,1.7,1.7 1.7,1.7,1.8,1.8
49,Idaho ..........................,"64,856","65,342","65,884","65,760 66,010","66,927","67,714","68,450",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4
50,Montana .....................,"45,186","46,207","46,119","45,868 45,789","45,642","46,041","46,506",0.3,0.3,0.3,0.3 0.3,0.2,0.2,0.2
51,Utah ..........................,"145,982","148,314","150,215","151,884 153,422","154,182","157,802","160,002",0.8,0.8,0.8,0.8 0.8,0.8,0.9,0.9
52,Wyoming ....................,"39,538","39,981","39,604","38,537 37,622","37,569","37,777","38,463",0.2,0.2,0.2,0.2 0.2,0.2,0.2,0.2
53,Far West ......................,"3,366,368","3,419,789","3,450,939","3,481,350 3,512,447","3,552,236","3,610,452","3,650,211",19.1,NaN,19.1,19.2 19.3,NaN,19.5,19.5
54,Alaska ........................,"53,997","54,615","53,155","51,770 50,059","50,545","50,742","51,506",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3
55,California ....................,"2,444,063","2,485,470","2,505,638","2,531,304 2,545,953","2,581,572","2,627,083","2,656,080",13.8,NaN,13.9,14.0 14.0,NaN,14.2,14.2
56,Hawaii .......................,"79,538","80,302","80,907","81,650 82,904","83,548","84,325","84,889",0.5,0.4,0.4,0.5 0.5,0.5,0.5,0.5
57,Nevada ......................,"137,533","140,194","142,952","143,602 143,572","145,068","149,913","151,348",0.8,0.8,0.8,0.8 0.8,0.8,0.8,0.8
58,Oregon .......................,"212,763","214,687","218,660","219,979 224,181","225,947","227,316","229,837",1.2,1.2,1.2,1.2 1.2,1.2,1.2,1.2
59,Washington ................,"438,475","444,522","449,627","453,045 465,779","465,556","471,073","476,550",2.5,2.5,2.5,2.5 2.6,2.5,2.5,2.5

In [73]:
for i in GDP15_16['Unnamed: 5'].index:
    splitList = GDP15_16.loc[i, 'Unnamed: 5'].split(" ")
    GDP15_16.loc[i, '2015 Q4'] = splitList[0]
    GDP15_16.loc[i, '2016 Q1'] = splitList[1]
GDP15_16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 12,Unnamed: 13,Percent of the U.S.,Unnamed: 15,Unnamed: 16,Unnamed: 17,2015 Q4,2016 Q1
0,United States,"..........................17,671,025","17,886,695","18,030,967","18,111,878 18,170,091","18,337,791","18,561,915","18,755,370",100.0,NaN,100.0,100.0 100.0,NaN,100.0,100.0,"18,111,878","18,170,091"
1,New England .....................,"941,945","959,027","964,703","982,152 983,200","990,080","1,002,400","1,012,104",5.3,5.4,5.4,5.4 5.4,5.4,5.4,5.4,"982,152","983,200"
2,Connecticut ................,"250,628","256,514","257,895","260,185 260,604","262,341","263,973","266,597",1.4,1.4,1.4,1.4 1.4,1.4,1.4,1.4,"260,185","260,604"
3,Maine ........................,"55,930","57,230","57,716","58,453 58,540","59,224","59,478","59,857",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"58,453","58,540"
4,Massachusetts ............,"478,320","485,938","487,509","500,634 500,418","503,357","511,392","516,483",2.7,2.7,2.7,2.8 2.8,2.7,2.8,2.8,"500,634","500,418"
5,New Hampshire ...........,"72,395","73,810","75,038","75,833 76,737","77,201","78,329","79,155",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"75,833","76,737"
6,Rhode Island ..............,"54,858","55,401","55,884","56,457 56,087","57,099","58,017","58,527",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"56,457","56,087"
7,Vermont .....................,"29,815","30,135","30,660","30,591 30,814","30,859","31,211","31,483",0.2,0.2,0.2,0.2 0.2,0.2,0.2,0.2,"30,591","30,814"
8,Mideast .......................,"3,223,326","3,270,682","3,302,756","3,301,626 3,329,683","3,358,622","3,381,370","3,408,478",18.2,NaN,18.3,18.2 18.3,NaN,18.2,18.2,"3,301,626","3,329,683"
9,Delaware ....................,"68,216","68,898","69,086","69,256 68,952","69,747","71,080","71,769",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"69,256","68,952"
10,District of Columbia .....,"120,100","121,210","121,295","121,870 125,356","126,100","127,208","128,597",0.7,0.7,0.7,0.7 0.7,0.7,0.7,0.7,"121,870","125,356"
11,Maryland ....................,"361,870","363,936","366,991","372,169 371,205","376,578","380,950","384,386",2.0,2.0,2.0,2.1 2.0,2.1,2.1,2.0,"372,169","371,205"
12,New Jersey ................,"547,279","565,951","571,204","573,006 574,277","577,703","583,804","588,706",3.1,3.2,3.2,3.2 3.2,3.2,3.1,3.1,"573,006","574,277"
13,New York ...................,"1,427,065","1,445,357","1,462,516","1,447,505 1,481,479","1,489,457","1,486,075","1,494,981",8.1,8.1,8.1,8.0 8.2,8.1,8.0,8.0,"1,447,505","1,481,479"
14,Pennsylvania ...............,"698,796","705,330","711,663","717,821 708,415","719,037","732,252","740,039",4.0,3.9,3.9,4.0 3.9,3.9,3.9,3.9,"717,821","708,415"
15,Great Lakes .................,"2,448,105","2,473,845","2,499,169","2,519,159 2,521,077","2,541,207","2,568,564","2,593,179",13.9,NaN,13.9,13.9 13.9,NaN,13.8,13.8,"2,519,159","2,521,077"
16,Illinois .......................,"763,309","766,689","778,688","780,040 788,510","787,470","791,450","798,999",4.3,4.3,4.3,4.3 4.3,4.3,4.3,4.3,"780,040","788,510"
17,Indiana ......................,"327,996","333,135","334,536","337,786 337,423","339,900","343,721","346,591",1.9,1.9,1.9,1.9 1.9,1.9,1.9,1.8,"337,786","337,423"
18,Michigan ....................,"460,714","468,784","473,861","479,085 477,634","485,680","490,342","495,300",2.6,2.6,2.6,2.6 2.6,2.6,2.6,2.6,"479,085","477,634"
19,Ohio ..........................,"599,820","605,409","608,502","615,575 612,191","621,138","631,347","638,185",3.4,3.4,3.4,3.4 3.4,3.4,3.4,3.4,"615,575","612,191"
20,Wisconsin ..................,"296,267","299,828","303,582","306,673 305,319","307,019","311,704","314,104",1.7,1.7,1.7,1.7 1.7,1.7,1.7,1.7,"306,673","305,319"
21,Plains ..........................,"1,147,993","1,161,066","1,171,307","1,174,283 1,167,069","1,177,073","1,190,606","1,199,789",6.5,6.5,6.5,6.5 6.4,6.4,6.4,6.4,"1,174,283","1,167,069"
22,Iowa ..........................,"172,410","175,098","177,491","178,238 176,443","177,667","179,944","181,007",1.0,1.0,1.0,1.0 1.0,1.0,1.0,1.0,"178,238","176,443"
23,Kansas ......................,"148,490","152,674","153,489","152,725 151,833","152,822","153,801","154,574",0.8,0.9,0.9,0.8 0.8,0.8,0.8,0.8,"152,725","151,833"
24,Minnesota ..................,"324,022","324,510","326,873","331,926 329,008","331,958","338,304","341,318",1.8,1.8,1.8,1.8 1.8,1.8,1.8,1.8,"331,926","329,008"
25,Missouri .....................,"288,381","292,194","294,997","295,298 297,412","299,897","301,824","304,431",1.6,1.6,1.6,1.6 1.6,1.6,1.6,1.6,"295,298","297,412"
26,Nebraska ...................,"111,411","113,604","114,836","113,982 113,782","114,805","116,025","116,769",0.6,0.6,0.6,0.6 0.6,0.6,0.6,0.6,"113,982","113,782"
27,North Dakota ...............,"57,402","56,560","55,719","54,027 51,450","52,015","52,096","52,796",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"54,027","51,450"
28,South Dakota ..............,"45,878","46,426","47,903","48,086 47,142","47,908","48,612","48,893",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"48,086","47,142"
29,Southeast .....................,"3,745,076","3,794,648","3,840,495","3,872,660 3,881,685","3,914,726","3,964,744","4,005,534",21.2,NaN,21.3,21.4 21.4,NaN,21.4,21.4,"3,872,660","3,881,685"
30,Alabama ....................,"196,820","199,677","201,498","201,926 202,298","204,232","205,307","207,608",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1,"201,926","202,298"
31,Arkansas ...................,"117,064","118,592","119,560","119,492 119,920","120,704","120,683","121,448",0.7,0.7,0.7,0.7 0.7,0.7,0.7,0.6,"119,492","119,920"
32,Florida ........................,"866,212","875,944","889,512","903,778 906,448","917,885","935,927","947,007",4.9,4.9,4.9,5.0 5.0,5.0,5.0,5.0,"903,778","906,448"
33,Georgia .....................,"491,481","498,673","505,437","510,496 520,453","520,479","527,705","532,805",2.8,2.8,2.8,2.8 2.9,2.8,2.8,2.8,"510,496","520,453"
34,Kentucky ...................,"188,148","191,427","193,072","194,942 191,394","195,685","199,550","201,545",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1,"194,942","191,394"
35,Louisiana ....................,"239,704","239,172","238,492","234,932 233,388","234,573","234,905","237,569",1.4,1.3,1.3,1.3 1.3,1.3,1.3,1.3,"234,932","233,388"
36,Mississippi .................,"104,325","105,635","106,684","106,841 107,425","107,397","107,683","108,215",0.6,0.6,0.6,0.6 0.6,0.6,0.6,0.6,"106,841","107,425"
37,North Carolina ..............,"490,176","496,874","503,657","508,257 509,358","514,182","521,265","526,809",2.8,2.8,2.8,2.8 2.8,2.8,2.8,2.8,"508,257","509,358"
38,South Carolina ............,"197,475","200,135","203,438","206,274 206,715","209,032","210,589","212,529",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1,"206,274","206,715"
39,Tennessee ..................,"309,207","314,661","319,867","322,900 323,864","326,262","330,988","333,966",1.7,1.8,1.8,1.8 1.8,1.8,1.8,1.8,"322,900","323,864"
40,Virginia .......................,"471,999","479,776","485,306","489,805 488,650","491,669","496,244","500,833",2.7,2.7,2.7,2.7 2.7,2.7,2.7,2.7,"489,805","488,650"
41,West Virginia ..............,"72,465","74,081","73,971","73,019 71,772","72,625","73,898","75,199",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"73,019","71,772"
42,Southwest ....................,"2,192,658","2,194,494","2,185,231","2,163,126 2,155,605","2,178,893","2,207,112","2,242,336",12.4,NaN,12.1,11.9 11.9,NaN,11.9,12.0,"2,163,126","2,155,605"
43,Arizona .......................,"287,190","290,463","292,540","295,597 296,314","299,626","306,764","309,103",1.6,1.6,1.6,1.6 1.6,1.6,1.7,1.6,"295,597","296,314"
44,New Mexico ................,"93,025","93,799","93,713","92,383 91,496","92,931","93,784","94,974",0.5,0.5,0.5,0.5 0.5,0.5,0.5,0.5,"92,383","91,496"
45,Oklahoma ...................,"191,872","189,264","187,795","183,112 180,399","182,688","183,061","185,602",1.1,1.1,1.0,1.0 1.0,1.0,1.0,1.0,"183,112","180,399"
46,Texas .........................,"1,620,571","1,620,968","1,611,183","1,592,033 1,587,395","1,603,648","1,623,503","1,652,657",9.2,9.1,8.9,8.8 8.7,8.7,8.7,8.8,"1,592,033","1,587,395"
47,Rocky Mountain ............,"605,555","613,147","616,369","617,524 619,325","624,954","636,667","643,739",3.4,3.4,3.4,3.4 3.4,3.4,3.4,3.4,"617,524","619,325"
48,Colorado ....................,"309,993","313,303","314,546","315,475 316,481","320,634","327,333","330,319",1.8,1.8,1.7,1.7 1.7,1.7,1.8,1.8,"315,475","316,481"
49,Idaho ..........................,"64,856","65,342","65,884","65,760 66,010","66,927","67,714","68,450",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"65,760","66,010"
50,Montana .....................,"45,186","46,207","46,119","45,868 45,789","45,642","46,041","46,506",0.3,0.3,0.3,0.3 0.3,0.2,0.2,0.2,"45,868","45,789"
51,Utah ..........................,"145,982","148,314","150,215","151,884 153,422","154,182","157,802","160,002",0.8,0.8,0.8,0.8 0.8,0.8,0.9,0.9,"151,884","153,422"
52,Wyoming ....................,"39,538","39,981","39,604","38,537 37,622","37,569","37,777","38,463",0.2,0.2,0.2,0.2 0.2,0.2,0.2,0.2,"38,537","37,622"
53,Far West ......................,"3,366,368","3,419,789","3,450,939","3,481,350 3,512,447","3,552,236","3,610,452","3,650,211",19.1,NaN,19.1,19.2 19.3,NaN,19.5,19.5,"3,481,350","3,512,447"
54,Alaska ........................,"53,997","54,615","53,155","51,770 50,059","50,545","50,742","51,506",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"51,770","50,059"
55,California ....................,"2,444,063","2,485,470","2,505,638","2,531,304 2,545,953","2,581,572","2,627,083","2,656,080",13.8,NaN,13.9,14.0 14.0,NaN,14.2,14.2,"2,531,304","2,545,953"
56,Hawaii .......................,"79,538","80,302","80,907","81,650 82,904","83,548","84,325","84,889",0.5,0.4,0.4,0.5 0.5,0.5,0.5,0.5,"81,650","82,904"
57,Nevada ......................,"137,533","140,194","142,952","143,602 143,572","145,068","149,913","151,348",0.8,0.8,0.8,0.8 0.8,0.8,0.8,0.8,"143,602","143,572"
58,Oregon .......................,"212,763","214,687","218,660","219,979 224,181","225,947","227,316","229,837",1.2,1.2,1.2,1.2 1.2,1.2,1.2,1.2,"219,979","224,181"
59,Washington ................,"438,475","444,522","449,627","453,045 465,779","465,556","471,073","476,550",2.5,2.5,2.5,2.5 2.6,2.5,2.5,2.5,"453,045","465,779"

In [74]:
for i in GDP15_16['Percent of the U.S.'].index:
    splitList = GDP15_16.loc[i, 'Percent of the U.S.'].split(" ")
    GDP15_16.loc[i, '2015 Q4 %'] = splitList[0]
    GDP15_16.loc[i, '2016 Q1 %'] = splitList[1]
GDP15_16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 12,Unnamed: 13,Percent of the U.S.,Unnamed: 15,Unnamed: 16,Unnamed: 17,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %
0,United States,"..........................17,671,025","17,886,695","18,030,967","18,111,878 18,170,091","18,337,791","18,561,915","18,755,370",100.0,NaN,100.0,100.0 100.0,NaN,100.0,100.0,"18,111,878","18,170,091",100.0,100.0
1,New England .....................,"941,945","959,027","964,703","982,152 983,200","990,080","1,002,400","1,012,104",5.3,5.4,5.4,5.4 5.4,5.4,5.4,5.4,"982,152","983,200",5.4,5.4
2,Connecticut ................,"250,628","256,514","257,895","260,185 260,604","262,341","263,973","266,597",1.4,1.4,1.4,1.4 1.4,1.4,1.4,1.4,"260,185","260,604",1.4,1.4
3,Maine ........................,"55,930","57,230","57,716","58,453 58,540","59,224","59,478","59,857",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"58,453","58,540",0.3,0.3
4,Massachusetts ............,"478,320","485,938","487,509","500,634 500,418","503,357","511,392","516,483",2.7,2.7,2.7,2.8 2.8,2.7,2.8,2.8,"500,634","500,418",2.8,2.8
5,New Hampshire ...........,"72,395","73,810","75,038","75,833 76,737","77,201","78,329","79,155",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"75,833","76,737",0.4,0.4
6,Rhode Island ..............,"54,858","55,401","55,884","56,457 56,087","57,099","58,017","58,527",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"56,457","56,087",0.3,0.3
7,Vermont .....................,"29,815","30,135","30,660","30,591 30,814","30,859","31,211","31,483",0.2,0.2,0.2,0.2 0.2,0.2,0.2,0.2,"30,591","30,814",0.2,0.2
8,Mideast .......................,"3,223,326","3,270,682","3,302,756","3,301,626 3,329,683","3,358,622","3,381,370","3,408,478",18.2,NaN,18.3,18.2 18.3,NaN,18.2,18.2,"3,301,626","3,329,683",18.2,18.3
9,Delaware ....................,"68,216","68,898","69,086","69,256 68,952","69,747","71,080","71,769",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"69,256","68,952",0.4,0.4
10,District of Columbia .....,"120,100","121,210","121,295","121,870 125,356","126,100","127,208","128,597",0.7,0.7,0.7,0.7 0.7,0.7,0.7,0.7,"121,870","125,356",0.7,0.7
11,Maryland ....................,"361,870","363,936","366,991","372,169 371,205","376,578","380,950","384,386",2.0,2.0,2.0,2.1 2.0,2.1,2.1,2.0,"372,169","371,205",2.1,2.0
12,New Jersey ................,"547,279","565,951","571,204","573,006 574,277","577,703","583,804","588,706",3.1,3.2,3.2,3.2 3.2,3.2,3.1,3.1,"573,006","574,277",3.2,3.2
13,New York ...................,"1,427,065","1,445,357","1,462,516","1,447,505 1,481,479","1,489,457","1,486,075","1,494,981",8.1,8.1,8.1,8.0 8.2,8.1,8.0,8.0,"1,447,505","1,481,479",8.0,8.2
14,Pennsylvania ...............,"698,796","705,330","711,663","717,821 708,415","719,037","732,252","740,039",4.0,3.9,3.9,4.0 3.9,3.9,3.9,3.9,"717,821","708,415",4.0,3.9
15,Great Lakes .................,"2,448,105","2,473,845","2,499,169","2,519,159 2,521,077","2,541,207","2,568,564","2,593,179",13.9,NaN,13.9,13.9 13.9,NaN,13.8,13.8,"2,519,159","2,521,077",13.9,13.9
16,Illinois .......................,"763,309","766,689","778,688","780,040 788,510","787,470","791,450","798,999",4.3,4.3,4.3,4.3 4.3,4.3,4.3,4.3,"780,040","788,510",4.3,4.3
17,Indiana ......................,"327,996","333,135","334,536","337,786 337,423","339,900","343,721","346,591",1.9,1.9,1.9,1.9 1.9,1.9,1.9,1.8,"337,786","337,423",1.9,1.9
18,Michigan ....................,"460,714","468,784","473,861","479,085 477,634","485,680","490,342","495,300",2.6,2.6,2.6,2.6 2.6,2.6,2.6,2.6,"479,085","477,634",2.6,2.6
19,Ohio ..........................,"599,820","605,409","608,502","615,575 612,191","621,138","631,347","638,185",3.4,3.4,3.4,3.4 3.4,3.4,3.4,3.4,"615,575","612,191",3.4,3.4
20,Wisconsin ..................,"296,267","299,828","303,582","306,673 305,319","307,019","311,704","314,104",1.7,1.7,1.7,1.7 1.7,1.7,1.7,1.7,"306,673","305,319",1.7,1.7
21,Plains ..........................,"1,147,993","1,161,066","1,171,307","1,174,283 1,167,069","1,177,073","1,190,606","1,199,789",6.5,6.5,6.5,6.5 6.4,6.4,6.4,6.4,"1,174,283","1,167,069",6.5,6.4
22,Iowa ..........................,"172,410","175,098","177,491","178,238 176,443","177,667","179,944","181,007",1.0,1.0,1.0,1.0 1.0,1.0,1.0,1.0,"178,238","176,443",1.0,1.0
23,Kansas ......................,"148,490","152,674","153,489","152,725 151,833","152,822","153,801","154,574",0.8,0.9,0.9,0.8 0.8,0.8,0.8,0.8,"152,725","151,833",0.8,0.8
24,Minnesota ..................,"324,022","324,510","326,873","331,926 329,008","331,958","338,304","341,318",1.8,1.8,1.8,1.8 1.8,1.8,1.8,1.8,"331,926","329,008",1.8,1.8
25,Missouri .....................,"288,381","292,194","294,997","295,298 297,412","299,897","301,824","304,431",1.6,1.6,1.6,1.6 1.6,1.6,1.6,1.6,"295,298","297,412",1.6,1.6
26,Nebraska ...................,"111,411","113,604","114,836","113,982 113,782","114,805","116,025","116,769",0.6,0.6,0.6,0.6 0.6,0.6,0.6,0.6,"113,982","113,782",0.6,0.6
27,North Dakota ...............,"57,402","56,560","55,719","54,027 51,450","52,015","52,096","52,796",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"54,027","51,450",0.3,0.3
28,South Dakota ..............,"45,878","46,426","47,903","48,086 47,142","47,908","48,612","48,893",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"48,086","47,142",0.3,0.3
29,Southeast .....................,"3,745,076","3,794,648","3,840,495","3,872,660 3,881,685","3,914,726","3,964,744","4,005,534",21.2,NaN,21.3,21.4 21.4,NaN,21.4,21.4,"3,872,660","3,881,685",21.4,21.4
30,Alabama ....................,"196,820","199,677","201,498","201,926 202,298","204,232","205,307","207,608",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1,"201,926","202,298",1.1,1.1
31,Arkansas ...................,"117,064","118,592","119,560","119,492 119,920","120,704","120,683","121,448",0.7,0.7,0.7,0.7 0.7,0.7,0.7,0.6,"119,492","119,920",0.7,0.7
32,Florida ........................,"866,212","875,944","889,512","903,778 906,448","917,885","935,927","947,007",4.9,4.9,4.9,5.0 5.0,5.0,5.0,5.0,"903,778","906,448",5.0,5.0
33,Georgia .....................,"491,481","498,673","505,437","510,496 520,453","520,479","527,705","532,805",2.8,2.8,2.8,2.8 2.9,2.8,2.8,2.8,"510,496","520,453",2.8,2.9
34,Kentucky ...................,"188,148","191,427","193,072","194,942 191,394","195,685","199,550","201,545",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1,"194,942","191,394",1.1,1.1
35,Louisiana ....................,"239,704","239,172","238,492","234,932 233,388","234,573","234,905","237,569",1.4,1.3,1.3,1.3 1.3,1.3,1.3,1.3,"234,932","233,388",1.3,1.3
36,Mississippi .................,"104,325","105,635","106,684","106,841 107,425","107,397","107,683","108,215",0.6,0.6,0.6,0.6 0.6,0.6,0.6,0.6,"106,841","107,425",0.6,0.6
37,North Carolina ..............,"490,176","496,874","503,657","508,257 509,358","514,182","521,265","526,809",2.8,2.8,2.8,2.8 2.8,2.8,2.8,2.8,"508,257","509,358",2.8,2.8
38,South Carolina ............,"197,475","200,135","203,438","206,274 206,715","209,032","210,589","212,529",1.1,1.1,1.1,1.1 1.1,1.1,1.1,1.1,"206,274","206,715",1.1,1.1
39,Tennessee ..................,"309,207","314,661","319,867","322,900 323,864","326,262","330,988","333,966",1.7,1.8,1.8,1.8 1.8,1.8,1.8,1.8,"322,900","323,864",1.8,1.8
40,Virginia .......................,"471,999","479,776","485,306","489,805 488,650","491,669","496,244","500,833",2.7,2.7,2.7,2.7 2.7,2.7,2.7,2.7,"489,805","488,650",2.7,2.7
41,West Virginia ..............,"72,465","74,081","73,971","73,019 71,772","72,625","73,898","75,199",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"73,019","71,772",0.4,0.4
42,Southwest ....................,"2,192,658","2,194,494","2,185,231","2,163,126 2,155,605","2,178,893","2,207,112","2,242,336",12.4,NaN,12.1,11.9 11.9,NaN,11.9,12.0,"2,163,126","2,155,605",11.9,11.9
43,Arizona .......................,"287,190","290,463","292,540","295,597 296,314","299,626","306,764","309,103",1.6,1.6,1.6,1.6 1.6,1.6,1.7,1.6,"295,597","296,314",1.6,1.6
44,New Mexico ................,"93,025","93,799","93,713","92,383 91,496","92,931","93,784","94,974",0.5,0.5,0.5,0.5 0.5,0.5,0.5,0.5,"92,383","91,496",0.5,0.5
45,Oklahoma ...................,"191,872","189,264","187,795","183,112 180,399","182,688","183,061","185,602",1.1,1.1,1.0,1.0 1.0,1.0,1.0,1.0,"183,112","180,399",1.0,1.0
46,Texas .........................,"1,620,571","1,620,968","1,611,183","1,592,033 1,587,395","1,603,648","1,623,503","1,652,657",9.2,9.1,8.9,8.8 8.7,8.7,8.7,8.8,"1,592,033","1,587,395",8.8,8.7
47,Rocky Mountain ............,"605,555","613,147","616,369","617,524 619,325","624,954","636,667","643,739",3.4,3.4,3.4,3.4 3.4,3.4,3.4,3.4,"617,524","619,325",3.4,3.4
48,Colorado ....................,"309,993","313,303","314,546","315,475 316,481","320,634","327,333","330,319",1.8,1.8,1.7,1.7 1.7,1.7,1.8,1.8,"315,475","316,481",1.7,1.7
49,Idaho ..........................,"64,856","65,342","65,884","65,760 66,010","66,927","67,714","68,450",0.4,0.4,0.4,0.4 0.4,0.4,0.4,0.4,"65,760","66,010",0.4,0.4
50,Montana .....................,"45,186","46,207","46,119","45,868 45,789","45,642","46,041","46,506",0.3,0.3,0.3,0.3 0.3,0.2,0.2,0.2,"45,868","45,789",0.3,0.3
51,Utah ..........................,"145,982","148,314","150,215","151,884 153,422","154,182","157,802","160,002",0.8,0.8,0.8,0.8 0.8,0.8,0.9,0.9,"151,884","153,422",0.8,0.8
52,Wyoming ....................,"39,538","39,981","39,604","38,537 37,622","37,569","37,777","38,463",0.2,0.2,0.2,0.2 0.2,0.2,0.2,0.2,"38,537","37,622",0.2,0.2
53,Far West ......................,"3,366,368","3,419,789","3,450,939","3,481,350 3,512,447","3,552,236","3,610,452","3,650,211",19.1,NaN,19.1,19.2 19.3,NaN,19.5,19.5,"3,481,350","3,512,447",19.2,19.3
54,Alaska ........................,"53,997","54,615","53,155","51,770 50,059","50,545","50,742","51,506",0.3,0.3,0.3,0.3 0.3,0.3,0.3,0.3,"51,770","50,059",0.3,0.3
55,California ....................,"2,444,063","2,485,470","2,505,638","2,531,304 2,545,953","2,581,572","2,627,083","2,656,080",13.8,NaN,13.9,14.0 14.0,NaN,14.2,14.2,"2,531,304","2,545,953",14.0,14.0
56,Hawaii .......................,"79,538","80,302","80,907","81,650 82,904","83,548","84,325","84,889",0.5,0.4,0.4,0.5 0.5,0.5,0.5,0.5,"81,650","82,904",0.5,0.5
57,Nevada ......................,"137,533","140,194","142,952","143,602 143,572","145,068","149,913","151,348",0.8,0.8,0.8,0.8 0.8,0.8,0.8,0.8,"143,602","143,572",0.8,0.8
58,Oregon .......................,"212,763","214,687","218,660","219,979 224,181","225,947","227,316","229,837",1.2,1.2,1.2,1.2 1.2,1.2,1.2,1.2,"219,979","224,181",1.2,1.2
59,Washington ................,"438,475","444,522","449,627","453,045 465,779","465,556","471,073","476,550",2.5,2.5,2.5,2.5 2.6,2.5,2.5,2.5,"453,045","465,779",2.5,2.6

In [75]:
GDP15_16 = GDP15_16.drop('Percent of the U.S.', axis = 1)
GDP15_16 = GDP15_16.drop('Unnamed: 5', axis = 1)
GDP15_16

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 12,Unnamed: 13,Unnamed: 15,Unnamed: 16,Unnamed: 17,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %
0,United States,"..........................17,671,025","17,886,695","18,030,967","18,337,791","18,561,915","18,755,370",100.0,NaN,100.0,NaN,100.0,100.0,"18,111,878","18,170,091",100.0,100.0
1,New England .....................,"941,945","959,027","964,703","990,080","1,002,400","1,012,104",5.3,5.4,5.4,5.4,5.4,5.4,"982,152","983,200",5.4,5.4
2,Connecticut ................,"250,628","256,514","257,895","262,341","263,973","266,597",1.4,1.4,1.4,1.4,1.4,1.4,"260,185","260,604",1.4,1.4
3,Maine ........................,"55,930","57,230","57,716","59,224","59,478","59,857",0.3,0.3,0.3,0.3,0.3,0.3,"58,453","58,540",0.3,0.3
4,Massachusetts ............,"478,320","485,938","487,509","503,357","511,392","516,483",2.7,2.7,2.7,2.7,2.8,2.8,"500,634","500,418",2.8,2.8
5,New Hampshire ...........,"72,395","73,810","75,038","77,201","78,329","79,155",0.4,0.4,0.4,0.4,0.4,0.4,"75,833","76,737",0.4,0.4
6,Rhode Island ..............,"54,858","55,401","55,884","57,099","58,017","58,527",0.3,0.3,0.3,0.3,0.3,0.3,"56,457","56,087",0.3,0.3
7,Vermont .....................,"29,815","30,135","30,660","30,859","31,211","31,483",0.2,0.2,0.2,0.2,0.2,0.2,"30,591","30,814",0.2,0.2
8,Mideast .......................,"3,223,326","3,270,682","3,302,756","3,358,622","3,381,370","3,408,478",18.2,NaN,18.3,NaN,18.2,18.2,"3,301,626","3,329,683",18.2,18.3
9,Delaware ....................,"68,216","68,898","69,086","69,747","71,080","71,769",0.4,0.4,0.4,0.4,0.4,0.4,"69,256","68,952",0.4,0.4
10,District of Columbia .....,"120,100","121,210","121,295","126,100","127,208","128,597",0.7,0.7,0.7,0.7,0.7,0.7,"121,870","125,356",0.7,0.7
11,Maryland ....................,"361,870","363,936","366,991","376,578","380,950","384,386",2.0,2.0,2.0,2.1,2.1,2.0,"372,169","371,205",2.1,2.0
12,New Jersey ................,"547,279","565,951","571,204","577,703","583,804","588,706",3.1,3.2,3.2,3.2,3.1,3.1,"573,006","574,277",3.2,3.2
13,New York ...................,"1,427,065","1,445,357","1,462,516","1,489,457","1,486,075","1,494,981",8.1,8.1,8.1,8.1,8.0,8.0,"1,447,505","1,481,479",8.0,8.2
14,Pennsylvania ...............,"698,796","705,330","711,663","719,037","732,252","740,039",4.0,3.9,3.9,3.9,3.9,3.9,"717,821","708,415",4.0,3.9
15,Great Lakes .................,"2,448,105","2,473,845","2,499,169","2,541,207","2,568,564","2,593,179",13.9,NaN,13.9,NaN,13.8,13.8,"2,519,159","2,521,077",13.9,13.9
16,Illinois .......................,"763,309","766,689","778,688","787,470","791,450","798,999",4.3,4.3,4.3,4.3,4.3,4.3,"780,040","788,510",4.3,4.3
17,Indiana ......................,"327,996","333,135","334,536","339,900","343,721","346,591",1.9,1.9,1.9,1.9,1.9,1.8,"337,786","337,423",1.9,1.9
18,Michigan ....................,"460,714","468,784","473,861","485,680","490,342","495,300",2.6,2.6,2.6,2.6,2.6,2.6,"479,085","477,634",2.6,2.6
19,Ohio ..........................,"599,820","605,409","608,502","621,138","631,347","638,185",3.4,3.4,3.4,3.4,3.4,3.4,"615,575","612,191",3.4,3.4
20,Wisconsin ..................,"296,267","299,828","303,582","307,019","311,704","314,104",1.7,1.7,1.7,1.7,1.7,1.7,"306,673","305,319",1.7,1.7
21,Plains ..........................,"1,147,993","1,161,066","1,171,307","1,177,073","1,190,606","1,199,789",6.5,6.5,6.5,6.4,6.4,6.4,"1,174,283","1,167,069",6.5,6.4
22,Iowa ..........................,"172,410","175,098","177,491","177,667","179,944","181,007",1.0,1.0,1.0,1.0,1.0,1.0,"178,238","176,443",1.0,1.0
23,Kansas ......................,"148,490","152,674","153,489","152,822","153,801","154,574",0.8,0.9,0.9,0.8,0.8,0.8,"152,725","151,833",0.8,0.8
24,Minnesota ..................,"324,022","324,510","326,873","331,958","338,304","341,318",1.8,1.8,1.8,1.8,1.8,1.8,"331,926","329,008",1.8,1.8
25,Missouri .....................,"288,381","292,194","294,997","299,897","301,824","304,431",1.6,1.6,1.6,1.6,1.6,1.6,"295,298","297,412",1.6,1.6
26,Nebraska ...................,"111,411","113,604","114,836","114,805","116,025","116,769",0.6,0.6,0.6,0.6,0.6,0.6,"113,982","113,782",0.6,0.6
27,North Dakota ...............,"57,402","56,560","55,719","52,015","52,096","52,796",0.3,0.3,0.3,0.3,0.3,0.3,"54,027","51,450",0.3,0.3
28,South Dakota ..............,"45,878","46,426","47,903","47,908","48,612","48,893",0.3,0.3,0.3,0.3,0.3,0.3,"48,086","47,142",0.3,0.3
29,Southeast .....................,"3,745,076","3,794,648","3,840,495","3,914,726","3,964,744","4,005,534",21.2,NaN,21.3,NaN,21.4,21.4,"3,872,660","3,881,685",21.4,21.4
30,Alabama ....................,"196,820","199,677","201,498","204,232","205,307","207,608",1.1,1.1,1.1,1.1,1.1,1.1,"201,926","202,298",1.1,1.1
31,Arkansas ...................,"117,064","118,592","119,560","120,704","120,683","121,448",0.7,0.7,0.7,0.7,0.7,0.6,"119,492","119,920",0.7,0.7
32,Florida ........................,"866,212","875,944","889,512","917,885","935,927","947,007",4.9,4.9,4.9,5.0,5.0,5.0,"903,778","906,448",5.0,5.0
33,Georgia .....................,"491,481","498,673","505,437","520,479","527,705","532,805",2.8,2.8,2.8,2.8,2.8,2.8,"510,496","520,453",2.8,2.9
34,Kentucky ...................,"188,148","191,427","193,072","195,685","199,550","201,545",1.1,1.1,1.1,1.1,1.1,1.1,"194,942","191,394",1.1,1.1
35,Louisiana ....................,"239,704","239,172","238,492","234,573","234,905","237,569",1.4,1.3,1.3,1.3,1.3,1.3,"234,932","233,388",1.3,1.3
36,Mississippi .................,"104,325","105,635","106,684","107,397","107,683","108,215",0.6,0.6,0.6,0.6,0.6,0.6,"106,841","107,425",0.6,0.6
37,North Carolina ..............,"490,176","496,874","503,657","514,182","521,265","526,809",2.8,2.8,2.8,2.8,2.8,2.8,"508,257","509,358",2.8,2.8
38,South Carolina ............,"197,475","200,135","203,438","209,032","210,589","212,529",1.1,1.1,1.1,1.1,1.1,1.1,"206,274","206,715",1.1,1.1
39,Tennessee ..................,"309,207","314,661","319,867","326,262","330,988","333,966",1.7,1.8,1.8,1.8,1.8,1.8,"322,900","323,864",1.8,1.8
40,Virginia .......................,"471,999","479,776","485,306","491,669","496,244","500,833",2.7,2.7,2.7,2.7,2.7,2.7,"489,805","488,650",2.7,2.7
41,West Virginia ..............,"72,465","74,081","73,971","72,625","73,898","75,199",0.4,0.4,0.4,0.4,0.4,0.4,"73,019","71,772",0.4,0.4
42,Southwest ....................,"2,192,658","2,194,494","2,185,231","2,178,893","2,207,112","2,242,336",12.4,NaN,12.1,NaN,11.9,12.0,"2,163,126","2,155,605",11.9,11.9
43,Arizona .......................,"287,190","290,463","292,540","299,626","306,764","309,103",1.6,1.6,1.6,1.6,1.7,1.6,"295,597","296,314",1.6,1.6
44,New Mexico ................,"93,025","93,799","93,713","92,931","93,784","94,974",0.5,0.5,0.5,0.5,0.5,0.5,"92,383","91,496",0.5,0.5
45,Oklahoma ...................,"191,872","189,264","187,795","182,688","183,061","185,602",1.1,1.1,1.0,1.0,1.0,1.0,"183,112","180,399",1.0,1.0
46,Texas .........................,"1,620,571","1,620,968","1,611,183","1,603,648","1,623,503","1,652,657",9.2,9.1,8.9,8.7,8.7,8.8,"1,592,033","1,587,395",8.8,8.7
47,Rocky Mountain ............,"605,555","613,147","616,369","624,954","636,667","643,739",3.4,3.4,3.4,3.4,3.4,3.4,"617,524","619,325",3.4,3.4
48,Colorado ....................,"309,993","313,303","314,546","320,634","327,333","330,319",1.8,1.8,1.7,1.7,1.8,1.8,"315,475","316,481",1.7,1.7
49,Idaho ..........................,"64,856","65,342","65,884","66,927","67,714","68,450",0.4,0.4,0.4,0.4,0.4,0.4,"65,760","66,010",0.4,0.4
50,Montana .....................,"45,186","46,207","46,119","45,642","46,041","46,506",0.3,0.3,0.3,0.2,0.2,0.2,"45,868","45,789",0.3,0.3
51,Utah ..........................,"145,982","148,314","150,215","154,182","157,802","160,002",0.8,0.8,0.8,0.8,0.9,0.9,"151,884","153,422",0.8,0.8
52,Wyoming ....................,"39,538","39,981","39,604","37,569","37,777","38,463",0.2,0.2,0.2,0.2,0.2,0.2,"38,537","37,622",0.2,0.2
53,Far West ......................,"3,366,368","3,419,789","3,450,939","3,552,236","3,610,452","3,650,211",19.1,NaN,19.1,NaN,19.5,19.5,"3,481,350","3,512,447",19.2,19.3
54,Alaska ........................,"53,997","54,615","53,155","50,545","50,742","51,506",0.3,0.3,0.3,0.3,0.3,0.3,"51,770","50,059",0.3,0.3
55,California ....................,"2,444,063","2,485,470","2,505,638","2,581,572","2,627,083","2,656,080",13.8,NaN,13.9,NaN,14.2,14.2,"2,531,304","2,545,953",14.0,14.0
56,Hawaii .......................,"79,538","80,302","80,907","83,548","84,325","84,889",0.5,0.4,0.4,0.5,0.5,0.5,"81,650","82,904",0.5,0.5
57,Nevada ......................,"137,533","140,194","142,952","145,068","149,913","151,348",0.8,0.8,0.8,0.8,0.8,0.8,"143,602","143,572",0.8,0.8
58,Oregon .......................,"212,763","214,687","218,660","225,947","227,316","229,837",1.2,1.2,1.2,1.2,1.2,1.2,"219,979","224,181",1.2,1.2
59,Washington ................,"438,475","444,522","449,627","465,556","471,073","476,550",2.5,2.5,2.5,2.5,2.5,2.5,"453,045","465,779",2.5,2.6

In [76]:
GDP15_16.columns = ['Area', '2015 Q1', '2015 Q2', '2015 Q3', '2016 Q2',
                 '2016 Q3', '2016 Q4','2015 Q1 %', '2015 Q2 %', '2015 Q3 %', '2016 Q2 %',
                 '2016 Q3 %', '2016 Q4 %', '2015 Q4', '2016 Q1', '2015 Q4 %', '2016 Q1 %']
GDP15_16

,Area,2015 Q1,2015 Q2,2015 Q3,2016 Q2,2016 Q3,2016 Q4,2015 Q1 %,2015 Q2 %,2015 Q3 %,2016 Q2 %,2016 Q3 %,2016 Q4 %,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %
0,United States,"..........................17,671,025","17,886,695","18,030,967","18,337,791","18,561,915","18,755,370",100.0,NaN,100.0,NaN,100.0,100.0,"18,111,878","18,170,091",100.0,100.0
1,New England .....................,"941,945","959,027","964,703","990,080","1,002,400","1,012,104",5.3,5.4,5.4,5.4,5.4,5.4,"982,152","983,200",5.4,5.4
2,Connecticut ................,"250,628","256,514","257,895","262,341","263,973","266,597",1.4,1.4,1.4,1.4,1.4,1.4,"260,185","260,604",1.4,1.4
3,Maine ........................,"55,930","57,230","57,716","59,224","59,478","59,857",0.3,0.3,0.3,0.3,0.3,0.3,"58,453","58,540",0.3,0.3
4,Massachusetts ............,"478,320","485,938","487,509","503,357","511,392","516,483",2.7,2.7,2.7,2.7,2.8,2.8,"500,634","500,418",2.8,2.8
5,New Hampshire ...........,"72,395","73,810","75,038","77,201","78,329","79,155",0.4,0.4,0.4,0.4,0.4,0.4,"75,833","76,737",0.4,0.4
6,Rhode Island ..............,"54,858","55,401","55,884","57,099","58,017","58,527",0.3,0.3,0.3,0.3,0.3,0.3,"56,457","56,087",0.3,0.3
7,Vermont .....................,"29,815","30,135","30,660","30,859","31,211","31,483",0.2,0.2,0.2,0.2,0.2,0.2,"30,591","30,814",0.2,0.2
8,Mideast .......................,"3,223,326","3,270,682","3,302,756","3,358,622","3,381,370","3,408,478",18.2,NaN,18.3,NaN,18.2,18.2,"3,301,626","3,329,683",18.2,18.3
9,Delaware ....................,"68,216","68,898","69,086","69,747","71,080","71,769",0.4,0.4,0.4,0.4,0.4,0.4,"69,256","68,952",0.4,0.4
10,District of Columbia .....,"120,100","121,210","121,295","126,100","127,208","128,597",0.7,0.7,0.7,0.7,0.7,0.7,"121,870","125,356",0.7,0.7
11,Maryland ....................,"361,870","363,936","366,991","376,578","380,950","384,386",2.0,2.0,2.0,2.1,2.1,2.0,"372,169","371,205",2.1,2.0
12,New Jersey ................,"547,279","565,951","571,204","577,703","583,804","588,706",3.1,3.2,3.2,3.2,3.1,3.1,"573,006","574,277",3.2,3.2
13,New York ...................,"1,427,065","1,445,357","1,462,516","1,489,457","1,486,075","1,494,981",8.1,8.1,8.1,8.1,8.0,8.0,"1,447,505","1,481,479",8.0,8.2
14,Pennsylvania ...............,"698,796","705,330","711,663","719,037","732,252","740,039",4.0,3.9,3.9,3.9,3.9,3.9,"717,821","708,415",4.0,3.9
15,Great Lakes .................,"2,448,105","2,473,845","2,499,169","2,541,207","2,568,564","2,593,179",13.9,NaN,13.9,NaN,13.8,13.8,"2,519,159","2,521,077",13.9,13.9
16,Illinois .......................,"763,309","766,689","778,688","787,470","791,450","798,999",4.3,4.3,4.3,4.3,4.3,4.3,"780,040","788,510",4.3,4.3
17,Indiana ......................,"327,996","333,135","334,536","339,900","343,721","346,591",1.9,1.9,1.9,1.9,1.9,1.8,"337,786","337,423",1.9,1.9
18,Michigan ....................,"460,714","468,784","473,861","485,680","490,342","495,300",2.6,2.6,2.6,2.6,2.6,2.6,"479,085","477,634",2.6,2.6
19,Ohio ..........................,"599,820","605,409","608,502","621,138","631,347","638,185",3.4,3.4,3.4,3.4,3.4,3.4,"615,575","612,191",3.4,3.4
20,Wisconsin ..................,"296,267","299,828","303,582","307,019","311,704","314,104",1.7,1.7,1.7,1.7,1.7,1.7,"306,673","305,319",1.7,1.7
21,Plains ..........................,"1,147,993","1,161,066","1,171,307","1,177,073","1,190,606","1,199,789",6.5,6.5,6.5,6.4,6.4,6.4,"1,174,283","1,167,069",6.5,6.4
22,Iowa ..........................,"172,410","175,098","177,491","177,667","179,944","181,007",1.0,1.0,1.0,1.0,1.0,1.0,"178,238","176,443",1.0,1.0
23,Kansas ......................,"148,490","152,674","153,489","152,822","153,801","154,574",0.8,0.9,0.9,0.8,0.8,0.8,"152,725","151,833",0.8,0.8
24,Minnesota ..................,"324,022","324,510","326,873","331,958","338,304","341,318",1.8,1.8,1.8,1.8,1.8,1.8,"331,926","329,008",1.8,1.8
25,Missouri .....................,"288,381","292,194","294,997","299,897","301,824","304,431",1.6,1.6,1.6,1.6,1.6,1.6,"295,298","297,412",1.6,1.6
26,Nebraska ...................,"111,411","113,604","114,836","114,805","116,025","116,769",0.6,0.6,0.6,0.6,0.6,0.6,"113,982","113,782",0.6,0.6
27,North Dakota ...............,"57,402","56,560","55,719","52,015","52,096","52,796",0.3,0.3,0.3,0.3,0.3,0.3,"54,027","51,450",0.3,0.3
28,South Dakota ..............,"45,878","46,426","47,903","47,908","48,612","48,893",0.3,0.3,0.3,0.3,0.3,0.3,"48,086","47,142",0.3,0.3
29,Southeast .....................,"3,745,076","3,794,648","3,840,495","3,914,726","3,964,744","4,005,534",21.2,NaN,21.3,NaN,21.4,21.4,"3,872,660","3,881,685",21.4,21.4
30,Alabama ....................,"196,820","199,677","201,498","204,232","205,307","207,608",1.1,1.1,1.1,1.1,1.1,1.1,"201,926","202,298",1.1,1.1
31,Arkansas ...................,"117,064","118,592","119,560","120,704","120,683","121,448",0.7,0.7,0.7,0.7,0.7,0.6,"119,492","119,920",0.7,0.7
32,Florida ........................,"866,212","875,944","889,512","917,885","935,927","947,007",4.9,4.9,4.9,5.0,5.0,5.0,"903,778","906,448",5.0,5.0
33,Georgia .....................,"491,481","498,673","505,437","520,479","527,705","532,805",2.8,2.8,2.8,2.8,2.8,2.8,"510,496","520,453",2.8,2.9
34,Kentucky ...................,"188,148","191,427","193,072","195,685","199,550","201,545",1.1,1.1,1.1,1.1,1.1,1.1,"194,942","191,394",1.1,1.1
35,Louisiana ....................,"239,704","239,172","238,492","234,573","234,905","237,569",1.4,1.3,1.3,1.3,1.3,1.3,"234,932","233,388",1.3,1.3
36,Mississippi .................,"104,325","105,635","106,684","107,397","107,683","108,215",0.6,0.6,0.6,0.6,0.6,0.6,"106,841","107,425",0.6,0.6
37,North Carolina ..............,"490,176","496,874","503,657","514,182","521,265","526,809",2.8,2.8,2.8,2.8,2.8,2.8,"508,257","509,358",2.8,2.8
38,South Carolina ............,"197,475","200,135","203,438","209,032","210,589","212,529",1.1,1.1,1.1,1.1,1.1,1.1,"206,274","206,715",1.1,1.1
39,Tennessee ..................,"309,207","314,661","319,867","326,262","330,988","333,966",1.7,1.8,1.8,1.8,1.8,1.8,"322,900","323,864",1.8,1.8
40,Virginia .......................,"471,999","479,776","485,306","491,669","496,244","500,833",2.7,2.7,2.7,2.7,2.7,2.7,"489,805","488,650",2.7,2.7
41,West Virginia ..............,"72,465","74,081","73,971","72,625","73,898","75,199",0.4,0.4,0.4,0.4,0.4,0.4,"73,019","71,772",0.4,0.4
42,Southwest ....................,"2,192,658","2,194,494","2,185,231","2,178,893","2,207,112","2,242,336",12.4,NaN,12.1,NaN,11.9,12.0,"2,163,126","2,155,605",11.9,11.9
43,Arizona .......................,"287,190","290,463","292,540","299,626","306,764","309,103",1.6,1.6,1.6,1.6,1.7,1.6,"295,597","296,314",1.6,1.6
44,New Mexico ................,"93,025","93,799","93,713","92,931","93,784","94,974",0.5,0.5,0.5,0.5,0.5,0.5,"92,383","91,496",0.5,0.5
45,Oklahoma ...................,"191,872","189,264","187,795","182,688","183,061","185,602",1.1,1.1,1.0,1.0,1.0,1.0,"183,112","180,399",1.0,1.0
46,Texas .........................,"1,620,571","1,620,968","1,611,183","1,603,648","1,623,503","1,652,657",9.2,9.1,8.9,8.7,8.7,8.8,"1,592,033","1,587,395",8.8,8.7
47,Rocky Mountain ............,"605,555","613,147","616,369","624,954","636,667","643,739",3.4,3.4,3.4,3.4,3.4,3.4,"617,524","619,325",3.4,3.4
48,Colorado ....................,"309,993","313,303","314,546","320,634","327,333","330,319",1.8,1.8,1.7,1.7,1.8,1.8,"315,475","316,481",1.7,1.7
49,Idaho ..........................,"64,856","65,342","65,884","66,927","67,714","68,450",0.4,0.4,0.4,0.4,0.4,0.4,"65,760","66,010",0.4,0.4
50,Montana .....................,"45,186","46,207","46,119","45,642","46,041","46,506",0.3,0.3,0.3,0.2,0.2,0.2,"45,868","45,789",0.3,0.3
51,Utah ..........................,"145,982","148,314","150,215","154,182","157,802","160,002",0.8,0.8,0.8,0.8,0.9,0.9,"151,884","153,422",0.8,0.8
52,Wyoming ....................,"39,538","39,981","39,604","37,569","37,777","38,463",0.2,0.2,0.2,0.2,0.2,0.2,"38,537","37,622",0.2,0.2
53,Far West ......................,"3,366,368","3,419,789","3,450,939","3,552,236","3,610,452","3,650,211",19.1,NaN,19.1,NaN,19.5,19.5,"3,481,350","3,512,447",19.2,19.3
54,Alaska ........................,"53,997","54,615","53,155","50,545","50,742","51,506",0.3,0.3,0.3,0.3,0.3,0.3,"51,770","50,059",0.3,0.3
55,California ....................,"2,444,063","2,485,470","2,505,638","2,581,572","2,627,083","2,656,080",13.8,NaN,13.9,NaN,14.2,14.2,"2,531,304","2,545,953",14.0,14.0
56,Hawaii .......................,"79,538","80,302","80,907","83,548","84,325","84,889",0.5,0.4,0.4,0.5,0.5,0.5,"81,650","82,904",0.5,0.5
57,Nevada ......................,"137,533","140,194","142,952","145,068","149,913","151,348",0.8,0.8,0.8,0.8,0.8,0.8,"143,602","143,572",0.8,0.8
58,Oregon .......................,"212,763","214,687","218,660","225,947","227,316","229,837",1.2,1.2,1.2,1.2,1.2,1.2,"219,979","224,181",1.2,1.2
59,Washington ................,"438,475","444,522","449,627","465,556","471,073","476,550",2.5,2.5,2.5,2.5,2.5,2.5,"453,045","465,779",2.5,2.6

In [77]:
for column in GDP15_16.columns:
    if column == 'Area':
        pass
    else:
        for i in GDP15_16[column].index:
            if isinstance(GDP15_16.loc[i, column], float):
                pass
            else:
                GDP15_16.loc[i, column] = GDP15_16.loc[i, column].replace(',','')
GDP15_16 = GDP15_16.apply(pd.to_numeric, errors = 'ignore')
GDP15_16

,Area,2015 Q1,2015 Q2,2015 Q3,2016 Q2,2016 Q3,2016 Q4,2015 Q1 %,2015 Q2 %,2015 Q3 %,2016 Q2 %,2016 Q3 %,2016 Q4 %,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %
0,United States,..........................17671025,17886695,18030967,18337791,18561915,18755370,100.0,NaN,100.0,NaN,100.0,100.0,18111878,18170091,100.0,100.0
1,New England .....................,941945,959027,964703,990080,1002400,1012104,5.3,5.4,5.4,5.4,5.4,5.4,982152,983200,5.4,5.4
2,Connecticut ................,250628,256514,257895,262341,263973,266597,1.4,1.4,1.4,1.4,1.4,1.4,260185,260604,1.4,1.4
3,Maine ........................,55930,57230,57716,59224,59478,59857,0.3,0.3,0.3,0.3,0.3,0.3,58453,58540,0.3,0.3
4,Massachusetts ............,478320,485938,487509,503357,511392,516483,2.7,2.7,2.7,2.7,2.8,2.8,500634,500418,2.8,2.8
5,New Hampshire ...........,72395,73810,75038,77201,78329,79155,0.4,0.4,0.4,0.4,0.4,0.4,75833,76737,0.4,0.4
6,Rhode Island ..............,54858,55401,55884,57099,58017,58527,0.3,0.3,0.3,0.3,0.3,0.3,56457,56087,0.3,0.3
7,Vermont .....................,29815,30135,30660,30859,31211,31483,0.2,0.2,0.2,0.2,0.2,0.2,30591,30814,0.2,0.2
8,Mideast .......................,3223326,3270682,3302756,3358622,3381370,3408478,18.2,NaN,18.3,NaN,18.2,18.2,3301626,3329683,18.2,18.3
9,Delaware ....................,68216,68898,69086,69747,71080,71769,0.4,0.4,0.4,0.4,0.4,0.4,69256,68952,0.4,0.4
10,District of Columbia .....,120100,121210,121295,126100,127208,128597,0.7,0.7,0.7,0.7,0.7,0.7,121870,125356,0.7,0.7
11,Maryland ....................,361870,363936,366991,376578,380950,384386,2.0,2.0,2.0,2.1,2.1,2.0,372169,371205,2.1,2.0
12,New Jersey ................,547279,565951,571204,577703,583804,588706,3.1,3.2,3.2,3.2,3.1,3.1,573006,574277,3.2,3.2
13,New York ...................,1427065,1445357,1462516,1489457,1486075,1494981,8.1,8.1,8.1,8.1,8.0,8.0,1447505,1481479,8.0,8.2
14,Pennsylvania ...............,698796,705330,711663,719037,732252,740039,4.0,3.9,3.9,3.9,3.9,3.9,717821,708415,4.0,3.9
15,Great Lakes .................,2448105,2473845,2499169,2541207,2568564,2593179,13.9,NaN,13.9,NaN,13.8,13.8,2519159,2521077,13.9,13.9
16,Illinois .......................,763309,766689,778688,787470,791450,798999,4.3,4.3,4.3,4.3,4.3,4.3,780040,788510,4.3,4.3
17,Indiana ......................,327996,333135,334536,339900,343721,346591,1.9,1.9,1.9,1.9,1.9,1.8,337786,337423,1.9,1.9
18,Michigan ....................,460714,468784,473861,485680,490342,495300,2.6,2.6,2.6,2.6,2.6,2.6,479085,477634,2.6,2.6
19,Ohio ..........................,599820,605409,608502,621138,631347,638185,3.4,3.4,3.4,3.4,3.4,3.4,615575,612191,3.4,3.4
20,Wisconsin ..................,296267,299828,303582,307019,311704,314104,1.7,1.7,1.7,1.7,1.7,1.7,306673,305319,1.7,1.7
21,Plains ..........................,1147993,1161066,1171307,1177073,1190606,1199789,6.5,6.5,6.5,6.4,6.4,6.4,1174283,1167069,6.5,6.4
22,Iowa ..........................,172410,175098,177491,177667,179944,181007,1.0,1.0,1.0,1.0,1.0,1.0,178238,176443,1.0,1.0
23,Kansas ......................,148490,152674,153489,152822,153801,154574,0.8,0.9,0.9,0.8,0.8,0.8,152725,151833,0.8,0.8
24,Minnesota ..................,324022,324510,326873,331958,338304,341318,1.8,1.8,1.8,1.8,1.8,1.8,331926,329008,1.8,1.8
25,Missouri .....................,288381,292194,294997,299897,301824,304431,1.6,1.6,1.6,1.6,1.6,1.6,295298,297412,1.6,1.6
26,Nebraska ...................,111411,113604,114836,114805,116025,116769,0.6,0.6,0.6,0.6,0.6,0.6,113982,113782,0.6,0.6
27,North Dakota ...............,57402,56560,55719,52015,52096,52796,0.3,0.3,0.3,0.3,0.3,0.3,54027,51450,0.3,0.3
28,South Dakota ..............,45878,46426,47903,47908,48612,48893,0.3,0.3,0.3,0.3,0.3,0.3,48086,47142,0.3,0.3
29,Southeast .....................,3745076,3794648,3840495,3914726,3964744,4005534,21.2,NaN,21.3,NaN,21.4,21.4,3872660,3881685,21.4,21.4
30,Alabama ....................,196820,199677,201498,204232,205307,207608,1.1,1.1,1.1,1.1,1.1,1.1,201926,202298,1.1,1.1
31,Arkansas ...................,117064,118592,119560,120704,120683,121448,0.7,0.7,0.7,0.7,0.7,0.6,119492,119920,0.7,0.7
32,Florida ........................,866212,875944,889512,917885,935927,947007,4.9,4.9,4.9,5.0,5.0,5.0,903778,906448,5.0,5.0
33,Georgia .....................,491481,498673,505437,520479,527705,532805,2.8,2.8,2.8,2.8,2.8,2.8,510496,520453,2.8,2.9
34,Kentucky ...................,188148,191427,193072,195685,199550,201545,1.1,1.1,1.1,1.1,1.1,1.1,194942,191394,1.1,1.1
35,Louisiana ....................,239704,239172,238492,234573,234905,237569,1.4,1.3,1.3,1.3,1.3,1.3,234932,233388,1.3,1.3
36,Mississippi .................,104325,105635,106684,107397,107683,108215,0.6,0.6,0.6,0.6,0.6,0.6,106841,107425,0.6,0.6
37,North Carolina ..............,490176,496874,503657,514182,521265,526809,2.8,2.8,2.8,2.8,2.8,2.8,508257,509358,2.8,2.8
38,South Carolina ............,197475,200135,203438,209032,210589,212529,1.1,1.1,1.1,1.1,1.1,1.1,206274,206715,1.1,1.1
39,Tennessee ..................,309207,314661,319867,326262,330988,333966,1.7,1.8,1.8,1.8,1.8,1.8,322900,323864,1.8,1.8
40,Virginia .......................,471999,479776,485306,491669,496244,500833,2.7,2.7,2.7,2.7,2.7,2.7,489805,488650,2.7,2.7
41,West Virginia ..............,72465,74081,73971,72625,73898,75199,0.4,0.4,0.4,0.4,0.4,0.4,73019,71772,0.4,0.4
42,Southwest ....................,2192658,2194494,2185231,2178893,2207112,2242336,12.4,NaN,12.1,NaN,11.9,12.0,2163126,2155605,11.9,11.9
43,Arizona .......................,287190,290463,292540,299626,306764,309103,1.6,1.6,1.6,1.6,1.7,1.6,295597,296314,1.6,1.6
44,New Mexico ................,93025,93799,93713,92931,93784,94974,0.5,0.5,0.5,0.5,0.5,0.5,92383,91496,0.5,0.5
45,Oklahoma ...................,191872,189264,187795,182688,183061,185602,1.1,1.1,1.0,1.0,1.0,1.0,183112,180399,1.0,1.0
46,Texas .........................,1620571,1620968,1611183,1603648,1623503,1652657,9.2,9.1,8.9,8.7,8.7,8.8,1592033,1587395,8.8,8.7
47,Rocky Mountain ............,605555,613147,616369,624954,636667,643739,3.4,3.4,3.4,3.4,3.4,3.4,617524,619325,3.4,3.4
48,Colorado ....................,309993,313303,314546,320634,327333,330319,1.8,1.8,1.7,1.7,1.8,1.8,315475,316481,1.7,1.7
49,Idaho ..........................,64856,65342,65884,66927,67714,68450,0.4,0.4,0.4,0.4,0.4,0.4,65760,66010,0.4,0.4
50,Montana .....................,45186,46207,46119,45642,46041,46506,0.3,0.3,0.3,0.2,0.2,0.2,45868,45789,0.3,0.3
51,Utah ..........................,145982,148314,150215,154182,157802,160002,0.8,0.8,0.8,0.8,0.9,0.9,151884,153422,0.8,0.8
52,Wyoming ....................,39538,39981,39604,37569,37777,38463,0.2,0.2,0.2,0.2,0.2,0.2,38537,37622,0.2,0.2
53,Far West ......................,3366368,3419789,3450939,3552236,3610452,3650211,19.1,NaN,19.1,NaN,19.5,19.5,3481350,3512447,19.2,19.3
54,Alaska ........................,53997,54615,53155,50545,50742,51506,0.3,0.3,0.3,0.3,0.3,0.3,51770,50059,0.3,0.3
55,California ....................,2444063,2485470,2505638,2581572,2627083,2656080,13.8,NaN,13.9,NaN,14.2,14.2,2531304,2545953,14.0,14.0
56,Hawaii .......................,79538,80302,80907,83548,84325,84889,0.5,0.4,0.4,0.5,0.5,0.5,81650,82904,0.5,0.5
57,Nevada ......................,137533,140194,142952,145068,149913,151348,0.8,0.8,0.8,0.8,0.8,0.8,143602,143572,0.8,0.8
58,Oregon .......................,212763,214687,218660,225947,227316,229837,1.2,1.2,1.2,1.2,1.2,1.2,219979,224181,1.2,1.2
59,Washington ................,438475,444522,449627,465556,471073,476550,2.5,2.5,2.5,2.5,2.5,2.5,453045,465779,2.5,2.6

In [78]:
gdp2015 = ['2015 Q1', '2015 Q2', '2015 Q3', '2015 Q4']
gdp2016 = ['2016 Q1', '2016 Q2', '2016 Q3', '2016 Q4']

filter_2015 = GDP15_16.filter(items = gdp2015)
filter_2016 = GDP15_16.filter(items = gdp2016)

GDP15_16['2015'] = filter_2015.mean(axis = 1)
GDP15_16['2016'] = filter_2016.mean(axis = 1)

GDP15_16

,Area,2015 Q1,2015 Q2,2015 Q3,2016 Q2,2016 Q3,2016 Q4,2015 Q1 %,2015 Q2 %,2015 Q3 %,2016 Q2 %,2016 Q3 %,2016 Q4 %,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %,2015,2016
0,United States,..........................17671025,17886695,18030967,18337791,18561915,18755370,100.0,NaN,100.0,NaN,100.0,100.0,18111878,18170091,100.0,100.0,1.800985e+07,18456291.75
1,New England .....................,941945,959027,964703,990080,1002400,1012104,5.3,5.4,5.4,5.4,5.4,5.4,982152,983200,5.4,5.4,9.686273e+05,996946.00
2,Connecticut ................,250628,256514,257895,262341,263973,266597,1.4,1.4,1.4,1.4,1.4,1.4,260185,260604,1.4,1.4,2.581980e+05,263378.75
3,Maine ........................,55930,57230,57716,59224,59478,59857,0.3,0.3,0.3,0.3,0.3,0.3,58453,58540,0.3,0.3,5.779967e+04,59274.75
4,Massachusetts ............,478320,485938,487509,503357,511392,516483,2.7,2.7,2.7,2.7,2.8,2.8,500634,500418,2.8,2.8,4.913603e+05,507912.50
5,New Hampshire ...........,72395,73810,75038,77201,78329,79155,0.4,0.4,0.4,0.4,0.4,0.4,75833,76737,0.4,0.4,7.489367e+04,77855.50
6,Rhode Island ..............,54858,55401,55884,57099,58017,58527,0.3,0.3,0.3,0.3,0.3,0.3,56457,56087,0.3,0.3,5.591400e+04,57432.50
7,Vermont .....................,29815,30135,30660,30859,31211,31483,0.2,0.2,0.2,0.2,0.2,0.2,30591,30814,0.2,0.2,3.046200e+04,31091.75
8,Mideast .......................,3223326,3270682,3302756,3358622,3381370,3408478,18.2,NaN,18.3,NaN,18.2,18.2,3301626,3329683,18.2,18.3,3.291688e+06,3369538.25
9,Delaware ....................,68216,68898,69086,69747,71080,71769,0.4,0.4,0.4,0.4,0.4,0.4,69256,68952,0.4,0.4,6.908000e+04,70387.00
10,District of Columbia .....,120100,121210,121295,126100,127208,128597,0.7,0.7,0.7,0.7,0.7,0.7,121870,125356,0.7,0.7,1.214583e+05,126815.25
11,Maryland ....................,361870,363936,366991,376578,380950,384386,2.0,2.0,2.0,2.1,2.1,2.0,372169,371205,2.1,2.0,3.676987e+05,378279.75
12,New Jersey ................,547279,565951,571204,577703,583804,588706,3.1,3.2,3.2,3.2,3.1,3.1,573006,574277,3.2,3.2,5.700537e+05,581122.50
13,New York ...................,1427065,1445357,1462516,1489457,1486075,1494981,8.1,8.1,8.1,8.1,8.0,8.0,1447505,1481479,8.0,8.2,1.451793e+06,1487998.00
14,Pennsylvania ...............,698796,705330,711663,719037,732252,740039,4.0,3.9,3.9,3.9,3.9,3.9,717821,708415,4.0,3.9,7.116047e+05,724935.75
15,Great Lakes .................,2448105,2473845,2499169,2541207,2568564,2593179,13.9,NaN,13.9,NaN,13.8,13.8,2519159,2521077,13.9,13.9,2.497391e+06,2556006.75
16,Illinois .......................,763309,766689,778688,787470,791450,798999,4.3,4.3,4.3,4.3,4.3,4.3,780040,788510,4.3,4.3,7.751390e+05,791607.25
17,Indiana ......................,327996,333135,334536,339900,343721,346591,1.9,1.9,1.9,1.9,1.9,1.8,337786,337423,1.9,1.9,3.351523e+05,341908.75
18,Michigan ....................,460714,468784,473861,485680,490342,495300,2.6,2.6,2.6,2.6,2.6,2.6,479085,477634,2.6,2.6,4.739100e+05,487239.00
19,Ohio ..........................,599820,605409,608502,621138,631347,638185,3.4,3.4,3.4,3.4,3.4,3.4,615575,612191,3.4,3.4,6.098287e+05,625715.25
20,Wisconsin ..................,296267,299828,303582,307019,311704,314104,1.7,1.7,1.7,1.7,1.7,1.7,306673,305319,1.7,1.7,3.033610e+05,309536.50
21,Plains ..........................,1147993,1161066,1171307,1177073,1190606,1199789,6.5,6.5,6.5,6.4,6.4,6.4,1174283,1167069,6.5,6.4,1.168885e+06,1183634.25
22,Iowa ..........................,172410,175098,177491,177667,179944,181007,1.0,1.0,1.0,1.0,1.0,1.0,178238,176443,1.0,1.0,1.769423e+05,178765.25
23,Kansas ......................,148490,152674,153489,152822,153801,154574,0.8,0.9,0.9,0.8,0.8,0.8,152725,151833,0.8,0.8,1.529627e+05,153257.50
24,Minnesota ..................,324022,324510,326873,331958,338304,341318,1.8,1.8,1.8,1.8,1.8,1.8,331926,329008,1.8,1.8,3.277697e+05,335147.00
25,Missouri .....................,288381,292194,294997,299897,301824,304431,1.6,1.6,1.6,1.6,1.6,1.6,295298,297412,1.6,1.6,2.941630e+05,300891.00
26,Nebraska ...................,111411,113604,114836,114805,116025,116769,0.6,0.6,0.6,0.6,0.6,0.6,113982,113782,0.6,0.6,1.141407e+05,115345.25
27,North Dakota ...............,57402,56560,55719,52015,52096,52796,0.3,0.3,0.3,0.3,0.3,0.3,54027,51450,0.3,0.3,5.543533e+04,52089.25
28,South Dakota ..............,45878,46426,47903,47908,48612,48893,0.3,0.3,0.3,0.3,0.3,0.3,48086,47142,0.3,0.3,4.747167e+04,48138.75
29,Southeast .....................,3745076,3794648,3840495,3914726,3964744,4005534,21.2,NaN,21.3,NaN,21.4,21.4,3872660,3881685,21.4,21.4,3.835934e+06,3941672.25
30,Alabama ....................,196820,199677,201498,204232,205307,207608,1.1,1.1,1.1,1.1,1.1,1.1,201926,202298,1.1,1.1,2.010337e+05,204861.25
31,Arkansas ...................,117064,118592,119560,120704,120683,121448,0.7,0.7,0.7,0.7,0.7,0.6,119492,119920,0.7,0.7,1.192147e+05,120688.75
32,Florida ........................,866212,875944,889512,917885,935927,947007,4.9,4.9,4.9,5.0,5.0,5.0,903778,906448,5.0,5.0,8.897447e+05,926816.75
33,Georgia .....................,491481,498673,505437,520479,527705,532805,2.8,2.8,2.8,2.8,2.8,2.8,510496,520453,2.8,2.9,5.048687e+05,525360.50
34,Kentucky ...................,188148,191427,193072,195685,199550,201545,1.1,1.1,1.1,1.1,1.1,1.1,194942,191394,1.1,1.1,1.931470e+05,197043.50
35,Louisiana ....................,239704,239172,238492,234573,234905,237569,1.4,1.3,1.3,1.3,1.3,1.3,234932,233388,1.3,1.3,2.375320e+05,235108.75
36,Mississippi .................,104325,105635,106684,107397,107683,108215,0.6,0.6,0.6,0.6,0.6,0.6,106841,107425,0.6,0.6,1.063867e+05,107680.00
37,North Carolina ..............,490176,496874,503657,514182,521265,526809,2.8,2.8,2.8,2.8,2.8,2.8,508257,509358,2.8,2.8,5.029293e+05,517903.50
38,South Carolina ............,197475,200135,203438,209032,210589,212529,1.1,1.1,1.1,1.1,1.1,1.1,206274,206715,1.1,1.1,2.032823e+05,209716.25
39,Tennessee ..................,309207,314661,319867,326262,330988,333966,1.7,1.8,1.8,1.8,1.8,1.8,322900,323864,1.8,1.8,3.191427e+05,328770.00
40,Virginia .......................,471999,479776,485306,491669,496244,500833,2.7,2.7,2.7,2.7,2.7,2.7,489805,488650,2.7,2.7,4.849623e+05,494349.00
41,West Virginia ..............,72465,74081,73971,72625,73898,75199,0.4,0.4,0.4,0.4,0.4,0.4,73019,71772,0.4,0.4,7.369033e+04,73373.50
42,Southwest ....................,2192658,2194494,2185231,2178893,2207112,2242336,12.4,NaN,12.1,NaN,11.9,12.0,2163126,2155605,11.9,11.9,2.180950e+06,2195986.50
43,Arizona .......................,287190,290463,292540,299626,306764,309103,1.6,1.6,1.6,1.6,1.7,1.6,295597,296314,1.6,1.6,2.928667e+05,302951.75
44,New Mexico ................,93025,93799,93713,92931,93784,94974,0.5,0.5,0.5,0.5,0.5,0.5,92383,91496,0.5,0.5,9.329833e+04,93296.25
45,Oklahoma ...................,191872,189264,187795,182688,183061,185602,1.1,1.1,1.0,1.0,1.0,1.0,183112,180399,1.0,1.0,1.867237e+05,182937.50
46,Texas .........................,1620571,1620968,1611183,1603648,1623503,1652657,9.2,9.1,8.9,8.7,8.7,8.8,1592033,1587395,8.8,8.7,1.608061e+06,1616800.75
47,Rocky Mountain ............,605555,613147,616369,624954,636667,643739,3.4,3.4,3.4,3.4,3.4,3.4,617524,619325,3.4,3.4,6.156800e+05,631171.25
48,Colorado ....................,309993,313303,314546,320634,327333,330319,1.8,1.8,1.7,1.7,1.8,1.8,315475,316481,1.7,1.7,3.144413e+05,323691.75
49,Idaho ..........................,64856,65342,65884,66927,67714,68450,0.4,0.4,0.4,0.4,0.4,0.4,65760,66010,0.4,0.4,6.566200e+04,67275.25
50,Montana .....................,45186,46207,46119,45642,46041,46506,0.3,0.3,0.3,0.2,0.2,0.2,45868,45789,0.3,0.3,4.606467e+04,45994.50
51,Utah ..........................,145982,148314,150215,154182,157802,160002,0.8,0.8,0.8,0.8,0.9,0.9,151884,153422,0.8,0.8,1.501377e+05,156352.00
52,Wyoming ....................,39538,39981,39604,37569,37777,38463,0.2,0.2,0.2,0.2,0.2,0.2,38537,37622,0.2,0.2,3.937400e+04,37857.75
53,Far West ......................,3366368,3419789,3450939,3552236,3610452,3650211,19.1,NaN,19.1,NaN,19.5,19.5,3481350,3512447,19.2,19.3,3.450693e+06,3581336.50
54,Alaska ........................,53997,54615,53155,50545,50742,51506,0.3,0.3,0.3,0.3,0.3,0.3,51770,50059,0.3,0.3,5.318000e+04,50713.00
55,California ....................,2444063,2485470,2505638,2581572,2627083,2656080,13.8,NaN,13.9,NaN,14.2,14.2,2531304,2545953,14.0,14.0,2.507471e+06,2602672.00
56,Hawaii .......................,79538,80302,80907,83548,84325,84889,0.5,0.4,0.4,0.5,0.5,0.5,81650,82904,0.5,0.5,8.095300e+04,83916.50
57,Nevada ......................,137533,140194,142952,145068,149913,151348,0.8,0.8,0.8,0.8,0.8,0.8,143602,143572,0.8,0.8,1.422493e+05,147475.25
58,Oregon .......................,212763,214687,218660,225947,227316,229837,1.2,1.2,1.2,1.2,1.2,1.2,219979,224181,1.2,1.2,2.177753e+05,226820.25
59,Washington ................,438475,444522,449627,465556,471073,476550,2.5,2.5,2.5,2.5,2.5,2.5,453045,465779,2.5,2.6,4.490647e+05,469739.50

In [79]:
GDP2015_2016 = QuarterlyGDP('GDP2015-2016_quarterly.pdf', 10, 2015, 2016, '2016')

In [80]:
GDP2015_2016.df = GDP15_16

In [81]:
GDP2015_2016.df

,Area,2015 Q1,2015 Q2,2015 Q3,2016 Q2,2016 Q3,2016 Q4,2015 Q1 %,2015 Q2 %,2015 Q3 %,2016 Q2 %,2016 Q3 %,2016 Q4 %,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %,2015,2016
0,United States,..........................17671025,17886695,18030967,18337791,18561915,18755370,100.0,NaN,100.0,NaN,100.0,100.0,18111878,18170091,100.0,100.0,1.800985e+07,18456291.75
1,New England .....................,941945,959027,964703,990080,1002400,1012104,5.3,5.4,5.4,5.4,5.4,5.4,982152,983200,5.4,5.4,9.686273e+05,996946.00
2,Connecticut ................,250628,256514,257895,262341,263973,266597,1.4,1.4,1.4,1.4,1.4,1.4,260185,260604,1.4,1.4,2.581980e+05,263378.75
3,Maine ........................,55930,57230,57716,59224,59478,59857,0.3,0.3,0.3,0.3,0.3,0.3,58453,58540,0.3,0.3,5.779967e+04,59274.75
4,Massachusetts ............,478320,485938,487509,503357,511392,516483,2.7,2.7,2.7,2.7,2.8,2.8,500634,500418,2.8,2.8,4.913603e+05,507912.50
5,New Hampshire ...........,72395,73810,75038,77201,78329,79155,0.4,0.4,0.4,0.4,0.4,0.4,75833,76737,0.4,0.4,7.489367e+04,77855.50
6,Rhode Island ..............,54858,55401,55884,57099,58017,58527,0.3,0.3,0.3,0.3,0.3,0.3,56457,56087,0.3,0.3,5.591400e+04,57432.50
7,Vermont .....................,29815,30135,30660,30859,31211,31483,0.2,0.2,0.2,0.2,0.2,0.2,30591,30814,0.2,0.2,3.046200e+04,31091.75
8,Mideast .......................,3223326,3270682,3302756,3358622,3381370,3408478,18.2,NaN,18.3,NaN,18.2,18.2,3301626,3329683,18.2,18.3,3.291688e+06,3369538.25
9,Delaware ....................,68216,68898,69086,69747,71080,71769,0.4,0.4,0.4,0.4,0.4,0.4,69256,68952,0.4,0.4,6.908000e+04,70387.00
10,District of Columbia .....,120100,121210,121295,126100,127208,128597,0.7,0.7,0.7,0.7,0.7,0.7,121870,125356,0.7,0.7,1.214583e+05,126815.25
11,Maryland ....................,361870,363936,366991,376578,380950,384386,2.0,2.0,2.0,2.1,2.1,2.0,372169,371205,2.1,2.0,3.676987e+05,378279.75
12,New Jersey ................,547279,565951,571204,577703,583804,588706,3.1,3.2,3.2,3.2,3.1,3.1,573006,574277,3.2,3.2,5.700537e+05,581122.50
13,New York ...................,1427065,1445357,1462516,1489457,1486075,1494981,8.1,8.1,8.1,8.1,8.0,8.0,1447505,1481479,8.0,8.2,1.451793e+06,1487998.00
14,Pennsylvania ...............,698796,705330,711663,719037,732252,740039,4.0,3.9,3.9,3.9,3.9,3.9,717821,708415,4.0,3.9,7.116047e+05,724935.75
15,Great Lakes .................,2448105,2473845,2499169,2541207,2568564,2593179,13.9,NaN,13.9,NaN,13.8,13.8,2519159,2521077,13.9,13.9,2.497391e+06,2556006.75
16,Illinois .......................,763309,766689,778688,787470,791450,798999,4.3,4.3,4.3,4.3,4.3,4.3,780040,788510,4.3,4.3,7.751390e+05,791607.25
17,Indiana ......................,327996,333135,334536,339900,343721,346591,1.9,1.9,1.9,1.9,1.9,1.8,337786,337423,1.9,1.9,3.351523e+05,341908.75
18,Michigan ....................,460714,468784,473861,485680,490342,495300,2.6,2.6,2.6,2.6,2.6,2.6,479085,477634,2.6,2.6,4.739100e+05,487239.00
19,Ohio ..........................,599820,605409,608502,621138,631347,638185,3.4,3.4,3.4,3.4,3.4,3.4,615575,612191,3.4,3.4,6.098287e+05,625715.25
20,Wisconsin ..................,296267,299828,303582,307019,311704,314104,1.7,1.7,1.7,1.7,1.7,1.7,306673,305319,1.7,1.7,3.033610e+05,309536.50
21,Plains ..........................,1147993,1161066,1171307,1177073,1190606,1199789,6.5,6.5,6.5,6.4,6.4,6.4,1174283,1167069,6.5,6.4,1.168885e+06,1183634.25
22,Iowa ..........................,172410,175098,177491,177667,179944,181007,1.0,1.0,1.0,1.0,1.0,1.0,178238,176443,1.0,1.0,1.769423e+05,178765.25
23,Kansas ......................,148490,152674,153489,152822,153801,154574,0.8,0.9,0.9,0.8,0.8,0.8,152725,151833,0.8,0.8,1.529627e+05,153257.50
24,Minnesota ..................,324022,324510,326873,331958,338304,341318,1.8,1.8,1.8,1.8,1.8,1.8,331926,329008,1.8,1.8,3.277697e+05,335147.00
25,Missouri .....................,288381,292194,294997,299897,301824,304431,1.6,1.6,1.6,1.6,1.6,1.6,295298,297412,1.6,1.6,2.941630e+05,300891.00
26,Nebraska ...................,111411,113604,114836,114805,116025,116769,0.6,0.6,0.6,0.6,0.6,0.6,113982,113782,0.6,0.6,1.141407e+05,115345.25
27,North Dakota ...............,57402,56560,55719,52015,52096,52796,0.3,0.3,0.3,0.3,0.3,0.3,54027,51450,0.3,0.3,5.543533e+04,52089.25
28,South Dakota ..............,45878,46426,47903,47908,48612,48893,0.3,0.3,0.3,0.3,0.3,0.3,48086,47142,0.3,0.3,4.747167e+04,48138.75
29,Southeast .....................,3745076,3794648,3840495,3914726,3964744,4005534,21.2,NaN,21.3,NaN,21.4,21.4,3872660,3881685,21.4,21.4,3.835934e+06,3941672.25
30,Alabama ....................,196820,199677,201498,204232,205307,207608,1.1,1.1,1.1,1.1,1.1,1.1,201926,202298,1.1,1.1,2.010337e+05,204861.25
31,Arkansas ...................,117064,118592,119560,120704,120683,121448,0.7,0.7,0.7,0.7,0.7,0.6,119492,119920,0.7,0.7,1.192147e+05,120688.75
32,Florida ........................,866212,875944,889512,917885,935927,947007,4.9,4.9,4.9,5.0,5.0,5.0,903778,906448,5.0,5.0,8.897447e+05,926816.75
33,Georgia .....................,491481,498673,505437,520479,527705,532805,2.8,2.8,2.8,2.8,2.8,2.8,510496,520453,2.8,2.9,5.048687e+05,525360.50
34,Kentucky ...................,188148,191427,193072,195685,199550,201545,1.1,1.1,1.1,1.1,1.1,1.1,194942,191394,1.1,1.1,1.931470e+05,197043.50
35,Louisiana ....................,239704,239172,238492,234573,234905,237569,1.4,1.3,1.3,1.3,1.3,1.3,234932,233388,1.3,1.3,2.375320e+05,235108.75
36,Mississippi .................,104325,105635,106684,107397,107683,108215,0.6,0.6,0.6,0.6,0.6,0.6,106841,107425,0.6,0.6,1.063867e+05,107680.00
37,North Carolina ..............,490176,496874,503657,514182,521265,526809,2.8,2.8,2.8,2.8,2.8,2.8,508257,509358,2.8,2.8,5.029293e+05,517903.50
38,South Carolina ............,197475,200135,203438,209032,210589,212529,1.1,1.1,1.1,1.1,1.1,1.1,206274,206715,1.1,1.1,2.032823e+05,209716.25
39,Tennessee ..................,309207,314661,319867,326262,330988,333966,1.7,1.8,1.8,1.8,1.8,1.8,322900,323864,1.8,1.8,3.191427e+05,328770.00
40,Virginia .......................,471999,479776,485306,491669,496244,500833,2.7,2.7,2.7,2.7,2.7,2.7,489805,488650,2.7,2.7,4.849623e+05,494349.00
41,West Virginia ..............,72465,74081,73971,72625,73898,75199,0.4,0.4,0.4,0.4,0.4,0.4,73019,71772,0.4,0.4,7.369033e+04,73373.50
42,Southwest ....................,2192658,2194494,2185231,2178893,2207112,2242336,12.4,NaN,12.1,NaN,11.9,12.0,2163126,2155605,11.9,11.9,2.180950e+06,2195986.50
43,Arizona .......................,287190,290463,292540,299626,306764,309103,1.6,1.6,1.6,1.6,1.7,1.6,295597,296314,1.6,1.6,2.928667e+05,302951.75
44,New Mexico ................,93025,93799,93713,92931,93784,94974,0.5,0.5,0.5,0.5,0.5,0.5,92383,91496,0.5,0.5,9.329833e+04,93296.25
45,Oklahoma ...................,191872,189264,187795,182688,183061,185602,1.1,1.1,1.0,1.0,1.0,1.0,183112,180399,1.0,1.0,1.867237e+05,182937.50
46,Texas .........................,1620571,1620968,1611183,1603648,1623503,1652657,9.2,9.1,8.9,8.7,8.7,8.8,1592033,1587395,8.8,8.7,1.608061e+06,1616800.75
47,Rocky Mountain ............,605555,613147,616369,624954,636667,643739,3.4,3.4,3.4,3.4,3.4,3.4,617524,619325,3.4,3.4,6.156800e+05,631171.25
48,Colorado ....................,309993,313303,314546,320634,327333,330319,1.8,1.8,1.7,1.7,1.8,1.8,315475,316481,1.7,1.7,3.144413e+05,323691.75
49,Idaho ..........................,64856,65342,65884,66927,67714,68450,0.4,0.4,0.4,0.4,0.4,0.4,65760,66010,0.4,0.4,6.566200e+04,67275.25
50,Montana .....................,45186,46207,46119,45642,46041,46506,0.3,0.3,0.3,0.2,0.2,0.2,45868,45789,0.3,0.3,4.606467e+04,45994.50
51,Utah ..........................,145982,148314,150215,154182,157802,160002,0.8,0.8,0.8,0.8,0.9,0.9,151884,153422,0.8,0.8,1.501377e+05,156352.00
52,Wyoming ....................,39538,39981,39604,37569,37777,38463,0.2,0.2,0.2,0.2,0.2,0.2,38537,37622,0.2,0.2,3.937400e+04,37857.75
53,Far West ......................,3366368,3419789,3450939,3552236,3610452,3650211,19.1,NaN,19.1,NaN,19.5,19.5,3481350,3512447,19.2,19.3,3.450693e+06,3581336.50
54,Alaska ........................,53997,54615,53155,50545,50742,51506,0.3,0.3,0.3,0.3,0.3,0.3,51770,50059,0.3,0.3,5.318000e+04,50713.00
55,California ....................,2444063,2485470,2505638,2581572,2627083,2656080,13.8,NaN,13.9,NaN,14.2,14.2,2531304,2545953,14.0,14.0,2.507471e+06,2602672.00
56,Hawaii .......................,79538,80302,80907,83548,84325,84889,0.5,0.4,0.4,0.5,0.5,0.5,81650,82904,0.5,0.5,8.095300e+04,83916.50
57,Nevada ......................,137533,140194,142952,145068,149913,151348,0.8,0.8,0.8,0.8,0.8,0.8,143602,143572,0.8,0.8,1.422493e+05,147475.25
58,Oregon .......................,212763,214687,218660,225947,227316,229837,1.2,1.2,1.2,1.2,1.2,1.2,219979,224181,1.2,1.2,2.177753e+05,226820.25
59,Washington ................,438475,444522,449627,465556,471073,476550,2.5,2.5,2.5,2.5,2.5,2.5,453045,465779,2.5,2.6,4.490647e+05,469739.50

In [82]:
GDP2015_2016.cleanStates()

,Area,2015 Q1,2015 Q2,2015 Q3,2016 Q2,2016 Q3,2016 Q4,2015 Q1 %,2015 Q2 %,2015 Q3 %,2016 Q2 %,2016 Q3 %,2016 Q4 %,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %,2015,2016,Cleaned Area
0,United States,..........................17671025,17886695,18030967,18337791,18561915,18755370,100.0,NaN,100.0,NaN,100.0,100.0,18111878,18170091,100.0,100.0,1.800985e+07,18456291.75,United States
1,New England .....................,941945,959027,964703,990080,1002400,1012104,5.3,5.4,5.4,5.4,5.4,5.4,982152,983200,5.4,5.4,9.686273e+05,996946.00,New England
2,Connecticut ................,250628,256514,257895,262341,263973,266597,1.4,1.4,1.4,1.4,1.4,1.4,260185,260604,1.4,1.4,2.581980e+05,263378.75,Connecticut
3,Maine ........................,55930,57230,57716,59224,59478,59857,0.3,0.3,0.3,0.3,0.3,0.3,58453,58540,0.3,0.3,5.779967e+04,59274.75,Maine
4,Massachusetts ............,478320,485938,487509,503357,511392,516483,2.7,2.7,2.7,2.7,2.8,2.8,500634,500418,2.8,2.8,4.913603e+05,507912.50,Massachusetts
5,New Hampshire ...........,72395,73810,75038,77201,78329,79155,0.4,0.4,0.4,0.4,0.4,0.4,75833,76737,0.4,0.4,7.489367e+04,77855.50,New Hampshire
6,Rhode Island ..............,54858,55401,55884,57099,58017,58527,0.3,0.3,0.3,0.3,0.3,0.3,56457,56087,0.3,0.3,5.591400e+04,57432.50,Rhode Island
7,Vermont .....................,29815,30135,30660,30859,31211,31483,0.2,0.2,0.2,0.2,0.2,0.2,30591,30814,0.2,0.2,3.046200e+04,31091.75,Vermont
8,Mideast .......................,3223326,3270682,3302756,3358622,3381370,3408478,18.2,NaN,18.3,NaN,18.2,18.2,3301626,3329683,18.2,18.3,3.291688e+06,3369538.25,Mideast
9,Delaware ....................,68216,68898,69086,69747,71080,71769,0.4,0.4,0.4,0.4,0.4,0.4,69256,68952,0.4,0.4,6.908000e+04,70387.00,Delaware
10,District of Columbia .....,120100,121210,121295,126100,127208,128597,0.7,0.7,0.7,0.7,0.7,0.7,121870,125356,0.7,0.7,1.214583e+05,126815.25,District of Columbia
11,Maryland ....................,361870,363936,366991,376578,380950,384386,2.0,2.0,2.0,2.1,2.1,2.0,372169,371205,2.1,2.0,3.676987e+05,378279.75,Maryland
12,New Jersey ................,547279,565951,571204,577703,583804,588706,3.1,3.2,3.2,3.2,3.1,3.1,573006,574277,3.2,3.2,5.700537e+05,581122.50,New Jersey
13,New York ...................,1427065,1445357,1462516,1489457,1486075,1494981,8.1,8.1,8.1,8.1,8.0,8.0,1447505,1481479,8.0,8.2,1.451793e+06,1487998.00,New York
14,Pennsylvania ...............,698796,705330,711663,719037,732252,740039,4.0,3.9,3.9,3.9,3.9,3.9,717821,708415,4.0,3.9,7.116047e+05,724935.75,Pennsylvania
15,Great Lakes .................,2448105,2473845,2499169,2541207,2568564,2593179,13.9,NaN,13.9,NaN,13.8,13.8,2519159,2521077,13.9,13.9,2.497391e+06,2556006.75,Great Lakes
16,Illinois .......................,763309,766689,778688,787470,791450,798999,4.3,4.3,4.3,4.3,4.3,4.3,780040,788510,4.3,4.3,7.751390e+05,791607.25,Illinois
17,Indiana ......................,327996,333135,334536,339900,343721,346591,1.9,1.9,1.9,1.9,1.9,1.8,337786,337423,1.9,1.9,3.351523e+05,341908.75,Indiana
18,Michigan ....................,460714,468784,473861,485680,490342,495300,2.6,2.6,2.6,2.6,2.6,2.6,479085,477634,2.6,2.6,4.739100e+05,487239.00,Michigan
19,Ohio ..........................,599820,605409,608502,621138,631347,638185,3.4,3.4,3.4,3.4,3.4,3.4,615575,612191,3.4,3.4,6.098287e+05,625715.25,Ohio
20,Wisconsin ..................,296267,299828,303582,307019,311704,314104,1.7,1.7,1.7,1.7,1.7,1.7,306673,305319,1.7,1.7,3.033610e+05,309536.50,Wisconsin
21,Plains ..........................,1147993,1161066,1171307,1177073,1190606,1199789,6.5,6.5,6.5,6.4,6.4,6.4,1174283,1167069,6.5,6.4,1.168885e+06,1183634.25,Plains
22,Iowa ..........................,172410,175098,177491,177667,179944,181007,1.0,1.0,1.0,1.0,1.0,1.0,178238,176443,1.0,1.0,1.769423e+05,178765.25,Iowa
23,Kansas ......................,148490,152674,153489,152822,153801,154574,0.8,0.9,0.9,0.8,0.8,0.8,152725,151833,0.8,0.8,1.529627e+05,153257.50,Kansas
24,Minnesota ..................,324022,324510,326873,331958,338304,341318,1.8,1.8,1.8,1.8,1.8,1.8,331926,329008,1.8,1.8,3.277697e+05,335147.00,Minnesota
25,Missouri .....................,288381,292194,294997,299897,301824,304431,1.6,1.6,1.6,1.6,1.6,1.6,295298,297412,1.6,1.6,2.941630e+05,300891.00,Missouri
26,Nebraska ...................,111411,113604,114836,114805,116025,116769,0.6,0.6,0.6,0.6,0.6,0.6,113982,113782,0.6,0.6,1.141407e+05,115345.25,Nebraska
27,North Dakota ...............,57402,56560,55719,52015,52096,52796,0.3,0.3,0.3,0.3,0.3,0.3,54027,51450,0.3,0.3,5.543533e+04,52089.25,North Dakota
28,South Dakota ..............,45878,46426,47903,47908,48612,48893,0.3,0.3,0.3,0.3,0.3,0.3,48086,47142,0.3,0.3,4.747167e+04,48138.75,South Dakota
29,Southeast .....................,3745076,3794648,3840495,3914726,3964744,4005534,21.2,NaN,21.3,NaN,21.4,21.4,3872660,3881685,21.4,21.4,3.835934e+06,3941672.25,Southeast
30,Alabama ....................,196820,199677,201498,204232,205307,207608,1.1,1.1,1.1,1.1,1.1,1.1,201926,202298,1.1,1.1,2.010337e+05,204861.25,Alabama
31,Arkansas ...................,117064,118592,119560,120704,120683,121448,0.7,0.7,0.7,0.7,0.7,0.6,119492,119920,0.7,0.7,1.192147e+05,120688.75,Arkansas
32,Florida ........................,866212,875944,889512,917885,935927,947007,4.9,4.9,4.9,5.0,5.0,5.0,903778,906448,5.0,5.0,8.897447e+05,926816.75,Florida
33,Georgia .....................,491481,498673,505437,520479,527705,532805,2.8,2.8,2.8,2.8,2.8,2.8,510496,520453,2.8,2.9,5.048687e+05,525360.50,Georgia
34,Kentucky ...................,188148,191427,193072,195685,199550,201545,1.1,1.1,1.1,1.1,1.1,1.1,194942,191394,1.1,1.1,1.931470e+05,197043.50,Kentucky
35,Louisiana ....................,239704,239172,238492,234573,234905,237569,1.4,1.3,1.3,1.3,1.3,1.3,234932,233388,1.3,1.3,2.375320e+05,235108.75,Louisiana
36,Mississippi .................,104325,105635,106684,107397,107683,108215,0.6,0.6,0.6,0.6,0.6,0.6,106841,107425,0.6,0.6,1.063867e+05,107680.00,Mississippi
37,North Carolina ..............,490176,496874,503657,514182,521265,526809,2.8,2.8,2.8,2.8,2.8,2.8,508257,509358,2.8,2.8,5.029293e+05,517903.50,North Carolina
38,South Carolina ............,197475,200135,203438,209032,210589,212529,1.1,1.1,1.1,1.1,1.1,1.1,206274,206715,1.1,1.1,2.032823e+05,209716.25,South Carolina
39,Tennessee ..................,309207,314661,319867,326262,330988,333966,1.7,1.8,1.8,1.8,1.8,1.8,322900,323864,1.8,1.8,3.191427e+05,328770.00,Tennessee
40,Virginia .......................,471999,479776,485306,491669,496244,500833,2.7,2.7,2.7,2.7,2.7,2.7,489805,488650,2.7,2.7,4.849623e+05,494349.00,Virginia
41,West Virginia ..............,72465,74081,73971,72625,73898,75199,0.4,0.4,0.4,0.4,0.4,0.4,73019,71772,0.4,0.4,7.369033e+04,73373.50,West Virginia
42,Southwest ....................,2192658,2194494,2185231,2178893,2207112,2242336,12.4,NaN,12.1,NaN,11.9,12.0,2163126,2155605,11.9,11.9,2.180950e+06,2195986.50,Southwest
43,Arizona .......................,287190,290463,292540,299626,306764,309103,1.6,1.6,1.6,1.6,1.7,1.6,295597,296314,1.6,1.6,2.928667e+05,302951.75,Arizona
44,New Mexico ................,93025,93799,93713,92931,93784,94974,0.5,0.5,0.5,0.5,0.5,0.5,92383,91496,0.5,0.5,9.329833e+04,93296.25,New Mexico
45,Oklahoma ...................,191872,189264,187795,182688,183061,185602,1.1,1.1,1.0,1.0,1.0,1.0,183112,180399,1.0,1.0,1.867237e+05,182937.50,Oklahoma
46,Texas .........................,1620571,1620968,1611183,1603648,1623503,1652657,9.2,9.1,8.9,8.7,8.7,8.8,1592033,1587395,8.8,8.7,1.608061e+06,1616800.75,Texas
47,Rocky Mountain ............,605555,613147,616369,624954,636667,643739,3.4,3.4,3.4,3.4,3.4,3.4,617524,619325,3.4,3.4,6.156800e+05,631171.25,Rocky Mountain
48,Colorado ....................,309993,313303,314546,320634,327333,330319,1.8,1.8,1.7,1.7,1.8,1.8,315475,316481,1.7,1.7,3.144413e+05,323691.75,Colorado
49,Idaho ..........................,64856,65342,65884,66927,67714,68450,0.4,0.4,0.4,0.4,0.4,0.4,65760,66010,0.4,0.4,6.566200e+04,67275.25,Idaho
50,Montana .....................,45186,46207,46119,45642,46041,46506,0.3,0.3,0.3,0.2,0.2,0.2,45868,45789,0.3,0.3,4.606467e+04,45994.50,Montana
51,Utah ..........................,145982,148314,150215,154182,157802,160002,0.8,0.8,0.8,0.8,0.9,0.9,151884,153422,0.8,0.8,1.501377e+05,156352.00,Utah
52,Wyoming ....................,39538,39981,39604,37569,37777,38463,0.2,0.2,0.2,0.2,0.2,0.2,38537,37622,0.2,0.2,3.937400e+04,37857.75,Wyoming
53,Far West ......................,3366368,3419789,3450939,3552236,3610452,3650211,19.1,NaN,19.1,NaN,19.5,19.5,3481350,3512447,19.2,19.3,3.450693e+06,3581336.50,Far West
54,Alaska ........................,53997,54615,53155,50545,50742,51506,0.3,0.3,0.3,0.3,0.3,0.3,51770,50059,0.3,0.3,5.318000e+04,50713.00,Alaska
55,California ....................,2444063,2485470,2505638,2581572,2627083,2656080,13.8,NaN,13.9,NaN,14.2,14.2,2531304,2545953,14.0,14.0,2.507471e+06,2602672.00,California
56,Hawaii .......................,79538,80302,80907,83548,84325,84889,0.5,0.4,0.4,0.5,0.5,0.5,81650,82904,0.5,0.5,8.095300e+04,83916.50,Hawaii
57,Nevada ......................,137533,140194,142952,145068,149913,151348,0.8,0.8,0.8,0.8,0.8,0.8,143602,143572,0.8,0.8,1.422493e+05,147475.25,Nevada
58,Oregon .......................,212763,214687,218660,225947,227316,229837,1.2,1.2,1.2,1.2,1.2,1.2,219979,224181,1.2,1.2,2.177753e+05,226820.25,Oregon
59,Washington ................,438475,444522,449627,465556,471073,476550,2.5,2.5,2.5,2.5,2.5,2.5,453045,465779,2.5,2.6,4.490647e+05,469739.50,Washington

In [83]:
GDP2015_2016.addGeoLocColumn()

,Area,2015 Q1,2015 Q2,2015 Q3,2016 Q2,2016 Q3,2016 Q4,2015 Q1 %,2015 Q2 %,2015 Q3 %,...,2016 Q3 %,2016 Q4 %,2015 Q4,2016 Q1,2015 Q4 %,2016 Q1 %,2015,2016,Cleaned Area,Geo Loc
0,United States,..........................17671025,17886695,18030967,18337791,18561915,18755370,100.0,NaN,100.0,...,100.0,100.0,18111878,18170091,100.0,100.0,1.800985e+07,18456291.75,United States,NaN
1,New England .....................,941945,959027,964703,990080,1002400,1012104,5.3,5.4,5.4,...,5.4,5.4,982152,983200,5.4,5.4,9.686273e+05,996946.00,New England,NaN
2,Connecticut ................,250628,256514,257895,262341,263973,266597,1.4,1.4,1.4,...,1.4,1.4,260185,260604,1.4,1.4,2.581980e+05,263378.75,Connecticut,New England
3,Maine ........................,55930,57230,57716,59224,59478,59857,0.3,0.3,0.3,...,0.3,0.3,58453,58540,0.3,0.3,5.779967e+04,59274.75,Maine,New England
4,Massachusetts ............,478320,485938,487509,503357,511392,516483,2.7,2.7,2.7,...,2.8,2.8,500634,500418,2.8,2.8,4.913603e+05,507912.50,Massachusetts,New England
5,New Hampshire ...........,72395,73810,75038,77201,78329,79155,0.4,0.4,0.4,...,0.4,0.4,75833,76737,0.4,0.4,7.489367e+04,77855.50,New Hampshire,New England
6,Rhode Island ..............,54858,55401,55884,57099,58017,58527,0.3,0.3,0.3,...,0.3,0.3,56457,56087,0.3,0.3,5.591400e+04,57432.50,Rhode Island,New England
7,Vermont .....................,29815,30135,30660,30859,31211,31483,0.2,0.2,0.2,...,0.2,0.2,30591,30814,0.2,0.2,3.046200e+04,31091.75,Vermont,New England
8,Mideast .......................,3223326,3270682,3302756,3358622,3381370,3408478,18.2,NaN,18.3,...,18.2,18.2,3301626,3329683,18.2,18.3,3.291688e+06,3369538.25,Mideast,NaN
9,Delaware ....................,68216,68898,69086,69747,71080,71769,0.4,0.4,0.4,...,0.4,0.4,69256,68952,0.4,0.4,6.908000e+04,70387.00,Delaware,Mideast
10,District of Columbia .....,120100,121210,121295,126100,127208,128597,0.7,0.7,0.7,...,0.7,0.7,121870,125356,0.7,0.7,1.214583e+05,126815.25,District of Columbia,Mideast
11,Maryland ....................,361870,363936,366991,376578,380950,384386,2.0,2.0,2.0,...,2.1,2.0,372169,371205,2.1,2.0,3.676987e+05,378279.75,Maryland,Mideast
12,New Jersey ................,547279,565951,571204,577703,583804,588706,3.1,3.2,3.2,...,3.1,3.1,573006,574277,3.2,3.2,5.700537e+05,581122.50,New Jersey,Mideast
13,New York ...................,1427065,1445357,1462516,1489457,1486075,1494981,8.1,8.1,8.1,...,8.0,8.0,1447505,1481479,8.0,8.2,1.451793e+06,1487998.00,New York,Mideast
14,Pennsylvania ...............,698796,705330,711663,719037,732252,740039,4.0,3.9,3.9,...,3.9,3.9,717821,708415,4.0,3.9,7.116047e+05,724935.75,Pennsylvania,Mideast
15,Great Lakes .................,2448105,2473845,2499169,2541207,2568564,2593179,13.9,NaN,13.9,...,13.8,13.8,2519159,2521077,13.9,13.9,2.497391e+06,2556006.75,Great Lakes,NaN
16,Illinois .......................,763309,766689,778688,787470,791450,798999,4.3,4.3,4.3,...,4.3,4.3,780040,788510,4.3,4.3,7.751390e+05,791607.25,Illinois,Great Lakes
17,Indiana ......................,327996,333135,334536,339900,343721,346591,1.9,1.9,1.9,...,1.9,1.8,337786,337423,1.9,1.9,3.351523e+05,341908.75,Indiana,Great Lakes
18,Michigan ....................,460714,468784,473861,485680,490342,495300,2.6,2.6,2.6,...,2.6,2.6,479085,477634,2.6,2.6,4.739100e+05,487239.00,Michigan,Great Lakes
19,Ohio ..........................,599820,605409,608502,621138,631347,638185,3.4,3.4,3.4,...,3.4,3.4,615575,612191,3.4,3.4,6.098287e+05,625715.25,Ohio,Great Lakes
20,Wisconsin ..................,296267,299828,303582,307019,311704,314104,1.7,1.7,1.7,...,1.7,1.7,306673,305319,1.7,1.7,3.033610e+05,309536.50,Wisconsin,Great Lakes
21,Plains ..........................,1147993,1161066,1171307,1177073,1190606,1199789,6.5,6.5,6.5,...,6.4,6.4,1174283,1167069,6.5,6.4,1.168885e+06,1183634.25,Plains,NaN
22,Iowa ..........................,172410,175098,177491,177667,179944,181007,1.0,1.0,1.0,...,1.0,1.0,178238,176443,1.0,1.0,1.769423e+05,178765.25,Iowa,Plains
23,Kansas ......................,148490,152674,153489,152822,153801,154574,0.8,0.9,0.9,...,0.8,0.8,152725,151833,0.8,0.8,1.529627e+05,153257.50,Kansas,Plains
24,Minnesota ..................,324022,324510,326873,331958,338304,341318,1.8,1.8,1.8,...,1.8,1.8,331926,329008,1.8,1.8,3.277697e+05,335147.00,Minnesota,Plains
25,Missouri .....................,288381,292194,294997,299897,301824,304431,1.6,1.6,1.6,...,1.6,1.6,295298,297412,1.6,1.6,2.941630e+05,300891.00,Missouri,Plains
26,Nebraska ...................,111411,113604,114836,114805,116025,116769,0.6,0.6,0.6,...,0.6,0.6,113982,113782,0.6,0.6,1.141407e+05,115345.25,Nebraska,Plains
27,North Dakota ...............,57402,56560,55719,52015,52096,52796,0.3,0.3,0.3,...,0.3,0.3,54027,51450,0.3,0.3,5.543533e+04,52089.25,North Dakota,Plains
28,South Dakota ..............,45878,46426,47903,47908,48612,48893,0.3,0.3,0.3,...,0.3,0.3,48086,47142,0.3,0.3,4.747167e+04,48138.75,South Dakota,Plains
29,Southeast .....................,3745076,3794648,3840495,3914726,3964744,4005534,21.2,NaN,21.3,...,21.4,21.4,3872660,3881685,21.4,21.4,3.835934e+06,3941672.25,Southeast,NaN
30,Alabama ....................,196820,199677,201498,204232,205307,207608,1.1,1.1,1.1,...,1.1,1.1,201926,202298,1.1,1.1,2.010337e+05,204861.25,Alabama,Southeast
31,Arkansas ...................,117064,118592,119560,120704,120683,121448,0.7,0.7,0.7,...,0.7,0.6,119492,119920,0.7,0.7,1.192147e+05,120688.75,Arkansas,Southeast
32,Florida ........................,866212,875944,889512,917885,935927,947007,4.9,4.9,4.9,...,5.0,5.0,903778,906448,5.0,5.0,8.897447e+05,926816.75,Florida,Southeast
33,Georgia .....................,491481,498673,505437,520479,527705,532805,2.8,2.8,2.8,...,2.8,2.8,510496,520453,2.8,2.9,5.048687e+05,525360.50,Georgia,Southeast
34,Kentucky ...................,188148,191427,193072,195685,199550,201545,1.1,1.1,1.1,...,1.1,1.1,194942,191394,1.1,1.1,1.931470e+05,197043.50,Kentucky,Southeast
35,Louisiana ....................,239704,239172,238492,234573,234905,237569,1.4,1.3,1.3,...,1.3,1.3,234932,233388,1.3,1.3,2.375320e+05,235108.75,Louisiana,Southeast
36,Mississippi .................,104325,105635,106684,107397,107683,108215,0.6,0.6,0.6,...,0.6,0.6,106841,107425,0.6,0.6,1.063867e+05,107680.00,Mississippi,Southeast
37,North Carolina ..............,490176,496874,503657,514182,521265,526809,2.8,2.8,2.8,...,2.8,2.8,508257,509358,2.8,2.8,5.029293e+05,517903.50,North Carolina,Southeast
38,South Carolina ............,197475,200135,203438,209032,210589,212529,1.1,1.1,1.1,...,1.1,1.1,206274,206715,1.1,1.1,2.032823e+05,209716.25,South Carolina,Southeast
39,Tennessee ..................,309207,314661,319867,326262,330988,333966,1.7,1.8,1.8,...,1.8,1.8,322900,323864,1.8,1.8,3.191427e+05,328770.00,Tennessee,Southeast
40,Virginia .......................,471999,479776,485306,491669,496244,500833,2.7,2.7,2.7,...,2.7,2.7,489805,488650,2.7,2.7,4.849623e+05,494349.00,Virginia,Southeast
41,West Virginia ..............,72465,74081,73971,72625,73898,75199,0.4,0.4,0.4,...,0.4,0.4,73019,71772,0.4,0.4,7.369033e+04,73373.50,West Virginia,Southeast
42,Southwest ....................,2192658,2194494,2185231,2178893,2207112,2242336,12.4,NaN,12.1,...,11.9,12.0,2163126,2155605,11.9,11.9,2.180950e+06,2195986.50,Southwest,NaN
43,Arizona .......................,287190,290463,292540,299626,306764,309103,1.6,1.6,1.6,...,1.7,1.6,295597,296314,1.6,1.6,2.928667e+05,302951.75,Arizona,Southwest
44,New Mexico ................,93025,93799,93713,92931,93784,94974,0.5,0.5,0.5,...,0.5,0.5,92383,91496,0.5,0.5,9.329833e+04,93296.25,New Mexico,Southwest
45,Oklahoma ...................,191872,189264,187795,182688,183061,185602,1.1,1.1,1.0,...,1.0,1.0,183112,180399,1.0,1.0,1.867237e+05,182937.50,Oklahoma,Southwest
46,Texas .........................,1620571,1620968,1611183,1603648,1623503,1652657,9.2,9.1,8.9,...,8.7,8.8,1592033,1587395,8.8,8.7,1.608061e+06,1616800.75,Texas,Southwest
47,Rocky Mountain ............,605555,613147,616369,624954,636667,643739,3.4,3.4,3.4,...,3.4,3.4,617524,619325,3.4,3.4,6.156800e+05,631171.25,Rocky Mountain,NaN
48,Colorado ....................,309993,313303,314546,320634,327333,330319,1.8,1.8,1.7,...,1.8,1.8,315475,316481,1.7,1.7,3.144413e+05,323691.75,Colorado,Rocky Mountain
49,Idaho ..........................,64856,65342,65884,66927,67714,68450,0.4,0.4,0.4,...,0.4,0.4,65760,66010,0.4,0.4,6.566200e+04,67275.25,Idaho,Rocky Mountain
50,Montana .....................,45186,46207,46119,45642,46041,46506,0.3,0.3,0.3,...,0.2,0.2,45868,45789,0.3,0.3,4.606467e+04,45994.50,Montana,Rocky Mountain
51,Utah ..........................,145982,148314,150215,154182,157802,160002,0.8,0.8,0.8,...,0.9,0.9,151884,153422,0.8,0.8,1.501377e+05,156352.00,Utah,Rocky Mountain
52,Wyoming ....................,39538,39981,39604,37569,37777,38463,0.2,0.2,0.2,...,0.2,0.2,38537,37622,0.2,0.2,3.937400e+04,37857.75,Wyoming,Rocky Mountain
53,Far West ......................,3366368,3419789,3450939,3552236,3610452,3650211,19.1,NaN,19.1,...,19.5,19.5,3481350,3512447,19.2,19.3,3.450693e+06,3581336.50,Far West,NaN
54,Alaska ........................,53997,54615,53155,50545,50742,51506,0.3,0.3,0.3,...,0.3,0.3,51770,50059,0.3,0.3,5.318000e+04,50713.00,Alaska,Far West
55,California ....................,2444063,2485470,2505638,2581572,2627083,2656080,13.8,NaN,13.9,...,14.2,14.2,2531304,2545953,14.0,14.0,2.507471e+06,2602672.00,California,Far West
56,Hawaii .......................,79538,80302,80907,83548,84325,84889,0.5,0.4,0.4,...,0.5,0.5,81650,82904,0.5,0.5,8.095300e+04,83916.50,Hawaii,Far West
57,Nevada ......................,137533,140194,142952,145068,149913,151348,0.8,0.8,0.8,...,0.8,0.8,143602,143572,0.8,0.8,1.422493e+05,147475.25,Nevada,Far West
58,Oregon .......................,212763,214687,218660,225947,227316,229837,1.2,1.2,1.2,...,1.2,1.2,219979,224181,1.2,1.2,2.177753e+05,226820.25,Oregon,Far West
59,Washington ................,438475,444522,449627,465556,471073,476550,2.5,2.5,2.5,...,2.5,2.5,453045,465779,2.5,2.6,4.490647e+05,469739.50,Washington,Far West

In [84]:
states = ["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Connecticut", "District of Columbia",
          "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", 
          "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", 
          "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", 
          "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
          "Texas", "Utah", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]
        
        # empty DataFrame to hold the new columns
GDPdf = pd.DataFrame()
        # count variable to increase the index by one after each row is added
count = 0
        
        # for loop to iterate through the years specified by the instance
for year in range(GDP2015_2016.yearStart, GDP2015_2016.yearEnd + 1):
            # for each state in that year, add in the following columns
    for state in states:
        GDPdf.loc[count, 'year'] = str(year)
        GDPdf.loc[count, 'state'] = state
        GDPdf.loc[count, 'current dollars'] = GDP2015_2016.dollars
        GDPdf.loc[count, 'GDP'] = GDP2015_2016.df.loc[GDP2015_2016.df['Cleaned Area'] == state, str(year)].item()
        GDPdf.loc[count, 'GDP_area'] = GDP2015_2016.df.loc[GDP2015_2016.df['Cleaned Area'] == state, 'Geo Loc'].item()
        count += 1

GDP2015_2016.df = GDPdf
GDP2015_2016.df

     year          state current dollars           GDP        GDP_area
0    2015         Alaska            2016  5.318000e+04        Far West
1    2015        Alabama            2016  2.010337e+05       Southeast
2    2015       Arkansas            2016  1.192147e+05       Southeast
3    2015        Arizona            2016  2.928667e+05       Southwest
4    2015     California            2016  2.507471e+06        Far West
..    ...            ...             ...           ...             ...
97   2016        Vermont            2016  3.109175e+04     New England
98   2016     Washington            2016  4.697395e+05        Far West
99   2016      Wisconsin            2016  3.095365e+05     Great Lakes
100  2016  West Virginia            2016  7.337350e+04       Southeast
101  2016        Wyoming            2016  3.785775e+04  Rocky Mountain

[102 rows x 5 columns]

# 2017 - 2018 Quarterly Data

In [85]:
GDP17_18 = tabula.read_pdf('GDP2017-2018_quarterly.pdf', pages = 8, stream = True)
GDP17_18

[              Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  \
 0                    NaN         NaN         NaN         NaN         NaN
 1                    NaN         NaN         NaN      2017.0         NaN
 2                    NaN          Q1          Q2         NaN          Q3
 3          United States  19,162,550  19,359,123         NaN  19,588,074
 4            New England   1,025,381   1,036,158         NaN   1,049,408
 ..                   ...         ...         ...         ...         ...
 59                Hawaii      88,183      88,593         NaN      89,383
 60                Nevada     154,797     155,890         NaN     158,250
 61                Oregon     221,100     224,764         NaN     227,132
 62            Washington     510,026     518,701         NaN     526,044
 63  Overseas activity 1/     114,239     113,992         NaN     113,239

                                   Millions of dollars Unnamed: 5  Unnamed: 6  \
 0   Percent of the U.S.Seasonally adjusted at annu...        NaN         NaN
 1                                           2018 2017        NaN      2018.0
 2                       Q4 Q1 Q2 Q3 Q4 Q1 Q2 Q3 Q4 Q1         Q2         NaN
 3   19,831,829 20,041,047 20,411,924 20,658,204 20...      100.0         NaN
 4   1,054,099 1,068,841 1,078,395 1,091,558 1,102,...        5.3         NaN
 ..                                                ...        ...         ...
 59  90,015 90,566 91,661 92,462 93,419 0.5 0.5 0.5...        0.4         NaN
 60  159,146 162,807 164,889 166,765 168,752 0.8 0....        0.8         NaN
 61  231,233 233,601 237,318 240,731 243,085 1.2 1....        1.2         NaN
 62  534,931 546,347 560,182 569,449 576,624 2.7 2....        2.7         NaN
 63  111,760 109,736 108,536 108,281 108,307 0.6 0....        0.6         NaN

    Unnamed: 7 Unnamed: 8
 0         NaN        NaN
 1         NaN        NaN
 2          Q3         Q4
 3       100.0      100.0
 4         5.3        5.3
 ..        ...        ...
 59        0.4        0.4
 60        0.8        0.8
 61        1.2        1.2
 62        2.8        2.8
 63        0.6        0.5

 [64 rows x 10 columns]]

In [86]:
GDP17_18 = pd.concat(GDP17_18, ignore_index = True)
GDP17_18

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Millions of dollars,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,Percent of the U.S.Seasonally adjusted at annu...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2017.0,NaN,2018 2017,NaN,2018.0,NaN,NaN
2,NaN,Q1,Q2,NaN,Q3,Q4 Q1 Q2 Q3 Q4 Q1 Q2 Q3 Q4 Q1,Q2,NaN,Q3,Q4
3,United States,"19,162,550","19,359,123",NaN,"19,588,074","19,831,829 20,041,047 20,411,924 20,658,204 20...",100.0,NaN,100.0,100.0
4,New England,"1,025,381","1,036,158",NaN,"1,049,408","1,054,099 1,068,841 1,078,395 1,091,558 1,102,...",5.3,NaN,5.3,5.3
...,...,...,...,...,...,...,...,...,...,...
59,Hawaii,"88,183","88,593",NaN,"89,383","90,015 90,566 91,661 92,462 93,419 0.5 0.5 0.5...",0.4,NaN,0.4,0.4
60,Nevada,"154,797","155,890",NaN,"158,250","159,146 162,807 164,889 166,765 168,752 0.8 0....",0.8,NaN,0.8,0.8
61,Oregon,"221,100","224,764",NaN,"227,132","231,233 233,601 237,318 240,731 243,085 1.2 1....",1.2,NaN,1.2,1.2
62,Washington,"510,026","518,701",NaN,"526,044","534,931 546,347 560,182 569,449 576,624 2.7 2....",2.7,NaN,2.8,2.8
63,Overseas activity 1/,"114,239","113,992",NaN,"113,239","111,760 109,736 108,536 108,281 108,307 0.6 0....",0.6,NaN,0.6,0.5

In [87]:
GDP17_18 = GDP17_18.drop(GDP17_18.index[0:3]).reset_index(drop = True)
GDP17_18

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Millions of dollars,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,United States,"19,162,550","19,359,123",NaN,"19,588,074","19,831,829 20,041,047 20,411,924 20,658,204 20...",100.0,NaN,100.0,100.0
1,New England,"1,025,381","1,036,158",NaN,"1,049,408","1,054,099 1,068,841 1,078,395 1,091,558 1,102,...",5.3,NaN,5.3,5.3
2,Connecticut,"261,977","264,949",NaN,"267,504","267,711 270,268 269,863 276,934 279,653 1.4 1....",1.3,NaN,1.3,1.3
3,Maine,"61,009","61,230",NaN,"62,104","62,538 63,173 64,082 64,798 65,349 0.3 0.3 0.3...",0.3,NaN,0.3,0.3
4,Massachusetts,"531,748","537,860",NaN,"545,137","549,051 558,137 565,224 570,024 575,635 2.8 2....",2.8,NaN,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,"88,183","88,593",NaN,"89,383","90,015 90,566 91,661 92,462 93,419 0.5 0.5 0.5...",0.4,NaN,0.4,0.4
57,Nevada,"154,797","155,890",NaN,"158,250","159,146 162,807 164,889 166,765 168,752 0.8 0....",0.8,NaN,0.8,0.8
58,Oregon,"221,100","224,764",NaN,"227,132","231,233 233,601 237,318 240,731 243,085 1.2 1....",1.2,NaN,1.2,1.2
59,Washington,"510,026","518,701",NaN,"526,044","534,931 546,347 560,182 569,449 576,624 2.7 2....",2.7,NaN,2.8,2.8
60,Overseas activity 1/,"114,239","113,992",NaN,"113,239","111,760 109,736 108,536 108,281 108,307 0.6 0....",0.6,NaN,0.6,0.5

In [88]:
GDP17_18 = GDP17_18.drop(['Unnamed: 3', 'Unnamed: 6'], axis = 1)

for i in GDP17_18['Millions of dollars'].index:
    splitList = GDP17_18.loc[i, 'Millions of dollars'].split(" ")
    GDP17_18.loc[i, '2017 Q4'] = splitList[0]
    GDP17_18.loc[i, '2018 Q1'] = splitList[1]
    GDP17_18.loc[i, '2018 Q2'] = splitList[2]
    GDP17_18.loc[i, '2018 Q3'] = splitList[3]
    GDP17_18.loc[i, '2018 Q4'] = splitList[4]
    GDP17_18.loc[i, '2017 Q1 %'] = splitList[5]
    GDP17_18.loc[i, '2017 Q2 %'] = splitList[6]
    GDP17_18.loc[i, '2017 Q3 %'] = splitList[7]
    GDP17_18.loc[i, '2017 Q4 %'] = splitList[8]
    GDP17_18.loc[i, '2018 Q1 %'] = splitList[9]

GDP17_18 = GDP17_18.drop('Millions of dollars', axis = 1)
    
GDP17_18

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 5,Unnamed: 7,Unnamed: 8,2017 Q4,2018 Q1,2018 Q2,2018 Q3,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %
0,United States,"19,162,550","19,359,123","19,588,074",100.0,100.0,100.0,"19,831,829","20,041,047","20,411,924","20,658,204","20,865,140",100.0,100.0,100.0,100.0,100.0
1,New England,"1,025,381","1,036,158","1,049,408",5.3,5.3,5.3,"1,054,099","1,068,841","1,078,395","1,091,558","1,102,178",5.4,5.4,5.4,5.3,5.3
2,Connecticut,"261,977","264,949","267,504",1.3,1.3,1.3,"267,711","270,268","269,863","276,934","279,653",1.4,1.4,1.4,1.3,1.3
3,Maine,"61,009","61,230","62,104",0.3,0.3,0.3,"62,538","63,173","64,082","64,798","65,349",0.3,0.3,0.3,0.3,0.3
4,Massachusetts,"531,748","537,860","545,137",2.8,2.8,2.8,"549,051","558,137","565,224","570,024","575,635",2.8,2.8,2.8,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,"88,183","88,593","89,383",0.4,0.4,0.4,"90,015","90,566","91,661","92,462","93,419",0.5,0.5,0.5,0.5,0.5
57,Nevada,"154,797","155,890","158,250",0.8,0.8,0.8,"159,146","162,807","164,889","166,765","168,752",0.8,0.8,0.8,0.8,0.8
58,Oregon,"221,100","224,764","227,132",1.2,1.2,1.2,"231,233","233,601","237,318","240,731","243,085",1.2,1.2,1.2,1.2,1.2
59,Washington,"510,026","518,701","526,044",2.7,2.8,2.8,"534,931","546,347","560,182","569,449","576,624",2.7,2.7,2.7,2.7,2.7
60,Overseas activity 1/,"114,239","113,992","113,239",0.6,0.6,0.5,"111,760","109,736","108,536","108,281","108,307",0.6,0.6,0.6,0.6,0.6

In [89]:
GDP17_18.columns = ['Area', '2017 Q1', '2017 Q2', '2017 Q3', '2018 Q2 %',
                 '2018 Q3 %', '2018 Q4 %','2017 Q4', '2018 Q1', '2018 Q2', '2018 Q3',
                 '2018 Q4', '2017 Q1 %', '2017 Q2 %', '2017 Q3 %', '2017 Q4 %', '2018 Q1 %']
GDP17_18

,Area,2017 Q1,2017 Q2,2017 Q3,2018 Q2 %,2018 Q3 %,2018 Q4 %,2017 Q4,2018 Q1,2018 Q2,2018 Q3,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %
0,United States,"19,162,550","19,359,123","19,588,074",100.0,100.0,100.0,"19,831,829","20,041,047","20,411,924","20,658,204","20,865,140",100.0,100.0,100.0,100.0,100.0
1,New England,"1,025,381","1,036,158","1,049,408",5.3,5.3,5.3,"1,054,099","1,068,841","1,078,395","1,091,558","1,102,178",5.4,5.4,5.4,5.3,5.3
2,Connecticut,"261,977","264,949","267,504",1.3,1.3,1.3,"267,711","270,268","269,863","276,934","279,653",1.4,1.4,1.4,1.3,1.3
3,Maine,"61,009","61,230","62,104",0.3,0.3,0.3,"62,538","63,173","64,082","64,798","65,349",0.3,0.3,0.3,0.3,0.3
4,Massachusetts,"531,748","537,860","545,137",2.8,2.8,2.8,"549,051","558,137","565,224","570,024","575,635",2.8,2.8,2.8,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,"88,183","88,593","89,383",0.4,0.4,0.4,"90,015","90,566","91,661","92,462","93,419",0.5,0.5,0.5,0.5,0.5
57,Nevada,"154,797","155,890","158,250",0.8,0.8,0.8,"159,146","162,807","164,889","166,765","168,752",0.8,0.8,0.8,0.8,0.8
58,Oregon,"221,100","224,764","227,132",1.2,1.2,1.2,"231,233","233,601","237,318","240,731","243,085",1.2,1.2,1.2,1.2,1.2
59,Washington,"510,026","518,701","526,044",2.7,2.8,2.8,"534,931","546,347","560,182","569,449","576,624",2.7,2.7,2.7,2.7,2.7
60,Overseas activity 1/,"114,239","113,992","113,239",0.6,0.6,0.5,"111,760","109,736","108,536","108,281","108,307",0.6,0.6,0.6,0.6,0.6

In [90]:
for column in GDP17_18.columns:
    if column == 'Area':
        pass
    else:
        for i in GDP17_18[column].index:
            if isinstance(GDP17_18.loc[i, column], float):
                pass
            else:
                GDP17_18.loc[i, column] = GDP17_18.loc[i, column].replace(',','')
GDP17_18 = GDP17_18.apply(pd.to_numeric, errors = 'ignore')
GDP17_18

,Area,2017 Q1,2017 Q2,2017 Q3,2018 Q2 %,2018 Q3 %,2018 Q4 %,2017 Q4,2018 Q1,2018 Q2,2018 Q3,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %
0,United States,19162550,19359123,19588074,100.0,100.0,100.0,19831829,20041047,20411924,20658204,20865140,100.0,100.0,100.0,100.0,100.0
1,New England,1025381,1036158,1049408,5.3,5.3,5.3,1054099,1068841,1078395,1091558,1102178,5.4,5.4,5.4,5.3,5.3
2,Connecticut,261977,264949,267504,1.3,1.3,1.3,267711,270268,269863,276934,279653,1.4,1.4,1.4,1.3,1.3
3,Maine,61009,61230,62104,0.3,0.3,0.3,62538,63173,64082,64798,65349,0.3,0.3,0.3,0.3,0.3
4,Massachusetts,531748,537860,545137,2.8,2.8,2.8,549051,558137,565224,570024,575635,2.8,2.8,2.8,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,88183,88593,89383,0.4,0.4,0.4,90015,90566,91661,92462,93419,0.5,0.5,0.5,0.5,0.5
57,Nevada,154797,155890,158250,0.8,0.8,0.8,159146,162807,164889,166765,168752,0.8,0.8,0.8,0.8,0.8
58,Oregon,221100,224764,227132,1.2,1.2,1.2,231233,233601,237318,240731,243085,1.2,1.2,1.2,1.2,1.2
59,Washington,510026,518701,526044,2.7,2.8,2.8,534931,546347,560182,569449,576624,2.7,2.7,2.7,2.7,2.7
60,Overseas activity 1/,114239,113992,113239,0.6,0.6,0.5,111760,109736,108536,108281,108307,0.6,0.6,0.6,0.6,0.6

In [91]:
gdp2017 = ['2017 Q1', '2017 Q2', '2017 Q3', '2017 Q4']
gdp2018 = ['2018 Q1', '2018 Q2', '2018 Q3', '2018 Q4']

filter_2017 = GDP17_18.filter(items = gdp2017)
filter_2018 = GDP17_18.filter(items = gdp2018)

GDP17_18['2017'] = filter_2017.mean(axis = 1)
GDP17_18['2018'] = filter_2018.mean(axis = 1)

GDP17_18

,Area,2017 Q1,2017 Q2,2017 Q3,2018 Q2 %,2018 Q3 %,2018 Q4 %,2017 Q4,2018 Q1,2018 Q2,2018 Q3,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %,2017,2018
0,United States,19162550,19359123,19588074,100.0,100.0,100.0,19831829,20041047,20411924,20658204,20865140,100.0,100.0,100.0,100.0,100.0,19485394.00,20494078.75
1,New England,1025381,1036158,1049408,5.3,5.3,5.3,1054099,1068841,1078395,1091558,1102178,5.4,5.4,5.4,5.3,5.3,1041261.50,1085243.00
2,Connecticut,261977,264949,267504,1.3,1.3,1.3,267711,270268,269863,276934,279653,1.4,1.4,1.4,1.3,1.3,265535.25,274179.50
3,Maine,61009,61230,62104,0.3,0.3,0.3,62538,63173,64082,64798,65349,0.3,0.3,0.3,0.3,0.3,61720.25,64350.50
4,Massachusetts,531748,537860,545137,2.8,2.8,2.8,549051,558137,565224,570024,575635,2.8,2.8,2.8,2.8,2.8,540949.00,567255.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,88183,88593,89383,0.4,0.4,0.4,90015,90566,91661,92462,93419,0.5,0.5,0.5,0.5,0.5,89043.50,92027.00
57,Nevada,154797,155890,158250,0.8,0.8,0.8,159146,162807,164889,166765,168752,0.8,0.8,0.8,0.8,0.8,157020.75,165803.25
58,Oregon,221100,224764,227132,1.2,1.2,1.2,231233,233601,237318,240731,243085,1.2,1.2,1.2,1.2,1.2,226057.25,238683.75
59,Washington,510026,518701,526044,2.7,2.8,2.8,534931,546347,560182,569449,576624,2.7,2.7,2.7,2.7,2.7,522425.50,563150.50
60,Overseas activity 1/,114239,113992,113239,0.6,0.6,0.5,111760,109736,108536,108281,108307,0.6,0.6,0.6,0.6,0.6,113307.50,108715.00

In [92]:
GDP2017_2018 = QuarterlyGDP('GDP2017-2018_quarterly.pdf', 8, 2017, 2018, '2018')

In [93]:
GDP2017_2018.df = GDP17_18

In [94]:
GDP2017_2018.df

,Area,2017 Q1,2017 Q2,2017 Q3,2018 Q2 %,2018 Q3 %,2018 Q4 %,2017 Q4,2018 Q1,2018 Q2,2018 Q3,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %,2017,2018
0,United States,19162550,19359123,19588074,100.0,100.0,100.0,19831829,20041047,20411924,20658204,20865140,100.0,100.0,100.0,100.0,100.0,19485394.00,20494078.75
1,New England,1025381,1036158,1049408,5.3,5.3,5.3,1054099,1068841,1078395,1091558,1102178,5.4,5.4,5.4,5.3,5.3,1041261.50,1085243.00
2,Connecticut,261977,264949,267504,1.3,1.3,1.3,267711,270268,269863,276934,279653,1.4,1.4,1.4,1.3,1.3,265535.25,274179.50
3,Maine,61009,61230,62104,0.3,0.3,0.3,62538,63173,64082,64798,65349,0.3,0.3,0.3,0.3,0.3,61720.25,64350.50
4,Massachusetts,531748,537860,545137,2.8,2.8,2.8,549051,558137,565224,570024,575635,2.8,2.8,2.8,2.8,2.8,540949.00,567255.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,88183,88593,89383,0.4,0.4,0.4,90015,90566,91661,92462,93419,0.5,0.5,0.5,0.5,0.5,89043.50,92027.00
57,Nevada,154797,155890,158250,0.8,0.8,0.8,159146,162807,164889,166765,168752,0.8,0.8,0.8,0.8,0.8,157020.75,165803.25
58,Oregon,221100,224764,227132,1.2,1.2,1.2,231233,233601,237318,240731,243085,1.2,1.2,1.2,1.2,1.2,226057.25,238683.75
59,Washington,510026,518701,526044,2.7,2.8,2.8,534931,546347,560182,569449,576624,2.7,2.7,2.7,2.7,2.7,522425.50,563150.50
60,Overseas activity 1/,114239,113992,113239,0.6,0.6,0.5,111760,109736,108536,108281,108307,0.6,0.6,0.6,0.6,0.6,113307.50,108715.00

In [95]:
GDP2017_2018.cleanStates()

,Area,2017 Q1,2017 Q2,2017 Q3,2018 Q2 %,2018 Q3 %,2018 Q4 %,2017 Q4,2018 Q1,2018 Q2,2018 Q3,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %,2017,2018,Cleaned Area
0,United States,19162550,19359123,19588074,100.0,100.0,100.0,19831829,20041047,20411924,20658204,20865140,100.0,100.0,100.0,100.0,100.0,19485394.00,20494078.75,United States
1,New England,1025381,1036158,1049408,5.3,5.3,5.3,1054099,1068841,1078395,1091558,1102178,5.4,5.4,5.4,5.3,5.3,1041261.50,1085243.00,New England
2,Connecticut,261977,264949,267504,1.3,1.3,1.3,267711,270268,269863,276934,279653,1.4,1.4,1.4,1.3,1.3,265535.25,274179.50,Connecticut
3,Maine,61009,61230,62104,0.3,0.3,0.3,62538,63173,64082,64798,65349,0.3,0.3,0.3,0.3,0.3,61720.25,64350.50,Maine
4,Massachusetts,531748,537860,545137,2.8,2.8,2.8,549051,558137,565224,570024,575635,2.8,2.8,2.8,2.8,2.8,540949.00,567255.00,Massachusetts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,88183,88593,89383,0.4,0.4,0.4,90015,90566,91661,92462,93419,0.5,0.5,0.5,0.5,0.5,89043.50,92027.00,Hawaii
57,Nevada,154797,155890,158250,0.8,0.8,0.8,159146,162807,164889,166765,168752,0.8,0.8,0.8,0.8,0.8,157020.75,165803.25,Nevada
58,Oregon,221100,224764,227132,1.2,1.2,1.2,231233,233601,237318,240731,243085,1.2,1.2,1.2,1.2,1.2,226057.25,238683.75,Oregon
59,Washington,510026,518701,526044,2.7,2.8,2.8,534931,546347,560182,569449,576624,2.7,2.7,2.7,2.7,2.7,522425.50,563150.50,Washington
60,Overseas activity 1/,114239,113992,113239,0.6,0.6,0.5,111760,109736,108536,108281,108307,0.6,0.6,0.6,0.6,0.6,113307.50,108715.00,Overseas activity

In [96]:
GDP2017_2018.addGeoLocColumn()

,Area,2017 Q1,2017 Q2,2017 Q3,2018 Q2 %,2018 Q3 %,2018 Q4 %,2017 Q4,2018 Q1,2018 Q2,...,2018 Q4,2017 Q1 %,2017 Q2 %,2017 Q3 %,2017 Q4 %,2018 Q1 %,2017,2018,Cleaned Area,Geo Loc
0,United States,19162550,19359123,19588074,100.0,100.0,100.0,19831829,20041047,20411924,...,20865140,100.0,100.0,100.0,100.0,100.0,19485394.00,20494078.75,United States,NaN
1,New England,1025381,1036158,1049408,5.3,5.3,5.3,1054099,1068841,1078395,...,1102178,5.4,5.4,5.4,5.3,5.3,1041261.50,1085243.00,New England,NaN
2,Connecticut,261977,264949,267504,1.3,1.3,1.3,267711,270268,269863,...,279653,1.4,1.4,1.4,1.3,1.3,265535.25,274179.50,Connecticut,New England
3,Maine,61009,61230,62104,0.3,0.3,0.3,62538,63173,64082,...,65349,0.3,0.3,0.3,0.3,0.3,61720.25,64350.50,Maine,New England
4,Massachusetts,531748,537860,545137,2.8,2.8,2.8,549051,558137,565224,...,575635,2.8,2.8,2.8,2.8,2.8,540949.00,567255.00,Massachusetts,New England
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,88183,88593,89383,0.4,0.4,0.4,90015,90566,91661,...,93419,0.5,0.5,0.5,0.5,0.5,89043.50,92027.00,Hawaii,Far West
57,Nevada,154797,155890,158250,0.8,0.8,0.8,159146,162807,164889,...,168752,0.8,0.8,0.8,0.8,0.8,157020.75,165803.25,Nevada,Far West
58,Oregon,221100,224764,227132,1.2,1.2,1.2,231233,233601,237318,...,243085,1.2,1.2,1.2,1.2,1.2,226057.25,238683.75,Oregon,Far West
59,Washington,510026,518701,526044,2.7,2.8,2.8,534931,546347,560182,...,576624,2.7,2.7,2.7,2.7,2.7,522425.50,563150.50,Washington,Far West
60,Overseas activity 1/,114239,113992,113239,0.6,0.6,0.5,111760,109736,108536,...,108307,0.6,0.6,0.6,0.6,0.6,113307.50,108715.00,Overseas activity,Far West

In [97]:
states = ["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Connecticut", "District of Columbia",
          "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", 
          "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", 
          "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", 
          "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
          "Texas", "Utah", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]
        
        # empty DataFrame to hold the new columns
GDPdf = pd.DataFrame()
        # count variable to increase the index by one after each row is added
count = 0
        
        # for loop to iterate through the years specified by the instance
for year in range(GDP2017_2018.yearStart, GDP2017_2018.yearEnd + 1):
            # for each state in that year, add in the following columns
    for state in states:
        GDPdf.loc[count, 'year'] = str(year)
        GDPdf.loc[count, 'state'] = state
        GDPdf.loc[count, 'current dollars'] = GDP2017_2018.dollars
        GDPdf.loc[count, 'GDP'] = GDP2017_2018.df.loc[GDP2017_2018.df['Cleaned Area'] == state, str(year)].item()
        GDPdf.loc[count, 'GDP_area'] = GDP2017_2018.df.loc[GDP2017_2018.df['Cleaned Area'] == state, 'Geo Loc'].item()
        count += 1

GDP2017_2018.df = GDPdf
GDP2017_2018.df

     year          state current dollars         GDP        GDP_area
0    2017         Alaska            2018    51686.75        Far West
1    2017        Alabama            2018   211665.75       Southeast
2    2017       Arkansas            2018   123713.75       Southeast
3    2017        Arizona            2018   326539.50       Southwest
4    2017     California            2018  2809922.50        Far West
..    ...            ...             ...         ...             ...
97   2018        Vermont            2018    33725.25     New England
98   2018     Washington            2018   563150.50        Far West
99   2018      Wisconsin            2018   336971.50     Great Lakes
100  2018  West Virginia            2018    77477.00       Southeast
101  2018        Wyoming            2018    39371.25  Rocky Mountain

[102 rows x 5 columns]

# 2019 Quarterly Data

In [98]:
GDP19_20 = tabula.read_pdf('GDP2019-2020_quarterly.pdf', pages = 7, stream = True)
GDP19_20

[              Unnamed: 0  Unnamed: 1  \
 0                    NaN         NaN
 1                    NaN         NaN
 2                    NaN          Q1
 3          United States  21,098,827
 4            New England   1,118,703
 ..                   ...         ...
 59                Hawaii      96,094
 60                Nevada     174,569
 61                Oregon     247,562
 62            Washington     587,758
 63  Overseas activity 1/     119,036

                                   Millions of dollars Unnamed: 2 Unnamed: 3
 0   Percent of the U.S.Seasonally adjusted at annu...        NaN        NaN
 1                                      2019 2020 2019        NaN       2020
 2                                Q2 Q3 Q4 Q1 Q1 Q2 Q3         Q4         Q1
 3   21,340,267 21,542,540 21,729,124 21,539,689 10...      100.0      100.0
 4   1,130,084 1,142,586 1,151,182 1,143,978 5.3 5....        5.3        5.3
 ..                                                ...        ...        ...
 59            96,832 97,664 98,536 97,089 0.5 0.5 0.5        0.5        0.5
 60        176,862 178,622 180,406 177,114 0.8 0.8 0.8        0.8        0.8
 61        250,402 253,036 255,418 253,990 1.2 1.2 1.2        1.2        1.2
 62        596,412 603,772 610,488 606,919 2.8 2.8 2.8        2.8        2.8
 63        119,946 121,310 122,305 123,033 0.6 0.6 0.6        0.6        0.6

 [64 rows x 5 columns]]

In [99]:
GDP19_20 = pd.concat(GDP19_20, ignore_index = True)
GDP19_20

,Unnamed: 0,Unnamed: 1,Millions of dollars,Unnamed: 2,Unnamed: 3
0,NaN,NaN,Percent of the U.S.Seasonally adjusted at annu...,NaN,NaN
1,NaN,NaN,2019 2020 2019,NaN,2020
2,NaN,Q1,Q2 Q3 Q4 Q1 Q1 Q2 Q3,Q4,Q1
3,United States,"21,098,827","21,340,267 21,542,540 21,729,124 21,539,689 10...",100.0,100.0
4,New England,"1,118,703","1,130,084 1,142,586 1,151,182 1,143,978 5.3 5....",5.3,5.3
...,...,...,...,...,...
59,Hawaii,"96,094","96,832 97,664 98,536 97,089 0.5 0.5 0.5",0.5,0.5
60,Nevada,"174,569","176,862 178,622 180,406 177,114 0.8 0.8 0.8",0.8,0.8
61,Oregon,"247,562","250,402 253,036 255,418 253,990 1.2 1.2 1.2",1.2,1.2
62,Washington,"587,758","596,412 603,772 610,488 606,919 2.8 2.8 2.8",2.8,2.8
63,Overseas activity 1/,"119,036","119,946 121,310 122,305 123,033 0.6 0.6 0.6",0.6,0.6

In [100]:
GDP19_20 = GDP19_20.drop(GDP19_20.index[0:3]).reset_index(drop = True)
GDP19_20

,Unnamed: 0,Unnamed: 1,Millions of dollars,Unnamed: 2,Unnamed: 3
0,United States,"21,098,827","21,340,267 21,542,540 21,729,124 21,539,689 10...",100.0,100.0
1,New England,"1,118,703","1,130,084 1,142,586 1,151,182 1,143,978 5.3 5....",5.3,5.3
2,Connecticut,"281,659","284,357 287,560 288,985 287,711 1.3 1.3 1.3",1.3,1.3
3,Maine,"66,590","67,138 67,905 68,441 67,793 0.3 0.3 0.3",0.3,0.3
4,Massachusetts,"586,347","592,588 599,092 604,208 600,554 2.8 2.8 2.8",2.8,2.8
...,...,...,...,...,...
56,Hawaii,"96,094","96,832 97,664 98,536 97,089 0.5 0.5 0.5",0.5,0.5
57,Nevada,"174,569","176,862 178,622 180,406 177,114 0.8 0.8 0.8",0.8,0.8
58,Oregon,"247,562","250,402 253,036 255,418 253,990 1.2 1.2 1.2",1.2,1.2
59,Washington,"587,758","596,412 603,772 610,488 606,919 2.8 2.8 2.8",2.8,2.8
60,Overseas activity 1/,"119,036","119,946 121,310 122,305 123,033 0.6 0.6 0.6",0.6,0.6

In [101]:
for i in GDP19_20['Millions of dollars'].index:
    splitList = GDP19_20.loc[i, 'Millions of dollars'].split(" ")
    GDP19_20.loc[i, '2019 Q2'] = splitList[0]
    GDP19_20.loc[i, '2019 Q3'] = splitList[1]
    GDP19_20.loc[i, '2019 Q4'] = splitList[2]
    GDP19_20.loc[i, '2020 Q1'] = splitList[3]
    GDP19_20.loc[i, '2019 Q1 %'] = splitList[4]
    GDP19_20.loc[i, '2019 Q2 %'] = splitList[5]
    GDP19_20.loc[i, '2019 Q3 %'] = splitList[6]

GDP19_20 = GDP19_20.drop('Millions of dollars', axis = 1)
    
GDP19_20

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %
0,United States,"21,098,827",100.0,100.0,"21,340,267","21,542,540","21,729,124","21,539,689",100.0,100.0,100.0
1,New England,"1,118,703",5.3,5.3,"1,130,084","1,142,586","1,151,182","1,143,978",5.3,5.3,5.3
2,Connecticut,"281,659",1.3,1.3,"284,357","287,560","288,985","287,711",1.3,1.3,1.3
3,Maine,"66,590",0.3,0.3,"67,138","67,905","68,441","67,793",0.3,0.3,0.3
4,Massachusetts,"586,347",2.8,2.8,"592,588","599,092","604,208","600,554",2.8,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,"96,094",0.5,0.5,"96,832","97,664","98,536","97,089",0.5,0.5,0.5
57,Nevada,"174,569",0.8,0.8,"176,862","178,622","180,406","177,114",0.8,0.8,0.8
58,Oregon,"247,562",1.2,1.2,"250,402","253,036","255,418","253,990",1.2,1.2,1.2
59,Washington,"587,758",2.8,2.8,"596,412","603,772","610,488","606,919",2.8,2.8,2.8
60,Overseas activity 1/,"119,036",0.6,0.6,"119,946","121,310","122,305","123,033",0.6,0.6,0.6

In [102]:
GDP19_20.columns = ['Area', '2019 Q1', '2019 Q4%', '2020 Q1%', '2019 Q2',
                 '2019 Q3', '2019 Q4','2020 Q1', '2019 Q1 %', '2019 Q2 %', '2019 Q3 %']
GDP19_20

,Area,2019 Q1,2019 Q4%,2020 Q1%,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %
0,United States,"21,098,827",100.0,100.0,"21,340,267","21,542,540","21,729,124","21,539,689",100.0,100.0,100.0
1,New England,"1,118,703",5.3,5.3,"1,130,084","1,142,586","1,151,182","1,143,978",5.3,5.3,5.3
2,Connecticut,"281,659",1.3,1.3,"284,357","287,560","288,985","287,711",1.3,1.3,1.3
3,Maine,"66,590",0.3,0.3,"67,138","67,905","68,441","67,793",0.3,0.3,0.3
4,Massachusetts,"586,347",2.8,2.8,"592,588","599,092","604,208","600,554",2.8,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,"96,094",0.5,0.5,"96,832","97,664","98,536","97,089",0.5,0.5,0.5
57,Nevada,"174,569",0.8,0.8,"176,862","178,622","180,406","177,114",0.8,0.8,0.8
58,Oregon,"247,562",1.2,1.2,"250,402","253,036","255,418","253,990",1.2,1.2,1.2
59,Washington,"587,758",2.8,2.8,"596,412","603,772","610,488","606,919",2.8,2.8,2.8
60,Overseas activity 1/,"119,036",0.6,0.6,"119,946","121,310","122,305","123,033",0.6,0.6,0.6

In [103]:
for column in GDP19_20.columns:
    if column == 'Area':
        pass
    else:
        for i in GDP19_20[column].index:
            if isinstance(GDP19_20.loc[i, column], float):
                pass
            else:
                GDP19_20.loc[i, column] = GDP19_20.loc[i, column].replace(',','')
GDP19_20 = GDP19_20.apply(pd.to_numeric, errors = 'ignore')
GDP19_20

,Area,2019 Q1,2019 Q4%,2020 Q1%,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %
0,United States,21098827,100.0,100.0,21340267,21542540,21729124,21539689,100.0,100.0,100.0
1,New England,1118703,5.3,5.3,1130084,1142586,1151182,1143978,5.3,5.3,5.3
2,Connecticut,281659,1.3,1.3,284357,287560,288985,287711,1.3,1.3,1.3
3,Maine,66590,0.3,0.3,67138,67905,68441,67793,0.3,0.3,0.3
4,Massachusetts,586347,2.8,2.8,592588,599092,604208,600554,2.8,2.8,2.8
...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,96094,0.5,0.5,96832,97664,98536,97089,0.5,0.5,0.5
57,Nevada,174569,0.8,0.8,176862,178622,180406,177114,0.8,0.8,0.8
58,Oregon,247562,1.2,1.2,250402,253036,255418,253990,1.2,1.2,1.2
59,Washington,587758,2.8,2.8,596412,603772,610488,606919,2.8,2.8,2.8
60,Overseas activity 1/,119036,0.6,0.6,119946,121310,122305,123033,0.6,0.6,0.6

In [104]:
gdp2019 = ['2019 Q1', '2019 Q2', '2019 Q3', '2019 Q4']

filter_2019 = GDP19_20.filter(items = gdp2019)

GDP19_20['2019'] = filter_2019.mean(axis = 1)

GDP19_20

,Area,2019 Q1,2019 Q4%,2020 Q1%,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %,2019
0,United States,21098827,100.0,100.0,21340267,21542540,21729124,21539689,100.0,100.0,100.0,21427689.50
1,New England,1118703,5.3,5.3,1130084,1142586,1151182,1143978,5.3,5.3,5.3,1135638.75
2,Connecticut,281659,1.3,1.3,284357,287560,288985,287711,1.3,1.3,1.3,285640.25
3,Maine,66590,0.3,0.3,67138,67905,68441,67793,0.3,0.3,0.3,67518.50
4,Massachusetts,586347,2.8,2.8,592588,599092,604208,600554,2.8,2.8,2.8,595558.75
...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,96094,0.5,0.5,96832,97664,98536,97089,0.5,0.5,0.5,97281.50
57,Nevada,174569,0.8,0.8,176862,178622,180406,177114,0.8,0.8,0.8,177614.75
58,Oregon,247562,1.2,1.2,250402,253036,255418,253990,1.2,1.2,1.2,251604.50
59,Washington,587758,2.8,2.8,596412,603772,610488,606919,2.8,2.8,2.8,599607.50
60,Overseas activity 1/,119036,0.6,0.6,119946,121310,122305,123033,0.6,0.6,0.6,120649.25

In [105]:
GDP2019_2020 = QuarterlyGDP('GDP2019-2020_quarterly.pdf', 7, 2019, 2019, '2019')

In [106]:
GDP2019_2020.df = GDP19_20

In [107]:
GDP2019_2020.df

,Area,2019 Q1,2019 Q4%,2020 Q1%,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %,2019
0,United States,21098827,100.0,100.0,21340267,21542540,21729124,21539689,100.0,100.0,100.0,21427689.50
1,New England,1118703,5.3,5.3,1130084,1142586,1151182,1143978,5.3,5.3,5.3,1135638.75
2,Connecticut,281659,1.3,1.3,284357,287560,288985,287711,1.3,1.3,1.3,285640.25
3,Maine,66590,0.3,0.3,67138,67905,68441,67793,0.3,0.3,0.3,67518.50
4,Massachusetts,586347,2.8,2.8,592588,599092,604208,600554,2.8,2.8,2.8,595558.75
...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,96094,0.5,0.5,96832,97664,98536,97089,0.5,0.5,0.5,97281.50
57,Nevada,174569,0.8,0.8,176862,178622,180406,177114,0.8,0.8,0.8,177614.75
58,Oregon,247562,1.2,1.2,250402,253036,255418,253990,1.2,1.2,1.2,251604.50
59,Washington,587758,2.8,2.8,596412,603772,610488,606919,2.8,2.8,2.8,599607.50
60,Overseas activity 1/,119036,0.6,0.6,119946,121310,122305,123033,0.6,0.6,0.6,120649.25

In [108]:
GDP2019_2020.cleanStates()

,Area,2019 Q1,2019 Q4%,2020 Q1%,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %,2019,Cleaned Area
0,United States,21098827,100.0,100.0,21340267,21542540,21729124,21539689,100.0,100.0,100.0,21427689.50,United States
1,New England,1118703,5.3,5.3,1130084,1142586,1151182,1143978,5.3,5.3,5.3,1135638.75,New England
2,Connecticut,281659,1.3,1.3,284357,287560,288985,287711,1.3,1.3,1.3,285640.25,Connecticut
3,Maine,66590,0.3,0.3,67138,67905,68441,67793,0.3,0.3,0.3,67518.50,Maine
4,Massachusetts,586347,2.8,2.8,592588,599092,604208,600554,2.8,2.8,2.8,595558.75,Massachusetts
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,96094,0.5,0.5,96832,97664,98536,97089,0.5,0.5,0.5,97281.50,Hawaii
57,Nevada,174569,0.8,0.8,176862,178622,180406,177114,0.8,0.8,0.8,177614.75,Nevada
58,Oregon,247562,1.2,1.2,250402,253036,255418,253990,1.2,1.2,1.2,251604.50,Oregon
59,Washington,587758,2.8,2.8,596412,603772,610488,606919,2.8,2.8,2.8,599607.50,Washington
60,Overseas activity 1/,119036,0.6,0.6,119946,121310,122305,123033,0.6,0.6,0.6,120649.25,Overseas activity

In [109]:
GDP2019_2020.addGeoLocColumn()

,Area,2019 Q1,2019 Q4%,2020 Q1%,2019 Q2,2019 Q3,2019 Q4,2020 Q1,2019 Q1 %,2019 Q2 %,2019 Q3 %,2019,Cleaned Area,Geo Loc
0,United States,21098827,100.0,100.0,21340267,21542540,21729124,21539689,100.0,100.0,100.0,21427689.50,United States,NaN
1,New England,1118703,5.3,5.3,1130084,1142586,1151182,1143978,5.3,5.3,5.3,1135638.75,New England,NaN
2,Connecticut,281659,1.3,1.3,284357,287560,288985,287711,1.3,1.3,1.3,285640.25,Connecticut,New England
3,Maine,66590,0.3,0.3,67138,67905,68441,67793,0.3,0.3,0.3,67518.50,Maine,New England
4,Massachusetts,586347,2.8,2.8,592588,599092,604208,600554,2.8,2.8,2.8,595558.75,Massachusetts,New England
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,Hawaii,96094,0.5,0.5,96832,97664,98536,97089,0.5,0.5,0.5,97281.50,Hawaii,Far West
57,Nevada,174569,0.8,0.8,176862,178622,180406,177114,0.8,0.8,0.8,177614.75,Nevada,Far West
58,Oregon,247562,1.2,1.2,250402,253036,255418,253990,1.2,1.2,1.2,251604.50,Oregon,Far West
59,Washington,587758,2.8,2.8,596412,603772,610488,606919,2.8,2.8,2.8,599607.50,Washington,Far West
60,Overseas activity 1/,119036,0.6,0.6,119946,121310,122305,123033,0.6,0.6,0.6,120649.25,Overseas activity,Far West

In [110]:
states = ["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Connecticut", "District of Columbia",
          "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", 
          "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", 
          "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", 
          "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", 
          "Texas", "Utah", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]
        
        # empty DataFrame to hold the new columns
GDPdf = pd.DataFrame()
        # count variable to increase the index by one after each row is added
count = 0
        
        # for loop to iterate through the years specified by the instance
for year in range(GDP2019_2020.yearStart, GDP2019_2020.yearEnd + 1):
            # for each state in that year, add in the following columns
    for state in states:
        GDPdf.loc[count, 'year'] = str(year)
        GDPdf.loc[count, 'state'] = state
        GDPdf.loc[count, 'current dollars'] = GDP2019_2020.dollars
        GDPdf.loc[count, 'GDP'] = GDP2019_2020.df.loc[GDP2019_2020.df['Cleaned Area'] == state, str(year)].item()
        GDPdf.loc[count, 'GDP_area'] = GDP2019_2020.df.loc[GDP2019_2020.df['Cleaned Area'] == state, 'Geo Loc'].item()
        count += 1

GDP2019_2020.df = GDPdf
GDP2019_2020.df

    year                 state current dollars         GDP        GDP_area
0   2019                Alaska            2019    55406.25        Far West
1   2019               Alabama            2019   230968.25       Southeast
2   2019              Arkansas            2019   133180.75       Southeast
3   2019               Arizona            2019   366190.00       Southwest
4   2019            California            2019  3137469.00        Far West
5   2019              Colorado            2019   390284.00  Rocky Mountain
6   2019           Connecticut            2019   285640.25     New England
7   2019  District of Columbia            2019   146194.50         Mideast
8   2019              Delaware            2019    75415.25         Mideast
9   2019               Florida            2019  1093350.75       Southeast
10  2019               Georgia            2019   616333.25       Southeast
11  2019                Hawaii            2019    97281.50        Far West
12  2019                  Iowa            2019   194788.50          Plains
13  2019                 Idaho            2019    80911.00  Rocky Mountain
14  2019              Illinois            2019   897123.75     Great Lakes
15  2019               Indiana            2019   377104.50     Great Lakes
16  2019                Kansas            2019   173142.25          Plains
17  2019              Kentucky            2019   214671.50       Southeast
18  2019             Louisiana            2019   263856.50       Southeast
19  2019         Massachusetts            2019   595558.75     New England
20  2019              Maryland            2019   428338.50         Mideast
21  2019                 Maine            2019    67518.50     New England
22  2019              Michigan            2019   541550.75     Great Lakes
23  2019             Minnesota            2019   380855.00          Plains
24  2019              Missouri            2019   332082.00          Plains
25  2019           Mississippi            2019   118779.75       Southeast
26  2019               Montana            2019    52169.25  Rocky Mountain
27  2019        North Carolina            2019   587711.00       Southeast
28  2019          North Dakota            2019    57036.50          Plains
29  2019              Nebraska            2019   127036.75          Plains
30  2019         New Hampshire            2019    88594.75     New England
31  2019            New Jersey            2019   644841.50         Mideast
32  2019            New Mexico            2019   104001.25       Southwest
33  2019                Nevada            2019   177614.75        Far West
34  2019              New York            2019  1731910.50         Mideast
35  2019                  Ohio            2019   698458.00     Great Lakes
36  2019              Oklahoma            2019   206058.00       Southwest
37  2019                Oregon            2019   251604.50        Far West
38  2019          Pennsylvania            2019   813513.50         Mideast
39  2019          Rhode Island            2019    63541.00     New England
40  2019        South Carolina            2019   246309.00       Southeast
41  2019          South Dakota            2019    53305.75          Plains
42  2019             Tennessee            2019   380137.75       Southeast
43  2019                 Texas            2019  1886956.00       Southwest
44  2019                  Utah            2019   188501.25  Rocky Mountain
45  2019              Virginia            2019   554211.25       Southeast
46  2019               Vermont            2019    34785.00     New England
47  2019            Washington            2019   599607.50        Far West
48  2019             Wisconsin            2019   347306.00     Great Lakes
49  2019         West Virginia            2019    78189.50       Southeast
50  2019               Wyoming            2019    39646.25  Rocky Mountain

# Combine Data Frames

In [111]:
# first, need to create a list of DataFrames to concatenate
dfs = [GDP95_01.df, GDP01_03.df, GDP04_06.df, GDP07_09.df, GDP10_12.df, GDP11_13.df,
       GDP_2014.df, GDP2015_2016.df, GDP2017_2018.df, GDP2019_2020.df]
dfs

[     year          state current dollars       GDP        GDP_area
 0    1995         Alaska            2001   24791.0        Far West
 1    1995        Alabama            2001   95514.0       Southeast
 2    1995       Arkansas            2001   53809.0       Southeast
 3    1995        Arizona            2001  104586.0       Southwest
 4    1995     California            2001  925931.0        Far West
 ..    ...            ...             ...       ...             ...
 301  2000        Vermont            2001   18124.0     New England
 302  2000     Washington            2001  218095.0        Far West
 303  2000      Wisconsin            2001  173016.0     Great Lakes
 304  2000  West Virginia            2001   40926.0       Southeast
 305  2000        Wyoming            2001   19113.0  Rocky Mountain

 [306 rows x 5 columns],
      year          state current dollars        GDP        GDP_area
 0    2001         Alaska            2004    27358.0        Far West
 1    2001        Alabama            2004   118263.0       Southeast
 2    2001       Arkansas            2004    68574.0       Southeast
 3    2001        Arizona            2004   164263.0       Southwest
 4    2001     California            2004  1307880.0        Far West
 ..    ...            ...             ...        ...             ...
 148  2003        Vermont            2004    20544.0     New England
 149  2003     Washington            2004   245143.0        Far West
 150  2003      Wisconsin            2004   198096.0     Great Lakes
 151  2003  West Virginia            2004    46726.0       Southeast
 152  2003        Wyoming            2004    22279.0  Rocky Mountain

 [153 rows x 5 columns],
      year          state current dollars        GDP        GDP_area
 0    2004         Alaska            2007    35102.0        Far West
 1    2004        Alabama            2007   141527.0       Southeast
 2    2004       Arkansas            2007    82137.0       Southeast
 3    2004        Arizona            2007   193448.0       Southwest
 4    2004     California            2007  1519443.0        Far West
 ..    ...            ...             ...        ...             ...
 148  2006        Vermont            2007    23628.0     New England
 149  2006     Washington            2007   291298.0        Far West
 150  2006      Wisconsin            2007   223394.0     Great Lakes
 151  2006  West Virginia            2007    56016.0       Southeast
 152  2006        Wyoming            2007    29904.0  Rocky Mountain

 [153 rows x 5 columns],
      year          state current dollars        GDP        GDP_area
 0    2007         Alaska            2010    44587.0        Far West
 1    2007        Alabama            2010   165981.0       Southeast
 2    2007       Arkansas            2010    97187.0       Southeast
 3    2007        Arizona            2010   260122.0       Southwest
 4    2007     California            2010  1874783.0        Far West
 ..    ...            ...             ...        ...             ...
 148  2009        Vermont            2010    24625.0     New England
 149  2009     Washington            2010   331639.0        Far West
 150  2009      Wisconsin            2010   239613.0     Great Lakes
 151  2009  West Virginia            2010    61043.0       Southeast
 152  2009        Wyoming            2010    36760.0  Rocky Mountain

 [153 rows x 5 columns],
      year          state current dollars        GDP        GDP_area
 0    2010         Alaska            2013    53251.0        Far West
 1    2010        Alabama            2013   175734.0       Southeast
 2    2010       Arkansas            2013   111355.0       Southeast
 3    2010        Arizona            2013   247752.0       Southwest
 4    2010     California            2013  1953411.0        Far West
 ..    ...            ...             ...        ...             ...
 148  2012        Vermont            2013    28422.0     New England
 149  2012     Washington            2013   390918.0        Far West
 150  2012      Wisconsin            2013   272086.0     Great Lakes
 151  2012  West Virginia            2013    69711.0       Southeast
 152  2012        Wyoming            2013    41839.0  Rocky Mountain

 [153 rows x 5 columns],
     year                 state current dollars        GDP        GDP_area
 0   2013                Alaska            2014    57276.0        Far West
 1   2013               Alabama            2014   194671.0       Southeast
 2   2013              Arkansas            2014   118553.0       Southeast
 3   2013               Arizona            2014   274734.0       Southwest
 4   2013            California            2014  2212991.0        Far West
 5   2013              Colorado            2014   288338.0  Rocky Mountain
 6   2013           Connecticut            2014   246897.0     New England
 7   2013  District of Columbia            2014   111695.0         Mideast
 8   2013              Delaware            2014    60816.0         Mideast
 9   2013               Florida            2014   800697.0       Southeast
 10  2013               Georgia            2014   456483.0       Southeast
 11  2013                Hawaii            2014    75095.0        Far West
 12  2013                  Iowa            2014   166787.0          Plains
 13  2013                 Idaho            2014    61117.0  Rocky Mountain
 14  2013              Illinois            2014   724795.0     Great Lakes
 15  2013               Indiana            2014   311188.0     Great Lakes
 16  2013                Kansas            2014   142449.0          Plains
 17  2013              Kentucky            2014   183582.0       Southeast
 18  2013             Louisiana            2014   246660.0       Southeast
 19  2013         Massachusetts            2014   441467.0     New England
 20  2013              Maryland            2014   339409.0         Mideast
 21  2013                 Maine            2014    54609.0     New England
 22  2013              Michigan            2014   434674.0     Great Lakes
 23  2013             Minnesota            2014   307270.0          Plains
 24  2013              Missouri            2014   276715.0          Plains
 25  2013           Mississippi            2014   104095.0       Southeast
 26  2013               Montana            2014    43006.0  Rocky Mountain
 27  2013        North Carolina            2014   467075.0       Southeast
 28  2013          North Dakota            2014    51048.0          Plains
 29  2013              Nebraska            2014   109364.0          Plains
 30  2013         New Hampshire            2014    68701.0     New England
 31  2013            New Jersey            2014   537396.0         Mideast
 32  2013            New Mexico            2014    90828.0       Southwest
 33  2013                Nevada            2014   127989.0        Far West
 34  2013              New York            2014  1341591.0         Mideast
 35  2013                  Ohio            2014   562845.0     Great Lakes
 36  2013              Oklahoma            2014   176398.0       Southwest
 37  2013                Oregon            2014   204867.0        Far West
 38  2013          Pennsylvania            2014   640294.0         Mideast
 39  2013          Rhode Island            2014    53300.0     New England
 40  2013        South Carolina            2014   182400.0       Southeast
 41  2013          South Dakota            2014    44673.0          Plains
 42  2013             Tennessee            2014   290125.0       Southeast
 43  2013                 Texas            2014  1557193.0       Southwest
 44  2013                  Utah            2014   134974.0  Rocky Mountain
 45  2013              Virginia            2014   454984.0       Southeast
 46  2013               Vermont            2014    28838.0     New England
 47  2013            Washington            2014   407160.0        Far West
 48  2013             Wisconsin            2014   284728.0     Great Lakes
 49  2013         West Virginia            2014    70595.0       Southeast
 50  2013               Wyoming            2014    41782.0  Rocky Mountain,
     year                 state current dollars        GDP        GDP_area
 0   2014                Alaska            2014    57080.0        Far West
 1   2014               Alabama            2014   199440.0       Southeast
 2   2014              Arkansas            2014   121395.0       Southeast
 3   2014               Arizona            2014   284156.0       Southwest
 4   2014            California            2014  2311616.0        Far West
 5   2014              Colorado            2014   306663.0  Rocky Mountain
 6   2014           Connecticut            2014   253036.0     New England
 7   2014  District of Columbia            2014   115473.0         Mideast
 8   2014              Delaware            2014    62756.0         Mideast
 9   2014               Florida            2014   839944.0       Southeast
 10  2014               Georgia            2014   476483.0       Southeast
 11  2014                Hawaii            2014    77389.0        Far West
 12  2014                  Iowa            2014   170613.0          Plains
 13  2014                 Idaho            2014    63952.0  Rocky Mountain
 14  2014              Illinois            2014   745875.0     Great Lakes
 15  2014               Indiana            2014   317840.0     Great Lakes
 16  2014                Kansas            2014   147075.0          Plains
 17  2014              Kentucky            2014   188602.0       Southeast
 18  2014             Louisiana            2014   251397.0       Southeast
 19  2014         Massachusetts            2014   459937.0     New England
 20  2014              Maryland            2014   348631.0         Mideast
 21  2014                 Maine            2014    55838.0     New England
 22  2014              Michigan            2014   451516.0     Great Lakes
 23  2014             Minnesota            2014   316204.0          Plains
 24  2014              Missouri            2014   284462.0          Plains
 25  2014           Mississippi            2014   104851.0       Southeast
 26  2014               Montana            2014    44269.0  Rocky Mountain
 27  2014        North Carolina            2014   483126.0       Southeast
 28  2014          North Dakota            2014    55136.0          Plains
 29  2014              Nebraska            2014   112159.0          Plains
 30  2014         New Hampshire            2014    71552.0     New England
 31  2014            New Jersey            2014   549099.0         Mideast
 32  2014            New Mexico            2014    92959.0       Southwest
 33  2014                Nevada            2014   132064.0        Far West
 34  2014              New York            2014  1404518.0         Mideast
 35  2014                  Ohio            2014   583261.0     Great Lakes
 36  2014              Oklahoma            2014   183501.0       Southwest
 37  2014                Oregon            2014   215677.0        Far West
 38  2014          Pennsylvania            2014   662890.0         Mideast
 39  2014          Rhode Island            2014    54960.0     New England
 40  2014        South Carolina            2014   190304.0       Southeast
 41  2014          South Dakota            2014    45867.0          Plains
 42  2014             Tennessee            2014   300604.0       Southeast
 43  2014                 Texas            2014  1648036.0       Southwest
 44  2014                  Utah            2014   141410.0  Rocky Mountain
 45  2014              Virginia            2014   463613.0       Southeast
 46  2014               Vermont            2014    29613.0     New England
 47  2014            Washington            2014   427052.0        Far West
 48  2014             Wisconsin            2014   292891.0     Great Lakes
 49  2014         West Virginia            2014    75337.0       Southeast
 50  2014               Wyoming            2014    44190.0  Rocky Mountain,
      year          state current dollars           GDP        GDP_area
 0    2015         Alaska            2016  5.318000e+04        Far West
 1    2015        Alabama            2016  2.010337e+05       Southeast
 2    2015       Arkansas            2016  1.192147e+05       Southeast
 3    2015        Arizona            2016  2.928667e+05       Southwest
 4    2015     California            2016  2.507471e+06        Far West
 ..    ...            ...             ...           ...             ...
 97   2016        Vermont            2016  3.109175e+04     New England
 98   2016     Washington            2016  4.697395e+05        Far West
 99   2016      Wisconsin            2016  3.095365e+05     Great Lakes
 100  2016  West Virginia            2016  7.337350e+04       Southeast
 101  2016        Wyoming            2016  3.785775e+04  Rocky Mountain

 [102 rows x 5 columns],
      year          state current dollars         GDP        GDP_area
 0    2017         Alaska            2018    51686.75        Far West
 1    2017        Alabama            2018   211665.75       Southeast
 2    2017       Arkansas            2018   123713.75       Southeast
 3    2017        Arizona            2018   326539.50       Southwest
 4    2017     California            2018  2809922.50        Far West
 ..    ...            ...             ...         ...             ...
 97   2018        Vermont            2018    33725.25     New England
 98   2018     Washington            2018   563150.50        Far West
 99   2018      Wisconsin            2018   336971.50     Great Lakes
 100  2018  West Virginia            2018    77477.00       Southeast
 101  2018        Wyoming            2018    39371.25  Rocky Mountain

 [102 rows x 5 columns],
     year                 state current dollars         GDP        GDP_area
 0   2019                Alaska            2019    55406.25        Far West
 1   2019               Alabama            2019   230968.25       Southeast
 2   2019              Arkansas            2019   133180.75       Southeast
 3   2019               Arizona            2019   366190.00       Southwest
 4   2019            California            2019  3137469.00        Far West
 5   2019              Colorado            2019   390284.00  Rocky Mountain
 6   2019           Connecticut            2019   285640.25     New England
 7   2019  District of Columbia            2019   146194.50         Mideast
 8   2019              Delaware            2019    75415.25         Mideast
 9   2019               Florida            2019  1093350.75       Southeast
 10  2019               Georgia            2019   616333.25       Southeast
 11  2019                Hawaii            2019    97281.50        Far West
 12  2019                  Iowa            2019   194788.50          Plains
 13  2019                 Idaho            2019    80911.00  Rocky Mountain
 14  2019              Illinois            2019   897123.75     Great Lakes
 15  2019               Indiana            2019   377104.50     Great Lakes
 16  2019                Kansas            2019   173142.25          Plains
 17  2019              Kentucky            2019   214671.50       Southeast
 18  2019             Louisiana            2019   263856.50       Southeast
 19  2019         Massachusetts            2019   595558.75     New England
 20  2019              Maryland            2019   428338.50         Mideast
 21  2019                 Maine            2019    67518.50     New England
 22  2019              Michigan            2019   541550.75     Great Lakes
 23  2019             Minnesota            2019   380855.00          Plains
 24  2019              Missouri            2019   332082.00          Plains
 25  2019           Mississippi            2019   118779.75       Southeast
 26  2019               Montana            2019    52169.25  Rocky Mountain
 27  2019        North Carolina            2019   587711.00       Southeast
 28  2019          North Dakota            2019    57036.50          Plains
 29  2019              Nebraska            2019   127036.75          Plains
 30  2019         New Hampshire            2019    88594.75     New England
 31  2019            New Jersey            2019   644841.50         Mideast
 32  2019            New Mexico            2019   104001.25       Southwest
 33  2019                Nevada            2019   177614.75        Far West
 34  2019              New York            2019  1731910.50         Mideast
 35  2019                  Ohio            2019   698458.00     Great Lakes
 36  2019              Oklahoma            2019   206058.00       Southwest
 37  2019                Oregon            2019   251604.50        Far West
 38  2019          Pennsylvania            2019   813513.50         Mideast
 39  2019          Rhode Island            2019    63541.00     New England
 40  2019        South Carolina            2019   246309.00       Southeast
 41  2019          South Dakota            2019    53305.75          Plains
 42  2019             Tennessee            2019   380137.75       Southeast
 43  2019                 Texas            2019  1886956.00       Southwest
 44  2019                  Utah            2019   188501.25  Rocky Mountain
 45  2019              Virginia            2019   554211.25       Southeast
 46  2019               Vermont            2019    34785.00     New England
 47  2019            Washington            2019   599607.50        Far West
 48  2019             Wisconsin            2019   347306.00     Great Lakes
 49  2019         West Virginia            2019    78189.50       Southeast
 50  2019               Wyoming            2019    39646.25  Rocky Mountain]

In [112]:
# concatenate DataFrames into one DataFrame using pd.concat()
yearlyGDPbyState = pd.concat(dfs, ignore_index = True)
yearlyGDPbyState = yearlyGDPbyState.sort_values(['year', 'state'])
yearlyGDPbyState

      year          state current dollars        GDP        GDP_area
1     1995        Alabama            2001   95514.00       Southeast
0     1995         Alaska            2001   24791.00        Far West
3     1995        Arizona            2001  104586.00       Southwest
2     1995       Arkansas            2001   53809.00       Southeast
4     1995     California            2001  925931.00        Far West
...    ...            ...             ...        ...             ...
1269  2019       Virginia            2019  554211.25       Southeast
1271  2019     Washington            2019  599607.50        Far West
1273  2019  West Virginia            2019   78189.50       Southeast
1272  2019      Wisconsin            2019  347306.00     Great Lakes
1274  2019        Wyoming            2019   39646.25  Rocky Mountain

[1275 rows x 5 columns]

# Writing DataFrame to CSV

## MAKE SURE TO CHANGE FILE LOCATION IF RUNNING ON YOUR MACHINE

In [113]:
# write the DataFrame to a CSV
file_location = 'C:/Users/Katie/Documents/MSDS Program/CS 5010/CS Project/LifeOfBrian-USHousing/DataSet/yearlyGDPbyState.csv'
yearlyGDPbyState.to_csv(file_location)